Dockerfile, package.json
=> Update to use DockerFile

Dockerfile, deployment/nginx.conf, openshift/koku-ui-template.yml, src/index.tsx
Updates to enable deployment onto Openshift with nginx.
=> Deploy on openshift

src/routes.tsx
Just some clean up based on our POC decisions. `yarn test` passed, I only saw this as the impacting area of code.
=> Prototype will only have dashboard and cost details, remove other routes for now.

src/components/reportSummary/reportSummaryTrend.tsx, src/components/trendChart/__snapshots__/trendChart.test.tsx.snap, src/components/trendChart/trendChart.styles.ts, src/components/trendChart/trendChart.test.tsx, src/components/trendChart/trendChart.tsx, src/components/trendChart/trendChartUtils.ts
Trend chart was meant to be a running total not the value of each day. 
Not sure what made me not realize this with the first pr.....
=> Make trend chart a running total

src/api/query.ts, src/api/reports.ts, src/locales/de.json, src/locales/en.json, src/locales/es.json, src/pages/dashboard/dashboardWidget.tsx, src/store/dashboard/__snapshots__/dashboard.test.ts.snap, src/store/dashboard/dashboard.test.ts, src/store/dashboard/dashboardCommon.ts, src/store/dashboard/dashboardWidgets.ts, src/utils/getComputedReportItems.ts
Just followed the example scaffolding I saw for accounts and services.
Feel free to pull and see if it works for you. Just trying to help with progress 😄
=> Added in region support to dashboard.

.gitignore, src/components/textInput/textInput.styles.ts, src/components/textInput/textInput.tsx, src/pages/login/__snapshots__/login.test.tsx.snap, src/pages/login/login.styles.ts, src/pages/login/login.test.tsx, src/pages/login/login.tsx, src/testIds.ts
Wanted to add this PR now so @ripcurld can review.
Note this includes a temporary workaround for a type error with the pf4 alert.
Fixes https://github.com/project-koku/koku-ui/issues/55
=> fix(login): add login page error handling

package.json, src/typings/patternfly-react.d.ts, webpack.config.js, yarn.lock
This will ultimately be used for the wizard and list components, required to implement on-boarding and cost details page.
As a test, I added the patternfly-react alert to the login page, but did not include those changes here.
=> Add Patternfly-React

src/components/trendChart/__snapshots__/trendChartLegendItem.test.tsx.snap, src/components/trendChart/trendChartLegendItem.tsx, src/locales/de.json, src/locales/en.json, src/locales/es.json, src/store/dashboard/dashboardWidgets.ts
=> Clean up duplicate legend range and some of the translation content. Closes #83.

src/api/query.ts, src/components/link/index.ts, src/components/link/link.tsx, src/components/reportSummary/reportSummary.tsx, src/locales/de.json, src/locales/en.json, src/locales/es.json, src/pages/costDetails/costDetails.styles.ts, src/pages/costDetails/costDetails.tsx, src/pages/dashboard/dashboardWidget.test.tsx, src/pages/dashboard/dashboardWidget.tsx, src/store/dashboard/dashboardWidgets.ts, src/utils/formatValue.ts, src/utils/getComputedReportItems.ts
Added initial details page routing and report loading.
=> WIP: Initial Cost Details Routing and Report Loading

src/components/reportSummary/reportSummary.test.tsx, src/components/reportSummary/reportSummary.tsx, src/locales/de.json, src/locales/en.json, src/locales/es.json, src/pages/dashboard/dashboardWidget.test.tsx, src/pages/dashboard/dashboardWidget.tsx
=> feat(ReportSummary): display loading text when fetch in progress

package.json
=> fix(packages): move jest-emotion to dependencies

.travis.yml
I noticed that tests are running too slow on our Travis CI:
```
PASS  src/utils/formatValue.test.ts (7.728s)
PASS  src/api/session.test.ts (7.356s)
PASS  src/components/textInput/textInput.test.tsx (10.198s)
PASS  src/api/users.test.ts
PASS  src/components/tabs/tabContent.test.tsx (5.045s)
PASS  src/components/reportSummary/reportSummaryItem.test.tsx (10.7s)
PASS  src/api/providers.test.ts (7.162s)
PASS  src/api/reports.test.ts (6.544s)
PASS  src/components/commonChart/chartLegendItem.test.tsx
PASS  src/components/reportSummary/reportSummaryItems.test.tsx (9.9s)
PASS  src/components/tabs/tabs.test.tsx (17.359s)
PASS  src/components/tabs/tabNavigation.test.tsx (8.566s)
PASS  src/utils/asyncComponent.test.tsx (16.94s)
PASS  src/components/reportSummary/reportSummary.test.tsx (13.127s)
PASS …
```
=> Travis is too slow

src/locales/de.json, src/locales/en.json, src/locales/es.json
Fixes https://github.com/project-koku/koku-ui/issues/143
=> Prefix sort labels with "Sort By:"

src/pages/providersModal/providersModal.styles.ts, src/pages/providersModal/providersModal.tsx
Fixes https://github.com/project-koku/koku-ui/issues/142
=> Moves documentation info to top of modal.

src/pages/costDetails/costDetails.styles.ts, src/pages/costDetails/costDetails.tsx, src/pages/costDetails/detailItem.tsx, src/pages/costDetails/detailsToolbar.tsx
This PR improves the styles for PF3 list and filter so they mimic closer PF4 styles
=> improves styles to make pf3 component look like pf4

src/components/progressBar/progressBar.styles.ts, src/components/tabs/tabItem.styles.ts
This PR improves tabs and progress bars
=> styles the dashboard

package.json, src/components/i18nProvider/i18nProvider.tsx, webpack.config.js, yarn.lock
* stable branch is production
* master branch is beta
* ci and qa branches still need to be defined.
Master branch is currently deployed to `https://access.redhat.com/insightsbeta/platform/cost-management/`
but files are failing to load due to the publicPath defined in the webpack config. Updating based on Insights deployment model.
=> Support publicPath based on branch deployment.

src/pages/costDetails/costDetails.styles.ts
Fix react-tokens `global_BoxShadow` breakage.
=> Fix global_BoxShadow breakage

.travis.yml, package.json, webpack.config.js, yarn.lock
Our master build is not creating the correct public path. Added logging to the webpack file to help view what is happening on Travis.
=> Add logging to clarify the build output from webpack.

package.json
This stops the currently running docker container and adds $PWD for the config directory.
=> fixed inisghts:proxy target

.travis/release.sh
Travis giving error:
```
error: src refspec ci-beta does not match any.
error: failed to push some refs to 'git@github.com:RedHatInsights/cost-management-build.git'
```
Trying push to HEAD:
https://stackoverflow.com/a/4183856
=> Push to remote HEAD on release run.

src/pages/providersModal/attributeField.test.tsx, src/pages/providersModal/attributeField.tsx
=> fix(providersModal): Replace TextInput with PF4

src/pages/awsDetails/awsDetails.styles.ts, src/pages/awsDetails/detailsItem.tsx, src/pages/ocpDetails/detailsItem.tsx, src/pages/ocpDetails/ocpDetails.styles.ts
Signed-off-by: Boaz Shuster <boaz.shuster.github@gmail.com>
=> fix(ocp/awsDetails): align vertically asc/desc arrows

src/pages/awsDetails/detailsToolbar.tsx
=> fix(costToolbar): update filter input on changing group-by

src/locales/de.json, src/locales/en.json, src/locales/es.json
Removes "for" from title shown with each dashboard card.
Fixes https://github.com/project-koku/koku-ui/issues/243
=> Remove "for" from card title

src/pages/awsDetails/awsDetails.styles.ts, src/pages/awsDetails/awsDetails.tsx, src/pages/ocpDetails/ocpDetails.styles.ts, src/pages/ocpDetails/ocpDetails.tsx
This PR closes #233 and #234
Added a sm pf spacer as padding bottom under the titles in the aws and ocp pages to reflect what we have in pf design.
=> Spacing added under Title

src/pages/awsDetails/awsDetails.styles.ts, src/pages/ocpDetails/ocpDetails.styles.ts
This PR closes issue #231 ... by adding back in the border to the input.
=> Add border back in for input

src/components/tabs/tabItem.styles.ts, src/pages/awsDashboard/awsDashboard.styles.ts, src/pages/awsDashboard/awsDashboard.tsx, src/pages/ocpDashboard/ocpDashboard.styles.ts, src/pages/ocpDashboard/ocpDashboard.tsx, src/pages/overview/overview.styles.ts, src/pages/overview/overview.tsx
fixes https://github.com/project-koku/koku-ui/issues/238
fixes https://github.com/project-koku/koku-ui/issues/240
fixes https://github.com/project-koku/koku-ui/issues/244
=> fix(overview): update page to use PF3 themed colors, clean up css

src/pages/awsDashboard/awsDashboard.styles.ts, src/pages/awsDashboard/awsDashboard.tsx, src/pages/ocpDashboard/ocpDashboard.styles.ts, src/pages/ocpDashboard/ocpDashboard.tsx, src/pages/overview/overview.styles.ts, src/pages/overview/overview.tsx, src/styles/global.css
fixes https://github.com/project-koku/koku-ui/issues/267
=> fix(overview): add pf4 global styles for a element, clean up css

src/styles/global.css
Fixes https://github.com/project-koku/koku-ui/issues/173
I put a fix in PF4 core for this, and added that fix to the global css here.
This includes https://github.com/project-koku/koku-ui/pull/268, so it should be merged after that PR.
=>  fix(overview): fix overlapping grid columns in firefox

src/components/trendChart/trendChart.tsx, src/components/usageChart/usageChart.tsx
This fixes the `unique key` error message.
=> fix(Charts): do not render legend when there is no data

webpack.config.js
This fixes an issue with refreshing pages locally. Note that Insights beta appears to refresh as expected.
Fixes https://github.com/project-koku/koku-ui/issues/287
Fixes https://github.com/project-koku/koku-ui/issues/175
=> Enable local page refresh

src/pages/ocpDetails/detailsChart.tsx
Attempt to workaround PF3 bullet chart issue #399. Adding IDs to help debug in production.
=> PF3 bullet chart issue

src/pages/ocpDetails/detailsChart.tsx
Temporarily hide memory chart to help debug issue #399 in production
=> Hide memory bullet chart

src/components/pieChart/pieChart.styles.ts, src/components/pieChart/pieChart.tsx
closes #424 
Now it looks like this:
And on mobile:
=> fix(pieChart): fix legend text cut

src/utils/getComputedAwsReportItems.ts, src/utils/getComputedOcpReportItems.ts
Add computed report check to ensure report is not undefined and has a data object.
Fixes https://github.com/project-koku/koku-ui/issues/413
=> Add computed report check

src/pages/awsDetails/awsDetails.styles.ts
Fixes https://github.com/project-koku/koku-ui/issues/431
=> Sort icon is not visible in AWS details page

src/index.html, src/pages/overview/overview.tsx
No visual changes, it will just adds new classes so we can update PF-next version in chrome.
=> Update page styling based on new components of PF-next

src/locales/de.json, src/locales/en.json, src/locales/es.json
Updated title on detail pages to match nav links and sync'ed de/es locale files.
Note that the nav links were renamed via https://github.com/RedHatInsights/insights-chrome/issues/138
Fixes https://github.com/project-koku/koku-ui/issues/442
=> Updated detail page titles

src/pages/overview/overview.tsx
Update Cost Management Overview header per high fidelity mock / Insights.
Mock: https://redhat.invisionapp.com/share/ENPJQTBXTAC#/screens/336165152
Note that the tabs will be updated via https://github.com/project-koku/koku-ui/issues/205
Fixes https://github.com/project-koku/koku-ui/issues/395
=> Update header per high fidelity mock

src/index.html
This change is needed after: https://github.com/RedHatInsights/insights-chrome/pull/150
=> Updating to use a single esi tag in index.html

src/pages/awsDetails/awsDetails.tsx
Inadvertently cut/pasted OCP code due to earlier PF4 table refactoring.
Fixes https://github.com/project-koku/koku-ui/issues/477
=> Fix AWS "group by" dropdown functionality

src/pages/onboardingModal/final/index.tsx, src/pages/onboardingModal/final/loader.css, src/pages/onboardingModal/final/loader.test.tsx, src/pages/onboardingModal/final/loader.tsx
fixes #486 
~~Do not merge yet. I want to add unit test.~~
=> fix(onboarding): display status message and animation

src/locales/de.json, src/locales/en.json, src/locales/es.json, src/pages/awsDetails/detailsToolbar.styles.ts, src/pages/awsDetails/detailsToolbar.tsx, src/pages/ocpDetails/detailsToolbar.styles.ts, src/pages/ocpDetails/detailsToolbar.tsx
Update export icon per Kyle's high fidelity mock below. Also fixed some missing toolbar localizations.
Kyle's high fidelity mock:
https://redhat.invisionapp.com/share/ENPJQTBXTAC#/screens/336165166
Fixes https://github.com/project-koku/koku-ui/issues/436
=> Update export icon

src/app.tsx
Simple fix to scroll to top of page when navigating routes.
Fixes https://github.com/project-koku/koku-ui/issues/479
=> Scroll to top

src/api/api.ts, src/api/providers.ts, src/pages/overview/overview.tsx, src/store/providers/providers.test.ts, src/store/providers/providersReducer.ts
Associated with PR https://github.com/project-koku/koku/pull/655
=> Update UI to handle pagination format update for existing items.

src/pages/providersModal/providersModal.test.tsx, src/pages/providersModal/providersModal.tsx
Updates to provider creation for new error object format from API.
Associated with: https://github.com/project-koku/koku/pull/665
=> Update to support new error format.

src/api/api.ts, src/api/awsReports.test.ts, src/api/awsReports.ts, src/api/ocpReports.test.ts, src/api/ocpReports.ts
Associated with: https://github.com/project-koku/koku/pull/670
=> Update API paths to conform to latest changes.

src/components/commonChart/chartUtils.ts, src/components/historicalTrendChart/historicalTrendChart.styles.ts, src/components/historicalTrendChart/historicalTrendChart.tsx, src/components/historicalUsageChart/historicalUsageChart.styles.ts, src/components/historicalUsageChart/historicalUsageChart.tsx, src/locales/de.json, src/locales/en.json, src/locales/es.json, src/pages/awsDetails/detailsTableItem.tsx, src/pages/awsDetails/historicalChart.styles.ts, src/pages/awsDetails/historicalChart.tsx, src/pages/awsDetails/historicalModal.styles.ts, src/pages/awsDetails/historicalModal.tsx, src/pages/ocpDetails/historicalChart.tsx
Adds AWS historical charts
Fixes https://github.com/project-koku/koku-ui/issues/513
=> AWS historical charts

src/pages/awsDetails/awsDetails.styles.ts, src/pages/ocpDetails/ocpDetails.styles.ts
Adda padding to bottom of table.
Fixes https://github.com/project-koku/koku-ui/issues/517
=> Add padding to bottom of table

src/pages/awsDetails/detailsTable.styles.ts, src/pages/ocpDetails/detailsTable.styles.ts, src/pages/ocpDetails/ocpDetails.tsx
Simple fix to align table text at top of each row.
Fixes https://github.com/project-koku/koku-ui/issues/521
=> Align table text

package.json, src/components/charts/bulletChart/bulletChart.tsx, src/components/charts/historicalTrendChart/historicalTrendChart.tsx, src/components/charts/historicalUsageChart/historicalUsageChart.tsx, src/components/charts/trendChart/trendChart.tsx, src/components/charts/usageChart/usageChart.tsx, yarn.lock
Fixes https://github.com/project-koku/koku-ui/issues/527
=> Replace VictoryAxis with PF4 component

src/components/state/noProvidersState/noProvidersState.tsx
=> fix(overview): use the onboarding wizard in the empty state

src/pages/onboardingModal/iamPolicy/instructions.tsx
=> fix(onboarding): fix JSON in IAM Policy instructions

src/api/awsQuery.ts, src/api/awsReports.ts, src/api/ocpQuery.ts, src/api/ocpReports.ts, src/components/charts/commonChart/chartUtils.ts, src/components/charts/historicalTrendChart/historicalTrendChart.test.tsx, src/components/charts/historicalUsageChart/historicalUsageChart.test.tsx, src/components/charts/trendChart/trendChart.test.tsx, src/components/charts/usageChart/__snapshots__/usageChart.test.tsx.snap, src/components/reports/awsReportSummary/awsReportSummaryDetails.test.tsx, src/components/reports/awsReportSummary/awsReportSummaryDetails.tsx, src/components/reports/ocpReportSummary/ocpReportSummaryDetails.test.tsx, src/components/reports/ocpReportSummary/ocpReportSummaryDetails.tsx, src/pages/awsDashboard/awsDashboardWidget.tsx, src/pages/awsDetails/awsDetails.tsx, src/pages/awsDetails/detailsChart.tsx, src/pages/awsDetails/detailsChartModal.tsx, src/pages/awsDetails/detailsTable.tsx, src/pages/ocpDashboard/ocpDashboardWidget.tsx, src/pages/ocpDetails/detailsChart.tsx, src/pages/ocpDetails/detailsSummary.tsx, src/pages/ocpDetails/detailsTable.tsx, src/pages/ocpDetails/ocpDetails.tsx, src/utils/getComputedAwsReportItems.test.ts, src/utils/getComputedAwsReportItems.ts, src/utils/getComputedOcpReportItems.ts
Update to match response consistency changes in API.
Associated with: https://github.com/project-koku/koku/pull/683
=> Update UI to match API response consistency changes.

src/api/ocpReports.test.ts, src/api/ocpReports.ts, src/components/reports/ocpReportSummary/ocpReportSummaryDetails.tsx, src/locales/de.json, src/locales/en.json, src/locales/es.json, src/pages/awsDetails/detailsTableItem.tsx, src/pages/ocpDashboard/ocpDashboardWidget.test.tsx, src/pages/ocpDashboard/ocpDashboardWidget.tsx, src/pages/ocpDetails/detailsCluster.tsx, src/pages/ocpDetails/detailsSummary.tsx, src/pages/ocpDetails/detailsTable.tsx, src/pages/ocpDetails/exportModal.tsx, src/pages/ocpDetails/groupBy.tsx, src/pages/ocpDetails/historicalChart.styles.ts, src/pages/ocpDetails/historicalChart.tsx, src/pages/ocpDetails/ocpDetails.styles.ts, src/pages/ocpDetails/ocpDetails.tsx, src/routes.tsx, src/store/ocpDashboard/__snapshots__/ocpDashboard.test.ts.snap, src/store/ocpDashboard/ocpDashboard.test.ts, src/store/ocpDashboard/ocpDashboardReducer.ts, src/store/ocpDashboard/ocpDashboardWidgets.ts, src/store/ocpExport/ocpExport.test.ts
Replace last remaining references to 'charge' with 'cost'.
Fixes https://github.com/project-koku/koku-ui/issues/572
=> Replace references to 'charge' with 'cost'

src/pages/onboardingModal/iamPolicy/index.ts, src/pages/onboardingModal/iamPolicy/instructions.test.tsx, src/pages/onboardingModal/iamPolicy/instructions.tsx
=> fix(onboarding): populate s3 bucket name into IAM policy JSON

src/pages/onboardingModal/wizard/wizard.tsx
=> fix(onboarding): show a 'Finish' button in the final step

src/app.tsx
This changes listens for the onboarding "Add Source" status and errors to see if the empty state should be refreshed.
Fixes https://github.com/project-koku/koku-ui/issues/561
=> Refresh empty state after adding provider

src/pages/onboardingModal/configure/instructions.tsx, src/pages/onboardingModal/obtainLogin/instructions.tsx
=> fix(onboarding): remove the pound sign from copy clipboard text

src/locales/de.json, src/locales/en.json, src/locales/es.json, src/pages/ocpOnAwsDashboard/ocpOnAwsDashboardWidget.tsx
Missed adding a localization string.
Fixes https://github.com/project-koku/koku-ui/issues/575
Total cost:
AWS cards:
=> OCP on AWS date ranges

src/pages/onboardingModal/iamPolicy/instructions.tsx
=> fix(onboarding): link to the correct AWS IAM console page

src/api/awsReports.ts, src/api/ocpOnAwsReports.ts, src/api/ocpReports.ts, src/components/reports/awsReportSummary/__snapshots__/awsReportSummaryDetails.test.tsx.snap, src/components/reports/awsReportSummary/awsReportSummaryDetails.test.tsx, src/components/reports/awsReportSummary/awsReportSummaryDetails.tsx, src/components/reports/ocpOnAwsReportSummary/__snapshots__/ocpOnAwsReportSummaryDetails.test.tsx.snap, src/components/reports/ocpOnAwsReportSummary/ocpOnAwsReportSummaryDetails.test.tsx, src/components/reports/ocpOnAwsReportSummary/ocpOnAwsReportSummaryDetails.tsx, src/components/reports/ocpReportSummary/__snapshots__/ocpReportSummaryDetails.test.tsx.snap, src/components/reports/ocpReportSummary/ocpReportSummaryDetails.test.tsx, src/components/reports/ocpReportSummary/ocpReportSummaryDetails.tsx, src/pages/awsDashboard/awsDashboardWidget.tsx, src/pages/awsDetails/awsDetails.tsx, src/pages/awsDetails/detailsChart.tsx, src/pages/awsDetails/detailsChartModal.tsx, src/pages/awsDetails/detailsTable.tsx, src/pages/ocpDashboard/ocpDashboardWidget.tsx, src/pages/ocpDetails/detailsChart.tsx, src/pages/ocpDetails/detailsSummary.tsx, src/pages/ocpDetails/detailsTable.tsx, src/pages/ocpDetails/ocpDetails.tsx, src/pages/ocpOnAwsDashboard/ocpOnAwsDashboardWidget.tsx
Associated with: https://github.com/project-koku/koku/pull/712
Current default limit is 100, so no need to make changes in the tables etc at the moment. Can be added in a follow up feature.
=> Changes to support API report pagination updates.

src/pages/onboardingModal/wizard/index.ts, src/pages/onboardingModal/wizard/wizard.tsx
=> fix(onboarding): clicking the x button cancels onboarding

src/routes.tsx
Revert routes for aws and ocp details introduced for testing
=> Fix routes

src/locales/en.json
Update page titles for details and overview pages.
Fixes https://github.com/project-koku/koku-ui/issues/652
Fixes https://github.com/project-koku/koku-ui/issues/651
Overview
OpenShift details
Cloud details
=> Page titles

src/pages/awsDashboard/awsDashboardWidget.tsx, src/pages/ocpOnAwsDashboard/ocpOnAwsDashboardWidget.tsx
Fixed values so AWS progress bars do not show 'NaNs' values.
Fixes https://github.com/project-koku/koku-ui/issues/685
AWS:
=> AWS progress bars show 'NaNs' values

README.md, config/spandx.config.js
Update spandx config to include /app and /beta paths
=> Update spandx config

src/styles/global.css
The left hand nav should not scroll with main content pane.
Fixes https://github.com/project-koku/koku-ui/issues/518
=> Main content pane scrolling

config/spandx.config.js, src/app.tsx, src/routes.tsx
General cleanup of spandx config, Insights nav, and routing properties.
=> Clean up router navigation properties

src/locales/en.json
This change ensures the UI is using sentence case per the latest mocks.
Fixes: https://github.com/project-koku/koku-ui/issues/658
=> UI to use sentence case

src/api/rates.test.ts, src/api/rates.ts, src/locales/en.json, src/pages/ocpDetails/detailsActions.tsx, src/pages/ocpDetails/priceListModal.styles.ts, src/pages/ocpDetails/priceListModal.tsx, src/pages/ocpDetails/priceListTable.tsx, src/store/priceList/__snapshots__/store.test.ts.snap, src/store/priceList/actions.ts, src/store/priceList/index.ts, src/store/priceList/reducer.ts, src/store/priceList/selectors.ts, src/store/priceList/store.test.ts, src/store/rootReducer.ts
=> feat(priceList): add price list

src/pages/sourceSettings/sourceSetting.test.tsx, src/pages/sourceSettings/sourceSettings.tsx
=> fix(sourceSettings): hide toolbar on in progress mode

src/locales/en.json, src/pages/onboardingModal/sourceKind/form.tsx
=> fix(Onboarding): small adjustments in the first step

src/components/actionKebab/index.tsx, src/pages/sourceSettings/rowCell.tsx
=> fix(Sources): fix react warning messages in the console

src/pages/onboardingModal/usageCollector/instructions.tsx
=> fix(onboarding): small adjustments in usage collector instructions

src/components/charts/costChart/costChart.tsx, src/components/charts/historicalCostChart/historicalCostChart.tsx, src/components/charts/historicalTrendChart/historicalTrendChart.tsx, src/components/charts/historicalUsageChart/historicalUsageChart.tsx, src/components/charts/trendChart/trendChart.tsx
This ensures unique keys for each chart.
=> Chart keys

src/pages/ocpDetails/detailsActions.tsx
=> fix(ocpDetails): disable price list on grouped-by tags

src/locales/en.json, src/pages/sourceSettings/noSourcesState.styles.ts, src/pages/sourceSettings/noSourcesState.tsx, src/pages/sourceSettings/sourceSetting.test.tsx, src/pages/sourceSettings/sourceSettings.tsx
closes #764 
//cc @dlabrecq @dayleparker
=> fix(Sources): update empty state texts to be more informative

src/locales/en.json
Fixes https://github.com/project-koku/koku-ui/issues/803
See screenshot in comment below...
=> Update text for overview info icon

src/locales/en.json, src/pages/onboardingModal/final/index.tsx, src/pages/onboardingModal/final/item.test.tsx, src/pages/onboardingModal/final/item.tsx, src/pages/onboardingModal/final/loader.test.tsx, src/pages/onboardingModal/final/loader.tsx, src/pages/onboardingModal/wizard/index.ts, src/pages/onboardingModal/wizard/wizard.tsx, src/store/onboarding/actions.ts, src/store/onboarding/reducer.ts
closes #762 
Confirmation before submitting
Confirmation after submitting and with errors
=> feat(onboarding): add confirmation step

src/locales/en.json
=> fix(Onboarding): update the first step instruction text

src/locales/en.json, src/pages/sourceSettings/filterToolbar.tsx, src/pages/sourceSettings/sourceSettings.tsx
Added missing localizations for sources page
Fixes https://github.com/project-koku/koku-ui/issues/823
=> Added missing localizations for sources page

src/locales/en.json, src/pages/onboardingModal/obtainLogin/instructions.tsx
=> fix(onboarding): update the obtain login step text and add popover

src/locales/en.json, src/pages/onboardingModal/configure/instructions.tsx
=> fix(onboarding): update the usage collector step

src/pages/sourceSettings/filterToolbar.tsx, src/pages/sourceSettings/index.tsx, src/pages/sourceSettings/sourcePagination.tsx, src/pages/sourceSettings/sourceSetting.test.tsx, src/pages/sourceSettings/sourceSettings.styles.ts, src/pages/sourceSettings/sourceSettings.tsx, src/store/sourceSettings/actions.ts, src/store/sourceSettings/reducer.ts, src/store/sourceSettings/selectors.ts
=> feat(sources): add pagination to the table

src/locales/en.json, src/pages/onboardingModal/final/loader.test.tsx, src/pages/onboardingModal/final/loader.tsx, src/pages/onboardingModal/iamPolicy/instructions.tsx, src/pages/onboardingModal/iamRole/instructions.tsx, src/pages/onboardingModal/obtainLogin/instructions.tsx, src/pages/onboardingModal/wizard/wizard.tsx
=> fix(onboarding): Fix missing localizations

src/locales/en.json, src/pages/sourceSettings/filterResults.tsx, src/pages/sourceSettings/filterToolbar.tsx, src/pages/sourceSettings/sourceSetting.test.tsx, src/pages/sourceSettings/sourceSettings.tsx, src/store/sourceSettings/reducer.ts
=> feat(sources): Add filter functionality

src/pages/onboardingModal/sourceKind/checkList.styles.ts, src/pages/onboardingModal/sourceKind/checkList.tsx
=> fix(onboarding): realign spaces and indentations in checkboxes

src/pages/onboardingModal/wizard/wizard.tsx
=> fix(onboarding): fix localization on navigation buttons

src/locales/en.json, src/pages/sourceSettings/deleteDialog.tsx
fixes #871 
//cc @dchorvat1 @lcouzens can you please review this as well.
=> fix(deleteDialog): fix the text overflow problem 

src/pages/ocpDetails/priceListModal.tsx, src/store/common.ts, src/store/ocpReports/ocpReportsActions.ts, src/store/priceList/__snapshots__/store.test.ts.snap, src/store/priceList/actions.ts, src/store/priceList/reducer.ts, src/store/priceList/selectors.ts, src/store/priceList/store.test.ts
=> feat(priceList): Fetch price list per cluster and cache it for 30 minutes

src/index.tsx, src/locales/en.json, src/pages/sourceSettings/index.tsx, src/store/onboarding/actions.ts, src/store/rootReducer.ts, src/store/store.ts
closes #760 
https://redhat.invisionapp.com/share/XJR3A3996KR#/screens/356380295
=> feat(onboarding): show a notification on success

src/locales/en.json, src/pages/onboardingModal/obtainLogin/instructions.tsx, src/pages/onboardingModal/usageCollector/form.tsx, src/pages/onboardingModal/usageCollector/instructions.tsx
=> fix(onboarding): headless popover must have aria-label

src/pages/onboardingModal/wizard/wizard.tsx
=> fix(onboarding): fix error message on adding source

src/pages/overview/overview.tsx
=> feat(onboarding): remove the 'add sources' button from overview

src/store/store.ts
=> fix(store): Remove the unnecessary logger middleware

src/components/charts/costChart/costChart.tsx, src/components/charts/historicalCostChart/historicalCostChart.tsx, src/components/charts/historicalTrendChart/historicalTrendChart.tsx, src/components/charts/historicalUsageChart/historicalUsageChart.tsx, src/components/charts/trendChart/trendChart.tsx, src/components/charts/usageChart/usageChart.tsx
This adds interpolation to area charts in order to show smooth, curved lines.
fixes https://github.com/project-koku/koku-ui/issues/910
=> Adds interpolation to area charts

src/locales/en.json, src/pages/onboardingModal/obtainLogin/instructions.tsx, src/pages/onboardingModal/sourceKind/sourceKind.tsx
=> fix(Onboarding): update Operator Metering to Reporting Operator

src/locales/en.json, src/pages/onboardingModal/configure/instructions.tsx
closes #923 
//cc @dayleparker @dlabrecq
=> fix(onboarding): small text edits in configure data collection

src/locales/en.json, src/pages/onboardingModal/usageCollector/instructions.tsx
=> fix(onboarding): update collector link and script command line

src/api/providers.ts, src/pages/sourceSettings/rowCell.tsx
=> fix(sourceSettings): display the correct 'Date added' of the source

src/locales/en.json, src/pages/onboardingModal/confirmDialog/index.tsx, src/pages/onboardingModal/wizard/index.ts, src/pages/onboardingModal/wizard/wizard.tsx, src/store/onboarding/__snapshots__/store.test.ts.snap, src/store/onboarding/actions.ts, src/store/onboarding/reducer.ts, src/store/onboarding/selectors.ts, src/store/onboarding/store.test.ts
=> feat(onboarding): show a dialog to confirm  the user wishes to quit

src/api/costModels.ts, src/app.tsx, src/locales/en.json, src/pages/costModelsDetails/costModelsDetails.styles.ts, src/pages/costModelsDetails/costModelsDetails.tsx, src/pages/costModelsDetails/costModelsPagination.tsx, src/pages/costModelsDetails/costModelsTable.styles.tsx, src/pages/costModelsDetails/costModelsTable.tsx, src/pages/costModelsDetails/emptyState.styles.ts, src/pages/costModelsDetails/emptyState.tsx, src/pages/costModelsDetails/filterResults.tsx, src/pages/costModelsDetails/filterToolbar.tsx, src/pages/costModelsDetails/header.tsx, src/pages/costModelsDetails/index.tsx, src/routes.tsx, src/store/costModels/actions.ts, src/store/costModels/index.ts, src/store/costModels/reducer.ts, src/store/costModels/selectors.ts, src/store/rootReducer.ts
=> feat(costModels): add the cost models details page

src/pages/awsDetails/detailsTable.tsx, src/pages/ocpDetails/detailsTable.tsx, src/pages/ocpOnAwsDetails/detailsTable.tsx
tiny additions to the tables for aws details, ocp details, and ocp on aws details
=> fixed issue #943 table resize

src/api/costModels.test.ts, src/api/costModels.ts, src/api/rates.ts, src/locales/en.json, src/pages/costModelsDetails/costModelsDetails.tsx, src/pages/createCostModelWizard/addPriceList.tsx, src/pages/createCostModelWizard/api.ts, src/pages/createCostModelWizard/context.ts, src/pages/createCostModelWizard/filterLogic.ts, src/pages/createCostModelWizard/filterResults.tsx, src/pages/createCostModelWizard/filterToolbar.tsx, src/pages/createCostModelWizard/generalInformation.tsx, src/pages/createCostModelWizard/index.tsx, src/pages/createCostModelWizard/markup.tsx, src/pages/createCostModelWizard/parseError.ts, src/pages/createCostModelWizard/priceList.tsx, src/pages/createCostModelWizard/priceListTable.tsx, src/pages/createCostModelWizard/priceListTier.tsx, src/pages/createCostModelWizard/review.tsx, src/pages/createCostModelWizard/sources.tsx, src/pages/createCostModelWizard/steps.tsx, src/pages/createCostModelWizard/table.tsx
=> feat(costModels): add the create-cost-model wizard

src/pages/onboardingModal/wizard/wizard.tsx, src/store/onboarding/actions.ts
=> fix(onboarding): reset index on cancelling the process

src/pages/costModelsDetails/costModelsDetails.tsx, src/pages/costModelsDetails/emptyState.tsx
=> fix(costmodels): open cost model wizard from empty state action button

package.json
This should fix the problem with Travis CI.
closes #971
=> chore(travis): webpack needs 4GB to complete build

src/api/costModels.ts, src/pages/costModelsDetails/costModelsDetails.tsx
=> fix(costmodels): change provider_uuids to providers in cost models api

src/pages/onboardingModal/iamPolicy/instructions.tsx
The JSON for the AWS provider wizard needs to be updated.
Fixes https://github.com/project-koku/koku-ui/issues/937
=> Update JSON for AWS provider wizard

src/locales/en.json, src/pages/costModelsDetails/addSourceWizard.tsx, src/pages/costModelsDetails/components/addRateModel.tsx, src/pages/costModelsDetails/components/updateRateModel.tsx, src/pages/costModelsDetails/costModelInfo/index.tsx, src/pages/costModelsDetails/review.tsx
=> fix(costmodel): fit & finish to dialogs and wizard texting

src/store/priceList/__snapshots__/store.test.ts.snap, src/store/priceList/selectors.ts, src/store/priceList/store.test.ts
closes #987 
thanks @dchorvat1 for the environment for testing this in live data.
=> fix(pricelist): update the rates API response

src/pages/createCostModelWizard/index.tsx
=> fix(costmodel): update cost models store on success creation

src/api/costModels.test.ts, src/api/costModels.ts, src/locales/en.json, src/pages/costModelsDetails/components/dialog.tsx, src/pages/costModelsDetails/costModelsDetails.tsx, src/pages/costModelsDetails/costModelsTable.tsx, src/pages/costModelsDetails/index.tsx, src/store/costModels/__snapshots__/store.test.ts.snap, src/store/costModels/actions.ts, src/store/costModels/reducer.ts, src/store/costModels/selectors.ts, src/store/costModels/store.test.ts
=> fix(costmodels): add kebab option to delete/view cost model

src/locales/en.json, src/pages/costModelsDetails/components/dialog.test.tsx, src/pages/costModelsDetails/components/dialog.tsx
=> fix(costmodel): cost model can be deleted when having no sources

src/locales/en.json
=> fix(costmodel): move dollar sign to the beginning in price list table

src/locales/en.json, src/pages/costModelsDetails/components/dialog.test.tsx, src/pages/costModelsDetails/components/dialog.tsx, src/pages/costModelsDetails/components/sourceTable.tsx, src/pages/costModelsDetails/components/table.tsx
@jlalbertson @chargio these are the changes you asked.
- "Unassign" instead of "Delete"
- Cost model description header
- Use "per" instead of "for every"
=> fix(costmodels): update text

src/pages/costModelsDetails/components/priceListTier.tsx, src/pages/costModelsDetails/costModelInfo/index.tsx, src/pages/costModelsDetails/costModelsDetails.tsx, src/pages/createCostModelWizard/priceListTier.tsx, src/utils/rateCurrency.test.ts, src/utils/rateCurrency.ts
=> fix(costmodel): display rates values correctly

src/locales/en.json, src/pages/onboardingModal/azureCreds/index.tsx, src/pages/onboardingModal/azureDataSource/index.tsx, src/pages/onboardingModal/final/index.tsx, src/pages/onboardingModal/final/loader.tsx, src/pages/onboardingModal/sourceKind/form.tsx, src/pages/onboardingModal/wizard/index.ts, src/pages/onboardingModal/wizard/wizard.tsx, src/store/onboarding/__snapshots__/store.test.ts.snap, src/store/onboarding/actions.ts, src/store/onboarding/reducer.ts, src/store/onboarding/selectors.ts
=> feat(onboarding): Add Microsoft Azure to the onboarding modal

src/locales/en.json, src/pages/onboardingModal/configure/instructions.tsx
Small typo fix on OpenShift sources instructions.
=> Fix typo: contrab -> crontab

src/locales/en.json
=> fix(costmodel): update title in the empty state

src/locales/en.json, src/pages/costModelsDetails/addSourceStep.tsx, src/pages/costModelsDetails/components/priceListTable.tsx, src/pages/costModelsDetails/components/priceListTier.tsx, src/pages/costModelsDetails/costModelsTable.tsx, src/pages/createCostModelWizard/priceListTable.tsx, src/pages/createCostModelWizard/table.tsx
=> fix(costmodel): address warning messages in the console log

src/store/onboarding/store.test.ts
Add more unit tests to the onboarding store for Azure
=> fix(onboarding): add tests to azure onboarding store

src/locales/en.json, src/pages/createCostModelWizard/context.ts, src/pages/createCostModelWizard/index.tsx, src/pages/createCostModelWizard/priceListTable.tsx, src/pages/createCostModelWizard/priceListTier.tsx
=> fix(costmodels): create cost model wizard view rates fit and finish

src/locales/en.json, src/pages/createCostModelWizard/filterToolbar.tsx, src/pages/createCostModelWizard/table.tsx
=> fix(costmodels): fit and finish in the assign sources step in wizard

src/locales/en.json, src/pages/createCostModelWizard/index.tsx, src/pages/createCostModelWizard/priceListTier.tsx, src/pages/createCostModelWizard/review.tsx
=> fix(costmodels): create cost model review step fit and finish

src/locales/en.json, src/pages/costModelsDetails/components/updateCostModel.tsx, src/pages/costModelsDetails/costModelInfo/header.tsx, src/pages/costModelsDetails/costModelInfo/index.tsx, src/pages/costModelsDetails/costModelsDetails.tsx, src/pages/costModelsDetails/costModelsTable.tsx, src/store/costModels/__snapshots__/store.test.ts.snap, src/store/costModels/actions.ts, src/store/costModels/reducer.ts, src/store/costModels/selectors.ts
=> fix(costmodel): add edit/delete options on cost model details page

src/pages/costModelsDetails/components/markup.tsx
Fix cost model undefined error for prod beta
Fixes https://github.com/project-koku/koku-ui/issues/1060
=> Cost model undefined error

src/pages/onboardingModal/configure/instructions.tsx
closes #1052 
@lcouzens & @dayleparker can you confirm?
Thanks.
=> fix(onboarding): incomplete commands for contrab

src/utils/formatValue.ts
=> Fixes for #1081 - Format usage hours similar to cost

src/pages/costModelsDetails/costModelsDetails.styles.ts
=> fix(costmodels): set header padding like inventory did

src/pages/costModelsDetails/addSourceWizard.tsx, src/pages/costModelsDetails/components/addRateModel.tsx, src/pages/costModelsDetails/components/dialog.tsx, src/pages/costModelsDetails/components/updateCostModel.tsx, src/pages/costModelsDetails/components/updateMarkupDialog.tsx, src/pages/costModelsDetails/components/updateRateModel.tsx
=> fix(costmodel): Align modal action buttons to left

src/components/forms/form.tsx, src/pages/createCostModelWizard/addPriceList.tsx, src/pages/createCostModelWizard/generalInformation.tsx, src/pages/createCostModelWizard/markup.tsx
=> fix(costmodels): on submit click on the 'Next' button in the wizard

src/pages/costModelsDetails/costModelInfo/header.tsx, src/pages/costModelsDetails/costModelInfo/index.tsx, src/pages/createCostModelWizard/review.tsx
=> fix(costmodels): show price list in the review step when type is OCP

src/pages/createCostModelWizard/priceListTable.tsx, src/pages/createCostModelWizard/table.tsx
=> fix(costmodels): Set pagination to compact in the wizard

src/locales/en.json, src/pages/costModelsDetails/costModelsDetails.tsx, src/pages/createCostModelWizard/index.tsx
=> fix(costmodels): show confirmation dialog before closing wizard

src/locales/en.json, src/pages/createCostModelWizard/review.tsx, src/pages/createCostModelWizard/table.tsx, src/pages/createCostModelWizard/warningIcon.tsx
=> fix(costmodels): display warning when going to override assignment

src/pages/createCostModelWizard/addPriceList.tsx, src/pages/createCostModelWizard/priceListTable.tsx
=> fix(costmodels): show available rates at the price list form in wizard

src/locales/en.json, src/pages/createCostModelWizard/table.tsx
=> fix(costmodels): Show type at the title in the source step

src/pages/createCostModelWizard/markup.tsx
=> fix(costmodels): Add timeout to markup validation in the wizard

src/locales/en.json
=> fix(costmodels): Change action button text to 'Create cost model'

src/locales/en.json
Fix typo with price list option in Ocp details kebab
Fixes https://github.com/project-koku/koku-ui/issues/1147
=> Fix typo with price list option in Ocp details kebab

src/locales/en.json
Fix missing i18n key for Azure details kebab "All accounts" option
Fixes https://github.com/project-koku/koku-ui/issues/1110
=> Azure details kebab "All accounts" option

src/pages/createCostModelWizard/table.tsx
=> fix(costmodels): Make the bottom pagination at assign-source compact

src/pages/ocpDetails/detailsActions.tsx
=> fix(pricelist): get price list cluster name from item's label

src/pages/costModelsDetails/addSourceStep.tsx
=> fix(costmodels): Add a warning message to the Assign Sources Modal

src/pages/createCostModelWizard/index.tsx
=> fix(costmodels): set wizard height and width to a normal size

src/pages/createCostModelWizard/generalInformation.tsx, src/pages/createCostModelWizard/wizard.styles.tsx
=> fix(costmodels): set min and max width/height to textarea

src/locales/en.json
=> fix(costmodels): Fix typo 'Select one or more source(s)'

src/pages/costModelsDetails/costModelsDetails.tsx, src/pages/costModelsDetails/costModelsTable.tsx, src/pages/costModelsDetails/sort.test.ts, src/pages/costModelsDetails/sort.ts, src/store/costModels/selectors.ts, src/store/costModels/store.test.ts
=> feat(costmodels): order cost models by name and last modification

src/locales/en.json
Rename details dialog titles
Fixes https://github.com/project-koku/koku-ui/issues/1185
=> Rename details dialog titles

src/api/providers.ts, src/app.tsx, src/pages/overview/overview.tsx, src/store/providers/providersActions.ts, src/store/providers/providersCommon.ts
Added support for Azure empty state
Fixes https://github.com/project-koku/koku-ui/issues/1051
=> Azure empty state

src/components/charts/costChart/costChart.styles.ts, src/components/charts/costChart/costChart.tsx, src/components/charts/historicalCostChart/__snapshots__/historicalCostChart.test.tsx.snap, src/components/charts/historicalCostChart/historicalCostChart.styles.ts, src/components/charts/historicalCostChart/historicalCostChart.test.tsx, src/components/charts/historicalCostChart/historicalCostChart.tsx, src/components/charts/historicalTrendChart/historicalTrendChart.styles.ts, src/components/charts/historicalTrendChart/historicalTrendChart.test.tsx, src/components/charts/historicalTrendChart/historicalTrendChart.tsx, src/components/charts/historicalUsageChart/__snapshots__/historicalUsageChart.test.tsx.snap, src/components/charts/historicalUsageChart/historicalUsageChart.styles.ts, src/components/charts/historicalUsageChart/historicalUsageChart.test.tsx, src/components/charts/historicalUsageChart/historicalUsageChart.tsx, src/components/charts/trendChart/trendChart.styles.ts, src/components/charts/trendChart/trendChart.test.tsx, src/components/charts/trendChart/trendChart.tsx, src/components/charts/usageChart/__snapshots__/usageChart.test.tsx.snap, src/components/charts/usageChart/usageChart.styles.ts, src/components/charts/usageChart/usageChart.test.tsx, src/components/charts/usageChart/usageChart.tsx, src/pages/awsDashboard/awsDashboardWidget.tsx, src/pages/azureDashboard/azureDashboardWidget.tsx, src/pages/ocpCloudDashboard/ocpCloudDashboardWidget.tsx, src/pages/ocpDashboard/ocpDashboardWidget.tsx
This introduces PatternFly's interactive legend functionality. 
This will help provide a visual highlight of each data set while hovering over legend symbols and labels. In addition, this will provide a visual indication of hidden data sets.
Fixes https://github.com/project-koku/koku-ui/issues/1204
Aws overview chart
Ocp on cloud historical chart
=> Add interactive legends

src/pages/ocpCloudDetails/detailsChart.tsx, src/pages/ocpDetails/detailsChart.tsx
Free space should show negative values
Fixes https://github.com/project-koku/koku-ui/issues/1214
Fixes https://github.com/project-koku/koku-ui/issues/1214
=> Free space to show negatiove values

src/pages/ocpCloudDashboard/ocpCloudDashboardWidget.tsx, src/pages/ocpCloudDetails/ocpCloudDetails.tsx, src/routes.tsx
Update URL from "/ocp-on-aws" to "/ocp-cloud". 
Fixes https://github.com/project-koku/koku-ui/issues/1230
Related to https://github.com/project-koku/koku-ui/issues/1177
=> Ocp cloud details: Update path

package.json, src/api/api.ts, src/api/awsReports.ts, src/api/azureReports.ts, src/api/costModels.ts, src/api/ocpCloudReports.ts, src/api/ocpReports.ts, src/api/providers.ts, src/api/rates.ts, src/store/providers/providersActions.ts, yarn.lock
Instead of checking if insights is in windows, use the Insights auth-interceptor that does this for us.
=> chore(api): use RedHat Insights auth interceptor

src/locales/en.json
=> fix(costmodels): update navigation and step titles in wizard

src/pages/createCostModelWizard/review.tsx, src/pages/createCostModelWizard/table.tsx
=> fix(costmodels): display warning when override source cost model

package.json, yarn.lock
https://github.com/project-koku/koku-ui/issues/1295
=> Update Victory packages

archive/pages/login/index.ts, archive/pages/onboardingModal/index.ts, archive/pages/providersModal/index.ts, package.json, src/app.tsx, src/pages/awsDashboard/index.ts, src/pages/awsDetails/index.ts, src/pages/azureDashboard/index.ts, src/pages/azureDetails/index.ts, src/pages/notFound/index.ts, src/pages/ocpCloudDashboard/index.ts, src/pages/ocpCloudDetails/index.ts, src/pages/ocpDashboard/index.ts, src/pages/ocpDetails/index.ts, src/pages/overview/index.ts, webpack.config.js, yarn.lock
The hot loader has not worked since we integrated with the Insights platform.
https://github.com/project-koku/koku-ui/issues/1299
=> Remove react-hot-loader

src/locales/en.json, src/pages/costModelsDetails/components/costModelRateItem.tsx, src/pages/costModelsDetails/components/updateMarkupDialog.tsx
=> fix(costmodel): fit and finish text updates

src/components/priceList/types.ts, src/locales/en.json, src/pages/costModelsDetails/components/addCostModelRateForm.tsx, src/pages/createCostModelWizard/Datatoolbar.tsx, src/pages/createCostModelWizard/priceListTable.tsx
=> feat(costmodels): Use data toolbar at price list step in the wizard

src/locales/en.json, src/pages/createCostModelWizard/index.tsx, src/pages/createCostModelWizard/review.tsx
=> fix(costmodel): cost model wizard texting updates

.github/workflows/status_code_review.yml, .github/workflows/status_qa.yml
=> chore(ci): add workflows to tag issues with the status label

.github/workflows/status_qa.yml
=> chore(github-actions): fix on merge workflow

src/pages/costModelsDetails/addSourceStep.tsx, src/pages/costModelsDetails/assignSourcesModalToolbar.tsx
=> feat(costmodel): assign sources modal migrate to pf4 datatoolbar

.github/workflows/status_code_review.yml, src/pages/createCostModelWizard/assignSourcesToolbar.tsx, src/pages/createCostModelWizard/filterLogic.test.ts, src/pages/createCostModelWizard/filterLogic.ts, src/pages/createCostModelWizard/index.tsx, src/pages/createCostModelWizard/table.tsx
=> feat(costmodels): Migrate to PF4 DataToolbar in Assign Sources

src/pages/costModelsDetails/components/priceListTable.tsx, src/pages/createCostModelWizard/Datatoolbar.tsx, src/pages/createCostModelWizard/priceListTable.tsx
=> feat(costmodels): migrate to pf4 datatoolbar in price list tab

src/locales/en.json, src/pages/costModelsDetails/components/sourceTable.tsx, src/pages/costModelsDetails/components/sourcesToolbar.tsx, src/pages/costModelsDetails/components/table.tsx
=> feat(costmodels): migrate to pf4 datatoolbar in the sources tab

src/locales/en.json
=> fix(costmodels): mismatch translation key

src/locales/en.json, src/pages/costModelsDetails/components/costModelsDetailsToolbar.tsx, src/pages/costModelsDetails/costModelsDetails.tsx, src/store/costModels/selectors.ts, src/store/costModels/store.test.ts
=> feat(costmodels): migrate to pf4 datatoolbar in the details page

src/locales/en.json, src/pages/createCostModelWizard/generalInformation.tsx
=> feat(costmodels): add link to documents in wizard

package.json, src/api/rbac.test.ts, src/api/rbac.ts, src/locales/en.json, src/pages/costModelsDetails/components/costModelsDetailsToolbar.tsx, src/pages/costModelsDetails/components/markup.tsx, src/pages/costModelsDetails/components/priceListTable.tsx, src/pages/costModelsDetails/components/readOnlyTooltip.test.tsx, src/pages/costModelsDetails/components/readOnlyTooltip.tsx, src/pages/costModelsDetails/components/sourcesToolbar.tsx, src/pages/costModelsDetails/components/table.tsx, src/pages/costModelsDetails/costModelInfo/header.tsx, src/pages/costModelsDetails/costModelsDetails.tsx, src/pages/costModelsDetails/costModelsTable.tsx, src/pages/costModelsDetails/index.tsx, src/pages/createCostModelWizard/Datatoolbar.tsx, src/store/rbac/actions.ts, src/store/rbac/index.ts, src/store/rbac/reducer.ts, src/store/rbac/selectors.ts, src/store/rbac/store.test.ts, src/store/rootReducer.ts, yarn.lock
=> feat(costmodel): render read-only view

src/pages/costModels/costModelsDetails/addSourceStep.tsx
=> fix(costmodels): filter sources correctly in assign sources modal

src/pages/costModels/costModelsDetails/costModelsDetails.tsx
=> fix(costmodels): do not show empty state on error

src/api/reports/awsCloudReports.test.ts, src/api/reports/awsCloudReports.ts, src/api/reports/report.ts, src/api/reports/reportUtils.ts, src/store/dashboard/awsCloudDashboard/awsCloudDashboardWidgets.ts
Updated the APIs for the "Aws filtered by Ocp" overview page
https://github.com/project-koku/koku-ui/issues/1340
=> Update APIs for "Aws filtered by Ocp" overview

src/locales/en.json, src/pages/costModels/components/addPriceList.tsx, src/pages/costModels/costModelsDetails/components/addRateModal.tsx
=> fix(costmodels): Replace 'price' with 'currency' in measurements

src/api/reports/azureCloudReports.test.ts, src/api/reports/azureCloudReports.ts, src/api/reports/report.ts, src/api/reports/reportUtils.ts, src/pages/dashboard/azureCloudDashboard/azureCloudDashboardWidget.tsx, src/store/dashboard/azureCloudDashboard/azureCloudDashboardActions.ts, src/store/dashboard/azureCloudDashboard/azureCloudDashboardWidgets.ts
Updated APIs for "Microsoft Azure filtered by Ocp" overview page
https://github.com/project-koku/koku-ui/issues/1341
=> Update APIs for "Microsoft Azure filtered by Ocp" overview

src/api/reports/ocpUsageReports.test.ts, src/api/reports/ocpUsageReports.ts, src/api/reports/report.ts, src/api/reports/reportUtils.ts, src/store/dashboard/ocpUsageDashboard/ocpUsageDashboardWidgets.ts
Updated the APIs for the "OpenShift usage" overview page
https://github.com/project-koku/koku-ui/issues/1342
=> Update APIs for OpenShift usage overview

src/store/dashboard/awsCloudDashboard/awsCloudDashboardActions.ts, src/store/dashboard/awsDashboard/awsDashboardActions.ts, src/store/dashboard/azureCloudDashboard/azureCloudDashboardActions.ts, src/store/dashboard/azureDashboard/azureDashboardActions.ts, src/store/dashboard/ocpDashboard/ocpDashboardActions.ts, src/store/dashboard/ocpSupplementaryDashboard/ocpSupplementaryDashboardActions.ts, src/store/dashboard/ocpUsageDashboard/ocpUsageDashboardActions.ts
Omit extra API requests for overview tabs that are no longer shown
https://github.com/project-koku/koku-ui/issues/1426
=> Omit extra API requests for overview

src/api/metrics.ts, src/api/rates.ts, src/locales/en.json, src/pages/costModels/components/addPriceList.test.tsx, src/pages/costModels/components/addPriceList.tsx, src/pages/costModels/components/rateTable.tsx, src/pages/costModels/costModelsDetails/components/addRateModal.test.tsx, src/pages/costModels/costModelsDetails/components/addRateModal.tsx, src/pages/costModels/costModelsDetails/components/priceListTable.tsx, src/pages/costModels/costModelsDetails/components/updateRateModel.tsx, src/pages/costModels/costModelsDetails/costModelInfo/index.tsx, src/pages/costModels/costModelsDetails/costModelsDetails.tsx, src/pages/costModels/createCostModelWizard/index.tsx, src/pages/costModels/createCostModelWizard/priceList.tsx, src/pages/costModels/createCostModelWizard/priceListTable.tsx, src/pages/costModels/createCostModelWizard/review.tsx
=> feat(costmodels): Add cost types to cost models UI

webpack.config.js
Modified webpack appDeployment to mimic @redhat-cloud-services/frontend-components-config
https://github.com/project-koku/koku-ui/issues/1389
=> Webpack appDeployment

src/__snapshots__/app.test.tsx.snap, src/app.tsx, src/index.tsx, src/routes.tsx, src/utils/getBaseName.ts, webpack.config.js
Modified routes to mimic Insights starter app
#1389
=> Updated routes

webpack.config.js
Fixed isProduction flag by testing NODE_ENV. This was previously only set via the build target.
=> Fix isProduction flag

src/index.tsx, src/routes.tsx, webpack.config.js
Added exact routes and cleaned up webpack.config log messages
=> Add exact routes

src/routes.tsx
There seems to be a production env issue with a Redirect in a Switch. As a workaround, this wraps the Redirect in a Route.
=> Added workaround for redirect in production

src/pages/details/awsDetails/awsDetails.tsx, src/pages/details/azureDetails/azureDetails.tsx, src/pages/details/ocpCloudDetails/ocpCloudDetails.tsx, src/pages/details/ocpDetails/ocpDetails.tsx, src/routes.tsx
The Redirect solution is not working in production (i.e., CI beta), so I've implemented a workaround using Routes.
=> Removed redirect in favor of route workaround

src/locales/en.json
=> fix(costmodels): add translation to the cluster metrics

src/locales/en.json
related to #1448 
//cc @nlcwong @chambridge
=> fix(costmodels): change to infrastructure cost in the table header 

src/locales/en.json, src/pages/costModels/createCostModelWizard/review.tsx
=> fix(costmodels): hide price list table in review if there are no rates

src/locales/en.json, src/pages/details/awsDetails/detailsHeader.tsx, src/pages/details/azureDetails/detailsHeader.tsx
Infrastructure details page title says “Cloud details”, should change to “Infrastructure details”
https://github.com/project-koku/koku-ui/issues/1463
=> Infrastructure details page title

src/components/reports/reportSummary/reportSummaryItems.test.tsx
Updated unit test for report summary
=> Updated unit test for report summary

src/pages/costModels/components/priceListToolbar.tsx, src/pages/costModels/components/toolbar/checkboxSelector.tsx, src/pages/costModels/components/toolbar/primarySelector.tsx, src/pages/costModels/costModelsDetails/components/priceListTable.tsx, src/pages/costModels/createCostModelWizard/priceListTable.tsx
=> fix(costmodels): disable price list filter on no rates

src/locales/en.json, src/store/rbac/actions.ts
=> fix(costmodels): show alert message on rbac request failure

src/locales/en.json, src/pages/costModels/components/addCostModelRateForm.tsx, src/pages/costModels/components/addPriceList.test.tsx, src/pages/costModels/components/addPriceList.tsx, src/pages/costModels/components/rateTable.tsx, src/pages/costModels/costModelsDetails/components/addRateModal.test.tsx, src/pages/costModels/costModelsDetails/components/addRateModal.tsx, src/pages/costModels/costModelsDetails/components/priceListTable.tsx, src/pages/costModels/costModelsDetails/components/updateRateModel.tsx, src/pages/costModels/createCostModelWizard/index.tsx, src/store/metrics/selectors.ts
=> fix(costmodels): Use cost type instead of infra cost

src/pages/overview/overview.tsx
Refactor tabs for when various providers are not available.
https://github.com/project-koku/koku-ui/issues/1476
=> Refactor tabs for when various providers are not available

src/pages/details/components/toolbar/toolbar.tsx
Updated export icon
https://github.com/project-koku/koku-ui/issues/1496
=> Updated export icon

src/pages/costModels/costModelsDetails/components/priceListTable.tsx
=> fix(costmodels): center emptystate & compact pgntn in price list tab

src/pages/costModels/costModelsDetails/costModelsDetails.tsx
=> fix(costmodels): add description to filtervalue

src/pages/costModels/createCostModelWizard/sources.tsx, src/pages/costModels/createCostModelWizard/table.tsx
=> fix(costmodels): fix source type to Azure when filtering sources

src/pages/costModels/costModelsDetails/costModelsTable.tsx
=> fix(costmodels): set a grid breakpoint to the table

src/locales/en.json
=> display cluster/node in openshift price list modal

src/components/charts/costChart/costChart.tsx, src/components/charts/trendChart/trendChart.tsx, src/components/charts/usageChart/usageChart.tsx
Adjust timeout to resize charts upon Insights nav toggle.
https://github.com/project-koku/koku-ui/issues/1504
=> Adjust timeout to resize charts

src/pages/overview/overview.tsx
Incorrect overview cards displayed for missing Ocp provider
https://github.com/project-koku/koku-ui/issues/1544
=> Incorrect overview cards displayed for missing Ocp provider

src/pages/costModels/costModelsDetails/emptyState.tsx
=> fix(costmodels): disable action button in empty state on read-only

src/pages/costModels/costModelsDetails/addSourceStep.tsx, src/pages/costModels/costModelsDetails/components/table.tsx, src/pages/costModels/createCostModelWizard/table.tsx
Refactored code to utilize 'DataToolbar' apposed to 'Toolbar'
=> changes to stay inline with patternfly V4

src/app.tsx
Maintenance mode should be disabled by default
=> disable maintenance mode

src/locales/en.json, src/pages/costModels/costModelsDetails/addSourceStep.tsx, src/pages/costModels/costModelsDetails/addSourceWizard.tsx, src/pages/costModels/createCostModelWizard/table.tsx
=> fix(costmodels): disable assigning assigned source to cost model

src/locales/en.json
need your review: @dayleparker @nlcwong @lcouzens 
Related to https://issues.redhat.com/browse/COST-54
=> fix(costmodels): update the assign sources step description

src/api/metrics.test.ts, src/api/rbac.test.ts
@dlabrecq  should i open a ticket for this on JIRA?
=> test(api): add unit tests to metrics and rbac

src/pages/costModels/createCostModelWizard/parseError.test.ts
=> test(costmodels): add unit tests to parseApiError

src/store/sourceSettings/__snapshots__/store.test.ts.snap, src/store/sourceSettings/store.test.ts
add unit tests to cost model sources
=> chore(redux): add unit tests to cost model sources

src/store/costModels/selectors.ts, src/store/djangoUtils/pagination.ts, src/store/djangoUtils/query.ts, src/store/djangoUtils/types.ts, src/store/sourceSettings/selectors.ts
Small refactor - created a selector for pagination and query data that comes from the Koku backend
=> refactor(store): django pagination and query selectors

src/pages/costModels/costModelsDetails/costModelsDetails.tsx, src/pages/costModels/costModelsDetails/costModelsTable.tsx
1) the delete option in the kebab option is black
2) the view cost model was removed from the kebab option
3) the upper pagination is in compact variation
=> fix(costmodels): use compact pagination + remove view opt from kebab

src/pages/costModels/costModel/header.tsx, src/pages/costModels/costModelsDetails/costModelsDetails.styles.ts
=> fix(costmodels): update cost model details header title size + padding

src/pages/costModels/components/priceListToolbar.styles.ts, src/pages/costModels/components/priceListToolbar.tsx, src/pages/costModels/costModel/costModelInfo.styles.ts, src/pages/costModels/costModelsDetails/components/priceListTable.tsx
=> fix(costmodels): remove padding, add pagintn footer, delete color black

src/locales/en.json, src/pages/costModels/costModelsDetails/components/updateCostModel.tsx
=> fix(costmodels): remove name from title in the cost model edit dialog

src/api/queries/query.ts, src/api/reports/awsReports.ts, src/api/reports/report.ts, src/components/charts/common/chartUtils.ts, src/pages/dashboard/components/dashboardWidget.test.tsx, src/pages/details/awsBreakdown/awsBreakdown.tsx, src/pages/details/awsDetails/awsDetails.tsx, src/pages/details/awsDetails/detailsTable.tsx, src/pages/details/components/breakdown/breakdownHeader.tsx, src/pages/details/components/costOverview/costOverviewBase.tsx, src/pages/details/components/historicalData/historicalDataBase.tsx, src/pages/details/components/historicalData/historicalDataCostChart.tsx, src/pages/details/components/historicalData/historicalDataTrendChart.tsx, src/pages/details/components/historicalData/historicalDataUsageChart.tsx, src/pages/details/components/summary/summaryCard.tsx, src/pages/details/components/summary/summaryModalView.tsx, src/pages/details/components/tag/tag.tsx, src/pages/details/components/tag/tagLink.tsx, src/pages/details/components/tag/tagView.tsx, src/pages/details/components/usageChart/usageChart.tsx, src/pages/details/components/utils/groupBy.tsx, src/utils/computedReport/getComputedReportItems.ts
Refactored AWS org units for new aws/cost API changes, related to group_by -- https://issues.redhat.com/browse/COST-310.
https://issues.redhat.com/browse/COST-356
=> COST-356: Refactored AWS org units

src/locales/en.json, src/pages/costModels/costModel/header.tsx, src/pages/costModels/costModelsDetails/addSourceStep.tsx, src/pages/costModels/costModelsDetails/addSourceWizard.tsx, src/pages/costModels/costModelsDetails/components/priceListTable.tsx, src/pages/costModels/costModelsDetails/components/table.tsx, src/pages/costModels/costModelsDetails/components/updateRateModel.styles.ts, src/pages/costModels/costModelsDetails/components/updateRateModel.tsx, src/pages/costModels/costModelsDetails/costModelsTable.tsx
=> fix(costmodels): assign-sources/pricelist fit & finish

src/pages/details/awsDetails/awsDetails.tsx, src/pages/details/azureDetails/azureDetails.tsx, src/pages/details/ocpDetails/ocpDetails.tsx
During testing, the AWS empty state is being shown instead of 403 error. The providers API may be returning before the reports API?
https://issues.redhat.com/browse/COST-390
=> AWS empty state is being shown instead of 403 error

src/locales/en.json, src/pages/details/components/actions/actions.tsx, src/store/costModels/actions.ts
=> feat(details): view cost model details from price list modal

src/pages/details/awsDetails/awsDetails.tsx, src/pages/details/awsDetails/detailsTable.tsx, src/pages/details/awsDetails/detailsToolbar.tsx, src/pages/details/azureDetails/azureDetails.tsx, src/pages/details/components/export/exportSubmit.tsx, src/pages/details/ocpDetails/ocpDetails.tsx, src/utils/computedReport/getComputedReportItems.ts
Enabled CSV export for AWS org units.
https://issues.redhat.com/browse/COST-488
=> Export AWS orgs

.travis/check_manifest.sh
Fixed error message so that it matched target name.
=> Fixed error message so that it matches target name.

archive/pages/details/ocpCloudDetails/detailsHeader.tsx, src/locales/en.json, src/pages/costModels/costModelsDetails/header.tsx, src/pages/details/components/costChart/costChart.tsx, src/pages/details/components/costOverview/costOverviewBase.tsx, src/pages/details/ocpDetails/detailsHeader.styles.ts, src/pages/details/ocpDetails/detailsHeader.tsx, src/pages/overview/overview.styles.ts, src/pages/overview/overview.tsx
Added popover to describe cost model terminology in breakdown chart
https://issues.redhat.com/browse/COST-496
=> COST-496 - Describe cost model terminology in application

src/pages/details/components/export/exportModal.tsx, src/pages/details/components/export/exportSubmit.tsx
The CSV export modal is generating a query which is not supported by the API.
"Multiple org_unit_id must be represented with the or: prefix."
https://issues.redhat.com/browse/COST-560
=> Export fails when doing view by OU and filter by OU

src/pages/details/azureDetails/azureDetailsTable.scss, src/pages/details/azureDetails/detailsTable.styles.ts, src/pages/details/azureDetails/detailsTable.tsx
=> remove emotion from Azure Details Table

src/pages/costModels/components/tagRateTable.tsx
=> fix(costmodels): add aria-label in tag rate table

src/pages/details/components/breakdown/breakdownHeader.scss, src/pages/details/components/breakdown/breakdownHeader.styles.ts, src/pages/details/components/breakdown/breakdownHeader.tsx
=> remove emotion from breakdownHeader

src/pages/details/awsDetails/detailsHeader.styles.ts, src/pages/details/azureDetails/detailsHeader.styles.ts
https://issues.redhat.com/browse/COST-604
**Before**
**After**
=> Tertiary nav alignment

src/locales/en.json, src/pages/costModels/costModelsDetails/components/priceListTable.tsx
=> fix(costmodels): show rate's metric in delete dialog

src/pages/details/components/cluster/clusterModal.tsx, src/pages/details/components/dataToolbar/dataToolbar.scss, src/pages/details/components/dataToolbar/dataToolbar.styles.ts, src/pages/details/components/dataToolbar/dataToolbar.tsx
=> remove emotion from dataToolbar

src/pages/details/components/priceList/priceListModal.scss, src/pages/details/components/priceList/priceListModal.styles.ts, src/pages/details/components/priceList/priceListModal.tsx
Work has been done for the following directories:
- pages/details/components/priceListModel
=> remove emotion from priceListModal

src/pages/details/components/summary/summaryModal.scss, src/pages/details/components/summary/summaryModal.styles.ts, src/pages/details/components/summary/summaryModal.tsx
=> remove emotion from summaryModal

src/__mocks__/react-i18next.ts, src/pages/costModels/components/addPriceList.test.tsx, src/pages/costModels/components/addPriceList.tsx, src/pages/costModels/components/inputs/rateInput.tsx, src/pages/costModels/components/inputs/selector.tsx, src/pages/costModels/components/inputs/simpleInput.tsx, src/pages/costModels/components/rateForm/rateForm.tsx, src/pages/costModels/components/rateForm/taggingRatesForm.tsx, src/pages/costModels/costModelsDetails/components/updateRateModel.test.tsx, src/pages/costModels/costModelsDetails/components/updateRateModel.tsx
=> chore(costmodels): enable tests again by stubbing useTranslation

src/pages/details/ocpDetails/detailsTable.scss, src/pages/details/ocpDetails/detailsTable.styles.ts, src/pages/details/ocpDetails/detailsTable.tsx
=> remove emotion from ocp detailsTable

src/pages/costModels/costModelsDetails/header.tsx
=> fix(costmodels): remove styling from cost models details header

src/app.tsx, src/globals.d.ts
=> chore(routes): add additional app data to improve Pendo

src/pages/costModels/costModelsDetails/components/dialog.tsx, src/pages/costModels/createCostModelWizard/index.tsx
=> fix(costmodels): add aria-label to Modal with custom header

src/locales/en.json, src/pages/costModels/components/errorState.tsx, src/pages/costModels/costModel/index.tsx, src/pages/costModels/costModelsDetails/addSourceStep.tsx, src/pages/costModels/costModelsDetails/addSourceWizard.tsx, src/pages/costModels/costModelsDetails/components/priceListTable.tsx, src/pages/costModels/costModelsDetails/costModelsDetails.tsx, src/pages/costModels/createCostModelWizard/sources.tsx, src/pages/costModels/createCostModelWizard/table.tsx
=> fix(costmodels): update error empty states to platforms

scripts/utils/i18n_excludes, scripts/utils/i18n_key_tool.py, src/components/charts/common/chartUtils.test.ts, src/locales/en.json
Cleanup of i18n keys, first of many. I am keeping these PR's small to make reviews easier
=> Rm dead i18n

src/api/rates.ts, src/locales/en.json, src/pages/costModels/components/addPriceList.test.tsx, src/pages/costModels/components/addPriceList.tsx, src/pages/costModels/components/rateForm/constants.ts, src/pages/costModels/components/rateForm/hasDiff.ts, src/pages/costModels/components/rateForm/useRateForm.tsx, src/pages/costModels/components/rateForm/utils.tsx, src/pages/costModels/components/rateTable.test.tsx, src/pages/costModels/components/rateTable.tsx, src/pages/costModels/costModelsDetails/components/addRateModal.tsx, src/pages/costModels/costModelsDetails/components/updateRateModel.test.tsx, src/pages/costModels/costModelsDetails/components/updateRateModel.tsx, src/pages/costModels/createCostModelWizard/context.ts, src/pages/costModels/createCostModelWizard/index.tsx
closes COST 713
related to https://github.com/project-koku/koku/pull/2497
=> fix(costmodels): update tag rates API + add tag key validation

src/locales/en.json
it looks like these keys are not being used anywhere
=> Rm details i18n keys

scripts/utils/i18n_excludes, src/locales/en.json
Some keys added to the exclude list some removed
=> Rm i18n breakdown keys

scripts/utils/i18n_excludes, scripts/utils/i18n_key_tool.py, src/locales/en.json
Removed more i18n keys that were dead.
Also added logic to i18n test tool to automatically exclude *_plural tag if the non-plural matching tag is found
=> Rm i18n keys

src/pages/details/gcpDetails/detailsTable.tsx
=> fix for name sort

scripts/utils/i18n_excludes, src/locales/en.json
added a few keys to excludelist
removed keys that were not being used
=> cleanup of source_details i18n keys

src/api/forecasts/azureForecast.ts, src/api/forecasts/forecastUtils.ts, src/components/charts/costChart/costChart.tsx, src/pages/costModels/components/addPriceList.test.tsx, src/pages/costModels/costModelsDetails/addSourceStep.tsx, src/pages/costModels/createCostModelWizard/sources.tsx, src/pages/dashboard/azureDashboard/azureDashboardWidget.tsx, src/store/dashboard/awsDashboard/awsDashboardSelectors.ts, src/store/dashboard/awsDashboard/awsDashboardWidgets.ts, src/store/dashboard/azureDashboard/azureDashboardActions.ts, src/store/dashboard/azureDashboard/azureDashboardSelectors.ts, src/store/dashboard/azureDashboard/azureDashboardWidgets.ts
Created the initial Azure cost forecast and cone of confidence.
https://issues.redhat.com/browse/COST-737
=> Azure cost forecast

src/locales/en.json
Bug Fix: key name for "cost_models_router.error_title"
Also removed unused provider keys
=> removed unused provider keys

src/pages/costModels/createCostModelWizard/priceListTable.tsx
=> fix(costmodels): filter rate by metric using metric labels

src/api/forecasts/azureCloudForecast.ts, src/api/forecasts/forecast.ts, src/api/forecasts/forecastUtils.ts, src/pages/dashboard/azureCloudDashboard/azureCloudDashboardWidget.tsx, src/store/dashboard/azureCloudDashboard/azureCloudDashboardActions.ts, src/store/dashboard/azureCloudDashboard/azureCloudDashboardCommon.ts, src/store/dashboard/azureCloudDashboard/azureCloudDashboardSelectors.ts, src/store/dashboard/azureCloudDashboard/azureCloudDashboardWidgets.ts
Added the "Microsoft Azure filtered by OpenShift" forecast
https://issues.redhat.com/browse/COST-826
=> "Microsoft Azure filtered by OpenShift" forecast

src/api/forecasts/awsCloudForecast.ts, src/api/forecasts/forecast.ts, src/api/forecasts/forecastUtils.ts, src/pages/dashboard/awsCloudDashboard/awsCloudDashboardWidget.tsx, src/store/dashboard/awsCloudDashboard/awsCloudDashboardActions.ts, src/store/dashboard/awsCloudDashboard/awsCloudDashboardCommon.ts, src/store/dashboard/awsCloudDashboard/awsCloudDashboardSelectors.ts, src/store/dashboard/awsCloudDashboard/awsCloudDashboardWidgets.ts
Added the "Amazon Web Services filtered by OpenShift" forecast
https://issues.redhat.com/browse/COST-825
=> "Amazon Web Services filtered by OpenShift" forecast

src/api/forecasts/forecast.ts, src/api/forecasts/forecastUtils.ts, src/api/forecasts/ocpCloudForecast.ts, src/pages/dashboard/ocpCloudDashboard/ocpCloudDashboardWidget.tsx, src/store/dashboard/ocpCloudDashboard/ocpCloudDashboardActions.ts, src/store/dashboard/ocpCloudDashboard/ocpCloudDashboardCommon.ts, src/store/dashboard/ocpCloudDashboard/ocpCloudDashboardSelectors.ts, src/store/dashboard/ocpCloudDashboard/ocpCloudDashboardWidgets.ts
Added the "All cloud filtered by OpenShift" forecast
https://issues.redhat.com/browse/COST-824
=> "All cloud filtered by OpenShift" forecast

src/api/forecasts/forecast.ts, src/api/forecasts/ocpForecast.ts, src/pages/dashboard/components/dashboardWidgetBase.tsx, src/pages/dashboard/ocpSupplementaryDashboard/ocpSupplementaryDashboard.tsx, src/pages/dashboard/ocpSupplementaryDashboard/ocpSupplementaryDashboardWidget.tsx, src/store/dashboard/ocpSupplementaryDashboard/ocpSupplementaryDashboardActions.ts, src/store/dashboard/ocpSupplementaryDashboard/ocpSupplementaryDashboardCommon.ts, src/store/dashboard/ocpSupplementaryDashboard/ocpSupplementaryDashboardSelectors.ts, src/store/dashboard/ocpSupplementaryDashboard/ocpSupplementaryDashboardWidgets.ts
Added supplementary forecast
https://issues.redhat.com/browse/COST-816
=> Add supplementary forecast

src/pages/dashboard/components/dashboardWidgetBase.tsx
Ensure date exists for reported values.
https://issues.redhat.com/browse/COST-799
=> Ensure date exists for reported values

src/pages/costModels/components/addPriceList.test.tsx, src/pages/costModels/components/rateForm/rateForm.tsx, src/pages/costModels/components/rateForm/taggingRatesForm.tsx, src/pages/costModels/components/rateForm/useRateForm.tsx, src/pages/costModels/components/rateForm/utils.tsx
do not merge before https://github.com/project-koku/koku/pull/2543
closes COST 833
=> fix(costmodels): allow for $0 rate

src/pages/dashboard/components/dashboardWidgetBase.tsx
Adding an additional user to facilitate rbac testing in CI (@esebesto @lcouzens )
=> Adding cost-management user to the allowed forecast list

src/utils/permissions.ts
This should include the "admin" wildcard access check for any RBAC permissions in the UI.
=> Add wildcard checking to rbac permissions check

src/api/reports/gcpReports.test.ts, src/api/reports/gcpReports.ts, src/api/tags/gcpTags.test.ts, src/api/tags/gcpTags.ts, src/locales/en.json, src/store/costOverview/gcpCostOverview/gcpCostOverviewReducer.ts, src/store/dashboard/gcpDashboard/gcpDashboard.test.ts, src/store/dashboard/gcpDashboard/gcpDashboardReducer.ts, src/store/dashboard/gcpDashboard/gcpDashboardWidgets.ts
Initial addition of GCP charts/stats
=> Enable gcp cost 866

scripts/utils/i18n_key_tool.py
A simple change that adds status notation in the report
=> Added status for found i18n key, looks cleaner.

src/pages/details/awsDetails/awsDetails.tsx, src/pages/details/azureDetails/azureDetails.tsx, src/pages/details/gcpDetails/gcpDetails.tsx, src/pages/details/ocpDetails/ocpDetails.tsx, src/pages/overview/overview.tsx
Cleanup unused code in the overview. 
https://issues.redhat.com/browse/COST-933
=> Cleanup unused code

src/pages/costModels/costModelsDetails/dialog.test.tsx, src/pages/costModels/costModelsDetails/table.test.tsx
=> chore(tests): fix unit test warnings

src/pages/dashboard/awsDashboard/awsDashboardWidget.tsx, src/pages/dashboard/components/dashboardWidgetBase.tsx
Remove unused `forecastFetchStatus` from `dashboardWidgetBase`.
https://issues.redhat.com/browse/COST-948
=> Remove unused forecastFetchStatus

src/api/costModels.data.ts, src/pages/costModels/costModelsDetails/toolbar.test.tsx, src/pages/costModels/costModelsDetails/utils/filters.tsx
=> fix(costmodels): remove description filter on clear all

src/store/costOverview/gcpCostOverview/gcpCostOverviewReducer.ts, src/store/dashboard/gcpDashboard/gcpDashboard.test.ts, src/store/dashboard/gcpDashboard/gcpDashboardReducer.ts, src/store/dashboard/gcpDashboard/gcpDashboardWidgets.ts
Closes: https://issues.redhat.com/browse/COST-918
Add GCP database charts
=> add gcp database views

src/store/dashboard/gcpDashboard/gcpDashboard.test.ts, src/store/dashboard/gcpDashboard/gcpDashboardReducer.ts, src/store/dashboard/gcpDashboard/gcpDashboardWidgets.ts
Closes: https://issues.redhat.com/browse/COST-919
=> add gcp network views

src/components/charts/common/chartUtils.ts, src/components/charts/dailyCostChart/dailyCostChart.tsx
`chartUtils` does not properly initialize domain with zero values. And a little clean up in `dailyCostChart`.
https://issues.redhat.com/browse/COST-957
=> Incorrect min domain shown for daily charts

src/api/queries/gcpQuery.ts, src/api/reports/gcpReports.ts, src/pages/dashboard/gcpDashboard/gcpDashboardWidget.test.tsx, src/pages/dashboard/gcpDashboard/gcpDashboardWidget.tsx, src/store/dashboard/gcpDashboard/gcpDashboardCommon.ts, src/store/dashboard/gcpDashboard/gcpDashboardWidgets.ts
Closes: https://issues.redhat.com/browse/COST-965
=> Gcp project cost 965

src/components/charts/common/chartDatumUtils.ts, src/components/charts/historicalExplorerChart/historicalExplorerChart.styles.ts, src/components/charts/historicalExplorerChart/historicalExplorerChart.tsx, src/components/charts/historicalExplorerChart/index.ts, src/locales/en.json, src/pages/explorer/explorer.styles.ts, src/pages/explorer/explorer.tsx, src/pages/explorer/explorerChart.styles.ts, src/pages/explorer/explorerChart.tsx, src/utils/computedReport/getComputedReportItems.ts
Added historical chart to explorer page.
=> Add chart to explorer page

src/api/reports/gcpReports.ts, src/api/reports/report.ts, src/pages/details/gcpDetails/detailsHeader.tsx, src/pages/details/gcpDetails/detailsToolbar.tsx, src/utils/computedReport/getComputedGcpReportItems.ts
Closes: https://issues.redhat.com/browse/COST-963
=> updates to GCP to allow 'project' to be used with group by and order by

config/spandx.config.js
Got tired of the linter complaining every time I need test Insights cloud-services-config
=> Formatted spandx for linter

src/store/dashboard/gcpDashboard/gcpDashboard.test.ts, src/store/dashboard/gcpDashboard/gcpDashboardReducer.ts
Closes: https://issues.redhat.com/browse/COST-920
=> add gcp storage charts

package.json, scripts/utils/i18n_key_tool.py
=> initial tooling to check for duplicate values in i18n keys

src/pages/costModels/costModelsDetails/createCostModelButton.tsx
Simple fix
https://issues.redhat.com/browse/COST-1007
=> Cost models button shows broken i18n key

scripts/utils/i18n_key_tool.py
we now appear to be capturing all duplicates in the i18n key values
Preview of total results...
=> fixed missing key matches

src/pages/explorer/explorer.tsx, src/pages/explorer/explorerTable.tsx
The cost reports have many missing days of data. As a result, the data shown may not appear in the correct table column.
This change ensures each column has the correct data and fills in any missing data with a "no data" message.
=> Explorer: Account for missing data

archive/pages/details/components/nav/tertiaryNav.tsx, archive/pages/details/ocpCloudDetails/ocpCloudDetails.tsx, src/app.tsx, src/components/async/permissionsComponent/permissions.tsx, src/pages/costModels/costModel/index.tsx, src/pages/details/awsDetails/awsDetails.tsx, src/pages/details/azureDetails/azureDetails.tsx, src/pages/details/components/breakdown/breakdownBase.tsx, src/pages/details/gcpDetails/gcpDetails.tsx, src/pages/details/ocpDetails/ocpDetails.tsx, src/pages/explorer/explorer.tsx, src/pages/explorer/explorerChart.tsx, src/pages/explorer/explorerHeader.tsx, src/pages/state/loading/loading.tsx, src/pages/state/noData/noData.tsx, src/pages/state/noData/noDataState.tsx, src/pages/state/noProviders/noProviders.tsx, src/pages/state/noProviders/noProvidersState.tsx, src/pages/state/notAuthorized/notAuthorized.tsx, src/pages/state/notAuthorized/notAuthorizedState.tsx, src/pages/state/notAvailable/notAvailable.tsx
It looks like this change is required for the UI to work with Chrome 2.0.
https://issues.redhat.com/browse/COST-1018
=> Changed react-router imports to use react-router-dom

src/locales/en.json, src/pages/views/explorer/explorerUtils.ts
Closes: https://issues.redhat.com/browse/COST-1082
name change on key
Key used here:
=> fixed typo in i18n key

src/store/breakdown/costOverview/gcpCostOverview/gcpCostOverview.test.ts, src/store/breakdown/costOverview/gcpCostOverview/gcpCostOverviewReducer.ts, src/store/breakdown/costOverview/gcpCostOverview/gcpCostOverviewWidgets.ts
Closes: https://issues.redhat.com/browse/COST-1023
Updated GCP details views to include "project" card
view by account:
view by project:
view by service:
view by region:
=> Gcp page breakdwn cost 1023

src/locales/en.json, src/pages/views/components/export/exportModal.tsx, src/pages/views/components/groupBy/groupBy.tsx, src/pages/views/explorer/explorer.tsx
Small fit and finish changes after reviewing with Natalie
=> Historical Cost Explorer fit and finish

src/components/charts/common/chartDatumUtils.ts, src/components/charts/trendChart/trendChart.tsx, src/locales/en.json, src/modules/ocpOverviewWidget/ocpOverviewChart.tsx, src/modules/ocpOverviewWidget/ocpOverviewWidget.tsx, webpack.config.js
Updated federated module to handle missing i18next dependency
https://issues.redhat.com/browse/COST-1124
=> OCP widget as federated module

src/locales/en.json, src/pages/views/details/ocpDetails/detailsHeader.tsx, src/pages/views/overview/overview.tsx, src/routes.tsx
removed unused i18n key(s) 
consolidated keys to remove duplicates
=> consolidated "Cost Management Overview" key value

src/pages/costModels/costModelsDetails/noCostModels.tsx
Closes: https://issues.redhat.com/browse/COST-1010
=> add "create cost model" button to empty state page

src/locales/en.json
closes: https://issues.redhat.com/browse/COST-1015
=> change wording in cost model markup|discount

src/components/async/permissionsComponent/permissions.tsx, src/pages/views/explorer/explorer.tsx, src/pages/views/explorer/explorerHeader.tsx, src/pages/views/explorer/explorerUtils.ts, src/pages/views/overview/overview.tsx, src/utils/userAccess.ts
Refactored user-access utils to a common area.
This will ensure all pages are testing user-access API props in the same way.
We also won't need to rewrite code for use with the `beta=true` flag.
https://issues.redhat.com/browse/COST-1172
=> Refactored user-access utils

src/pages/views/details/awsDetails/awsDetails.tsx, src/utils/computedReport/getComputedReportItems.ts
This ensures sub orgs are displayed properly for root orgs
https://issues.redhat.com/browse/COST-1173
=> Ensure sub orgs are displayed properly

src/store/dashboard/ocpDashboard/ocpDashboardWidgets.ts
Closes: https://issues.redhat.com/browse/COST-1179
=> fix i18n key variable

webpack.config.js
Disabled the federated module widget used for testing
=> Disabled federated module widget

src/store/dashboard/awsCloudDashboard/awsCloudDashboardWidgets.ts, src/store/dashboard/awsDashboard/awsDashboardWidgets.ts, src/store/dashboard/azureCloudDashboard/azureCloudDashboardWidgets.ts, src/store/dashboard/azureDashboard/azureDashboardWidgets.ts, src/store/dashboard/gcpDashboard/gcpDashboardWidgets.ts, src/store/dashboard/ibmDashboard/ibmDashboardWidgets.ts, src/store/dashboard/ocpCloudDashboard/ocpCloudDashboardWidgets.ts, src/store/dashboard/ocpDashboard/ocpDashboardWidgets.ts, src/store/dashboard/ocpSupplementaryDashboard/ocpSupplementaryDashboardWidgets.ts, src/store/dashboard/ocpUsageDashboard/ocpUsageDashboardWidgets.ts
Closes: https://issues.redhat.com/browse/COST-1179 
There were some keys that were consolidated in an earlier PR, some of the references were missed when doing the sweep.
=> Fixes for i18n keys that were consolidated

src/api/providers.ts, src/api/userAccess.ts, src/store/providers/providersCommon.ts, src/store/userAccess/userAccessCommon.ts
issue: https://issues.redhat.com/browse/COST-1194
=> we are not displaying the proper IBM empty state page

src/pages/views/explorer/explorer.tsx, src/pages/views/explorer/explorerChart.tsx, src/pages/views/explorer/explorerFilter.tsx, src/pages/views/explorer/explorerHeader.tsx, src/pages/views/explorer/explorerTable.tsx, src/pages/views/explorer/explorerUtils.ts
Modified the Cost Explorer default perspective to be based on user RBAC permissions (i.e., using our UserAccess utils)
https://issues.redhat.com/browse/COST-1205
=> Explorer default should be based on page permissions

src/components/charts/common/chartUtils.ts, src/components/charts/costChart/costChart.tsx, src/components/charts/costExplorerChart/costExplorerChart.tsx, src/components/charts/dailyCostChart/dailyCostChart.tsx, src/components/charts/dailyTrendChart/dailyTrendChart.tsx, src/components/charts/historicalCostChart/historicalCostChart.tsx, src/components/charts/historicalTrendChart/historicalTrendChart.tsx, src/components/charts/historicalUsageChart/historicalUsageChart.tsx, src/components/charts/trendChart/trendChart.tsx, src/components/charts/usageChart/usageChart.tsx
Closes: https://issues.redhat.com/browse/COST-1200
These changes are to fix an intermittent failure that "Sentry" is reporting
=> changes for "ResizeObserver loop limit exceeded"

webpack.config.js
closes: https://issues.redhat.com/browse/COST-1223
=> show files that were changed during auto compilation in dev mode

src/locales/en.json, src/pages/costModels/components/inputs/simpleInput.tsx, src/pages/costModels/components/rateForm/rateForm.tsx, src/pages/costModels/components/rateForm/taggingRatesForm.tsx
Closes: https://issues.redhat.com/browse/COST-1188
=> change to displayed title on button

webpack.config.js
closes: https://issues.redhat.com/browse/COST-1234
https://user-images.githubusercontent.com/57504257/112659869-35115b80-8e2b-11eb-8fe8-b0f3c50626f3.mov
=> see compilation progress in real time

src/components/reports/reportSummary/reportSummary.tsx, src/components/reports/reportSummary/reportSummaryAlt.tsx, src/components/reports/reportSummary/reportSummaryItems.tsx, src/modules/ocpOverviewWidget/ocpOverviewChart.tsx, src/pages/views/details/components/costChart/costChart.tsx, src/pages/views/details/components/historicalData/historicalDataCostChart.tsx, src/pages/views/details/components/historicalData/historicalDataTrendChart.tsx, src/pages/views/details/components/historicalData/historicalDataUsageChart.tsx, src/pages/views/details/components/summary/summaryCard.tsx, src/pages/views/details/components/usageChart/usageChart.tsx, src/pages/views/explorer/explorerChart.tsx
closes: https://issues.redhat.com/browse/COST-974
Replace the components from the @redhat-cloud-services/frontend-components/components/Skeleton package with components available from PatternFly
Before Changes:
After Changes:
=> Skeleton chg cost 974

src/pages/views/explorer/explorerUtils.ts, src/utils/dateRange.ts
We need to set the first day before subtracting the month.
https://issues.redhat.com/browse/COST-1249
=> Incorrect start_date param in previous_month_to_date preset

src/locales/en.json, src/pages/costModels/components/rateForm/rateForm.tsx, src/pages/costModels/components/rateForm/taggingRatesForm.tsx, src/pages/costModels/components/rateTable.tsx, src/pages/costModels/components/tagRateTable.tsx, src/pages/costModels/costModel/addSourceStep.tsx, src/pages/costModels/costModel/addSourceWizard.tsx, src/pages/costModels/costModel/sourcesTable.tsx, src/pages/costModels/costModel/table.tsx, src/pages/costModels/costModel/updateCostModel.tsx, src/pages/costModels/costModelsDetails/table.tsx, src/pages/costModels/costModelsDetails/utils/filters.tsx, src/pages/costModels/costModelsDetails/utils/toolbar.tsx, src/pages/costModels/createCostModelWizard/generalInformation.tsx, src/pages/costModels/createCostModelWizard/review.tsx, src/pages/costModels/createCostModelWizard/table.tsx
combined some duplicate key/value pairs.
=> I18n cleanup cost 727

src/pages/costModels/costModelsDetails/utils/filters.tsx
closes: https://issues.redhat.com/browse/COST-1274
These changes fix the deformation of the toolbar when you select the search input to filter by Name or Description.
https://user-images.githubusercontent.com/57504257/114562159-408ec000-9c3c-11eb-9996-849dff375da3.mov
=> fix for cost model filter search input

src/locales/en.json
Updated links to reflect latest docs.
https://issues.redhat.com/browse/COST-1266
=> Updated doc links

koku-ui-manifest, package.json, webpack.config.js, yarn.lock
Updated webpack-dev-server version as well as config changes. 
The changes shoudl help in debug mode and also get rid of the websocket errors when running dev server
=> Upgrade webpack dev server

src/locales/en.json, src/pages/costModels/components/addPriceList.test.tsx, src/pages/costModels/components/inputs/rateInput.tsx, src/pages/costModels/components/rateForm/constants.ts, src/pages/costModels/components/rateForm/rateForm.tsx, src/pages/costModels/components/rateForm/taggingRatesForm.tsx, src/pages/costModels/components/rateTable.tsx, src/pages/costModels/components/tagRateTable.tsx, src/pages/costModels/costModel/updateRateModel.test.tsx, src/pages/costModels/createCostModelWizard/steps.tsx
=> Removed duplicate keys on cost-models area

package.json, scripts/utils/i18n_excludes, scripts/utils/i18n_key_tool.py
Closes: https://issues.redhat.com/browse/COST-1346
Add in i18n exclude list key validation.  This tooling will alow us to make sure any key value we have in the exclude list is an actual i18n key.
Example of output:
=> added i18n exclude list key validation

src/pages/state/notAuthorized/notAuthorizedState.tsx, src/pages/views/explorer/explorer.tsx, src/pages/views/explorer/explorerChart.tsx, src/pages/views/explorer/explorerFilter.tsx, src/pages/views/explorer/explorerHeader.tsx, src/pages/views/explorer/explorerTable.tsx, src/pages/views/explorer/explorerUtils.ts
Fixed default perspective menu for Cost Explorer.
https://issues.redhat.com/browse/COST-1339
https://issues.redhat.com/browse/COST-1340
=> Cost Explorer perspective

src/locales/en.json, src/pages/costModels/costModelsDetails/header.tsx, src/pages/costModels/costModelsDetails/noCostModels.tsx, src/pages/costModels/createCostModelWizard/generalInformation.tsx, src/pages/views/details/components/costOverview/costOverviewBase.tsx
Added learn more links to cost models popup and empty state.
Popup
Empty state
=> Add learn more links

src/locales/en.json, src/pages/costModels/components/errorState.tsx, src/pages/costModels/createCostModelWizard/priceListTable.tsx, src/pages/costModels/createCostModelWizard/review.tsx
closes: https://issues.redhat.com/browse/COST-1373
=> fixed empty and error state i18n for cost model sources

src/locales/en.json, src/pages/views/components/dataToolbar/dataToolbar.tsx, src/pages/views/details/components/columnManagement/columnManagementModal.tsx, src/pages/views/details/ocpDetails/detailsTable.tsx, src/pages/views/details/ocpDetails/detailsToolbar.tsx, src/pages/views/details/ocpDetails/ocpDetails.tsx
Added column management support to the OCP details table.
https://issues.redhat.com/browse/COST-1506
=> Column management

webpack.config.js
Fixes need to declare patternfly separate by using https://github.com/RedHatInsights/frontend-components/blob/master/packages/config-utils/federated-modules.js
=> fix(webpack): use upstream federated config

src/components/async/permissionsComponent/permissions.tsx
The Permissions component should match paths exactly.
https://issues.redhat.com/browse/COST-1578
=> Update permissions to match exact path

src/pages/views/components/dataToolbar/dataToolbar.tsx, src/pages/views/components/resourceTypeahead/resourceSelect.tsx, src/pages/views/components/resourceTypeahead/resourceTypeahead.tsx
Added `onCreateOption` functionality to AWS typeahead feature. This allows users to provide input other than what the typehead API provides.
https://issues.redhat.com/browse/COST-1597
=> 1597 typeahead

src/store/dashboard/azureDashboard/azureDashboardWidgets.ts
This change fixes the value from 'aws' to 'azure'
=> fix for appNavId value

src/pages/views/explorer/explorerUtils.ts
https://issues.redhat.com/browse/COST-1653
=> OCP supplementary & usage type-ahead

scripts/rebase-branch.sh
This script will rebase the selected branch with master, then push changes to origin
```
sh [-x] rebase-branch.sh [-h] -<c|q|s|r>
OPTIONS:
h       Display this message
c       CI stable
q       QA beta
s       QA stable
r       React Intl
```
=> Script to rebase branches

src/pages/views/overview/components/dashboardWidgetBase.tsx
This fixes an error for when there is no forecast data.
https://issues.redhat.com/browse/COST-1668
=> Fix error while loading Overview in ci beta

src/locales/en.json, src/pages/views/overview/components/dashboardWidgetBase.tsx
This fills in a one-day gap between forecast and Azure's last reported day for the current month.
https://issues.redhat.com/browse/COST-1666
=> Forecast API may result in data gap

src/locales/en.json
Updating the UI's doc links now that the new getting started docs have been published.
https://issues.redhat.com/browse/COST-1562
=> Update UI doc links

scripts/rebase-branch.sh
=> Fix status code check

koku-ui-manifest, package.json, yarn.lock
This upgrade will upgrade one of the version of post-css in our manifest
=> upgrade css-loader

src/locales/en.json, src/pages/costModels/costModel/costCalc.styles.ts, src/pages/costModels/costModel/updateDistributionDialog.tsx, src/pages/costModels/costModel/updateMarkupDialog.tsx
Changes for pop up modal for markup or discount changes
=> added markup or discount model changes

koku-ui-manifest, package.json, src/api/costModels.data.ts, src/components/charts/historicalCostChart/historicalCostChart.tsx, src/components/filter/filterComposition.tsx, src/modules/ocpOverviewWidget/ocpOverviewWidget.tsx, src/pages/costModels/components/inputs/simpleInput.tsx, src/pages/costModels/costModel/index.tsx, src/pages/costModels/costModelsDetails/utils/filters.tsx, src/pages/views/details/components/historicalData/historicalDataCostChart.tsx, src/pages/views/details/components/historicalData/historicalDataTrendChart.tsx, src/pages/views/explorer/explorerFilter.tsx, src/store/costModels/selectors.ts, src/store/rbac/actions.ts, src/store/sourceSettings/selectors.ts, yarn.lock
Upgrade prettier package and fixes for files based on new rules
https://issues.redhat.com/browse/COST-1699
=> upgrade prettier package

.travis/custom_release.sh
Need to clean up newly created .git directory before releasing a second branch
=> Clean directory before releasing another branch

.travis/custom_release.sh
Reset git head for stage release
=> Reset git head for stage release

.travis/custom_release.sh
Cleanup `dist/.git` directory for stage release
=> Cleanup dist/.git directory

koku-ui-manifest, package.json, yarn.lock
Allows proxying to https://cloud.stage.redhat.com/ or https://console.stage.redhat.com/ assuming your system-wide proxy is configured.
Closes https://issues.redhat.com/browse/RHCLOUD-14975
=> allow proxying stage envs

src/components/charts/common/chartDatumUtils.ts, src/locales/messages.ts, src/pages/views/overview/components/__snapshots__/dashboardWidget.test.tsx.snap, src/utils/dateRange.ts
Updated to reflect latest date formatting changes
**Overview:**
**Ocp details:**
=> Show month first for dates

src/pages/costModels/costModel/costCalc.styles.ts, src/pages/costModels/costModel/updateMarkupDialog.tsx, src/pages/costModels/createCostModelWizard/markup.tsx
Closes: https://issues.redhat.com/browse/COST-1738
=> Change radio buttons so they are stacked and input field is moved closer

src/pages/views/components/resourceTypeahead/resourceTypeahead.tsx
During a fit-and-finish meeting, we spoke about the typeahead delay. We would like to try reducing the typeahead delay slightly.
https://issues.redhat.com/browse/COST-1742
=> Reduce typeahead delay

src/pages/costModels/costModel/header.tsx
closes: https://issues.redhat.com/browse/COST-1739
=> change description for cost model to none title text

src/pages/costModels/costModel/header.tsx, src/pages/costModels/costModel/sourceTable.tsx, src/pages/costModels/costModel/table.styles.ts, src/pages/costModels/costModel/table.tsx
closes: https://issues.redhat.com/browse/COST-1740
=> moved source type under sources tab

.travis.yml, README.md
Update Node to use the latest 14.x LTS release.
https://issues.redhat.com/browse/COST-1751
=> Update Node version

src/locales/messages.ts, src/pages/costModels/components/errorState.tsx
Updated cost model error state for sources
=> moved cost model sources error state over to react-intl

src/locales/en.json
This is just a test to ensure the stage environment updates as expected.
=> stage-beta propagation test

src/locales/messages.ts, src/pages/state/maintenance/maintenanceState.tsx, src/utils/formatValue.ts
change over for maintenance message
=> Maintenance state changeover

.github/workflows/pull_request.yml
Added react-intl_changeover to list of branches Github PR action runs with
=> Github PR action branches

src/pages/views/overview/awsDashboard/awsDashboard.tsx, src/pages/views/overview/awsDashboard/awsDashboardWidget.tsx, src/pages/views/overview/awsOcpDashboard/awsOcpDashboard.tsx, src/pages/views/overview/awsOcpDashboard/awsOcpDashboardWidget.tsx, src/pages/views/overview/azureDashboard/azureDashboard.tsx, src/pages/views/overview/azureDashboard/azureDashboardWidget.tsx, src/pages/views/overview/azureOcpDashboard/azureOcpDashboard.tsx, src/pages/views/overview/azureOcpDashboard/azureOcpDashboardWidget.tsx, src/pages/views/overview/gcpDashboard/gcpDashboard.tsx, src/pages/views/overview/gcpDashboard/gcpDashboardWidget.tsx, src/pages/views/overview/gcpOcpDashboard/gcpOcpDashboard.tsx, src/pages/views/overview/gcpOcpDashboard/gcpOcpDashboardWidget.tsx, src/pages/views/overview/ibmDashboard/ibmDashboard.tsx, src/pages/views/overview/ibmDashboard/ibmDashboardWidget.tsx, src/pages/views/overview/ocpCloudDashboard/ocpCloudDashboard.tsx, src/pages/views/overview/ocpCloudDashboard/ocpCloudDashboardWidget.tsx, src/pages/views/overview/ocpDashboard/ocpDashboard.tsx, src/pages/views/overview/ocpDashboard/ocpDashboardWidget.tsx
Removed i18Next form overview dashboard pages.
=> Removed i18Next from overview dashbords

src/locales/messages.ts, src/pages/views/components/dataToolbar/dataToolbar.tsx, src/pages/views/components/resourceTypeahead/resourceSelect.tsx, src/pages/views/details/awsDetails/detailsToolbar.tsx, src/pages/views/details/azureDetails/detailsToolbar.tsx, src/pages/views/details/gcpDetails/detailsToolbar.tsx, src/pages/views/details/ibmDetails/detailsToolbar.tsx, src/pages/views/details/ocpDetails/detailsToolbar.tsx
https://user-images.githubusercontent.com/57504257/129579412-f9ab9051-bc52-4f0e-9a77-d280aa33fa8b.mov
=> React intl filter by in provider details views

src/pages/views/details/awsDetails/awsDetails.tsx, src/pages/views/details/azureDetails/azureDetails.tsx, src/pages/views/details/gcpDetails/gcpDetails.tsx, src/pages/views/details/ibmDetails/ibmDetails.tsx, src/pages/views/details/ocpDetails/ocpDetails.tsx, src/pages/views/explorer/explorer.tsx, src/pages/views/overview/overview.tsx, src/store/exports/exportReducer.ts, src/store/forecasts/forecastReducer.ts, src/store/orgs/orgReducer.ts, src/store/reports/reportReducer.ts, src/store/resources/resourceReducer.ts, src/store/tags/tagReducer.ts, src/store/ui/uiActions.ts
This ensures that any cached API responses are reset when navigating to a new page.
https://issues.redhat.com/browse/COST-1786
=> Reset API cache

src/locales/en.json
=> Fixed i18n key

src/locales/messages.ts, src/pages/views/details/ibmDetails/detailsHeader.tsx, src/pages/views/details/ibmDetails/ibmDetails.tsx, src/pages/views/details/ocpDetails/ocpDetails.tsx
group by changes for ibm details header
=> group by changes for ibm details header

src/locales/messages.ts, src/pages/views/details/gcpDetails/detailsHeader.tsx, src/pages/views/details/gcpDetails/gcpDetails.tsx
=> React intl grpby gcp details

src/locales/messages.ts, src/pages/views/components/export/exportModal.tsx, src/pages/views/components/export/exportSubmit.tsx
Updated the export modal to use react-intl
=> React-intl: Export modal

src/pages/views/details/azureDetails/detailsTable.tsx
=> React intl azure details table

src/pages/views/details/ibmDetails/detailsTable.tsx
=> react-intl changes for IBM table details

src/pages/views/details/gcpDetails/detailsTable.tsx
=> react-react-intl changes for GCP table details

src/components/async/permissionsComponent/permissions.tsx
Localized permissions component by adding page titles.
=> Localized permissions

src/locales/messages.ts
Remove unused CostExplorerTitle message
=> Unused CostExplorerTitle message

src/components/icons/costIcon/costIcon.tsx
=> Localized icon component

src/pages/costModels/costModel/updateDistributionDialog.tsx
Localized cost models distribution dialog
=> Localized distribution dialog

src/components/i18n/index.ts, src/components/i18n/intl.ts, src/components/state/emptyFilterState/emptyFilterState.tsx, src/components/state/loadingState/loadingState.tsx, src/locales/messages.ts, src/pages/costModels/costModel/dialog.test.tsx, src/pages/costModels/costModel/dialog.tsx, src/pages/costModels/costModelsDetails/table.test.tsx, src/pages/costModels/costModelsDetails/table.tsx
Created default intlMock for testing and enabled tests for cost models dialog and table.
=> Enabled cost models tests

src/pages/costModels/components/__snapshots__/rateTable.test.tsx.snap, src/pages/costModels/components/rateTable.test.tsx, src/pages/costModels/components/rateTable.tsx, src/pages/costModels/components/tagRateTable.tsx
=> Enabled rateTable tests

src/pages/costModels/costModelsDetails/dialog.test.tsx, src/pages/costModels/costModelsDetails/dialog.tsx
Enabled cost models wizard dialog tests
=> Enabled cost models wizard dialog tests

src/pages/costModels/costModelsDetails/utils/toolbar.tsx
=> Localized cost models toolbar

src/pages/costModels/costModel/addRateModal.tsx
Localize addRate modal
Note: body is localized elsewhere
=> Localize addRate modal

src/pages/costModels/costModel/addRateModal.tsx, src/pages/costModels/costModel/updateRateModel.tsx
=> Localized update rate modal

src/locales/messages.ts, src/pages/costModels/costModelsDetails/utils/filters.tsx
Fix cost models filter placeholder
=> Fix cost models filter placeholder

src/components/reports/reportSummary/reportSummaryItem.tsx, src/locales/messages.ts, src/pages/costModels/components/errorState.tsx, src/pages/state/maintenance/maintenanceState.tsx
Fixed percentage message strings
=> Fixed percentage message strings

locales/data.json, locales/translations.json, src/locales/messages.ts, src/pages/views/components/dataToolbar/dataToolbar.tsx
Localized bulk selector in data toolbar
=> Localized bulk selector

koku-ui-manifest, package.json, yarn.lock
Dependabot is showing a vulnerability alert for Axios.
https://issues.redhat.com/browse/COST-1837
=> Axios vulnerability alert

.github/workflows/pull_request.yml, .travis/custom_release.sh
Cleanup unused branches for github actions and travis build
=> Cleanup unused branches

src/api/currency.ts, src/store/currency/__snapshots__/currency.test.ts.snap, src/store/currency/currency.test.ts, src/store/currency/currencyActions.ts, src/store/currency/currencyCommon.ts, src/store/currency/currencyReducer.ts, src/store/currency/currencySelectors.ts, src/store/currency/index.ts, src/store/rootReducer.ts, src/store/userAccess/userAccessActions.ts, src/store/userAccess/userAccessSelectors.ts
Added support for currency API
https://issues.redhat.com/browse/COST-1808
=> Currency api

src/api/currency.ts, src/components/currency/currency.styles.ts, src/components/currency/currency.tsx, src/components/sources/inactiveSources/inactiveSources.tsx, src/pages/views/components/groupBy/groupBy.tsx, src/pages/views/components/perspective/perspective.tsx, src/pages/views/details/components/columnManagement/columnManagementModal.tsx, src/pages/views/overview/overview.tsx, src/store/currency/currencyActions.ts, src/store/currency/currencyCommon.ts, src/store/currency/currencySelectors.ts, src/utils/cookie.ts
Added initial currency dropdown to overview page. 
State is maintained via session cookies. If the user logs out or closes the browser, the dropdown selection will be reset. 
https://issues.redhat.com/browse/COST-1808
=> Currency dropdown

src/components/currency/currency.tsx, src/components/inactiveSources/inactiveSources.tsx, src/utils/cookie.ts, src/utils/localStorage.ts
Added `localStorage` utils to make it easier to retrieve currency units used by APIs
=> Added localStorage utils

src/components/reports/reportSummary/reportSummaryDetails.tsx, src/pages/costModels/components/rateForm/rateForm.tsx, src/pages/views/details/components/historicalData/historicalDataTrendChart.tsx, src/pages/views/overview/components/dashboardWidgetBase.tsx
Ensure the `unitlookup` function is being used properly with messages.Units
=> Ensure unit lookup is being used properly

src/pages/views/details/awsDetails/detailsHeader.styles.ts, src/pages/views/details/awsDetails/detailsHeader.tsx, src/pages/views/details/azureDetails/detailsHeader.styles.ts, src/pages/views/details/azureDetails/detailsHeader.tsx, src/pages/views/details/components/breakdown/breakdownHeader.styles.ts, src/pages/views/details/components/breakdown/breakdownHeader.tsx, src/pages/views/details/gcpDetails/detailsHeader.styles.ts, src/pages/views/details/gcpDetails/detailsHeader.tsx, src/pages/views/details/ibmDetails/detailsHeader.styles.ts, src/pages/views/details/ibmDetails/detailsHeader.tsx, src/pages/views/details/ocpDetails/detailsHeader.styles.ts, src/pages/views/details/ocpDetails/detailsHeader.tsx, src/pages/views/explorer/explorerHeader.styles.ts, src/pages/views/explorer/explorerHeader.tsx, src/pages/views/overview/overview.styles.ts, src/pages/views/overview/overview.tsx
Added currency selector to all page headings, except cost models.
https://user-images.githubusercontent.com/17481322/133475898-f5ac04ee-90b9-471a-9196-d351258d7ffc.mov
Details breakdown
=> Added currency selector to page headings

locales/data.json, locales/translations.json, src/locales/messages.ts, src/pages/views/explorer/explorerUtils.ts, src/utils/dateRange.ts
https://issues.redhat.com/browse/COST-1688
Blocked by https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/25516
=> Expand cost explorer to show 90 days

src/pages/costModels/createCostModelWizard/review.tsx
Adds currency selection to cost models review
https://issues.redhat.com/browse/COST-1916
=> Add currency selection to cost models review

src/api/costModels.ts, src/pages/costModels/costModel/costModelsDetails.styles.ts, src/pages/costModels/costModel/header.tsx, src/store/costModels/selectors.ts, src/store/costModels/store.test.ts
Add currency to cost model page, under the description.
https://issues.redhat.com/browse/COST-1916
=> Add currency to cost model page

src/utils/format.ts
=> Updated currency notes

src/pages/views/components/groupBy/groupBy.styles.ts, src/pages/views/components/groupBy/groupBy.tsx, src/pages/views/components/groupBy/groupByOrg.tsx, src/pages/views/components/groupBy/groupByTag.tsx, src/pages/views/details/awsDetails/awsDetails.tsx, src/pages/views/details/awsDetails/detailsHeader.tsx, src/pages/views/details/azureDetails/azureDetails.tsx, src/pages/views/details/azureDetails/detailsHeader.tsx, src/pages/views/details/gcpDetails/detailsHeader.tsx, src/pages/views/details/gcpDetails/gcpDetails.tsx, src/pages/views/details/ibmDetails/detailsHeader.tsx, src/pages/views/details/ibmDetails/ibmDetails.tsx, src/pages/views/details/ocpDetails/detailsHeader.tsx, src/pages/views/details/ocpDetails/ocpDetails.tsx, src/pages/views/explorer/explorer.tsx, src/pages/views/explorer/explorerHeader.tsx
Converted `groupBy` dropdown component to use PatternFly `Select`
=> Convert groupBy dropdown component to use Select

src/components/currency/currency.tsx, src/pages/views/overview/components/chartComparison.tsx, src/pages/views/overview/components/dashboardWidget.styles.ts, src/pages/views/overview/components/dashboardWidgetBase.tsx
Converted the chart comparison dropdown to use PatternFly Select component
=> Convert chart comparison dropdown to PatternFly Select component

src/components/costType/costType.tsx, src/components/currency/currency.tsx, src/pages/views/components/dataToolbar/dataToolbar.tsx, src/pages/views/components/groupBy/groupBy.tsx, src/pages/views/components/perspective/perspective.tsx, src/pages/views/explorer/dateRange.tsx, src/pages/views/overview/components/chartComparison.tsx
Converted Cost Explorer's date range dropdown to PatternFly Select component.
=> Convert date range dropdown to PatternFly Select component

src/components/costType/costType.tsx, src/components/currency/currency.tsx, src/pages/views/components/dataToolbar/dataToolbar.tsx, src/pages/views/components/groupBy/groupBy.tsx, src/pages/views/components/perspective/perspective.tsx, src/pages/views/overview/components/chartComparison.tsx
Converted category dropdown to PatternFly `Select` component
=> Convert category dropdown to PatternFly Select component

src/components/costType/costType.tsx, src/components/currency/currency.tsx
Ensure currency and cost type API request is performed for beta env only
https://issues.redhat.com/browse/COST-1905
=> Ensure currency and cost type fetch is performed for beta env only

src/components/costType/costType.tsx, src/components/currency/currency.tsx, src/pages/views/details/awsDetails/detailsHeader.tsx, src/pages/views/details/azureDetails/detailsHeader.tsx, src/pages/views/details/components/breakdown/breakdownHeader.tsx, src/pages/views/details/gcpDetails/detailsHeader.tsx, src/pages/views/details/ibmDetails/detailsHeader.tsx, src/pages/views/details/ocpDetails/detailsHeader.tsx, src/pages/views/explorer/explorerHeader.tsx, src/pages/views/overview/overview.tsx
Wrap currency and cost type components with isBeta check instead of relying on the component's componentDidMount and render functions.
https://issues.redhat.com/browse/COST-1905
=> Wrap components with isBeta check

src/api/costType.ts
Update URL to match latest cost type API.
https://issues.redhat.com/browse/COST-2024
=> Update URL for cost type API

src/pages/views/details/awsDetails/awsDetails.tsx, src/pages/views/details/azureDetails/azureDetails.tsx, src/pages/views/details/gcpDetails/gcpDetails.tsx, src/pages/views/details/ibmDetails/ibmDetails.tsx, src/pages/views/details/ocpDetails/ocpDetails.tsx, src/pages/views/explorer/explorer.tsx, src/pages/views/explorer/explorerFilter.tsx, src/pages/views/explorer/explorerHeader.tsx
- Ensure API query has all params for AWS savings feature 
- Ensure history.location is called after state is saved
=> AWS savings plan updates

src/api/resources/gcpResource.ts, src/api/resources/resource.ts, src/api/resources/resourceUtils.ts
Enable type-ahead support for gcp_project
https://issues.redhat.com/browse/COST-1980
=> Enable type-ahead support for gcp_project

package.json, webpack.config.js, yarn.lock
jira: https://issues.redhat.com/browse/RHCLOUD-16972
=> Force react-redux sharing

src/api/queries/query.ts, src/pages/views/components/dataToolbar/dataToolbar.tsx
Make category prefix longer to prevent key collisions
https://issues.redhat.com/browse/COST-2094
=> Update category prefix

src/pages/views/explorer/explorer.tsx
Enable monthly resolution for Cost Explorer's CSV export
https://issues.redhat.com/browse/COST-1691
=> Enable monthly resolution for Cost Explorer's CSV export

src/pages/views/details/awsDetails/detailsToolbar.tsx, src/pages/views/details/azureDetails/detailsToolbar.tsx, src/pages/views/details/gcpDetails/detailsToolbar.tsx, src/pages/views/details/ibmDetails/detailsToolbar.tsx, src/pages/views/details/ocpDetails/detailsToolbar.tsx
This ensures the tag API request is not generated while already in progress.
https://issues.redhat.com/browse/COST-2053
=> Lazy generate API requests for tags

src/api/costType.ts, src/api/reports/awsReports.ts, src/components/costType/costType.tsx, src/pages/views/details/awsDetails/detailsHeader.tsx, src/pages/views/details/components/breakdown/breakdownHeader.tsx, src/pages/views/explorer/explorerHeader.tsx, src/pages/views/overview/overview.tsx, src/store/reports/reportCommon.ts, src/utils/localStorage.ts
- Remove `isBeta` flag from AWS saving plan feature 
- Sync with the user's preferred choice from the settings page
https://issues.redhat.com/browse/COST-2108
=> Remove isBeta flag from AWS saving plan feature

src/pages/views/overview/overview.tsx
Adjusted the default perspective for the overview infrastructure tab. This will help ensure the default overview tab has data available.
=> Adjusted the default perspective for the overview infrastructure tab

src/pages/views/overview/overview.tsx
Clean up default perspective for the overview infrastructure tab. We just need to change the default perspective for "all cloud".
=> Clean up default perspective

src/pages/views/components/costType/costTypeWrapper.tsx, src/pages/views/explorer/explorer.tsx, src/pages/views/explorer/explorerHeader.tsx, src/pages/views/explorer/explorerUtils.ts, src/pages/views/overview/overview.tsx, src/utils/userAccess.ts
Simplify provider 'has data' utils by removing fetch status
=> Simplify provider utils

src/pages/views/explorer/explorer.tsx, src/pages/views/explorer/explorerUtils.ts
Clean up explorer default perspective utils
=> Clean up explorer default perspective utils

src/api/providers.ts, src/api/userAccess.ts, src/components/accountSettings/accountSettings.tsx, src/components/async/permissionsComponent/permissions.tsx, src/components/inactiveSources/inactiveSources.tsx, src/modules/ocpOverviewWidget/ocpOverviewWidget.tsx, src/pages/views/details/awsBreakdown/awsBreakdown.tsx, src/pages/views/details/awsDetails/awsDetails.tsx, src/pages/views/details/awsDetails/detailsHeader.tsx, src/pages/views/details/azureBreakdown/azureBreakdown.tsx, src/pages/views/details/azureDetails/azureDetails.tsx, src/pages/views/details/azureDetails/detailsHeader.tsx, src/pages/views/details/components/breakdown/breakdownBase.tsx, src/pages/views/details/gcpBreakdown/gcpBreakdown.tsx, src/pages/views/details/gcpDetails/detailsHeader.tsx, src/pages/views/details/gcpDetails/gcpDetails.tsx, src/pages/views/details/ibmBreakdown/ibmBreakdown.tsx, src/pages/views/details/ibmDetails/detailsHeader.tsx, src/pages/views/details/ibmDetails/ibmDetails.tsx, src/pages/views/details/ocpBreakdown/ocpBreakdown.tsx, src/pages/views/details/ocpDetails/detailsHeader.tsx, src/pages/views/details/ocpDetails/ocpDetails.tsx, src/pages/views/explorer/explorer.tsx, src/pages/views/explorer/explorerHeader.tsx, src/pages/views/overview/overview.tsx, src/pages/views/utils/providers.ts, src/store/providers/index.ts, src/store/providers/providersCommon.ts, src/store/userAccess/index.ts, src/store/userAccess/userAccessCommon.ts
Modified UI to use a single sources API request instead of using the type param.
https://issues.redhat.com/browse/COST-2202
=> Request sources API without type param

koku-ui-manifest, package.json, yarn.lock
Update the axios and webpack-dev-server packages to silence github's Dependabot alerts.
https://issues.redhat.com/browse/COST-2263
=> Dependabot alerts

src/components/inactiveSources/inactiveSources.tsx, src/components/permissions/permissionsWrapper.tsx
Updated comments for permissionsWrapper
=> Updated comments

src/pages/views/details/components/cluster/clusterContent.tsx, src/pages/views/details/components/cluster/clusterModal.tsx, src/pages/views/details/components/summary/summaryModal.tsx, src/pages/views/details/components/summary/summaryModalContent.tsx, src/pages/views/details/components/tag/tagContent.tsx, src/pages/views/details/components/tag/tagModal.tsx
Renamed *View components as *Content to match PatternFly drawer component
=> Cleaned up component names to match future export component

src/components/export/exportDrawer.tsx, src/components/export/exportLink.tsx, src/store/ui/ui.test.ts, src/store/ui/uiActions.ts, src/store/ui/uiReducer.ts
Remove unused UI actions from Redux store
=> Remove unused UI actions

src/pages/views/explorer/explorerUtils.ts
Enable 90 day UI view in stable stage/prod
https://issues.redhat.com/browse/COST-2210
=> Enable 90 day UI view in stable stage/prod

src/store/dashboard/gcpDashboard/gcpDashboardWidgets.ts
Update GCP network card filters
https://issues.redhat.com/browse/COST-2325
=> Update GCP network card filters

src/components/exports/exports.styles.ts, src/components/exports/exportsTable.tsx, src/pages/views/details/awsDetails/awsDetails.styles.ts, src/pages/views/details/azureDetails/azureDetails.styles.ts, src/pages/views/details/ibmDetails/ibmDetails.styles.ts, src/pages/views/details/ocpDetails/ocpDetails.styles.ts, src/pages/views/explorer/explorer.styles.ts
Add content to "All exports" drawer
- Fixed download and delete icon colors
- Fixed bottom pagination margins
=> Add content to "All exports" drawer

src/api/reports/gcpOcpReports.ts, src/api/resources/gcpOcpResource.ts, src/api/resources/gcpResource.ts, src/pages/views/explorer/explorerHeader.tsx, src/pages/views/explorer/explorerUtils.ts, src/pages/views/overview/gcpOcpDashboard/gcpOcpDashboardWidget.test.tsx, src/pages/views/overview/gcpOcpDashboard/gcpOcpDashboardWidget.tsx, src/pages/views/overview/overview.tsx, src/store/dashboard/gcpOcpDashboard/gcpOcpDashboardCommon.ts, src/store/dashboard/gcpOcpDashboard/gcpOcpDashboardWidgets.ts
Enable GCP on OpenShift
https://issues.redhat.com/browse/COST-2245
=> Enable GCP on OpenShift

src/pages/costModels/costModel/header.tsx, src/pages/costModels/costModelsDetails/header.tsx, src/pages/costModels/createCostModelWizard/generalInformation.tsx, src/pages/views/components/export/exportModal.tsx, src/pages/views/details/awsDetails/detailsHeader.tsx, src/pages/views/details/azureDetails/detailsHeader.tsx, src/pages/views/details/components/breakdown/breakdownHeader.tsx, src/pages/views/details/gcpDetails/detailsHeader.tsx, src/pages/views/details/ibmDetails/detailsHeader.tsx, src/pages/views/details/ocpDetails/detailsHeader.tsx, src/pages/views/explorer/explorerHeader.tsx, src/pages/views/overview/overview.tsx, src/store/export/exportActions.tsx, src/utils/feature.ts
Created a new `isFeatureVisible` function that allows features to be named. This helps identify multiple code segments belonging to any given feature.
https://issues.redhat.com/browse/COST-2359
=> Create isFeatureVisible for named features

.travis/custom_release.sh, archive/utils/permissions.ts, scripts/release-branch.sh, webpack.config.js
Rename master branch as main
https://issues.redhat.com/browse/COST-2360
=> Rename master branch

.travis/custom_release.sh, README.md, archive/utils/permissions.ts, scripts/release-branch.sh, webpack.config.js
A prerequisite to renaming the master branch as main
https://issues.redhat.com/browse/COST-2360
=> Prereq to renaming master branch

README.md
Added getting started step to README
https://issues.redhat.com/browse/COST-2476
=> Added getting started step to README

src/pages/costModels/components/inputs/selector.tsx, src/pages/costModels/components/rateForm/rateForm.tsx, src/pages/costModels/components/rateForm/useRateForm.tsx, src/pages/costModels/createCostModelWizard/generalInformation.tsx
[2488](https://issues.redhat.com/browse/COST-2488)
=> update generalinformation to use new selector

src/pages/costModels/components/addPriceList.test.tsx, src/pages/costModels/costModel/updateRateModel.test.tsx
This is a test to see if the cost model rate tests will pass on GitHub without errors and/or warnings. Seems to be working for me locally.
https://issues.redhat.com/browse/COST-2530
=> Enable cost model rate tests

src/utils/format.ts
Just clarifying, in comments, how the unFormat function is used
https://issues.redhat.com/browse/COST-2557
=> Clarify how the unFormat function is used

README.md, release.md
Document our release process and link it to the README.
https://issues.redhat.com/browse/COST-2568
=> Document release process

src/pages/views/details/components/columnManagement/columnManagementModal.tsx
Modify DataListCheck to use isChecked after latest PatternFly milestone breakage
https://issues.redhat.com/browse/COST-2571
=> Modify DataListCheck to use isChecked

koku-ui-manifest, package.json, yarn.lock
The dependency below doesn't appear to be imported anywhere in our the UI.
https://issues.redhat.com/browse/COST-2700
=> Remove unused fortawesome dependency

src/store/dashboard/gcpDashboard/gcpDashboardWidgets.ts
QE suggested that we include "Firebase" to the GCP database filter.
https://issues.redhat.com/browse/COST-2733
=> Add "Firebase" to the GCP database filter

src/api/export/exportUtils.ts, src/api/export/ociExport.ts, src/api/forecasts/ociForecast.ts, src/api/queries/ociQuery.ts, src/api/reports/ociReports.test.ts, src/api/reports/ociReports.ts, src/api/reports/report.ts, src/api/resources/ociResource.ts, src/api/resources/resource.ts, src/api/tags/ociTags.test.ts, src/api/tags/ociTags.ts, src/api/tags/tag.ts, src/api/tags/tagUtils.ts
=> stub OCI api queries and reports

src/api/forecasts/forecast.ts, src/routes.tsx, src/store/dashboard/azureDashboard/__snapshots__/azureDashboard.test.ts.snap, src/store/dashboard/azureDashboard/azureDashboard.test.ts, src/store/dashboard/common/dashboardCommon.ts, src/store/dashboard/ociDashboard/__snapshots__/ociDashboard.test.ts.snap, src/store/dashboard/ociDashboard/index.ts, src/store/dashboard/ociDashboard/ociDashboard.test.ts, src/store/dashboard/ociDashboard/ociDashboardActions.ts, src/store/dashboard/ociDashboard/ociDashboardCommon.ts, src/store/dashboard/ociDashboard/ociDashboardReducer.ts, src/store/dashboard/ociDashboard/ociDashboardSelectors.ts, src/store/dashboard/ociDashboard/ociDashboardWidgets.ts
stub out the dashboard for oci.. saw there were empty object tests that shouldn't have been, fixed that in azure tests as well.
=> oci stub dashboard

src/pages/views/components/groupBy/groupBy.tsx, src/pages/views/details/awsDetails/detailsToolbar.tsx, src/pages/views/details/azureDetails/detailsToolbar.tsx, src/pages/views/details/gcpDetails/detailsToolbar.tsx, src/pages/views/details/ibmDetails/detailsToolbar.tsx, src/pages/views/details/ocpDetails/detailsToolbar.tsx, src/pages/views/explorer/explorer.tsx, src/pages/views/explorer/explorerChart.tsx, src/pages/views/explorer/explorerFilter.tsx, src/pages/views/explorer/explorerHeader.tsx, src/pages/views/explorer/explorerTable.tsx
Our tags API requests should either include start_date and end_date or use the time_scope_value filter.
https://issues.redhat.com/browse/COST-2806
=> Tags API should include date range

src/pages/views/explorer/explorerHeader.tsx, src/pages/views/explorer/explorerUtils.ts, src/pages/views/overview/overview.tsx
Testing OCI with Luke's OCI source provider. There are some issues which are causing breakage in the cost explorer page. A few missing pieces in explorerUtils to ensure the correct API is called.
=> OCI fixes for Cost Explorer

src/store/dashboard/ociDashboard/ociDashboardWidgets.ts
Encountered a "Unsupported parameter or invalid value" error while testing the overview page. This fixes the OCI filter name for network and database cards.
=> OCI filter name for network and database cards

build_deploy.sh, package.json, pr_check.sh
Adds scripts for container focused build pipeline.
https://issues.redhat.com/browse/COST-2350
=> Container focused build pipeline

deploy/frontend.yaml
Added CRD deploy folder for containerized builds.
https://issues.redhat.com/browse/COST-2350
=> Added CRD deploy folder

src/store/dashboard/ociDashboard/ociDashboardWidgets.ts
Adjusts OCI filters for the database, network, and compute cards
https://issues.redhat.com/browse/COST-2883
=> OCI filters

scripts/start-dev-server.js, webpack.config.js
The UI's startup script currently asks 4 questions about the run environment, which can be a little annoying when starting the UI with the default values.
I'd like to add a single question, asking the user if they want to setup the run environment. If the answer is yes, then we can bombard the user with questions. Otherwise, it's just one click for running with the default stage-beta env.
https://issues.redhat.com/browse/COST-2948
=> Add question to UI's startup script

.eslintrc.json, koku-ui-manifest, package.json, src/federatedEntry.tsx, src/store/costModels/actions.ts, src/store/export/exportActions.tsx, src/store/rbac/actions.ts, src/store/rootReducer.ts, src/store/store.ts, yarn.lock
Adds the @redhat-cloud-services/eslint-config-redhat-cloud-services extension to eslintrc.json and fixes linter issues associated with the extension.
=> Add eslint-config-redhat-cloud-services

src/app.tsx, src/components/featureFlags/featureFlags.tsx, src/components/permissions/permissionsWrapper.tsx
Fix hook warning for feature flag component
=> Fix hook warning for feature flag component

package.json, yarn.lock
okay to assign to https://issues.redhat.com/secure/RapidBoard.jspa?rapidView=5662&view=detail&selectedIssue=COST-2936 ?
=> add npm check updates and a script target for it

package.json, src/locales/messages.ts, src/routes/costModels/costModelsDetails/utils/table.tsx, yarn.lock
[COST-2938](https://issues.redhat.com/browse/COST-2938)
=> replace human-date with date-fns

package.json, yarn.lock
=> Revert eslint to previous version to fix linter

locales/data.json, locales/translations.json, src/api/queries/query.ts, src/components/exports/exportsContent.tsx, src/components/exports/exportsToolbar.tsx, src/components/featureFlags/featureFlags.tsx, src/locales/messages.ts, src/routes/views/components/dataToolbar/dataToolbar.tsx, src/routes/views/details/awsDetails/awsDetails.tsx, src/routes/views/details/awsDetails/detailsToolbar.tsx, src/routes/views/details/azureDetails/azureDetails.tsx, src/routes/views/details/azureDetails/detailsToolbar.tsx, src/routes/views/details/gcpDetails/detailsToolbar.tsx, src/routes/views/details/gcpDetails/gcpDetails.tsx, src/routes/views/details/ibmDetails/detailsToolbar.tsx, src/routes/views/details/ibmDetails/ibmDetails.tsx, src/routes/views/details/ociDetails/detailsToolbar.tsx, src/routes/views/details/ociDetails/ociDetails.tsx, src/routes/views/details/ocpDetails/detailsToolbar.tsx, src/routes/views/details/ocpDetails/ocpDetails.tsx, src/routes/views/explorer/explorer.tsx, src/routes/views/explorer/explorerFilter.tsx, src/routes/views/explorer/explorerHeader.tsx, src/routes/views/explorer/explorerUtils.ts, src/routes/views/utils/query.ts, src/store/featureFlags/__snapshots__/featureFlags.test.ts.snap, src/store/featureFlags/featureFlags.test.ts, src/store/featureFlags/featureFlagsActions.ts, src/store/featureFlags/featureFlagsReducer.ts, src/store/featureFlags/featureFlagsSelectors.ts
Adds the excludes select component to support negative filtering
https://issues.redhat.com/browse/COST-2773
=> Negative filtering

src/components/featureFlags/featureFlags.tsx
Want to ensure Uleash feature toggles are enabled per account basis in the stage env.
For example, cost-demo, cost-cloud, etc. should be able to see in-progress features, but insights-qa should only see completed features. The insights-qa user should only test what users will see in prod.
https://issues.redhat.com/browse/COST-3079
=> Ensure Unleash toggles are based on user ID

src/components/featureFlags/featureFlags.styles.ts, src/components/featureFlags/featureFlags.tsx
Replace styles with PF bullseye component
=> Replace styles with PF bullseye component

src/components/featureFlags/featureFlags.tsx, src/store/featureFlags/__snapshots__/featureFlags.test.ts.snap, src/store/featureFlags/featureFlagsReducer.ts, src/store/featureFlags/featureFlagsSelectors.ts
Update feature flags to wait until store is updated
=> Update feature flags to wait until store is updated

src/components/featureFlags/featureFlags.tsx, src/store/featureFlags/featureFlagsReducer.ts
Remove store reset and add useLayoutEffect
=> Remove store reset and add useLayoutEffect

src/components/featureFlags/featureFlags.tsx
Restore hasFlags and add messages to debug
=> Restore hasFlags

package.json, yarn.lock
jira: https://issues.redhat.com/browse/RHCLOUD-21492
=> Add yarn resolution for eslint-plugin-rulesdir dependency.

src/routes/costModels/createCostModelWizard/generalInformation.tsx, src/routes/costModels/createCostModelWizard/steps.tsx
https://issues.redhat.com/browse/COST-3077
=> fix js errors on form errors within cost model wizard

package.json, src/routes/costModels/costModelsDetails/noCostModels.tsx, src/routes/costModels/costModelsDetails/utils/filters.tsx, src/routes/costModels/costModelsDetails/utils/toolbar.tsx, src/typings/types.d.ts
Refactored the cost models filter to avoid using the hook-into-props dependency.
https://issues.redhat.com/browse/COST-2941
=> Remove hook-into-props dependency

src/routes/views/components/export/exportSubmit.tsx
Need to ensure that we include start and end dates for the export request.
https://issues.redhat.com/browse/COST-3172
=> Add start & end dates to export request

src/routes/components/state/emptyFilterState/emptyFilterState.tsx
Fix types used in emptyFilterState
https://issues.redhat.com/browse/COST-3187
=> EmptyFilterState types

src/components/exports/exportsTable.tsx, src/routes/views/details/awsDetails/detailsTable.tsx, src/routes/views/details/azureDetails/detailsTable.tsx, src/routes/views/details/gcpDetails/detailsTable.tsx, src/routes/views/details/ibmDetails/detailsTable.tsx, src/routes/views/details/ociDetails/detailsTable.tsx, src/routes/views/details/ocpDetails/detailsTable.tsx, src/routes/views/explorer/explorerTable.tsx
Remove unused sortBy property from details tables
https://issues.redhat.com/browse/COST-3188
=> Remove unused sortBy property

locales/data.json, locales/translations.json, src/locales/messages.ts, src/routes/views/details/awsDetails/detailsTable.tsx, src/routes/views/details/azureDetails/detailsTable.tsx, src/routes/views/details/components/dataTable/dataTable.tsx, src/routes/views/details/gcpDetails/detailsTable.tsx, src/routes/views/details/ibmDetails/detailsTable.tsx, src/routes/views/details/ociDetails/detailsTable.tsx, src/routes/views/details/ocpDetails/detailsTable.tsx
Simplified the details aria label
https://issues.redhat.com/browse/COST-2349
=> Simplify details aria label

src/components/featureFlags/featureFlags.tsx, src/routes/views/components/dataToolbar/dataToolbar.tsx, src/store/featureFlags/__snapshots__/featureFlags.test.ts.snap, src/store/featureFlags/featureFlags.test.ts, src/store/featureFlags/featureFlagsActions.ts, src/store/featureFlags/featureFlagsReducer.ts, src/store/featureFlags/featureFlagsSelectors.ts
Adding new Unleash feature flags for some upcoming features. Initially, these flags will be available to the cost-demo user in the stage environment.
- cost-management.ui.cost-type
- cost-management.ui.default-projects
- cost-management.ui.unallocated-costs
https://issues.redhat.com/browse/COST-3258
=> Unleash feature toggles

src/components/featureFlags/featureFlags.tsx, src/store/featureFlags/__snapshots__/featureFlags.test.ts.snap, src/store/featureFlags/featureFlags.test.ts, src/store/featureFlags/featureFlagsActions.ts, src/store/featureFlags/featureFlagsReducer.ts, src/store/featureFlags/featureFlagsSelectors.ts
Rename Unleash flag from "default projects" to "platform costs"
https://issues.redhat.com/browse/COST-2774
=> Rename Unleash flag

src/routes/views/details/ocpDetails/ocpDetails.tsx
Reset pagination and row selections when "sum platform costs" is toggled
https://issues.redhat.com/browse/COST-2774
=> Reset pagination and row selections

src/routes/views/components/export/exportModal.tsx, src/routes/views/components/export/exportSubmit.tsx, src/routes/views/details/awsDetails/awsDetails.tsx, src/routes/views/details/awsDetails/detailsTable.tsx, src/routes/views/details/azureDetails/azureDetails.tsx, src/routes/views/details/azureDetails/detailsTable.tsx, src/routes/views/details/components/actions/actions.tsx, src/routes/views/details/components/dataTable/dataTable.tsx, src/routes/views/details/gcpDetails/detailsTable.tsx, src/routes/views/details/gcpDetails/gcpDetails.tsx, src/routes/views/details/ibmDetails/detailsTable.tsx, src/routes/views/details/ibmDetails/ibmDetails.tsx, src/routes/views/details/ociDetails/detailsTable.tsx, src/routes/views/details/ociDetails/ociDetails.tsx, src/routes/views/details/ocpDetails/detailsTable.tsx, src/routes/views/details/ocpDetails/ocpDetails.tsx, src/routes/views/explorer/explorer.tsx, src/routes/views/utils/paths.ts
This ensures the export feature uses the same query params used to generate API reports for the details table.
https://issues.redhat.com/browse/COST-3278
=> Export should include AWS cost type (2 of 2)

src/routes/views/details/awsDetails/detailsTable.tsx, src/routes/views/details/azureDetails/detailsTable.tsx, src/routes/views/details/gcpDetails/detailsTable.tsx, src/routes/views/details/ibmDetails/detailsTable.tsx, src/routes/views/details/ociDetails/detailsTable.tsx, src/routes/views/details/ocpDetails/detailsTable.tsx, src/routes/views/explorer/explorer.tsx, src/routes/views/overview/overview.tsx
Simplify and remove unused `queryString` code.
=> Simplify and remove unused code

src/routes/views/components/export/exportSubmit.tsx, src/routes/views/details/awsDetails/detailsTable.tsx, src/routes/views/details/azureDetails/detailsTable.tsx, src/routes/views/details/gcpDetails/detailsTable.tsx, src/routes/views/details/ibmDetails/detailsTable.tsx, src/routes/views/details/ociDetails/detailsTable.tsx, src/routes/views/details/ocpDetails/detailsTable.tsx, src/store/userAccess/userAccess.test.ts
- Disabled details table kebab for 'no-project' projects
- Fixed wrong query type
- Renamed query as userAccessQuery
- Refactored details table row selection state
https://issues.redhat.com/browse/COST-3278
=> Disabled details table kebab

src/routes/views/components/dataToolbar/tagValue.tsx, src/routes/views/components/groupBy/groupBy.tsx, src/routes/views/details/awsBreakdown/awsBreakdown.tsx, src/routes/views/details/awsDetails/detailsToolbar.tsx, src/routes/views/details/azureBreakdown/azureBreakdown.tsx, src/routes/views/details/components/historicalData/historicalDataCostChart.tsx, src/routes/views/details/components/historicalData/historicalDataTrendChart.tsx, src/routes/views/details/components/historicalData/historicalDataUsageChart.tsx, src/routes/views/details/components/summary/summaryCard.tsx, src/routes/views/details/components/summary/summaryModalContent.tsx, src/routes/views/details/components/tag/tagLink.tsx, src/routes/views/details/components/tag/tagModal.tsx, src/routes/views/details/components/usageChart/usageChart.tsx, src/routes/views/details/gcpBreakdown/gcpBreakdown.tsx, src/routes/views/details/ibmBreakdown/ibmBreakdown.tsx, src/routes/views/details/ociBreakdown/ociBreakdown.tsx, src/routes/views/details/ocpBreakdown/ocpBreakdown.tsx
Clean up by renaming query as queryFromRoute
=> Rename query as queryFromRoute

src/routes/views/details/components/costOverview/costOverviewBase.tsx, src/routes/views/details/components/historicalData/historicalDataCostChart.tsx, src/routes/views/details/components/historicalData/historicalDataTrendChart.tsx, src/routes/views/details/components/historicalData/historicalDataUsageChart.tsx, src/routes/views/details/components/summary/summaryCard.tsx, src/routes/views/details/components/tag/tagContent.tsx, src/routes/views/details/components/tag/tagModal.tsx, src/routes/views/details/components/usageChart/usageChart.tsx, src/routes/views/details/ocpBreakdown/ocpBreakdown.tsx, src/routes/views/details/ocpDetails/detailsTable.tsx, src/routes/views/utils/paths.ts, src/store/breakdown/costOverview/common/costOverviewCommon.ts, src/store/breakdown/costOverview/ocpCostOverview/ocpCostOverviewWidgets.ts
Simplify platform costs using multiple group_by's
https://issues.redhat.com/browse/COST-3283
=> Simplify platform costs impl

src/routes/views/explorer/explorer.tsx, src/routes/views/explorer/explorerTable.tsx
Cost Explorer allows selection of no-tag items
https://issues.redhat.com/browse/COST-3285
=> Cost Explorer allows selection of no-tag items

src/routes/views/details/awsBreakdown/awsBreakdown.tsx, src/routes/views/details/azureBreakdown/azureBreakdown.tsx, src/routes/views/details/gcpBreakdown/gcpBreakdown.tsx, src/routes/views/details/ibmBreakdown/ibmBreakdown.tsx, src/routes/views/details/ociBreakdown/ociBreakdown.tsx, src/routes/views/details/ocpBreakdown/ocpBreakdown.tsx
Fix query for details breakdown return link, so page can be restored.
https://github.com/project-koku/koku-ui/pull/2711
=> Fix query for details breakdown

package.json, yarn.lock
Removed unused @formatjs/cli package
=> Remove unused @formatjs/cli package

src/routes/views/utils/paths.ts
Fix isPlatformCost function, ensuring filter query is not undefined
=> Ensure filter query is not undefined

src/components/featureFlags/featureFlags.tsx, src/routes/views/overview/overview.tsx, src/store/featureFlags/__snapshots__/featureFlags.test.ts.snap, src/store/featureFlags/featureFlags.test.ts, src/store/featureFlags/featureFlagsActions.ts, src/store/featureFlags/featureFlagsReducer.ts, src/store/featureFlags/featureFlagsSelectors.ts
Adding Unleash support for FINsights. 
Note that a new flag has already been created for Unleash stage / prod.
https://issues.redhat.com/browse/COST-3305
=> Unleash support for FINsights

src/routes/views/components/dataToolbar/dataToolbar.tsx
Reset platform costs toggle when group_by changes
https://issues.redhat.com/browse/COST-2774
=> Reset platform costs toggle

package.json, yarn.lock
Update @redhat-cloud-services/frontend-components-utilities pkg
=> @redhat-cloud-services/frontend-components-utilities update

src/app.tsx
Use app name from package.json
=> Update app name

src/api/queries/query.ts, src/api/reports/report.ts, src/routes/views/components/dataToolbar/dataToolbar.tsx, src/routes/views/details/awsDetails/awsDetails.tsx, src/routes/views/details/awsDetails/detailsTable.tsx, src/routes/views/details/azureDetails/azureDetails.tsx, src/routes/views/details/azureDetails/detailsTable.tsx, src/routes/views/details/components/summary/summaryCard.tsx, src/routes/views/details/gcpDetails/detailsTable.tsx, src/routes/views/details/gcpDetails/gcpDetails.tsx, src/routes/views/details/ibmDetails/detailsTable.tsx, src/routes/views/details/ibmDetails/ibmDetails.tsx, src/routes/views/details/ociDetails/detailsTable.tsx, src/routes/views/details/ociDetails/ociDetails.tsx, src/routes/views/details/ocpDetails/detailsTable.tsx, src/routes/views/details/ocpDetails/ocpDetails.tsx, src/routes/views/details/rhelDetails/detailsTable.tsx, src/routes/views/details/rhelDetails/rhelDetails.tsx, src/routes/views/explorer/explorer.tsx, src/routes/views/explorer/explorerTable.tsx, src/store/breakdown/costOverview/ocpCostOverview/ocpCostOverviewWidgets.ts, src/store/breakdown/costOverview/rhelCostOverview/rhelCostOverviewWidgets.ts
The APIs must also use `category=Platform` and `filter[category]=Platform`
https://issues.redhat.com/browse/COST-3335
=> Match new labels in details table

src/routes/views/components/dataToolbar/dataToolbar.tsx
=> Lint warning

src/routes/costModels/costModelsDetails/costModelsDetails.tsx
Remove unused console.log statements
=> Remove console.log statements

src/__mocks__/react-intl.ts, src/routes/costModels/costModelsDetails/utils/table.tsx, src/routes/views/components/charts/historicalCostChart/__snapshots__/historicalCostChart.test.tsx.snap, src/routes/views/components/charts/historicalTrendChart/__snapshots__/historicalTrendChart.test.tsx.snap, src/routes/views/components/charts/historicalUsageChart/__snapshots__/historicalUsageChart.test.tsx.snap, src/routes/views/components/charts/trendChart/__snapshots__/trendChart.test.tsx.snap, src/routes/views/components/charts/usageChart/__snapshots__/usageChart.test.tsx.snap
=> Update react-intl mock

src/routes/views/details/awsBreakdown/awsBreakdown.tsx, src/routes/views/details/awsBreakdown/costOverview.tsx, src/routes/views/details/ocpBreakdown/costOverview.tsx, src/routes/views/details/rhelBreakdown/costOverview.tsx
Cleanup title for cluster modal
https://issues.redhat.com/browse/COST-3371
=> Breakdown page doesn't show all "platform" clusters

src/routes/views/components/dataToolbar/dataToolbar.tsx, src/routes/views/components/resourceTypeahead/resourceInput.tsx
=> Unused code

src/routes/views/details/azureDetails/detailsTable.tsx, src/routes/views/details/gcpDetails/detailsTable.tsx, src/routes/views/details/ibmDetails/detailsTable.tsx, src/routes/views/details/ociDetails/detailsTable.tsx, src/routes/views/details/ocpDetails/detailsTable.tsx, src/routes/views/details/rhelDetails/detailsTable.tsx, src/routes/views/utils/paths.ts
Updated getBreakdownPath to use ID explicitly
=> getBreakdownPath to use ID

package.json, src/api/api.ts, yarn.lock
Axios header type changed, again.
Also rebuilt the yarn lock file.
=> Axios package update

package.json, src/api/api.ts, yarn.lock
Bump axios from 1.2.3 to 1.2.4
=> Bump axios

locales/data.json, locales/translations.json, src/components/userAccess/permissions.tsx, src/locales/messages.ts, src/routes/state/notAuthorized/notAuthorizedState.tsx
Fix OCI user access message
https://issues.redhat.com/browse/COST-3418
=> OCI user access message

src/api/resources/resourceUtils.ts
Enabled typeahead support for the OCI details page.
https://issues.redhat.com/browse/COST-3413
=> OCI typeahead support

locales/data.json, locales/translations.json, src/locales/messages.ts
The "overview" in "Cost overview" tab should not be capitalized
=> Cost overview tab title

src/routes/costModels/costModelWizard/priceListTable.tsx
The wizard's "to skip this step" message is shown twice.
https://issues.redhat.com/browse/COST-3437
=> "to skip this step" message

locales/data.json, locales/translations.json, src/api/userAccess.ts, src/components/featureFlags/featureFlags.tsx, src/components/userAccess/permissions.tsx, src/locales/messages.ts, src/routes.tsx, src/routes/state/notAuthorized/notAuthorizedState.tsx, src/routes/views/explorer/explorer.tsx, src/routes/views/explorer/explorerHeader.tsx, src/routes/views/overview/overview.tsx, src/store/featureFlags/__snapshots__/featureFlags.test.ts.snap, src/store/featureFlags/featureFlags.test.ts, src/store/featureFlags/featureFlagsActions.ts, src/store/featureFlags/featureFlagsReducer.ts, src/store/featureFlags/featureFlagsSelectors.ts, src/utils/userAccess.ts
Want to add Unleash and routing for ROS.
- Create Unleash flag for stage and prod
- Add Unleash support to FeatureFlag component and Redux store
- Add routing paths for recommendation pages
- Add empty state message when user doesn't have access to pages
https://issues.redhat.com/browse/COST-3478
=> Unleash for ROS

src/api/ros/recommendations.test.ts, src/api/ros/recommendations.ts, src/api/ros/ros.ts, src/api/ros/rosUtils.ts, src/store/rootReducer.ts, src/store/ros/__snapshots__/ros.test.ts.snap, src/store/ros/index.ts, src/store/ros/ros.test.ts, src/store/ros/rosActions.ts, src/store/ros/rosCommon.ts, src/store/ros/rosReducer.ts, src/store/ros/rosSelectors.ts
Added support for ROS APIs. The recommendations API request will be based on OCP for now.
- Add support for API requests
- Add Redux support for API
https://issues.redhat.com/browse/COST-3481
=> Boiler plate for ROS APIs

locales/data.json, locales/translations.json, src/api/providers.ts, src/api/queries/rosQuery.ts, src/api/ros/recommendations.ts, src/api/ros/ros.ts, src/api/tags/tag.ts, src/components/userAccess/permissions.tsx, src/locales/messages.ts, src/routes.tsx, src/routes/state/notAuthorized/notAuthorizedState.tsx, src/routes/views/ros/recommendations/index.ts, src/routes/views/ros/recommendations/recommendations.styles.ts, src/routes/views/ros/recommendations/recommendations.tsx, src/routes/views/ros/recommendations/rosHeader.styles.ts, src/routes/views/ros/recommendations/rosHeader.tsx, src/routes/views/ros/recommendations/rosTable.tsx, src/routes/views/ros/recommendations/rosToolbar.tsx, src/utils/computedReport/getComputedRosItems.ts
Add boiler plate support for a recommendations page, based on OCP for now.
This will be available in the stage env only, under an Unleash flag.
https://issues.redhat.com/browse/COST-3477
=> Boiler plate for ROS pages

src/components/featureFlags/featureFlags.tsx
Ensure Unleash features are not invoked until we have the fetched the user ID from Insights.
https://issues.redhat.com/browse/COST-3499
=> Fetch user ID for Unleash

src/store/costModels/actions.ts
Fixed link to "price list" on OCP details page
https://issues.redhat.com/browse/COST-3531
=> OCP details "price list" link

src/routes/views/components/dataToolbar/dataToolbar.tsx, src/routes/views/components/resourceTypeahead/resourceInput.tsx, src/routes/views/components/resourceTypeahead/resourceTypeahead.tsx
Adds placeholder text to the details filter.
https://issues.redhat.com/browse/COST-3536
=> Add placeholder to details filter

.eslintrc.json, src/components/pageTitle/pageTitle.tsx, src/routes/views/components/dataToolbar/dataToolbar.tsx
- Fix hasFilters reference
- Add react-hooks plugin for lint
=> Toolbar actions clean up

package.json, yarn.lock
Revert @redhat-cloud-services/frontend-components version bump
See https://issues.redhat.com/browse/RHCLOUD-24528
=> Revert @redhat-cloud-services/frontend-components

src/routes/costModels/costModel/costModelInfo.tsx, src/routes/state/loading/loading.tsx, src/routes/state/maintenance/maintenance.tsx, src/routes/state/noData/noData.tsx, src/routes/state/noProviders/noProviders.tsx, src/routes/state/notAuthorized/notAuthorized.tsx, src/routes/state/notAvailable/notAvailable.tsx, src/routes/state/notFound/notFound.tsx
Deprecated Main component
https://issues.redhat.com/browse/COST-3402
=> Deprecated Main component

package.json, yarn.lock
Bump frontend-components dependency
=> Bump frontend-components

locales/data.json, locales/translations.json, src/locales/messages.ts, src/routes/views/overview/components/dashboardBase.tsx, src/routes/views/overview/components/dashboardWidgetBase.tsx, src/routes/views/overview/components/rosSummary/rosSummary.scss, src/routes/views/overview/components/rosSummary/rosSummary.tsx, src/routes/views/overview/ocpDashboard/ocpDashboardWidget.tsx, src/store/dashboard/common/dashboardCommon.ts, src/store/dashboard/ocpDashboard/ocpDashboard.test.ts, src/store/dashboard/ocpDashboard/ocpDashboardActions.ts, src/store/dashboard/ocpDashboard/ocpDashboardReducer.ts, src/store/dashboard/ocpDashboard/ocpDashboardSelectors.ts, src/store/dashboard/ocpDashboard/ocpDashboardWidgets.ts
Stubbed out recommendations overview card without APIs
https://issues.redhat.com/browse/COST-3562
=> Recommendations overview card

locales/data.json, locales/translations.json, src/api/queries/query.ts, src/components/ros/recommendationsContent.tsx, src/locales/messages.ts, src/routes/views/components/dataToolbar/dataToolbar.styles.ts, src/routes/views/details/awsDetails/awsDetails.styles.ts, src/routes/views/details/awsDetails/awsDetails.tsx, src/routes/views/details/azureDetails/azureDetails.styles.ts, src/routes/views/details/azureDetails/azureDetails.tsx, src/routes/views/details/components/breakdown/breakdownBase.tsx, src/routes/views/details/components/breakdown/breakdownHeader.tsx, src/routes/views/details/gcpDetails/gcpDetails.styles.ts, src/routes/views/details/gcpDetails/gcpDetails.tsx, src/routes/views/details/ibmDetails/ibmDetails.styles.ts, src/routes/views/details/ibmDetails/ibmDetails.tsx, src/routes/views/details/ociDetails/ociDetails.styles.ts, src/routes/views/details/ociDetails/ociDetails.tsx, src/routes/views/details/ocpBreakdown/ocpBreakdown.tsx, src/routes/views/details/ocpDetails/ocpDetails.styles.ts, src/routes/views/details/ocpDetails/ocpDetails.tsx, src/routes/views/details/rhelDetails/rhelDetails.styles.ts, src/routes/views/details/rhelDetails/rhelDetails.tsx, src/routes/views/explorer/explorer.styles.ts, src/routes/views/explorer/explorer.tsx, src/routes/views/ros/recommendations/recommendations.styles.ts, src/routes/views/ros/recommendations/recommendations.tsx, src/routes/views/ros/recommendations/rosTable.tsx, src/routes/views/utils/paths.ts
Added recommendations to the OCP breakdown page
https://issues.redhat.com/browse/COST-3493
Demo
https://user-images.githubusercontent.com/17481322/225171442-f091dc99-3d9d-465a-adee-990de2095c71.mov
=> Added recommendations to the OCP breakdown page

src/appEntry.tsx, src/components/drawers/commonDrawer/commonDrawer.scss, src/components/drawers/commonDrawer/commonDrawer.tsx, src/routes/views/details/ocpDetails/ocpDetails.styles.ts, src/routes/views/recommendations/recommendations.styles.ts, src/routes/views/recommendations/recommendations.tsx
Clean up recommendations drawer
https://issues.redhat.com/browse/COST-3493
=> Clean up recommendations drawer

src/app.tsx, src/components/drawers/commonDrawer/commonDrawer.scss, src/components/drawers/commonDrawer/commonDrawer.styles.ts, src/components/drawers/commonDrawer/commonDrawer.tsx, src/components/drawers/exports/exportsDrawer.tsx, src/components/drawers/recommendations/recommendationsDrawer.tsx, src/routes/views/details/ocpDetails/detailsTable.tsx
Sticky drawer implementation is based on RHOSAK app
=> Make PatternFly drawer sticky

package.json, yarn.lock
Added missing @formatjs/intl dependency
=> Added missing dependency

package.json, yarn.lock
This is blocking the UI from rendering
=> Revert @formatjs/intl v2.6.8

package.json, yarn.lock
remove @formatjs/intl dependency
=> remove @formatjs/intl dependency

src/routes/views/components/charts/common/chartDatum.ts, src/routes/views/components/charts/common/chartDatumForecast.ts, src/routes/views/overview/components/dashboardWidgetBase.tsx, src/store/dashboard/awsDashboard/awsDashboardWidgets.ts, src/store/dashboard/awsOcpDashboard/awsOcpDashboardWidgets.ts, src/store/dashboard/azureDashboard/azureDashboardWidgets.ts, src/store/dashboard/azureOcpDashboard/azureOcpDashboardWidgets.ts, src/store/dashboard/gcpDashboard/gcpDashboardWidgets.ts, src/store/dashboard/gcpOcpDashboard/gcpOcpDashboardWidgets.ts, src/store/dashboard/ibmDashboard/ibmDashboardWidgets.ts, src/store/dashboard/ociDashboard/ociDashboardWidgets.ts, src/store/dashboard/ocpCloudDashboard/ocpCloudDashboardWidgets.ts, src/store/dashboard/ocpDashboard/ocpDashboardWidgets.ts, src/store/dashboard/rhelDashboard/rhelDashboardWidgets.ts
Move forecast chart utils to its own file
=> Refactor forecast utils

package-lock.json, package.json
Update lock file and other dependencies
=> Update lock file

src/routes/views/components/dataToolbar/dataToolbar.tsx
Removed trailing comma and ampersand from filter field input
https://issues.redhat.com/browse/COST-3641
=> Remove trailing comma from filter field input

src/components/drawers/recommendations/recommendationsContent.tsx
Fix for default ros date range
=> Default ros date range

src/routes/views/details/ocpBreakdown/ocpBreakdown.tsx
Omit filters associated with the current group_by
https://issues.redhat.com/browse/COST-3642
=> Omit filters associated with the current group_by

src/routes/views/utils/paths.ts
Clear recommendationsTab query param
=> Clear recommendationsTab

src/api/api.ts
* remove extra auth interceptor call adding additional Bearer token.
=> Remove extra auth interceptor call.

src/routes/views/components/reports/reportSummary/reportSummaryItem.tsx
PatternFly progress bar cannot handle formatted locale values.
https://issues.redhat.com/browse/COST-3673
=> PatternFly progress bar fix

src/api/queries/rosQuery.ts, src/components/drawers/optimzations/optimizations.scss, src/components/drawers/optimzations/optimizations.styles.ts, src/components/drawers/optimzations/optimizationsContent.tsx, src/routes/views/components/optimizations/optimizationsToolbar.tsx, src/routes/views/details/ocpBreakdown/optimizationsBreakdown.tsx, src/routes/views/optimizations/optimizations.tsx, src/routes/views/utils/orderBy.ts
Updated optimizations toolbar to support ROS sorting, filtering, and pagination
https://issues.redhat.com/browse/COST-3676
=> Updated optimizations toolbar

src/api/queries/query.ts, src/routes/views/details/awsBreakdown/awsBreakdown.tsx, src/routes/views/details/azureBreakdown/azureBreakdown.tsx, src/routes/views/details/components/historicalData/historicalDataCostChart.tsx, src/routes/views/details/components/historicalData/historicalDataTrendChart.tsx, src/routes/views/details/components/historicalData/historicalDataUsageChart.tsx, src/routes/views/details/components/summary/summaryCard.tsx, src/routes/views/details/components/summary/summaryModalContent.tsx, src/routes/views/details/components/tag/tagLink.tsx, src/routes/views/details/components/tag/tagModal.tsx, src/routes/views/details/components/usageChart/usageChart.tsx, src/routes/views/details/gcpBreakdown/gcpBreakdown.tsx, src/routes/views/details/ibmBreakdown/ibmBreakdown.tsx, src/routes/views/details/ociBreakdown/ociBreakdown.tsx, src/routes/views/details/ocpBreakdown/ocpBreakdown.tsx, src/routes/views/details/rhelBreakdown/rhelBreakdown.tsx
Fix "All projects" summary for Platform project breakdown
https://issues.redhat.com/browse/COST-3679
=> "All projects" summary for Platform project breakdown

src/routes/views/details/awsBreakdown/awsBreakdown.tsx, src/routes/views/details/awsDetails/awsDetails.tsx, src/routes/views/details/components/historicalData/historicalDataCostChart.tsx, src/routes/views/details/components/historicalData/historicalDataTrendChart.tsx, src/routes/views/details/components/historicalData/historicalDataUsageChart.tsx, src/routes/views/details/components/summary/summaryCard.tsx, src/routes/views/details/components/summary/summaryModalContent.tsx
Added a workaround for AWS org unit filters
https://issues.redhat.com/browse/COST-3680
=> AWS org unit filter workaround

src/store/accountSettings/accountSettingsReducer.ts
Don't set local storage as undefined
=> Local storage

src/api/queries/query.ts, src/routes/views/details/ocpBreakdown/ocpBreakdown.tsx
Inaccessible OCP - Clusters/Nodes/Tags Breakdown page
https://issues.redhat.com/browse/COST-3684
=> Inaccessible OCP - Clusters/Nodes/Tags Breakdown page

src/routes/views/details/components/summary/summaryModalContent.tsx
Adjusted query params for for "All projects" modal
https://issues.redhat.com/browse/COST-3684
=> Adjusted query params for for "All projects" modal

src/components/drawers/optimzations/optimizationsContent.tsx, src/routes/views/optimizations/optimizations.tsx
Added function to help determine if config and variation are empty objects
=> Added function to check for empty ROS objects

src/routes/views/optimizations/optimizations.tsx
=> ROS pagination offset

src/routes/views/components/optimizations/optimizationsToolbar.tsx
Update optimizations filter options in alphabetical order
=> Update optimizations filter order

src/routes/views/details/ocpBreakdown/optimizationsBadge.tsx
Fix optimizations badge during pagination.
=> Fix optimizations badge during pagination

src/routes/views/components/charts/common/chartDatum.ts, src/routes/views/details/components/breakdown/breakdownBase.tsx, src/routes/views/details/components/breakdown/breakdownHeader.tsx, src/routes/views/details/components/costDistributionChart/costDistributionChart.tsx, src/routes/views/details/components/costOverview/costOverviewBase.tsx, src/routes/views/details/components/historicalData/historicalDataBase.tsx, src/routes/views/details/components/historicalData/historicalDataCostChart.tsx, src/routes/views/details/components/historicalData/historicalDataTrendChart.tsx, src/routes/views/details/components/summary/summaryCard.tsx, src/routes/views/details/components/summary/summaryModal.tsx, src/routes/views/details/components/summary/summaryModalContent.tsx, src/routes/views/details/ocpBreakdown/ocpBreakdown.tsx, src/routes/views/details/ocpDetails/detailsHeader.tsx, src/routes/views/details/ocpDetails/detailsTable.tsx, src/routes/views/details/ocpDetails/ocpDetails.tsx
Refactor OCP details and breakdown pages to use distributed cost values
=> Refactor OCP details and breakdown pages to use distributed cost values

src/routes/views/explorer/explorer.tsx, src/routes/views/explorer/explorerChart.tsx, src/routes/views/explorer/explorerTable.tsx, src/routes/views/explorer/explorerUtils.ts
Remove getComputedReportItemType and getComputedReportItemValueType functions
=> Celanup "ComputedReportItem" functions

src/routes/views/details/components/summary/summaryCard.tsx
Add default cost distribution for breakdown summary
https://issues.redhat.com/browse/COST-3724
=> Add default cost distribution for breakdown summary

locales/data.json, locales/translations.json, src/components/drawers/optimzations/optimizationsContent.tsx, src/locales/messages.ts
Added support to disable the link in optimizations drawer
=> Disable link in optimizations drawer

locales/data.json, locales/translations.json, src/locales/messages.ts
Update disabled "view all" message for optimizations drawer
=> Update disabled "view all" message

src/routes/views/details/ocpDetails/ocpDetails.tsx
Add distributed_cost as a delta option
https://issues.redhat.com/browse/COST-3723
=> Add distributed_cost as a delta option

src/routes/views/details/ocpDetails/detailsTable.tsx, src/routes/views/explorer/explorerChart.tsx, src/routes/views/explorer/explorerTable.tsx
Add distributed cost as an order by option
https://issues.redhat.com/browse/COST-3722
=> Add distributed cost as an order by option

src/api/queries/query.ts, src/routes/views/utils/query.ts
Reset offset for optimization filters
https://issues.redhat.com/browse/COST-3676
=> Reset offset for optimization filters

src/routes/views/components/dataToolbar/workloadType.tsx
Add daemonset for workload type filtering
https://issues.redhat.com/browse/COST-3676
=> Add daemonset for workload type filtering

src/routes/views/details/components/breakdown/breakdownHeader.tsx
Add default costDistribution for breakdown header
https://issues.redhat.com/browse/COST-3740
=> Cost distribution

src/routes/views/components/costDistribution/costDistribution.tsx, src/routes/views/details/components/historicalData/historicalDataBase.tsx, src/routes/views/details/components/historicalData/historicalDataCostChart.tsx, src/routes/views/details/components/historicalData/historicalDataTrendChart.tsx, src/routes/views/details/components/summary/summaryModalContent.tsx
Add costDistribution defaults
https://issues.redhat.com/browse/COST-3740
=> Add costDistribution defaults

src/routes/views/details/ocpDetails/detailsTable.tsx
Only show overhead labels when cost is distributed
=> Overhead labels

src/components/featureFlags/featureFlags.tsx, src/routes/views/components/groupBy/groupBy.tsx, src/routes/views/details/awsDetails/detailsToolbar.tsx, src/routes/views/details/components/breakdown/breakdownHeader.tsx, src/routes/views/details/components/costOverview/costOverviewBase.tsx, src/routes/views/details/components/historicalData/historicalDataCostChart.tsx, src/routes/views/details/components/summary/summaryCard.tsx, src/routes/views/details/components/summary/summaryModalContent.tsx, src/routes/views/details/ocpBreakdown/ocpBreakdown.tsx, src/routes/views/details/ocpDetails/detailsHeader.tsx, src/routes/views/details/ocpDetails/detailsTable.tsx, src/routes/views/details/ocpDetails/ocpDetails.tsx, src/routes/views/explorer/explorer.tsx, src/routes/views/explorer/explorerChart.tsx, src/routes/views/explorer/explorerHeader.tsx, src/routes/views/explorer/explorerTable.tsx, src/routes/views/utils/handles.ts, src/store/featureFlags/__snapshots__/featureFlags.test.ts.snap, src/store/featureFlags/featureFlags.test.ts, src/store/featureFlags/featureFlagsActions.ts, src/store/featureFlags/featureFlagsReducer.ts, src/store/featureFlags/featureFlagsSelectors.ts
- Add Unleash flag for cost categories dropdown options
- Add Unleash flag for cost distribution feature
- Fix default order_by for cost distribution
=> Add Unleash flags

src/routes/views/details/awsDetails/awsDetails.tsx, src/routes/views/details/azureDetails/azureDetails.tsx, src/routes/views/details/gcpDetails/gcpDetails.tsx, src/routes/views/details/ibmDetails/ibmDetails.tsx, src/routes/views/details/ociDetails/ociDetails.tsx, src/routes/views/details/ocpDetails/ocpDetails.tsx, src/routes/views/details/rhelDetails/rhelDetails.tsx, src/routes/views/overview/components/dashboardWidgetBase.tsx, src/routes/views/utils/handles.ts
Clear sort when new group by is selected
=> Clear sort

src/appEntry.tsx
Initialize Axios within AppEntry Vs global
https://issues.redhat.com/browse/RHCLOUD-25573
=> Initialize Axios

src/appEntry.tsx
Rename global store variable to help ensure it's not overridden by HCS
https://issues.redhat.com/browse/RHCLOUD-25573
=> Rename global store variable

locales/data.json, locales/translations.json, src/locales/messages.ts
Update optimizations empty state message
See https://docs.google.com/document/d/1kS1uEktplCOkP6_yguwdnCqiTFxGox-3X3ot2GYSiCk/edit
=> Update optimizations empty state message

src/routes/views/components/optimizations/optimizationsTable.tsx, src/routes/views/details/awsDetails/detailsTable.tsx, src/routes/views/details/azureDetails/detailsTable.tsx, src/routes/views/details/components/dataTable/dataTable.scss, src/routes/views/details/components/dataTable/dataTable.styles.ts, src/routes/views/details/gcpDetails/detailsTable.tsx, src/routes/views/details/ibmDetails/detailsTable.tsx, src/routes/views/details/ociDetails/detailsTable.tsx, src/routes/views/details/ocpDetails/detailsTable.tsx, src/routes/views/explorer/explorer.tsx, src/routes/views/explorer/explorerFilter.tsx, src/routes/views/explorer/explorerHeader.tsx, src/routes/views/explorer/explorerTable.scss, src/routes/views/explorer/explorerTable.styles.ts, src/routes/views/explorer/explorerTable.tsx
- Adjust checkbox vertical position for compact tables
- Reset pagination after date range has been selected
- Clean up unused div tags in table cells
- Adjust sticky columns for compact table
=> Adjustments for compact tables

src/app.tsx, src/components/inactiveSources/inactiveSources.tsx, src/routes/components/currency/currency.tsx, src/routes/views/components/costDistribution/costDistribution.tsx, src/routes/views/components/costType/costType.tsx, src/store/accountSettings/accountSettingsReducer.ts, src/utils/localStorage.ts
Moved `invalidateSession` to `app.tsx` to ensure it's called prior to updating local storage
https://issues.redhat.com/browse/COST-3780
=> Update local storage

locales/data.json, locales/translations.json, src/locales/messages.ts
Update no optimizations message for Summit
https://docs.google.com/document/d/1kS1uEktplCOkP6_yguwdnCqiTFxGox-3X3ot2GYSiCk
=> Update no optimizations message

src/components/drawers/exports/exportsTable.tsx, src/routes/components/costType/costType.tsx, src/routes/components/currency/currency.tsx, src/routes/components/state/errorState/errorState.tsx, src/routes/components/state/loadingState/loadingState.tsx, src/routes/costModels/components/errorState.tsx, src/routes/costModels/costModel/updateDistributionDialog.tsx, src/routes/costModels/costModel/updateMarkupDialog.tsx, src/routes/settings/calculations/calculations.tsx, src/routes/settings/components/errorState.tsx, src/routes/settings/costModel/updateDistributionDialog.tsx, src/routes/settings/costModel/updateMarkupDialog.tsx, src/routes/settings/costModelWizard/distribution.tsx, src/routes/settings/costModelWizard/markup.tsx, src/routes/settings/costModelsDetails/table.tsx, src/routes/settings/costModelsDetails/utils/table.tsx, src/routes/state/noData/noDataState.tsx, src/routes/state/noOptimizations/noOptimizationsState.tsx, src/routes/state/noProviders/noProvidersState.tsx, src/routes/views/components/charts/costChart/costChart.tsx, src/routes/views/components/charts/dailyCostChart/dailyCostChart.tsx, src/routes/views/components/charts/dailyTrendChart/dailyTrendChart.tsx, src/routes/views/components/charts/trendChart/trendChart.tsx, src/routes/views/components/charts/usageChart/usageChart.tsx, src/routes/views/components/costDistribution/costDistribution.tsx, src/routes/views/explorer/explorerChart.tsx, src/store/accountSettings/accountSettingsReducer.ts
Update title sizes for settings page and various bug fixes.
- Update title sizes
- Use PatternFLy's TitleSizes
- Fixed setting currency in local storage
- Fixed cost models loading state
=> Update title sizes

src/routes/settings/calculations/calculations.tsx, src/routes/settings/costModelsDetails/toolbar.tsx, src/routes/views/components/dataToolbar/dataToolbar.scss
- Removed save and reset buttons in favor of auto-updates
- Fixed cost models toolbar layout
- Fixed search icon border
=> Removed save and reset buttons

src/routes/settings/costCategory/costCategory.tsx, src/routes/settings/tagDetails/tagDetails.tsx
Convert tags tab to use React hooks
=> Convert tags tab to use React hooks

src/routes/views/details/ocpBreakdown/optimizationsBreakdown.tsx, src/routes/views/optimizations/optimizations.tsx
=> Remove unused properties

locales/data.json, locales/translations.json, src/components/permissions/permissions.tsx, src/locales/messages.ts, src/routes/components/page/notAuthorized/notAuthorizedState.tsx, src/routes/explorer/explorer.tsx, src/routes/settings/costCategory/costCategory.tsx, src/routes/settings/settings.tsx, src/routes/settings/tagDetails/tagDetails.tsx, src/utils/chrome.ts, src/utils/chrome.tsx
Refactored settings page to show empty states for cost-model and org admin permissions
=> Settings page Rbac permissions

src/routes/details/components/tag/tagLink.tsx, src/routes/details/components/tag/tagModal.tsx
Omit unsupported query params from tag API requests
https://issues.redhat.com/browse/COST-3834
=> Omit unsupported query params

src/routes/components/reports/reportSummary/reportSummaryItems.tsx, src/routes/details/components/summary/summaryCard.tsx
"Cost by default projects" card should reflect "Overhead cost" selection
https://issues.redhat.com/browse/COST-3838
=> "Cost by default projects" card should reflect "Overhead cost" selection

src/routes/details/components/costOverview/costOverviewBase.tsx, src/routes/details/components/summary/summaryCard.tsx, src/routes/details/components/summary/summaryModalContent.tsx, src/routes/overview/components/dashboardWidgetBase.tsx, src/store/dashboard/common/dashboardCommon.ts, src/store/dashboard/ocpDashboard/__snapshots__/ocpDashboard.test.ts.snap, src/store/dashboard/ocpDashboard/ocpDashboardSelectors.ts, src/store/dashboard/ocpDashboard/ocpDashboardWidgets.ts
Show distributed costs for "top 3 projects" in overview and "cost by projects" card when grouped by cluster.
=> Show distributed costs for "top 3 projects" and "cost by projects" card

src/components/permissions/permissions.tsx
Update isSettingsFeatureEnabled property name
=> isSettingsFeatureEnabled property

src/components/drawers/optimzations/optimizationsContent.tsx
Removes `toFixed` for optimization CPU and recommendation values
https://issues.redhat.com/browse/COST-3918
=> Optimizations decimal places

src/routes/details/components/usageChart/usageChart.tsx
Fix missing capacity for usage chart
=> Fix missing capacity

package-lock.json, package.json, src/routes/components/charts/historicalCostChart/__snapshots__/historicalCostChart.test.tsx.snap, src/routes/components/charts/historicalTrendChart/__snapshots__/historicalTrendChart.test.tsx.snap, src/routes/components/charts/historicalUsageChart/__snapshots__/historicalUsageChart.test.tsx.snap, src/routes/components/charts/trendChart/__snapshots__/trendChart.test.tsx.snap, src/routes/components/charts/usageChart/__snapshots__/usageChart.test.tsx.snap
Dependency updates
https://github.com/project-koku/koku-ui/pull/3238
=> Dependency updates

src/components/async/asyncComponent.test.tsx, src/routes/costModels/components/inputs/rateInput.tsx, src/routes/costModels/components/inputs/selector.tsx, src/routes/costModels/components/inputs/simpleInput.tsx, src/routes/costModels/costModel/sourcesTable.tsx, src/routes/costModels/costModelWizard/sources.tsx, src/routes/settings/costModels/components/inputs/rateInput.tsx, src/routes/settings/costModels/components/inputs/selector.tsx, src/routes/settings/costModels/components/inputs/simpleInput.tsx, src/routes/settings/costModels/costModel/sourcesTable.tsx, src/routes/settings/costModels/costModelWizard/sources.tsx, src/routes/settings/settings.tsx
Update Typescript types for future React 18 update
https://issues.redhat.com/browse/COST-3928
=> Update types for future React 18 update

src/components/drawers/optimzations/optimizationsContent.tsx
Reset Optimizations drawer selection whenever a new recommendation is displayed.
https://issues.redhat.com/browse/COST-3945
=> Reset Optimizations drawer selection

src/components/drawers/optimzations/optimizationsContent.tsx, src/utils/format.ts
Localize numeric values for optimizations drawer
https://issues.redhat.com/browse/COST-3959
=> Localize numeric values

src/components/drawers/optimzations/optimizationsContent.tsx
Check undefined before localizing values
https://issues.redhat.com/browse/COST-3959
=> Check undefined before localizing values

locales/data.json, locales/translations.json, src/api/ros/recommendations.ts, src/api/ros/ros.ts, src/components/drawers/optimzations/optimizationsContent.tsx, src/components/drawers/optimzations/optimizationsToolbar.tsx, src/locales/messages.ts, src/routes/components/dataTable/dataTable.styles.ts, src/routes/components/optimizations/optimizationsTable.tsx, src/utils/recomendations.ts
Display optimization notifications
Note: The alert title is still being debated, so that may be updated later.
https://issues.redhat.com/browse/COST-3980
**"No recommendations" notification**
=> Display optimization notifications

package-lock.json, package.json, src/api/ros/recommendations.ts, src/components/drawers/optimzations/optimizationsContent.tsx, src/utils/recomendations.ts
Update notifications for latest API update
=> Notifications api update

src/api/ros/recommendations.ts, src/components/drawers/optimzations/optimizationsContent.tsx
Use new API "current" value instead of calculating client-side
https://issues.redhat.com/browse/COST-4004
=> Use new API "current" value instead of calculating client-side

src/api/accountSettings.ts, src/routes/settings/calculations/calculations.tsx, src/store/accountSettings/accountSettingsActions.ts, src/store/accountSettings/accountSettingsReducer.ts, src/store/accountSettings/accountSettingsSelectors.ts
Update cost type and currency APIs for new settings page
=> Update cost type and currency APIs

scripts/release-branch.sh
Update release script to create pull requests
=> Update release script to create pull request

scripts/release-branch.sh
Update release script PR branch
=> Update release script PR branch

scripts/release-branch.sh
=> Update script PR message

locales/data.json, locales/translations.json, src/api/costModels.ts, src/components/featureFlags/featureFlags.tsx, src/locales/messages.ts, src/routes/settings/costModels/costModel/sourcesTable.tsx, src/routes/settings/tagDetails/tagTable.tsx, src/routes/settings/tagDetails/tagToolbar.tsx
- Replace provider_type with source_type
- Add last processed date to sources table
- Replace deprecated insights.chrome object with `useChrome` hook
=> Source type

src/components/permissions/permissions.tsx, src/store/costModels/actions.ts
- Unleash flag should override cost model permissions for new settings page feature.
- Fix price list path
=> Settings flag fix

src/api/providers.ts, src/components/inactiveSources/inactiveSources.tsx
https://issues.redhat.com/browse/COST-4163
=> Test paused state of inactive sources

locales/data.json, locales/translations.json, src/locales/messages.ts, src/store/settings/settingsActions.ts
https://issues.redhat.com/browse/COST-4164
=> Fix notification message for updated tag

locales/data.json, locales/translations.json, src/locales/messages.ts, src/store/settings/settingsActions.ts
UI should display an error message per mock.
https://issues.redhat.com/browse/COST-4183
=> UI should handle the 200 tag limit

src/routes/settings/calculations/calculations.tsx, src/store/accountSettings/accountSettingsReducer.ts, src/utils/localStorage.ts
"Currency and calculations" settings tab should show default values
https://issues.redhat.com/browse/COST-4265
=> "Currency and calculations" settings tab should show default values

package.json, src/components/featureFlags/featureFlags.tsx, src/typings/globals.d.ts
Add install links target. This helps install a local build of charts package to test the UI.
Also fixed isProd and isBeta types
=> Add install links target

src/routes/details/components/pvcChart/modal/pvcContent.tsx, src/routes/details/components/pvcChart/pvcChart.tsx
PVC "more" link should be shown if there is at least one more pvc
https://issues.redhat.com/browse/COST-3823
=> PVC "more" link

src/routes/settings/costModels/costModel/updateCostModel.tsx, src/routes/settings/costModels/costModelWizard/costModelWizard.tsx
"Edit cost model" should allow currency update.
https://issues.redhat.com/browse/COST-4356
=> "Edit cost model" should allow currency update

src/routes/details/ocpBreakdown/ocpBreakdownOptimizations.tsx
Project filter should be shown for optimization details page
https://issues.redhat.com/browse/COST-4325
=> Add optimizations project filter

src/routes/settings/calculations/calculations.tsx, src/store/accountSettings/accountSettingsActions.ts, src/store/accountSettings/accountSettingsReducer.ts
Override user's currency and cost-type when applying default settings
https://issues.redhat.com/browse/COST-4485
=> Currency and cost-type settings

src/store/accountSettings/accountSettingsReducer.ts, src/utils/localStorage.ts
Update account currency and cost type upon fetch
=> Update account currency and cost type

package-lock.json, package.json, src/store/mockStore.ts, src/store/store.ts
https://issues.redhat.com/browse/COST-4511
=> Update Redux to use latest packages

src/routes/settings/platformProjects/platformProjects.tsx
Update table selection functionality for Platform projects
https://issues.redhat.com/browse/COST-3818
=> Update selection functionality

src/routes/settings/platformProjects/platformProjects.tsx
Merged main branch to stage-stable.
Use latest commit to update namespace `ref` in app-interface repo. Don't use merge commit, SHAs must be unique when images are created for each branch.
=> Deployment commit for stage-stable

src/routes/settings/platformProjects/platformProjects.tsx
Merged stage-stable branch to prod-beta.
Use latest commit to update namespace `ref` in app-interface repo. Don't use merge commit, SHAs must be unique when images are created for each branch.
=> Deployment commit for prod-beta

src/routes/settings/platformProjects/platformProjects.tsx
Merged prod-beta branch to prod-stable.
Use latest commit to update namespace `ref` in app-interface repo. Don't use merge commit, SHAs must be unique when images are created for each branch.
=> Deployment commit for prod-stable

src/routes/settings/costModels/costModel/header.tsx, src/routes/settings/costModels/costModel/priceListTable.tsx, src/routes/settings/costModels/costModelsDetails/utils/table.tsx, src/store/costModels/actions.ts
Fix cost-models navigation and tooltips
=> Fix cost-models navigation and tooltips

src/routes/components/resourceTypeahead/resourceFetch.tsx, src/routes/components/resourceTypeahead/resourceInput.tsx, src/routes/components/resourceTypeahead/resourceTypeahead.tsx
https://issues.redhat.com/browse/COST-4599
=> Refactor typeahead to use React functional components

locales/data.json, locales/translations.json, src/locales/messages.ts, src/routes/components/resourceTypeahead/resourceInput.tsx
Localize aria label for resource typeahead
=> Localize aria label

package-lock.json, package.json, src/routes/components/page/notAuthorized/notAuthorizedState.tsx, src/routes/components/page/notAvailable/notAvailable.tsx
https://issues.redhat.com/browse/COST-4512
=> Migrate frontend components -> patternfly/react-component-groups

locales/data.json, locales/translations.json, src/locales/messages.ts
https://issues.redhat.com/browse/COST-4586
=> Update platform projects docs link

locales/data.json, locales/translations.json, src/api/providers.ts, src/locales/messages.ts, src/routes/details/ocpBreakdown/clusterInfo/clusterInfoContent.tsx, src/routes/details/ocpBreakdown/clusterInfo/modal.styles.ts
https://issues.redhat.com/browse/COST-4559
=> Add cluster info links to cluster and source

src/components/featureFlags/featureFlags.tsx, src/routes/settings/tagLabels/tagLabels.tsx, src/store/featureFlags/__snapshots__/featureFlags.test.ts.snap, src/store/featureFlags/featureFlagsActions.ts, src/store/featureFlags/featureFlagsReducer.ts, src/store/featureFlags/featureFlagsSelectors.ts
Update Unleash flags for tag mapping
https://issues.redhat.com/browse/COST-3824
=> Unleash flag for tag mapping

src/components/featureFlags/featureFlags.tsx, src/routes/components/charts/costChart/costChart.tsx, src/routes/components/charts/costExplorerChart/costExplorerChart.tsx, src/routes/components/charts/dailyCostChart/dailyCostChart.tsx, src/routes/components/charts/dailyTrendChart/dailyTrendChart.tsx, src/routes/components/charts/historicalCostChart/historicalCostChart.tsx, src/routes/components/charts/historicalTrendChart/historicalTrendChart.tsx, src/routes/components/charts/historicalUsageChart/historicalUsageChart.tsx, src/routes/components/charts/trendChart/trendChart.tsx, src/routes/components/charts/usageChart/usageChart.tsx
https://issues.redhat.com/browse/COST-4733
=> Unleash's UserIDs strategy should use an account IDs

src/components/featureFlags/featureFlags.tsx, src/components/featureFlags/index.ts, src/routes/settings/tagLabels/tagLabels.tsx
https://issues.redhat.com/browse/COST-4733
=> Add hooks for feature flags

src/routes/details/components/breakdown/breakdownHeader.styles.ts, src/routes/details/components/breakdown/breakdownHeader.tsx, src/routes/details/ocpBreakdown/providerDetails/clusterInfo/clusterInfo.styles.ts, src/routes/details/ocpBreakdown/providerDetails/clusterInfo/clusterInfo.tsx, src/routes/details/ocpBreakdown/providerDetails/dataDetails/components/cloudIData.tsx, src/routes/details/ocpBreakdown/providerDetails/dataDetails/components/clusterData.tsx, src/routes/details/ocpBreakdown/providerDetails/dataDetails/components/overallStatus.tsx, src/routes/details/ocpBreakdown/providerDetails/dataDetails/dataDetails.styles.ts, src/routes/details/ocpBreakdown/providerDetails/dataDetails/dataDetails.tsx, src/routes/details/ocpBreakdown/providerDetails/dataDetails/utils/status.ts
Add overall status label to breakdown header
=> Add overall status label to breakdown header

src/routes/settings/costModels/components/rateForm/taggingRatesForm.tsx, src/routes/settings/costModels/components/readOnlyTooltip.tsx, src/routes/settings/costModels/costModel/sourcesTable.tsx, src/routes/settings/costModels/costModelsDetails/table.tsx
https://issues.redhat.com/browse/COST-4795
=> Add tooltips to delete actions

src/routes/details/components/breakdown/breakdownBase.tsx, src/routes/details/components/pvcChart/modal/pvcContent.tsx, src/routes/details/components/pvcChart/modal/pvcToolbar.tsx, src/routes/details/ocpBreakdown/ocpBreakdown.tsx, src/routes/details/ocpBreakdown/ocpBreakdownOptimizations.tsx, src/routes/details/ocpDetails/detailsTable.tsx
https://issues.redhat.com/browse/COST-4477
=> Apply cluster filters from OCP details to Optimizations

src/routes/details/components/breakdown/breakdownHeader.styles.ts, src/routes/details/components/breakdown/breakdownHeader.tsx
=> Lack of description omits cluster info link

src/routes/details/ocpBreakdown/providerDetails/dataDetails/components/overallStatus.tsx
=> Status props may not be available initially.

src/routes/details/ocpBreakdown/providerDetails/dataDetails/components/overallStatus.tsx
=> Fix message when infrastructure is missing properties

src/routes/details/ocpBreakdown/providerDetails/dataDetails/components/overallStatus.tsx, src/routes/details/ocpBreakdown/providerDetails/dataDetails/utils/status.ts
=> Skip summaryState for cloud

locales/data.json, locales/translations.json, src/locales/messages.ts, src/routes/settings/tagLabels/tagMapping/components/parentTagMapping/parentTagMappingReview.tsx, src/routes/settings/tagLabels/tagMapping/components/parentTags/parentTagsTable.tsx, src/routes/settings/tagLabels/tagMapping/components/parentTags/parentTagsToolbar.tsx
https://issues.redhat.com/browse/COST-3824
=> Restore source type column in tag mapping wizard

src/routes/settings/tagLabels/tagMapping/components/childTags/childTags.tsx, src/routes/settings/tagLabels/tagMapping/components/parentTags/parentTags.tsx, src/routes/settings/tagLabels/tagMapping/tagMapping.tsx
https://issues.redhat.com/browse/COST-3824
=> Fix sorting keys for parent and child tag mapping APIs

locales/data.json, locales/translations.json, src/locales/messages.ts
https://issues.redhat.com/browse/COST-4797
=> Update broken doc link

src/components/inactiveSources/inactiveSources.tsx, src/routes/components/page/noProviders/noProvidersState.tsx
https://issues.redhat.com/browse/COST-4815
=> Integrations links need to be updated

src/routes/details/awsDetails/detailsHeader.styles.ts, src/routes/details/awsDetails/detailsHeader.tsx, src/routes/details/azureDetails/detailsHeader.styles.ts, src/routes/details/azureDetails/detailsHeader.tsx, src/routes/details/components/breakdown/breakdownHeader.styles.ts, src/routes/details/components/breakdown/breakdownHeader.tsx, src/routes/details/gcpDetails/detailsHeader.styles.ts, src/routes/details/gcpDetails/detailsHeader.tsx, src/routes/details/ibmDetails/detailsHeader.styles.ts, src/routes/details/ibmDetails/detailsHeader.tsx, src/routes/details/ociDetails/detailsHeader.styles.ts, src/routes/details/ociDetails/detailsHeader.tsx, src/routes/details/ocpDetails/detailsHeader.styles.ts, src/routes/details/ocpDetails/detailsHeader.tsx, src/routes/details/rhelDetails/detailsHeader.styles.ts, src/routes/details/rhelDetails/detailsHeader.tsx, src/routes/explorer/explorerHeader.styles.ts, src/routes/explorer/explorerHeader.tsx, src/routes/overview/overview.styles.ts, src/routes/overview/overview.tsx
Refactor page headers to wrap better at small sizes
https://issues.redhat.com/browse/COST-4823
=> Refactor page headers to wrap better at small sizes

locales/data.json, locales/translations.json, src/locales/messages.ts, src/store/settings/settingsActions.ts
Add alert for when attempting to delete a tag mapping key
https://issues.redhat.com/browse/COST-3824
=> Add alert for tag mapping error

src/routes/settings/costModels/costModelsDetails/table.tsx, src/routes/settings/costModels/costModelsDetails/utils/filters.tsx
Add aria label and remove test label
=> Add aria label

.github/workflows/pull_request.yml, .github/workflows/stale.yml, .github/workflows/tag_release.yml
=> CI - Update actions to use non-deprecated version of node.js

.github/workflows/ci.yml
Add branches for codecov upload
=> Add branches for codecov upload

src/api/settings.test.ts, src/api/settings.ts, src/routes/settings/costModels/costModelsDetails/table.tsx
Add settings api test and silence PatternFly Th aria-label warning
=> Add settings api test

src/api/orgs/orgUtils.test.ts, src/api/queries/awsQuery.test.ts, src/api/queries/azureQuery.test.ts, src/api/queries/gcpQuery.test.ts, src/api/queries/ibmQuery.test.ts, src/api/queries/ociQuery.test.ts, src/api/queries/ocpCloudQuery.test.ts, src/api/queries/ocpQuery.test.ts, src/api/queries/overviewQuery.test.ts, src/api/queries/providers.test.ts, src/api/queries/query.test.ts, src/api/queries/query.ts, src/api/queries/rhelQuery.test.ts, src/api/queries/userAccessQuery.test.ts, src/routes/settings/costModels/costModelsDetails/table.tsx
=> Add query tests

src/api/accountSettings.test.ts, src/api/export/awsExport.test.ts, src/api/export/awsOcpExport.test.ts, src/api/export/azureExport.test.ts, src/api/export/azureOcpExport.test.ts, src/api/export/exportUtils.test.ts, src/api/export/gcpExport.test.ts, src/api/export/gcpOcpExport.test.ts, src/api/export/ibmExport.test.ts, src/api/export/ociExport.test.ts, src/api/export/ocpCloudExport.test.ts, src/api/export/ocpExport.test.ts, src/api/export/rhelExport.test.ts, src/api/settings.test.ts
=> Add export API tests

locales/data.json, locales/translations.json, src/locales/messages.ts, src/routes/details/ocpBreakdown/providerDetails/clusterInfo/clusterInfoContent.tsx, src/routes/details/ocpBreakdown/providerDetails/clusterInfo/components/cloudIntegration.tsx, src/utils/paths.ts
Add cost model links to cluster info
https://issues.redhat.com/browse/COST-4925
**Example 1**
**Example 2**
=> Add cost model links to cluster info

src/components/featureToggle/featureToggle.tsx, src/routes/details/components/breakdown/breakdownHeader.tsx, src/routes/settings/settings.tsx, src/routes/settings/tagLabels/tagLabels.tsx, src/store/featureToggle/__snapshots__/featureToggle.test.ts.snap, src/store/featureToggle/featureToggle.test.ts, src/store/featureToggle/featureToggleActions.ts, src/store/featureToggle/featureToggleReducer.ts, src/store/featureToggle/featureToggleSelectors.ts
* Create Unleash toggles for new features; COST-4855, COST-4781, and COST-4855
* Remove unused Unleash toggles for settings platform, cluster info, and tag mapping
=> Unleash toggles

src/routes/details/ocpBreakdown/providerDetails/clusterInfo/clusterInfoContent.tsx
Ensure cluster info providers have unique keys
=> Add unique key

locales/data.json, locales/translations.json, src/locales/messages.ts, src/routes/details/components/breakdown/breakdownHeader.styles.ts, src/routes/details/components/breakdown/breakdownHeader.tsx
Show filter chips in details breakdown
https://issues.redhat.com/browse/COST-4977
=> Show filter chips in details breakdown

src/routes/details/components/breakdown/breakdownHeader.styles.ts, src/routes/details/components/breakdown/breakdownHeader.tsx
Changed the filter-by alert to an info icon with a pop-over
=> Filter-by info icon

locales/data.json, locales/translations.json, src/locales/messages.ts, src/routes/components/dropdownWrapper/dropdownWrapper.tsx
https://issues.redhat.com/browse/COST-5008
=> Add kebab tooltips

src/routes/settings/costModels/components/rateTable.tsx
https://issues.redhat.com/browse/COST-5008
=> Add tooltip for price list kebab

src/routes/details/components/breakdown/breakdownHeader.tsx
Ensure excludes filter is shown in breakdown
https://issues.redhat.com/browse/COST-4977
=> Ensure excludes filter is shown in breakdown

src/api/costModels.ts, src/routes/settings/costModels/components/rateForm/utils.tsx, src/routes/settings/costModels/costModel/distribution.tsx, src/routes/settings/costModels/costModel/updateDistributionDialog.tsx, src/routes/settings/costModels/costModelWizard/costModelWizard.tsx
Rename network and storage properties to reflect cost model API update
https://issues.redhat.com/browse/COST-4781
=> Rename cost model properties

src/routes/details/components/historicalData/historicalDataBase.tsx, src/routes/details/ocpDetails/detailsTable.tsx, src/utils/props.ts
Disable breakdown links for unattributed network and storage projects
https://issues.redhat.com/browse/COST-4781
=> Disable breakdown links for unattributed projects

src/api/reports/report.ts, src/routes/components/charts/common/chartDatum.ts, src/routes/utils/computedReport/getComputedReportItems.ts
https://issues.redhat.com/browse/COST-4781
=> Update network usage chart to support data_transfer_in values

src/routes/details/ocpDetails/detailsTable.tsx, src/routes/utils/paths.ts, src/utils/props.ts
Update project classification variables
=> Update project classifications

src/routes/settings/costModels/costModelWizard/costModelWizard.tsx
Replace deprecated PatternFly wizard component
https://issues.redhat.com/browse/COST-3738
=> Replace deprecated PatternFly wizard component

src/components/drawers/exports/exportsTable.tsx, src/routes/components/dataTable/dataTable.tsx, src/routes/components/dataTable/expandableTable.tsx, src/routes/components/dataTable/selectableTable.tsx, src/routes/details/awsBreakdown/instances/instancesTable.tsx, src/routes/details/awsDetails/detailsTable.tsx, src/routes/details/azureDetails/detailsTable.tsx, src/routes/details/components/pvcChart/modal/pvcTable.tsx, src/routes/details/gcpDetails/detailsTable.tsx, src/routes/details/ibmDetails/detailsTable.tsx, src/routes/details/ociDetails/detailsTable.tsx, src/routes/details/ocpDetails/detailsTable.tsx, src/routes/details/rhelDetails/detailsTable.tsx, src/routes/explorer/explorerTable.tsx, src/routes/settings/costCategory/costCategoryTable.tsx, src/routes/settings/platformProjects/platformProjectsTable.tsx, src/routes/settings/tagLabels/tagMapping/components/childTags/childTagsTable.tsx, src/routes/settings/tagLabels/tagMapping/components/parentTags/parentTagsTable.tsx, src/routes/settings/tagLabels/tagMapping/tagMappingTable.tsx, src/routes/settings/tagLabels/tags/tagsTable.tsx
Replace deprecated PatternFly table components
https://issues.redhat.com/browse/COST-5184
=> Replace deprecated PatternFly table components

src/routes/settings/costModels/costModelWizard/costModelWizard.tsx
Wizard's final step should have "create" button
https://issues.redhat.com/browse/COST-3738
=> Wizard final step buton text

src/api/reports/awsReports.ts, src/routes/details/awsBreakdown/instances/instancesTable.tsx, src/routes/utils/computedReport/getComputedReportItems.ts
Update AWS EC2 instances table for new API structure
https://issues.redhat.com/browse/COST-4855
=> Update AWS EC2 instances table

src/routes/details/awsBreakdown/awsBreakdown.tsx, src/routes/details/azureBreakdown/azureBreakdown.tsx, src/routes/details/components/breakdown/breakdownBase.tsx, src/routes/details/components/breakdown/breakdownHeader.tsx, src/routes/details/gcpBreakdown/gcpBreakdown.tsx, src/routes/details/ibmBreakdown/ibmBreakdown.tsx, src/routes/details/ociBreakdown/ociBreakdown.tsx, src/routes/details/ocpBreakdown/ocpBreakdown.tsx, src/routes/details/ocpBreakdown/optimizations.tsx, src/routes/details/rhelBreakdown/rhelBreakdown.tsx, src/routes/optimizations/optimizationsBreakdown/optimizationsBreakdown.tsx, src/routes/optimizations/optimizationsDetails/optimizationsDetails.tsx, src/routes/utils/queryState.ts
Add project link to optimizations breakdown page
https://issues.redhat.com/browse/COST-4527
**Enabled**
**Disabled**
=> Add project link to optimizations breakdown page

src/routes/components/dataToolbar/dataToolbar.styles.ts, src/routes/components/dataToolbar/utils/actions.tsx, src/routes/details/ocpDetails/detailsTable.tsx
https://issues.redhat.com/browse/COST-5301
=> OCP unallocated and unattributed projects should be exportable

locales/data.json, locales/translations.json, src/locales/messages.ts
https://issues.redhat.com/browse/COST-5426
=> Modified overhead label to read "Includes overhead"

src/routes/components/resourceTypeahead/resourceFetch.tsx
Refactor type-ahead to test if search string matches alias
https://issues.redhat.com/browse/COST-4855
=> Refactor type-ahead matching

src/routes/details/awsBreakdown/instances/instances.tsx, src/routes/utils/groupBy.ts
Omit AWS details page filters from available EC2 filters
https://issues.redhat.com/browse/COST-5464
=> Omit AWS details page filters from available EC2 filters

src/routes/details/awsBreakdown/instances/instancesTable.tsx
https://issues.redhat.com/browse/COST-5472
=> Add sorting for usage column

src/routes/details/awsBreakdown/instances/instancesTable.tsx
Removed percentage from EC2 instances table per design discussion with team.
https://issues.redhat.com/browse/COST-4855
=> Remove percentage from EC2 instances table

src/routes/details/awsBreakdown/instances/instancesTable.tsx, src/routes/details/awsDetails/detailsTable.tsx, src/routes/details/azureDetails/detailsTable.tsx, src/routes/details/components/actions/actions.tsx, src/routes/details/gcpDetails/detailsTable.tsx, src/routes/details/ibmDetails/detailsTable.tsx, src/routes/details/ociDetails/detailsTable.tsx, src/routes/details/ocpDetails/detailsTable.tsx, src/routes/details/rhelDetails/detailsTable.tsx
https://issues.redhat.com/browse/COST-5487
=> Refactor export to support EC2 instances

src/components/featureToggle/featureToggle.tsx, src/store/featureToggle/__snapshots__/featureToggle.test.ts.snap, src/store/featureToggle/featureToggleActions.ts, src/store/featureToggle/featureToggleReducer.ts, src/store/featureToggle/featureToggleSelectors.ts
Add support for `cost-management.ui.ocp-cloud-group-bys` Unleash flag
=> Unleash flag

src/api/resources/resource.ts, src/routes/details/awsBreakdown/instances/instancesTable.tsx, src/routes/details/awsBreakdown/instances/instancesToolbar.tsx, src/routes/details/awsDetails/detailsTable.tsx, src/routes/details/azureDetails/detailsTable.tsx, src/routes/details/gcpDetails/detailsTable.tsx, src/routes/details/ibmDetails/detailsTable.tsx, src/routes/details/ociDetails/detailsTable.tsx, src/routes/details/ocpDetails/detailsTable.tsx, src/routes/details/rhelDetails/detailsTable.tsx, src/routes/explorer/explorerTable.tsx
- Omit resource_id / account_id if it is identical to alias https://issues.redhat.com/browse/COST-5524
- EC2 page should use a common filter key https://issues.redhat.com/browse/COST-5524
=> Ec2 fit an finish

src/routes/details/awsDetails/awsDetails.tsx, src/routes/details/azureDetails/azureDetails.tsx, src/routes/details/gcpDetails/gcpDetails.tsx, src/routes/details/ibmDetails/ibmDetails.tsx, src/routes/details/ociDetails/ociDetails.tsx, src/routes/details/ocpDetails/ocpDetails.tsx, src/routes/details/rhelDetails/rhelDetails.tsx
Need to apply filter props differently for the pagination "per page" toggle
https://issues.redhat.com/browse/COST-5563
=> Fix pagination "per page" toggle

src/components/featureToggle/featureToggle.tsx, src/routes/details/awsDetails/awsDetails.tsx, src/routes/details/awsDetails/detailsTable.tsx, src/routes/details/azureDetails/azureDetails.tsx, src/routes/details/azureDetails/detailsTable.tsx, src/routes/details/components/providerDetails/components/overallStatus.tsx, src/routes/details/components/providerDetails/providerDetailsContent.tsx, src/routes/details/components/providerDetails/providerDetailsModal.tsx, src/routes/details/components/providerDetails/providerDetailsTable.tsx, src/routes/details/gcpDetails/detailsTable.tsx, src/routes/details/gcpDetails/gcpDetails.tsx, src/routes/details/ibmDetails/detailsTable.tsx, src/routes/details/ibmDetails/ibmDetails.tsx, src/routes/details/ociDetails/detailsTable.tsx, src/routes/details/ociDetails/ociDetails.tsx, src/routes/details/ocpBreakdown/ocpBreakdown.tsx, src/routes/details/ocpDetails/detailsTable.tsx, src/routes/details/ocpDetails/ocpDetails.tsx, src/routes/details/rhelDetails/detailsTable.tsx, src/routes/details/rhelDetails/rhelDetails.tsx, src/store/featureToggle/__snapshots__/featureToggle.test.ts.snap, src/store/featureToggle/featureToggleActions.ts, src/store/featureToggle/featureToggleReducer.ts, src/store/featureToggle/featureToggleSelectors.ts
Add integrations status in the details page
https://issues.redhat.com/browse/COST-5386
=> Integration status

src/api/resources/awsOcpResource.test.ts, src/api/resources/awsOcpResource.ts, src/routes/components/resourceTypeahead/resourceInput.tsx, src/routes/explorer/explorerFilter.tsx, src/routes/explorer/explorerToolbar.tsx, src/routes/explorer/explorerUtils.ts
Improve resource type search in Cost explorer (AWS and OCP on AWS)
https://issues.redhat.com/browse/COST-5596
=> Improve resource type search in Cost explorer

src/api/resources/awsOcpResource.ts
https://issues.redhat.com/browse/COST-5596
=> Fix & symbol

src/routes/components/dataToolbar/costCategoryValue.tsx, src/routes/components/dataToolbar/tagValue.tsx, src/routes/components/dataToolbar/utils/category.tsx, src/routes/settings/costModels/costModel/assignSourcesModalToolbar.tsx, src/routes/settings/costModels/costModel/sourcesToolbar.tsx, src/routes/settings/costModels/costModelWizard/assignSourcesToolbar.tsx, src/routes/settings/costModels/costModelsDetails/utils/filters.tsx
https://issues.redhat.com/browse/COST-5611
=> Replace legacy filter pattern with PatternFly's Search

src/routes/components/dateRange/dateRange.tsx, src/routes/details/awsDetails/awsDetails.tsx, src/routes/details/awsDetails/detailsHeader.tsx, src/routes/details/azureDetails/azureDetails.tsx, src/routes/details/azureDetails/detailsHeader.tsx, src/routes/details/gcpDetails/detailsHeader.tsx, src/routes/details/gcpDetails/gcpDetails.tsx, src/routes/details/ibmDetails/detailsHeader.tsx, src/routes/details/ibmDetails/ibmDetails.tsx, src/routes/details/ociDetails/detailsHeader.tsx, src/routes/details/ociDetails/ociDetails.tsx, src/routes/details/ocpDetails/detailsHeader.tsx, src/routes/details/ocpDetails/ocpDetails.tsx, src/routes/details/rhelDetails/detailsHeader.tsx, src/routes/details/rhelDetails/rhelDetails.tsx, src/routes/explorer/explorer.tsx, src/routes/explorer/explorerFilter.tsx, src/routes/explorer/explorerHeader.tsx
Disable previous month selection if data is not available
https://issues.redhat.com/browse/COST-5563
=> Disable previous month

src/routes/details/awsBreakdown/instances/instances.tsx, src/routes/details/components/providerStatus/providerBreakdownContent.tsx, src/routes/details/components/providerStatus/providerDetailsContent.tsx, src/routes/details/components/providerStatus/providerStatus.tsx, src/routes/details/components/pvcChart/modal/pvcContent.tsx, src/routes/details/ocpBreakdown/clusterInfo/clusterInfoContent.tsx, src/routes/details/ocpBreakdown/virtualization/virtualization.tsx
NotAvailable empty state should omit title for tabs. We only want to display a title when shown in a full page.
https://issues.redhat.com/browse/COST-5684
=> NotAvailable empty state should omit title for tabs

src/routes/details/awsBreakdown/instances/instances.styles.ts, src/routes/details/awsBreakdown/instances/instances.tsx, src/routes/details/ocpBreakdown/virtualization/virtualization.styles.ts, src/routes/details/ocpBreakdown/virtualization/virtualization.tsx, src/routes/optimizations/optimizationsBreakdown/optimizationsBreakdown.styles.ts, src/routes/optimizations/optimizationsDetails/optimizationsDetails.styles.ts
Instances and virtualization should have their own styles. Currently pointing to unused styles for optimizations
=> Instances and virtualization should have their own styles

src/routes/details/ocpBreakdown/virtualization/virtualizationTable.tsx
https://issues.redhat.com/browse/COST-5720
=> Virtualization cpu and memory sort use incorrect query params

src/routes/details/components/providerStatus/providerDetailsModal.tsx
https://issues.redhat.com/browse/COST-5748
=> Integration status modal is sometimes misnamed

src/routes/details/components/providerStatus/components/cloudData.tsx
https://issues.redhat.com/browse/COST-5750
=> Incorrect status on Integration details page for misconfigured source

src/routes/components/dataToolbar/dataToolbar.tsx, src/routes/components/dataToolbar/utils/tags.tsx, src/routes/components/groupBy/groupBy.tsx, src/routes/details/awsDetails/awsDetails.tsx, src/routes/details/awsDetails/detailsHeader.tsx, src/routes/details/awsDetails/detailsToolbar.tsx, src/routes/details/azureDetails/azureDetails.tsx, src/routes/details/azureDetails/detailsHeader.tsx, src/routes/details/azureDetails/detailsToolbar.tsx, src/routes/details/gcpDetails/detailsHeader.tsx, src/routes/details/gcpDetails/detailsToolbar.tsx, src/routes/details/gcpDetails/gcpDetails.tsx, src/routes/details/ibmDetails/detailsHeader.tsx, src/routes/details/ibmDetails/detailsToolbar.tsx, src/routes/details/ibmDetails/ibmDetails.tsx, src/routes/details/ociDetails/detailsHeader.tsx, src/routes/details/ociDetails/detailsToolbar.tsx, src/routes/details/ociDetails/ociDetails.tsx, src/routes/details/ocpDetails/detailsHeader.tsx, src/routes/details/ocpDetails/detailsToolbar.tsx, src/routes/details/ocpDetails/ocpDetails.tsx, src/routes/details/rhelDetails/detailsHeader.tsx, src/routes/details/rhelDetails/detailsToolbar.tsx, src/routes/details/rhelDetails/rhelDetails.tsx, src/routes/explorer/explorerFilter.tsx, src/routes/explorer/explorerHeader.tsx
his will ensure the tags filter has the correct options for the selected month
https://issues.redhat.com/browse/COST-5753
=> Filter dropdown on Details pages lacks correct Tag options

src/routes/details/awsDetails/detailsHeader.tsx, src/routes/details/azureDetails/detailsHeader.tsx, src/routes/details/gcpDetails/detailsHeader.tsx, src/routes/details/ibmDetails/detailsHeader.tsx, src/routes/details/ociDetails/detailsHeader.tsx, src/routes/details/ocpDetails/detailsHeader.tsx, src/routes/details/rhelDetails/detailsHeader.tsx, src/routes/utils/dateRange.ts
Reset details page date range dropdown when nav link is clicked
https://issues.redhat.com/browse/COST-5830
=> Reset details page date range dropdown

locales/data.json, locales/translations.json, src/locales/messages.ts, src/routes/components/export/exportModal.tsx, src/routes/components/export/exportSubmit.tsx, src/routes/details/awsDetails/awsDetails.tsx, src/routes/details/awsDetails/detailsTable.tsx, src/routes/details/azureDetails/azureDetails.tsx, src/routes/details/azureDetails/detailsTable.tsx, src/routes/details/components/actions/actions.tsx, src/routes/details/gcpDetails/detailsTable.tsx, src/routes/details/gcpDetails/gcpDetails.tsx, src/routes/details/ibmDetails/detailsTable.tsx, src/routes/details/ibmDetails/ibmDetails.tsx, src/routes/details/ociDetails/detailsTable.tsx, src/routes/details/ociDetails/ociDetails.tsx, src/routes/details/ocpDetails/detailsTable.tsx, src/routes/details/ocpDetails/ocpDetails.tsx, src/routes/details/rhelDetails/detailsTable.tsx, src/routes/details/rhelDetails/rhelDetails.tsx, src/routes/explorer/explorer.tsx
Details page export doesn't always reflect date range selection
https://issues.redhat.com/browse/COST-5831
=> Details page export doesn't always reflect date range selection

src/routes/utils/query.ts
Reset pagination offset upon per page selection
https://issues.redhat.com/browse/COST-5848
=> Reset pagination offset upon per-page selection

src/routes/details/components/breakdown/breakdownBase.tsx
Adjust optimizations active tab key index in breakdown page
https://issues.redhat.com/browse/COST-5849
=> Adjust optimizations active tab key index

src/routes/details/ocpDetails/detailsHeader.tsx, src/routes/explorer/explorerHeader.tsx, src/routes/explorer/explorerTable.tsx
https://issues.redhat.com/browse/COST-5870
=> Make Overhead Costs dropdown always available

src/api/resources/awsOcpResource.ts, src/routes/details/ocpDetails/detailsHeader.tsx, src/routes/explorer/explorerHeader.styles.ts, src/routes/explorer/explorerHeader.tsx, src/routes/utils/cost.tsx
- COST-5891 Show total cost in Cost Explorer header
- COST-5921 resource-types/aws-categories API doesn't support openshift param
=> Show total cost in Cost Explorer header

src/routes/details/components/breakdown/breakdownBase.tsx, src/routes/details/ocpBreakdown/ocpBreakdown.tsx, src/routes/details/ocpBreakdown/virtualization/virtualization.tsx, src/routes/details/ocpBreakdown/virtualization/virtualizationTable.tsx
https://issues.redhat.com/browse/COST-6024
=> Display the overhead cost selection in the VMs tab

locales/data.json, locales/translations.json, src/locales/messages.ts, src/routes/settings/costModels/components/__snapshots__/rateTable.test.tsx.snap
https://issues.redhat.com/browse/COST-5987
=> Cost model update to include VM core metric

src/routes/details/components/costBreakdownChart/costBreakdownChart.tsx
Clean up Sankey `links` and `valueFormatter`
=> Clean up Sankey links

src/routes/details/ocpBreakdown/virtualization/storage/modal/storageModal.tsx, src/routes/details/ocpBreakdown/virtualization/virtualization.tsx, src/routes/settings/costModels/costModel/costModelInfo.tsx
Fix VM storage modal for PatternFly v6 and add cards for cost model views
=> PatternFly v6 fixes

src/routes/details/components/costBreakdownChart/costBreakdownChart.tsx, src/routes/details/ocpBreakdown/virtualization/storage/modal/storageContent.tsx
VM storage values should to be formatted with units label
=> Format VM storage values

locales/data.json, locales/translations.json, package-lock.json, package.json, src/locales/messages.ts, src/routes/details/components/costBreakdownChart/costBreakdownChart.tsx
Sankey should use "all other costs" label
=> Sankey should use "all other costs" label

src/routes/details/components/costBreakdownChart/costBreakdownChart.styles.ts, src/routes/details/components/costBreakdownChart/costBreakdownChart.tsx
Add node gap to Sankey chart and remove min node height toggle
=> Add node gap to Sankey chart

src/routes/details/awsBreakdown/costOverview.tsx, src/routes/details/azureBreakdown/costOverview.tsx, src/routes/details/gcpBreakdown/costOverview.tsx, src/routes/details/ibmBreakdown/costOverview.tsx, src/routes/details/ociBreakdown/costOverview.tsx, src/routes/details/rhelBreakdown/costOverview.tsx, src/store/breakdown/costOverview/awsCostOverview/awsCostOverview.test.ts, src/store/breakdown/costOverview/awsCostOverview/awsCostOverviewReducer.ts, src/store/breakdown/costOverview/awsCostOverview/awsCostOverviewWidgets.ts, src/store/breakdown/costOverview/azureCostOverview/azureCostOverview.test.ts, src/store/breakdown/costOverview/azureCostOverview/azureCostOverviewReducer.ts, src/store/breakdown/costOverview/azureCostOverview/azureCostOverviewWidgets.ts, src/store/breakdown/costOverview/gcpCostOverview/gcpCostOverview.test.ts, src/store/breakdown/costOverview/gcpCostOverview/gcpCostOverviewReducer.ts, src/store/breakdown/costOverview/gcpCostOverview/gcpCostOverviewWidgets.ts, src/store/breakdown/costOverview/ibmCostOverview/ibmCostOverview.test.ts, src/store/breakdown/costOverview/ibmCostOverview/ibmCostOverviewReducer.ts, src/store/breakdown/costOverview/ibmCostOverview/ibmCostOverviewWidgets.ts, src/store/breakdown/costOverview/ociCostOverview/ociCostOverview.test.ts, src/store/breakdown/costOverview/ociCostOverview/ociCostOverviewReducer.ts, src/store/breakdown/costOverview/ociCostOverview/ociCostOverviewWidgets.ts, src/store/breakdown/costOverview/ocpCostOverview/ocpCostOverviewWidgets.ts, src/store/breakdown/costOverview/rhelCostOverview/rhelCostOverview.test.ts, src/store/breakdown/costOverview/rhelCostOverview/rhelCostOverviewReducer.ts, src/store/breakdown/costOverview/rhelCostOverview/rhelCostOverviewWidgets.ts
https://issues.redhat.com/browse/COST-6144
=> Replace pie charts in cloud breakdowns

src/routes/details/components/costBreakdownChart/costBreakdownChart.tsx
Sankey support for negative markup values
https://issues.redhat.com/browse/COST-6144
=> Sankey support for negative markup values

src/routes/details/components/costBreakdownChart/costBreakdownChart.tsx
Changed to use max decimals possible
https://issues.redhat.com/browse/COST-6235
=> Want most decimals so value is still unique
