project-koku/koku-ui

openshift/koku-ui-template.yml
Current cluster resource limits & quotas can cause build and deploy failures due to default limits.
=> Add resource limit updates to override defaults for BuildConfig and DeployConfig.

src/api/reports.ts, src/components/trendChart/trendChart.tsx, src/utils/formatValue.ts
The api can at times return null for the units in total for reports. Add a null check and return value if that is the case.
=> Handle null units from the api

package.json
This PR should also trigger a snapshot on Netlify.com which allows me to log into the staging environment.
Update: The https://deploy-preview-89--project-koku.netlify.com URL below allows me to log into koku-staging. Will follow up with Doug to transfer ownership of the older Netlify site.
=> Added target for koku-staging

src/locales/de.json, src/locales/en.json, src/locales/es.json, src/pages/costDetails/costDetails.tsx
* Fix an issue where initial page could be empty because report wasn't fetched yet.
=> Add column headers for cost details list page.

src/components/commonChart/chartUtils.ts, src/components/pieChart/pieChart.styles.ts, src/components/pieChart/pieChart.tsx
`VictoryGroup` changes the style of the `colorScale`. It takes the two items in the array and applies them as the border and the background color.
In addition, setting the `strokeWidth` makes the style similar to what shown in the mockup design.
@chambridge can you look at this, please?
=> Fix pie chart look using a workaround

src/components/masthead/masthead.styles.ts, src/components/masthead/masthead.test.tsx, src/components/masthead/masthead.tsx, src/components/masthead/navToggleButton.test.tsx, src/components/masthead/navToggleButton.tsx, src/components/sidebar/sidebar.styles.ts
On small devices such as Android the `nav toggle button` is displayed but can't be seen because both `masthead` and `bars icon` are black.
To fix this, the `bars icon` color is set to white by changing the color to `global_Color_light_100` in `navToggle`.
In addition, show the times icon when sidebar open.
=>  Set navigation toggle button according to the mockup

src/app.tsx
Fetch providers within the app's componentDidUpdate method instead of within componentDidMount. 
Fixes: https://github.com/project-koku/koku-ui/issues/100
=> Fetch providers within the app's componentDidUpdate

src/testIds.ts
Simple change for the data-test-id for providers[submit_btn] from 'submit-byn'  to 'submit-btn'
=> Fix typo in the data-test-id for Add Account modal confirm (submit button)

src/pages/login/login.test.tsx, src/pages/login/login.tsx
Apparently the API returns the error data as an array.
For example, if `username` is missing the following error is returned:
```js
{
...
"data": {
...
"username": ["This field may not be blank"]
}
}
```
This array is passed to the `title` props in `Alert` but it is supposed to be a string which ends up with printing a warning message in the console.
This commit fixes this by converting the array to string by using the `String` method.
=> fix(Login): Alert title is not string

src/components/textInput/textInput.tsx, src/pages/costDetails/costDetails.tsx, src/pages/costDetails/detailsToolbar.tsx
Added filtering to the toolbar.
Current setup is:
1. You select what you want to filter (e.g. Services)
2. Then type  your filter and hit enter (e.g. AmazonEC2)
To clear the filter, delete the text and press Enter.
=> Wire up cost details filter within toolbar.

src/api/reports.ts, src/utils/getComputedReportItems.ts
Show Account alias instead of account numbers as the label if available.
Dashboard:
Cost Details:
=> If an AWS account has an alias it should be shown in the UI.

src/pages/dashboard/dashboardWidget.test.tsx, src/pages/dashboard/dashboardWidget.tsx
Added two more tests:
- getIdKeyForTabs
- updateTab
I had to move `getIdKeyFromTabs` to be external function as it can be used both in `getTabTitle` and `getDetailsLinkTitle`. In addition, it was easy to test it that way.
=> test(dashboardWidget): add two more tests

src/api/query.ts, src/pages/dashboard/dashboardWidget.test.tsx, src/pages/dashboard/dashboardWidget.tsx, src/store/dashboard/__snapshots__/dashboard.test.ts.snap, src/store/dashboard/dashboard.test.ts, src/store/dashboard/dashboardActions.ts, src/store/dashboard/dashboardCommon.ts, src/store/dashboard/dashboardSelectors.ts
The data that is rendered in tabs is taken from the current computed results which its resolution is set to 'daily' while it should be 'monthly'.
In this commit, another API call is done to fetch this data with the right parameters and render tabs according to it.
closes #114
=> fix(dashboardWidget): display daily data in tabs

src/api/query.ts, src/pages/costDetails/costDetails.tsx, src/pages/costDetails/detailsToolbar.tsx, src/pages/dashboard/dashboardWidget.tsx
The sort dropdown and direction indicator are now functional. The query params update properly and state can be restored upon a page refresh, allowing bookmarking. Although, the sort has been intentionally disabled for now.
The "Cost Details" and "All Services" links have been fixed to also include the query params as expected. Previously, clicking on the "Cost Details" link (a second time) would lose all query params.
Note that order_by has been temporarily omitted from the request. This is due to the issue below when order_by is included, generating bad requests. When this issue has been resolved, we can easily enable the sort in another PR.
https://github.com/project-koku/koku/issues/375
=> Add sort functionality

Dockerfile, package.json, yarn.lock
This pf-react update allows webpack 4 to run in production mode. Tested with `container:test` and `webpack-dev-server --env production`
Note that there may still be issues that pf-react must address. However, this update appears to be working with the PF3 components currently in use on the cost details page.
See: https://github.com/patternfly/patternfly-react/pull/564
=> Update pf-react to support webpack production

package.json, src/pages/costDetails/costDetails.tsx, src/pages/costDetails/detailItem.tsx, src/pages/costDetails/detailsToolbar.tsx, src/pages/dashboard/dashboardWidget.tsx, src/utils/getComputedReportItems.ts
This change enables sorting by cost and name on the cost details page.
Sort Cost Descending
Sort Cost Ascending
=> Enable sorting for cost details page

package.json
Added an `insights:proxy` target for convenience. This allows an IDE to run the Inisghts proxy as well as `start:dev`.
=> Add insights:proxy target for convenience

package.json, src/index.html, webpack.config.js, yarn.lock
Essentially updates @@insights in the `<esi:include src=` to be either `insights` or `insightsbeta` so the include here aligns with the target deployment dependent on branch.
=> Update chroming based on deployment so it aligns with publicPath

package.json, src/api/export.ts, src/api/reports.ts, src/locales/de.json, src/locales/en.json, src/locales/es.json, src/pages/costDetails/costDetails.tsx, src/pages/costDetails/detailItem.tsx, src/pages/costDetails/detailsToolbar.styles.ts, src/pages/costDetails/detailsToolbar.tsx, src/pages/costDetails/exportModal.styles.ts, src/pages/costDetails/exportModal.tsx, src/pages/providersModal/providersModal.tsx, src/store/export/__snapshots__/export.test.ts.snap, src/store/export/export.test.ts, src/store/export/exportActions.ts, src/store/export/exportReducer.ts, src/store/export/exportSelectors.ts, src/store/export/index.ts, src/store/rootReducer.ts, src/store/ui/__snapshots__/ui.test.ts.snap, src/store/ui/ui.test.ts, src/store/ui/uiActions.ts, src/store/ui/uiReducer.ts, src/store/ui/uiSelectors.ts, src/testIds.ts, yarn.lock
Added the export modal to download csv files. 
After the request returns, the browser is triggered to save data to a file as if it was downloaded, and the modal closes.
This also enables the checkboxes and select all features. If all rows are selected, the select all checkbox is also selected. In addition, the export button is disabled when there are no selections.
Based on the mockup below (click on Export)
https://redhat.invisionapp.com/share/HEO4ISHAT8Z#/screens/323822462
Screenshot
=> Export modal

src/api/query.ts, src/api/reports.ts, src/locales/de.json, src/locales/en.json, src/locales/es.json, src/pages/costDetails/costDetails.styles.ts, src/pages/costDetails/costDetails.tsx, src/pages/costDetails/detailItem.tsx, src/utils/getComputedReportItems.ts
This adds the month over month change to the cost details page. The following scenarios are handled per the mocks.
- Cost increase shows red text & arrow with "increase since <date>" text
- Cost decrease shows green text & arrow with "decrease since <date>" text
- When delta value is 0, the "no change since <date>" text is shown
- When the date is 31, the "since last month" text is shown
Note that start:dev / Insights proxy currently returns 0 for all delta_percent values; although, I believe this is just a matter of populating the data manually (e.g., koku-dev has values for delta_percent)? I had to hard code the percentages to get the screenshots.
Fixes https://github.com/project-koku/koku-ui/issues/168
Cost decrease:
Cost Increase:
=> Cost details: Add month over month change

src/pages/awsDetails/detailsToolbar.tsx, src/pages/ocpDetails/detailsToolbar.tsx
Now that group_by appears to support account aliases, I'm removing the workaround to cache the initial report in order to lookup account aliases/IDs after multiple filters are applied.
=> Remove account alias workaround to apply filters

src/locales/de.json, src/locales/en.json, src/locales/es.json
It seems like the text is not rendered in the group by selector because it doesn't have it in the locales files.
fixes #210
=> fix(details): show group-by label selector text

src/pages/ocpDetails/detailsToolbar.tsx
Simple filter fix for OCP details page, which mimics the fix applied to the AWS details page.
Fixes https://github.com/project-koku/koku-ui/issues/222
=> Filter fix for OCP details page

src/pages/awsDashboard/awsDashboardWidget.tsx, src/pages/ocpDashboard/ocpDashboardWidget.tsx
Removes the "Total Cost" subscript next to dollar value. This is shown on each dashboard card.
Fixes https://github.com/project-koku/koku-ui/issues/246
AWS dashboard
OCP dashboard
=> Remove subscript next to dollar value

src/store/awsDashboard/awsDashboardWidgets.ts, src/store/ocpDashboard/ocpDashboardWidgets.ts
This ensures the cost shown on the dashboard matches what is shown on the details page.
Fixes https://github.com/project-koku/koku-ui/issues/216
AWS dashboard
OCP dashboard
=> Match dashboard cost with cost shown on details page

src/locales/de.json, src/locales/en.json, src/locales/es.json
Added space to column table headers for AWS & OCP details page
Fixes https://github.com/project-koku/koku-ui/issues/236
AWS details page
OCP details page
=> Added space to column table headers

src/components/tabs/tabItem.styles.ts
This closes issue #239 .
Currently, tab font size is 14px and progress bar text is 16px. This PR changes the tab font size to 16px to match what is the pf designs.
=> Increase font size for tabs

src/components/reportSummary/reportSummary.styles.ts, src/components/reportSummary/reportSummary.tsx
This closes issue #242 
Padding removed from card header and body so that hero value is moved closer to title.
=> Remove padding to move hero value closer to title

src/pages/overview/overview.styles.ts, src/pages/overview/overview.tsx, webpack.config.js
fixes https://github.com/project-koku/koku-ui/issues/274
@dlabrecq we're pulling in fairly large utility class stylesheets to make this change. While I think it's beneficial to use the utilities and write as little custom CSS as possible, do you think it's worth it in this case to replace the custom CSS here?
=> chore(overview): replace custom CSS with utility classes

src/api/providers.ts, src/api/reports.ts
Invoking the Insights user promise before making axios calls. This appears to resolve the issue where the browser must be refreshed upon first login.
Fixes https://github.com/project-koku/koku-ui/issues/250
See https://docs.google.com/document/d/1xjITNYbp1aw9Xu3lYLQppKQl-Rtj6_BaThwy1Zkazm4/edit#
=> Invoke Insights user promise

src/pages/awsDetails/detailsToolbar.tsx, src/pages/ocpDetails/detailsToolbar.tsx
Replaces an incorrect, PF3 `download` icon with PF4 `FileExportIcon`.
Fixes https://github.com/project-koku/koku-ui/issues/284
=> Fix wrong export icon

src/api/query.ts, src/pages/awsDetails/awsDetails.tsx, src/pages/ocpDetails/ocpDetails.tsx
I _believe_ this will accommodate the change for delta from being a Boolean to a string.
* The accepted delta value for AWS is currently `total`. 
* The accepted delta values for OCP are currently `charge`, `usage`, and `request` for memory and cpu inventory APIs, and `charge` for the charge API. The default value is `charge`.
=> Update delta param to string with defaults

src/pages/awsDetails/detailsChart.tsx, src/pages/ocpDetails/detailsChart.tsx
This change shows the `group by cost` dropdown for the list detail item (i.e., expandable list row) when no data is available. It's possible that there may be data for `region`, but not `service`. If there is no data for either, then the chart is not shown.
Related to https://github.com/project-koku/koku-ui/issues/326
=> Always show group by cost dropdown in detail item

src/locales/de.json, src/locales/en.json, src/locales/es.json, src/pages/ocpDetails/detailsToolbar.tsx, src/pages/ocpDetails/ocpDetails.tsx
Fixed a TypeError issue in OCP details page.
Note that the OCP page still needs some refactoring to use the OCP APIs properly. For example, the toolbar is missing the filter and sort. That will be updated via another PR. This just gets the page working after the work to refactor the OCP dashboard.
Fixes https://github.com/project-koku/koku-ui/issues/337
Sreenshot
=> Fix TypeError in OCP details page

src/api/api.ts
fixes #250 
In PR #151 axios timeout setting was set to 4 seconds to make sure the integration with 3scales works properly.
However, this setting is no longer relevant because:
1. 3scale timeouts requests if it takes too long to respond
2. requests might fail because of that even though it is reasonable to wait for a response
-------
To solve this I used the default settings in `axios` which is no timeouts as you can see [here](https://github.com/axios/axios/blob/release/1.0.0/lib/defaults.js#L83-L87).
I ran some tests locally on my machine and it seems to work (I see that on the first time it takes 7-9 seconds to get the providers and in the second and the third refreshes it takes it much less time)
=> fix(Providers): Do not timeout HTTP requests

src/locales/de.json, src/locales/en.json, src/locales/es.json, src/pages/ocpDetails/detailsItem.tsx, src/pages/ocpDetails/ocpDetails.tsx
This PR changes the "cost" label to "charge" for OCP details page
=> OCP details page should show "charge" label instead of "cost"

src/pages/awsDetails/detailsItem.tsx, src/pages/ocpDetails/detailsItem.tsx
The API is changing to return a null for the deltaPercent value. The UI should be able to handle a null value and not display the up/down arrow in that scenario. That is, show no change.
Fixes https://github.com/project-koku/koku-ui/issues/357
=> Show no change when deltaPercent is null

src/components/trendChart/trendChart.styles.ts, src/components/trendChart/trendChart.tsx, src/components/usageChart/usageChart.styles.ts, src/components/usageChart/usageChart.tsx
Modified the order of the chart lengends shown on the dashboards. That is, the previous month is now shown before the current month.
AWS
OCP
Fixes https://github.com/project-koku/koku-ui/issues/351
=> Legend should be reordered to show previous month first

src/components/commonChart/chartUtils.test.ts, src/components/commonChart/chartUtils.ts, src/components/trendChart/trendChart.test.tsx, src/components/trendChart/trendChart.tsx, src/components/usageChart/usageChart.test.tsx, src/components/usageChart/usageChart.tsx, src/locales/de.json, src/locales/en.json, src/locales/es.json, src/pages/awsDashboard/awsDashboardWidget.tsx, src/pages/ocpDashboard/ocpDashboardWidget.tsx, src/utils/formatValue.test.ts, src/utils/formatValue.ts
This should fix the current error by using a different format for the report summary trend and the report summary details.
=> fix(TrendChart): move tooltip label format logic to chart utils

package.json, src/components/bulletChart/bulletChart.tsx, src/locales/de.json, src/locales/en.json, src/locales/es.json, src/pages/ocpDetails/detailsChart.tsx, yarn.lock
Now that the PF3 bullet chart no longer assumes given values are percentages, I've removed the custom code to override the axis tics and legend. See: patternfly/patternfly-react#1031
This also adds the correct units (Core-Hours Vs GB-Hours) for the CPU and memory charts.
Fixes https://github.com/project-koku/koku-ui/issues/362
=> Remove custom bullet chart legend & axis tics

src/components/commonChart/chartUtils.ts, src/components/trendChart/trendChart.tsx, src/pages/ocpDashboard/ocpDashboardWidget.tsx
Modified the legend to show the date range we're trying to cover for the previous month. For example, the label for the previous month should be Nov 1-30.
Fixes https://github.com/project-koku/koku-ui/issues/360
=> Dashboard legend to indicate full date range for previous month

src/components/trendChart/trendChart.tsx, src/components/usageChart/usageChart.tsx
A small nitpick fix.
When the chart is mounted there is a chance that `containerRef.current` wasn't set yet.
Thus, getting the following error:
```
TypeError: this.containerRef.current is null
```
To avoid this, added a check that `containerRef.current` is  not `null` and only then update the state.
In addition, removed the `setTimeout` function as `containerRef` updates before componentDidMount and so `componentDidMount` will be called twice - once when `containerRef` is null and when it is set to the node in the DOM. Read more [here](https://reactjs.org/docs/refs-and-the-dom.html#adding-a-ref-to-a-dom-element)
=> fix(Charts): fix the null error in usage/trend charts

src/components/pieChart/pieChart.tsx
Removes a Victory color pallet that is not shared by the legend.
Fixes https://github.com/project-koku/koku-ui/issues/372
=> Pie chart colors do not match legend

src/pages/awsDetails/detailsItem.tsx, src/pages/ocpDetails/detailsItem.tsx
This fixes an issue with a bad mod calculation for month over month value. This only happens when subtracting one from January's position in the localization index. This solution accounts for negative numbers.
Fixes https://github.com/project-koku/koku-ui/issues/379
=> Bad month over month value

src/components/measureChart/measureChart.styles.ts, src/components/measureChart/measureChart.tsx, src/locales/de.json, src/locales/en.json, src/locales/es.json, src/pages/ocpDetails/detailsChart.tsx, src/pages/ocpDetails/detailsItem.tsx, src/pages/ocpDetails/detailsSummary.tsx, src/pages/ocpDetails/detailsTag.tsx, src/pages/ocpDetails/ocpDetails.styles.ts
Updated the OCP detail (expanded) list items to reflect the latest high fidelity mock layout. For example, "View Historical Data" should be a button at the top right, extra padding around the titles, etc.
Fixes https://github.com/project-koku/koku-ui/issues/384
=> Update the OCP details to reflect the latest high fedelity mock

src/api/ocpQuery.ts, src/api/ocpReports.ts, src/locales/de.json, src/locales/en.json, src/locales/es.json, src/pages/ocpDetails/detailsCluster.tsx, src/pages/ocpDetails/detailsItem.tsx, src/pages/ocpDetails/detailsTag.tsx, src/pages/ocpDetails/detailsToolbar.tsx, src/pages/ocpDetails/ocpDetails.styles.ts, src/pages/ocpDetails/ocpDetails.tsx, src/testIds.ts, src/utils/getComputedOcpReportItems.ts
Adds tags to OCP details page for groupBy project. This also allows the user to filter by clicking on a tag.
Note that there are 20 tags for the "metering-koku" project. 
Fixes https://github.com/project-koku/koku-ui/issues/392
=> Add project tags to OCP details page

src/components/trendChart/trendChart.styles.ts, src/components/trendChart/trendChart.test.tsx, src/components/trendChart/trendChart.tsx, src/components/usageChart/usageChart.styles.ts, src/components/usageChart/usageChart.test.tsx, src/components/usageChart/usageChart.tsx, src/pages/overview/overview.tsx
Also adds axis lines to overview charts in order to look better with a light theme
Fixes https://github.com/project-koku/koku-ui/issues/385
=> Use light theme per high fidelity mock

src/pages/ocpDetails/ocpDetails.styles.ts
Ensured the sort icon is visible in the AWS/OCP detail pages by removing the white color property. It's possible that this was set to white due to the dark theme?
Fixes https://github.com/project-koku/koku-ui/issues/409
=> Sort icon is not visible

src/pages/ocpDetails/ocpDetails.tsx
Changed sort to use `cluster` instead of `cluster_alias` in OCP details.
Fixes https://github.com/project-koku/koku-ui/issues/411
=> Fix cluster sort in OCP details

package.json, yarn.lock
Update PF4 packages to fix the broken dropdown onClick event in the AWS/OCP detail pages.
Fixes https://github.com/project-koku/koku-ui/issues/407
=> Fix dropdown onClick event

src/locales/de.json, src/locales/en.json, src/locales/es.json, src/pages/awsDetails/awsDetails.tsx, src/pages/awsDetails/groupBy.tsx, src/pages/ocpDetails/groupBy.tsx, src/pages/ocpDetails/ocpDetails.tsx
Added functionality to group by tag keys in OCP details page. Moved "group by" dropdown to its own component in order to add tag key support.
Note: https://github.com/project-koku/koku-ui/pull/430 and https://github.com/project-koku/koku-ui/pull/425 should be merged first.
Fixes https://github.com/project-koku/koku-ui/issues/400
Mocks:
https://redhat.invisionapp.com/share/HEO4ISHAT8Z#/screens/332238366
Screenshot:
=> OCP Details: Group by tag keys

src/components/bulletChart/bulletChart.tsx, src/components/commonChart/chartUtils.ts, src/components/historicalTrendChart/historicalTrendChart.tsx, src/components/historicalUsageChart/__snapshots__/historicalUsageChart.test.tsx.snap, src/components/historicalUsageChart/historicalUsageChart.styles.ts, src/components/historicalUsageChart/historicalUsageChart.tsx, src/components/pieChart/pieChart.tsx, src/components/trendChart/trendChart.tsx, src/components/usageChart/__snapshots__/usageChart.test.tsx.snap, src/components/usageChart/usageChart.styles.ts, src/components/usageChart/usageChart.tsx, src/typings/victory.d.ts
Added chart legend onClick functionality to hide/show individual pieces of data.
This adds a legend toggle to every chart in the Koku UI. For example, the trend and usage charts on the overview page. The history charts shown in the OCP details. And the pie chart for AWS details.
Also fixed some mismatched chart colors.
Fixes https://github.com/project-koku/koku-ui/issues/391
Screenshot of historical charts with several pieces of data turned off, making the data more readable.
=> Add chart legend click to hide/show data

src/components/historicalTrendChart/historicalTrendChart.styles.ts, src/components/historicalTrendChart/historicalTrendChart.tsx, src/components/historicalUsageChart/historicalUsageChart.styles.ts, src/components/historicalUsageChart/historicalUsageChart.tsx, src/components/trendChart/trendChart.styles.ts, src/components/trendChart/trendChart.tsx, src/components/usageChart/usageChart.styles.ts, src/components/usageChart/usageChart.tsx, src/pages/ocpDetails/historicalChart.tsx, src/pages/ocpDetails/historicalModal.styles.ts
Added a couple tic labels to the chart x-axis. This helps indicate the day of month at a glance (e.g., 1, 15, 31, etc.).
Fixes https://github.com/project-koku/koku-ui/issues/451
Historical charts:
OCP charts:
AWS charts:
=> Added tic labels to charts

src/api/awsQuery.ts, src/api/awsReports.ts, src/pages/awsDetails/awsDetails.tsx, src/pages/awsDetails/groupBy.tsx, src/utils/getComputedAwsReportItems.ts
Added group by tags functionality to AWS details page.
Note that the `5dc_key` and `c25_key` tags keys are both on the `hccm-alias` account.
Fixes https://github.com/project-koku/koku-ui/issues/445
=> AWS: Group By Account Tags

src/api/awsQuery.ts, src/api/awsReports.ts, src/locales/de.json, src/locales/en.json, src/locales/es.json, src/pages/awsDetails/awsDetails.styles.ts, src/pages/awsDetails/awsDetails.tsx, src/pages/awsDetails/detailsChart.tsx, src/pages/awsDetails/detailsItem.tsx, src/pages/awsDetails/detailsTag.styles.ts, src/pages/awsDetails/detailsTag.tsx, src/pages/awsDetails/groupBy.tsx, src/pages/ocpDetails/detailsCluster.tsx, src/pages/ocpDetails/detailsItem.tsx, src/pages/ocpDetails/detailsTag.styles.ts, src/pages/ocpDetails/ocpDetails.styles.ts, src/testIds.ts, src/utils/getComputedAwsReportItems.ts
Added tags to AWS details page. Also modified the OCP details page to mimic the tag functionality for AWS. The details pages now show a few tags initially, with additional/all tags shown in a popover (per @nlcwong).
See mock: https://redhat.invisionapp.com/share/HEO4ISHAT8Z#/screens/343778744
Notes:
- https://github.com/project-koku/koku-ui/pull/455 should be merged first.
- Depends on https://github.com/project-koku/koku/issues/605 in order for AWS to show tags per account.
Fixes https://github.com/project-koku/koku-ui/issues/444
Fixes https://github.com/project-koku/koku-ui/issues/416
=> AWS tags details

src/components/bulletChart/bulletChart.styles.ts, src/components/bulletChart/bulletChart.tsx, src/pages/ocpDetails/detailsChart.tsx
Update bullet chart per high fidelity mock.
Mock: https://redhat.invisionapp.com/share/ENPJQTBXTAC#/screens/336165167
Fixes https://github.com/project-koku/koku-ui/issues/464
Example (new):
Old PF3 style:
=> Update bullet chart per high fidelity mock

src/pages/ocpDetails/detailsTable.tsx
Modified table to lazily load expandable rows. There is a significant performance improvement loading rows only after the row toggle has been clicked. 
Fixes https://github.com/project-koku/koku-ui/issues/469
=> Modified table to lazily load expandable rows

src/pages/awsDetails/detailsTable.tsx, src/pages/awsDetails/detailsTableItem.tsx, src/pages/ocpDetails/detailsTable.tsx, src/pages/ocpDetails/detailsTableItem.tsx
Fixed sorting and table updating during navigation. 
While switching between back and forth between `Cloud Cost` and `OpenShift Charge`, the table wouldn't initialize properly.
=> Table fixes

src/pages/awsDetails/detailsTable.tsx, src/pages/ocpDetails/detailsTable.tsx
It appears that the PF4 table generates a `Cannot read property 'title' of null` error if any cells are null or undefined. This fixes the issue when the region label is null.
See PF4 table issue for more details:
https://github.com/patternfly/patternfly-react/issues/1371
=> Table fix for null region label

src/components/awsReportSummary/__snapshots__/awsReportSummaryDetails.test.tsx.snap, src/components/awsReportSummary/awsReportSummaryDetails.tsx, src/components/ocpReportSummary/ocpReportSummaryDetails.tsx
This ensures a dollar sign is used when there is no total. Also sync'ed default value with OCP card.
Fixes https://github.com/project-koku/koku-ui/issues/448
=> AWS total cost card missing dollar sign

package.json, src/locales/de.json, src/locales/en.json, src/locales/es.json, src/pages/awsDetails/detailsChart.styles.ts, src/pages/awsDetails/detailsChart.tsx, src/pages/awsDetails/detailsChartModal.styles.ts, src/pages/awsDetails/detailsChartModal.tsx, src/pages/awsDetails/detailsTable.tsx, src/pages/awsDetails/detailsTableItem.styles.ts, src/pages/awsDetails/detailsTableItem.tsx, src/pages/awsDetails/detailsTag.tsx, src/pages/ocpDetails/detailsTable.tsx, src/pages/ocpDetails/detailsTableItem.tsx, src/pages/ocpDetails/detailsTag.tsx, src/testIds.ts, yarn.lock
This replaces the pie chart with PF4 progress bars in the AWS details page. There is no mock, but worked with Natalie to create progress bars similar to the overview page. The difference here is that we only display the top 3 and use a scrollable modal to show more.
=> AWS details progress bars

src/components/historicalUsageChart/__snapshots__/historicalUsageChart.test.tsx.snap, src/components/usageChart/__snapshots__/usageChart.test.tsx.snap, src/utils/getComputedOcpReportItems.ts
Fixes an issue where the OCP charge card is missing its dollar sign -- units are not being mapped correctly.
Fixes https://github.com/project-koku/koku-ui/issues/440
=> OCP charge card missing dollar sign

src/app.tsx, yarn.lock
In order to push the latest UI to production, we need the ability to create an AWS provider. This modifies the "Add Source" button to show old provider modal for now.
When the AWS provider functionality is available, we can then open the new modal.
Fixes https://github.com/project-koku/koku-ui/issues/485
=> Change "Add Source" button to show old provider modal

src/locales/de.json, src/locales/en.json, src/locales/es.json, src/pages/awsDetails/detailsChartModal.tsx, src/pages/awsDetails/detailsTableItem.tsx, src/pages/awsDetails/detailsTag.styles.ts, src/pages/awsDetails/detailsTag.tsx, src/pages/awsDetails/detailsTagModal.styles.ts, src/pages/awsDetails/detailsTagModal.tsx, src/pages/ocpDetails/detailsTableItem.tsx, src/pages/ocpDetails/detailsTag.styles.ts, src/pages/ocpDetails/detailsTag.tsx, src/pages/ocpDetails/detailsTagModal.styles.ts, src/pages/ocpDetails/detailsTagModal.tsx
Replaces the 'more tags' popover with a scrollable modal. This will ensure the popup doesn't appear off the page with too many tags, as shown in the issue below.
Fixes https://github.com/project-koku/koku-ui/issues/481
=> Replace 'more tags' popover with modal

src/pages/awsDetails/detailsChart.tsx
Display the "Show More" link for the "1 Other" edge case. This will ensure the user can see "Other" items in the modal.
Fixes https://github.com/project-koku/koku-ui/issues/489
=> Display the "Show More" link

src/components/bulletChart/bulletChart.styles.ts, src/components/bulletChart/bulletChart.tsx, src/pages/ocpDetails/detailsChart.tsx
This ensures legend colors match the colors used in the bullet chart.
Fixes https://github.com/project-koku/koku-ui/issues/494
=> Match bullet chart colors with legend

src/pages/overview/overview.tsx, src/pages/providersModal/providersModal.tsx
closes #492 
Since onboardingModal and providersModal are using different parameters in Redux state to determine whether the modal is shown or not, there was a conflict.
In this patch, I fully reverted that part.
//cc @lcouzens
=> fix(providersModal): close the provider modal on success

src/api/providers.test.ts, src/api/providersQuery.ts, src/app.tsx, src/pages/overview/overview.tsx, src/store/providers/providersCommon.ts
This enables the UI to fetch AWS and OCP provider counts separately.
Note that the providers API now supports a type query parameter -- See: https://github.com/project-koku/koku/issues/658
Fixes https://github.com/project-koku/koku-ui/issues/453
Fixes https://github.com/project-koku/koku-ui/issues/437
=> Enable providers request to fetch AWS and OCP counts separately

src/components/awsReportSummary/awsReportSummaryItems.tsx, src/components/ocpReportSummary/ocpReportSummaryItems.tsx
The label returned in the report doesn't contain "Other" only, but something more like "8 Others". The underlying issue was that we were looking for an exact match. 
This change will ensure "Others" appears last in the overview's top 5 as originally intended.
Fixes https://github.com/project-koku/koku-ui/issues/355
=> Ensure "others" appears last in top 5

src/pages/providersModal/providersModal.test.tsx, src/pages/providersModal/providersModal.tsx
fixes #422 
It will be easier for me later to take that validation and use it in AWS onboarding process.
The flow is: if the user enters less than "arn:aws:". For example, "arn:a" then a server side error message will appear. Although I can set that the minimal length is 10 and avoid getting this error from server side and be more "user-friendly".
Whatever you like.
//cc @lcouzens
=> fix(providersModal): show error regarding resource name after arn:aws

src/locales/de.json, src/locales/en.json, src/locales/es.json, src/pages/awsDetails/detailsTable.styles.ts, src/pages/awsDetails/detailsTable.tsx, src/pages/awsDetails/groupBy.tsx, src/pages/ocpDetails/detailsTable.styles.ts, src/pages/ocpDetails/detailsTable.tsx, src/pages/ocpDetails/groupBy.tsx
Adds an empty state to the AWS/OCP details table.
Fixes https://github.com/project-koku/koku-ui/issues/389
Fixes https://github.com/project-koku/koku-ui/issues/388
AWS:
OCP:
Known PF4 issues:
- PF4 Table: Disable header controls when no rows are available https://github.com/patternfly/patternfly-react/issues/1431
- PF4 Empty State Icon: Allow size to be set https://github.com/patternfly/patternfly-react/issues/1434
- PF4 Table: Provide empty state support https://github.com/patternfly/patternfly-react/issues/1433
=> Add empty state to AWS/OCP details table

src/components/trendChart/trendChart.styles.ts, src/pages/awsDashboard/awsDashboardWidget.styles.ts, src/pages/awsDashboard/awsDashboardWidget.test.tsx, src/pages/awsDashboard/awsDashboardWidget.tsx, src/pages/ocpDashboard/ocpDashboardWidget.styles.ts, src/pages/ocpDashboard/ocpDashboardWidget.test.tsx, src/pages/ocpDashboard/ocpDashboardWidget.tsx, src/pages/overview/overview.tsx
This replaces our custom tabs with the PF4 tabs component.
The next step will be to move the overview tabs into the header, per Kyle's high fidelity mock. However, the PF4 tabs component is currently being refactored to support this requirement. See https://github.com/patternfly/patternfly-react/issues/1364
Fixes https://github.com/project-koku/koku-ui/issues/205
Card Tabs Before:
Card Tabs After:
=> Replace custom tabs with PF4 tabs

src/pages/awsDashboard/awsDashboardWidget.tsx, src/pages/ocpDashboard/ocpDashboardWidget.tsx, src/pages/overview/overview.tsx
This modifies the tabs to use lazy loading. Currently, both AWS and OCP tabs and sub-tabs are loaded when the overview page is first rendered.
This ensures tabs are not loaded until the user selects a new tab. Thus, child components such as charts and progress bars are updated properly when switching between tabs.
Fixes https://github.com/project-koku/koku-ui/issues/528
=> Modify tabs to use lazy loading

package.json, src/components/charts/historicalUsageChart/historicalUsageChart.tsx, src/components/charts/usageChart/usageChart.tsx, yarn.lock
Remove custom VictoryPoint in favor of the ChartPoint component I created for PF4. This ChartPoint (responsible for dashed lines in the legend) component is now used in ChartLegend by default.
Fixes https://github.com/project-koku/koku-ui/issues/531
=> Remove custom VictoryPoint

src/pages/awsDetails/awsDetails.tsx, src/pages/ocpDetails/ocpDetails.tsx, src/pages/overview/overview.tsx
This change ensures empty states are shown as expected when a provider has just been added -- just needed to tweak the logic a bit.
The Overview and AWS/OCP detail pages display empty states as expected.
The AWS tab is not shown in the overview -- for OCP only providers.
The add provider screen is shown for the AWS details page -- for OCP only providers.
Fixes https://github.com/project-koku/koku-ui/issues/533
=> Loading never times out

src/components/charts/historicalTrendChart/historicalTrendChart.styles.ts, src/components/charts/historicalTrendChart/historicalTrendChart.tsx, src/components/charts/historicalUsageChart/historicalUsageChart.styles.ts, src/components/charts/historicalUsageChart/historicalUsageChart.tsx, src/components/charts/trendChart/trendChart.styles.ts, src/components/charts/usageChart/usageChart.styles.ts, src/pages/awsDetails/historicalChart.styles.ts, src/pages/awsDetails/historicalChart.tsx, src/pages/ocpDetails/historicalChart.styles.ts, src/pages/ocpDetails/historicalChart.tsx
AWS historical charts appear smaller on some screens.
Fixes https://github.com/project-koku/koku-ui/issues/537
=> AWS historical chart widths

src/pages/onboardingModal/final/loader.tsx
fixes #542 
//cc @lcouzens 
@chambridge How does the response look when there is a failure on the server side? is it always similar to this?:
```json
{
"errors": [
{ 
"details": "....",
},
{ 
"details": "....",
}
]
}
```
Thanks.
=> fix(onboarding): check for failure message in errors

src/pages/awsDetails/historicalModal.styles.ts
Increasing the modal width slightly for AWS historical charts. This should keep the legend from wrapping onto the next line.
Fixes https://github.com/project-koku/koku-ui/issues/559
=> Increase modal width for AWS historical charts

src/pages/awsDetails/awsDetails.tsx
Recent API change requires 'order_by' to use 'cost' instead of 'total'. 
Fixes https://github.com/project-koku/koku-ui/issues/560
=> API change for 'order_by'

src/pages/awsDashboard/awsDashboardWidget.test.tsx, src/pages/ocpDashboard/ocpDashboardWidget.test.tsx
This test had previously simulated a change event in our custom tabs component. However, the test no longer functions properly after replacing our custom tabs with PF4 tabs. Both @boaz0 and I attempted to refactor it, but we agreed the test should be removed for technical reasons.
For more details, please see: https://github.com/project-koku/koku-ui/issues/551
=> Invalid tabs test

src/pages/providersModal/providersModal.tsx
Remove PF3 from providers modal. 
Not quite ready to remove the component, but at least want to get rid of PF3. This leaves just the PF3 toolbar to replace in the details pages.
=> Remove PF3 from providers modal

src/store/awsReports/awsReportsActions.ts, src/store/ocpOnAwsReports/ocpOnAwsReportsActions.ts, src/store/ocpReports/ocpReportsActions.ts, src/utils/dropCurrentMonthData.ts
Minimal impact UI update to have the new API which will return 2 months of data to "act" like old API.
Another PR can make performance improvements to alter API calls to use one API call and process the previous and current data from the single 2 months of data call.
Real impact here is on the historical charts previous/current data calls.
Associated with: https://github.com/project-koku/koku/pull/679
=> UI change for time scope API updates.

src/pages/awsDashboard/awsDashboardWidget.tsx
Due to a recent API change, the AWS instance & storage cards incorrectly used 'cost' instead of 'usage' value to calculate percentages.
Fixes https://github.com/project-koku/koku-ui/issues/584
=> AWS instance & storage cards calculate wrong percentages

src/locales/de.json, src/locales/en.json, src/locales/es.json, src/pages/awsDetails/awsDetails.styles.ts, src/pages/awsDetails/awsDetails.tsx, src/pages/awsDetails/detailsHeader.styles.ts, src/pages/awsDetails/detailsHeader.tsx, src/pages/awsDetails/detailsTable.styles.ts, src/pages/awsDetails/detailsTable.tsx, src/pages/awsDetails/detailsTableItem.tsx, src/pages/awsDetails/exportModal.tsx, src/pages/awsDetails/groupBy.tsx, src/pages/ocpDetails/detailsHeader.styles.ts, src/pages/ocpDetails/detailsHeader.tsx, src/pages/ocpDetails/detailsTable.styles.ts, src/pages/ocpDetails/detailsTable.tsx, src/pages/ocpDetails/exportModal.tsx, src/pages/ocpDetails/groupBy.tsx, src/pages/ocpDetails/ocpDetails.styles.ts, src/pages/ocpDetails/ocpDetails.tsx, src/utils/getComputedAwsReportItems.ts, src/utils/getComputedOcpOnAwsReportItems.ts, src/utils/getComputedOcpReportItems.ts
Refactored the group by tags functionality for the AWS/OCP detail pages. Ensured the group by feature works with sorting, filtering, .csv export, etc.
Notes:
- Sorting via tag name is not supported: https://github.com/project-koku/koku/issues/714
- The expanding rows are disabled intentionally
Fixes https://github.com/project-koku/koku-ui/issues/582
=> Refactor group by tags

src/api/ocpOnAwsReports.test.ts, src/api/ocpOnAwsReports.ts, src/api/ocpReports.test.ts, src/api/ocpReports.ts
Replaces `reports/openshift/charges` API with `reports/openshift/costs`
Fixes https://github.com/project-koku/koku-ui/issues/591
=> Replace OCP charges API with costs

src/app.tsx, src/pages/awsDetails/awsDetails.tsx, src/pages/ocpDetails/ocpDetails.tsx
Removed the `shouldComponentUpdate` function since it did not explicitly check if provider status was updated.
Fixes https://github.com/project-koku/koku-ui/issues/587
=> Loading state does not always update properly

src/pages/awsDetails/awsDetails.tsx, src/pages/awsDetails/detailsChart.tsx, src/pages/awsDetails/exportModal.tsx, src/pages/ocpDetails/detailsChart.tsx, src/pages/ocpDetails/exportModal.tsx, src/pages/ocpDetails/ocpDetails.tsx
This enables selection by label for the export modal's radio button. 
The underlying fix is to use unique IDs for each radio button; however, I also wanted to refactor the code a bit to ensure the constructor binds the `handleResolutionChange` function properly.
Fixes https://github.com/project-koku/koku-ui/issues/586
=> Fix radio button in export modal

src/components/charts/historicalTrendChart/historicalTrendChart.tsx, src/components/charts/historicalUsageChart/historicalUsageChart.tsx, src/components/charts/trendChart/trendChart.tsx, src/components/charts/usageChart/usageChart.tsx
This solves an issue where the historical chart tooltips are cut off for the first day or two. There just isn't enough room in the left side margin.
Ideally, we would just set the overflow to visible, which would display the tooltip in its entirety. However, this has the side effect of disabling vertical scrolling. In order to scroll vertically when the window is resized, the chart container cannot overflow. 
Instead, I've modified our PF4 Victory charts to use voronoiDimension='x', which forces the tooltip to be displayed within the chart's x-axis. This also stacks all tooltips for any given point on the x-axis, which is something we planned to do anyway.
Fixes https://github.com/project-koku/koku-ui/issues/606
Example:
=> Historical chart tooltips are cut off

src/pages/awsDashboard/awsDashboardWidget.tsx, src/pages/awsDetails/awsDetails.tsx, src/pages/awsDetails/detailsChart.tsx, src/pages/awsDetails/detailsChartModal.tsx, src/pages/awsDetails/detailsHeader.tsx, src/pages/awsDetails/detailsTable.tsx, src/pages/awsDetails/detailsTableItem.tsx, src/pages/awsDetails/detailsTag.tsx, src/pages/awsDetails/detailsTagModal.tsx, src/pages/awsDetails/exportModal.tsx, src/pages/awsDetails/groupBy.tsx, src/pages/awsDetails/historicalChart.tsx, src/pages/ocpDetails/detailsChart.tsx, src/pages/ocpDetails/detailsCluster.tsx, src/pages/ocpDetails/detailsHeader.tsx, src/pages/ocpDetails/detailsSummary.tsx, src/pages/ocpDetails/detailsTable.tsx, src/pages/ocpDetails/detailsTableItem.tsx, src/pages/ocpDetails/detailsTag.tsx, src/pages/ocpDetails/detailsTagModal.tsx, src/pages/ocpDetails/exportModal.tsx, src/pages/ocpDetails/groupBy.tsx, src/pages/ocpDetails/historicalChart.tsx, src/pages/ocpDetails/ocpDetails.tsx, src/pages/ocpOnAwsDashboard/ocpOnAwsDashboardWidget.tsx, src/pages/overview/overview.tsx
When a request encounters a 400 error; for example, the UI continues to invoke the same request repeatedly.
It turns out that a retry limit is not what is needed to resolve this issue. The UI makes a request each time the page is updated and it has yet to obtain a report. We simply need to check if we received an error before making another request.
Now if we encounter a 400 error, the unexpected error state is shown. This avoids hitting the server unnecessarily.
Fixes https://github.com/project-koku/koku-ui/issues/590
=> Harden request errors

src/api/ocpOnAwsReports.test.ts, src/api/ocpOnAwsReports.ts
This simply updates the OCP on AWS cost card to use the new reports/openshift/infrastructure/aws/costs/ API.
Fixes https://github.com/project-koku/koku-ui/issues/612
=> Update API for OCP on AWS cost card

README.md, config/spandx.config.js, config/spandx.config.local.js, src/api/api.ts, src/index.html, src/index.tsx, webpack.config.js, yarn.lock
FYI - I believe these are the set of changes for the upcoming app format changes to work on cloud.redhat.com.
FYI - @dlabrecq @boaz0 
Run from the insights proxy folder:
`SPANDX_CONFIG=/path/to/koku-ui/config/spandx.config.js bash scripts/run.sh`
then `yarn start:dev`
Point browser to: 
https://ci.foo.redhat.com:1337/apps/cost-management/
This should also work; but doesn't seem to:
https://ci.foo.redhat.com:1337/hcm/cost-management/
Worked of the changes seen here:
https://github.com/RedHatInsights/insights-frontend-starter-app/pull/62/files
=> Changes to work under the cloud.redhat.com setup

src/pages/awsDetails/detailsTable.tsx, src/pages/ocpDetails/detailsTable.tsx, src/pages/ocpOnAwsDetails/detailsTable.tsx
Now that we're showing the expanding row column, while grouping by tags, we must adjust the sort functionality to work with the proper number of table columns.
Fixes https://github.com/project-koku/koku-ui/issues/625
=> Enable sort by cost while grouping by tags

src/app.tsx
Added code to check if the request generated an error. This ensures we don't make additional API requests each time the page is updated upon the API reponse.
Fixes https://github.com/project-koku/koku-ui/issues/634
=> Add provider error check

src/components/charts/bulletChart/bulletChart.tsx
Moves the Bullet chart tooltip orientation to top.
Fixes https://github.com/project-koku/koku-ui/issues/637
=> Bullet chart tooltip orientation

src/components/charts/commonChart/chartUtils.ts, src/components/reports/awsReportSummary/awsReportSummaryItems.test.tsx, src/components/reports/awsReportSummary/awsReportSummaryItems.tsx, src/components/reports/ocpOnAwsReportSummary/ocpOnAwsReportSummaryItems.test.tsx, src/components/reports/ocpOnAwsReportSummary/ocpOnAwsReportSummaryItems.tsx, src/components/reports/ocpReportSummary/ocpReportSummaryItems.test.tsx, src/components/reports/ocpReportSummary/ocpReportSummaryItems.tsx, src/pages/awsDetails/detailsHeader.tsx, src/pages/ocpDetails/detailsHeader.tsx, src/pages/ocpOnAwsDetails/detailsHeader.tsx, src/pages/overview/overview.tsx, src/store/awsDashboard/__snapshots__/awsDashboard.test.ts.snap, src/store/awsDashboard/awsDashboard.test.ts, src/store/awsDashboard/awsDashboardCommon.ts, src/store/awsDashboard/awsDashboardSelectors.ts, src/store/ocpDashboard/__snapshots__/ocpDashboard.test.ts.snap, src/store/ocpDashboard/ocpDashboard.test.ts, src/store/ocpDashboard/ocpDashboardCommon.ts, src/store/ocpDashboard/ocpDashboardSelectors.ts, src/store/ocpOnAwsDashboard/__snapshots__/ocpOnAwsDashboard.test.ts.snap, src/store/ocpOnAwsDashboard/ocpOnAwsDashboard.test.ts, src/store/ocpOnAwsDashboard/ocpOnAwsDashboardCommon.ts, src/store/ocpOnAwsDashboard/ocpOnAwsDashboardSelectors.ts
The OCP and OCP on AWS overview / details pages show incorrect total costs.
We're showing an incorrect total cost because 'group by' project is applied to the underlying API request. Similarly, the details page also shows a total cost, based on 'group by' project.
This change ensures 'group by' is applied only to the overview tabs, not the API requests associated with total cost.
Fixes https://github.com/project-koku/koku-ui/issues/632
OCP overview:
OCP details:
=> Incorrect total costs

src/locales/en.json, src/pages/ocpDetails/detailsSummary.styles.ts, src/pages/ocpDetails/detailsSummary.tsx, src/pages/ocpDetails/detailsTableItem.styles.ts, src/pages/ocpDetails/detailsTableItem.tsx
Update the expanding rows area, for the OCP details page, per the mock below.
Mock: https://redhat.invisionapp.com/share/HEO4ISHAT8Z#/screens/352926695
Note: Tags are shown only for 'group by' project.
Fixes https://github.com/project-koku/koku-ui/issues/599
Group by cluster:
Group by project:
=> OCP Details: update expanding rows area

src/pages/ocpOnAwsDetails/detailsSummary.styles.ts, src/pages/ocpOnAwsDetails/detailsSummary.tsx, src/pages/ocpOnAwsDetails/detailsTableItem.styles.ts
The OCP on AWS details page should match the margins / padding used by the OCP and AWS details pages.
Fixes https://github.com/project-koku/koku-ui/issues/639
=> Update OCP on AWS details page margins

src/pages/ocpOnAwsDetails/detailsTableItem.tsx, src/pages/ocpOnAwsDetails/detailsTag.tsx, src/pages/ocpOnAwsDetails/detailsTagModal.tsx, src/pages/ocpOnAwsDetails/groupBy.tsx
When attempting OCP on AWS is groupped by tag, the API returns a "400 Bad Request". The specific message is "Unsupported parameter" message. We need to call the tags API for AWS.
Fixes https://github.com/project-koku/koku-ui/issues/647
=> OCP on Aws: Cannot group by tag

src/pages/ocpOnAwsDetails/detailsTableItem.tsx, src/pages/ocpOnAwsDetails/detailsWidget.tsx
Per today's UI review, we want to show tabs for AWS accounts, services, and regions when each table row is expanded. Currently, we only show AWS services for 'group by' accounts.
Fixes https://github.com/project-koku/koku-ui/issues/645
=> OCP on AWS Details: Show AWS accounts, services, and regions

src/utils/getComputedOcpOnAwsReportItems.ts, src/utils/getComputedOcpReportItems.ts
While processing API reports, we flatten items for the detail tables and charts. Items are stored using project, cluster, node, or tag as map identifiers. As long as those values are unique, there is no issue. However, there may be projects in different clusters with the same name. In that case, IDs could override each other in our flattened list.
This change ensures we use unique IDs while flattening report items.
Fixes https://github.com/project-koku/koku-ui/issues/706
=> Ensure unique IDs while flattening report items

src/locales/en.json
Update OCP cost card title as "Total cost".
Fixes https://github.com/project-koku/koku-ui/issues/660
=> Update OCP cost card title

src/pages/ocpOnAwsDashboard/ocpOnAwsDashboardWidget.tsx, src/pages/ocpOnAwsDetails/historicalChart.tsx
Using infrastructure_cost for OpenShift on AWS, instead of cost
Fixes https://github.com/project-koku/koku-ui/issues/666
OCP on cloud overview:
OCP on cloud details:
=> Use infrastructure cost for OpenShift on AWS

src/locales/en.json
Update OCP on AWS card title to "Infrastructure cost"
Fixes https://github.com/project-koku/koku-ui/issues/665
=> Update OCP on AWS card title

src/store/ocpOnAwsDashboard/ocpOnAwsDashboard.test.ts, src/store/ocpOnAwsDashboard/ocpOnAwsDashboardReducer.ts, src/store/ocpOnAwsDashboard/ocpOnAwsDashboardWidgets.ts
Adds database and network AWS cards to the OpenShift on AWS overview page.
Note there is an issue with the `/reports/openshift/infrastructures/aws/cost` API returning the same cost, regardless of the product family. See https://github.com/project-koku/koku/issues/789
Fixes https://github.com/project-koku/koku-ui/issues/667
OpenShift on AWS:
=> Add all AWS cards to OpenShift on AWS

src/index.tsx
This should add the release name (e.g., /beta) into the router path.
Fixes https://github.com/project-koku/koku-ui/issues/683
=> Ensure release name is not omitted from router path

config/spandx.config.js
The current spandx config uses /apps instead of /hybrid. This forces chrome to use the legacy navigation pane, while the unused /hcm route appears to cause the UI to hang.
Fixes https://github.com/project-koku/koku-ui/issues/712
=> spandx not configured properly

src/components/reports/awsReportSummary/__snapshots__/awsReportSummaryItem.test.tsx.snap, src/components/reports/awsReportSummary/awsReportSummaryDetails.test.tsx, src/components/reports/awsReportSummary/awsReportSummaryDetails.tsx, src/components/reports/awsReportSummary/awsReportSummaryItem.test.tsx, src/components/reports/awsReportSummary/awsReportSummaryItem.tsx, src/components/reports/ocpOnAwsReportSummary/__snapshots__/ocpOnAwsReportSummaryItem.test.tsx.snap, src/components/reports/ocpOnAwsReportSummary/ocpOnAwsReportSummaryDetails.test.tsx, src/components/reports/ocpOnAwsReportSummary/ocpOnAwsReportSummaryDetails.tsx, src/components/reports/ocpOnAwsReportSummary/ocpOnAwsReportSummaryItem.test.tsx, src/components/reports/ocpOnAwsReportSummary/ocpOnAwsReportSummaryItem.tsx, src/components/reports/ocpReportSummary/__snapshots__/ocpReportSummaryItem.test.tsx.snap, src/components/reports/ocpReportSummary/ocpReportSummaryDetails.test.tsx, src/components/reports/ocpReportSummary/ocpReportSummaryDetails.tsx, src/components/reports/ocpReportSummary/ocpReportSummaryItem.test.tsx, src/components/reports/ocpReportSummary/ocpReportSummaryItem.tsx, src/locales/en.json, src/pages/awsDashboard/awsDashboardWidget.tsx, src/pages/ocpDashboard/ocpDashboardWidget.tsx, src/pages/ocpOnAwsDashboard/ocpOnAwsDashboardWidget.tsx, src/store/awsDashboard/awsDashboardCommon.ts, src/store/awsDashboard/awsDashboardWidgets.ts, src/store/ocpDashboard/ocpDashboardCommon.ts, src/store/ocpDashboard/ocpDashboardWidgets.ts, src/store/ocpOnAwsDashboard/ocpOnAwsDashboardCommon.ts, src/store/ocpOnAwsDashboard/ocpOnAwsDashboardWidgets.ts, src/utils/formatValue.test.ts, src/utils/formatValue.ts
Add missing units to progress bars shown on the AWS and OCP overview pages.
Fixes https://github.com/project-koku/koku-ui/issues/687
AWS:
OpenShift:
=> Add missing units

src/pages/awsDetails/historicalModal.tsx, src/pages/ocpDetails/detailsChart.tsx, src/pages/ocpDetails/historicalModal.tsx, src/pages/ocpOnAwsDetails/detailsChart.tsx, src/pages/ocpOnAwsDetails/detailsSummary.tsx, src/pages/ocpOnAwsDetails/historicalModal.tsx, src/store/awsDashboard/awsDashboard.test.ts, src/store/awsDashboard/awsDashboardCommon.ts, src/store/ocpDashboard/ocpDashboard.test.ts, src/store/ocpDashboard/ocpDashboardCommon.ts, src/store/ocpOnAwsDashboard/ocpOnAwsDashboard.test.ts, src/store/ocpOnAwsDashboard/ocpOnAwsDashboardCommon.ts
Show top 3 instead of top 5 projects, services, etc.
Fixes https://github.com/project-koku/koku-ui/issues/659
AWS:
OCP:
AWS Details:
=> Show top 3

src/components/charts/historicalTrendChart/historicalTrendChart.styles.ts, src/components/charts/historicalTrendChart/historicalTrendChart.tsx, src/components/charts/historicalUsageChart/historicalUsageChart.styles.ts, src/components/charts/historicalUsageChart/historicalUsageChart.tsx, src/components/charts/trendChart/trendChart.styles.ts, src/components/charts/trendChart/trendChart.tsx, src/components/charts/usageChart/usageChart.styles.ts, src/components/charts/usageChart/usageChart.tsx
Updates the chart tooltip styling to mimic PF4 tooltips. For example, the white text, black background, padding, and pointer size.
Fixes https://github.com/project-koku/koku-ui/issues/703
Single line:
Multi-line:
=> Chart tooltip styling to mimic PF4

src/components/charts/costChart/costChart.styles.ts, src/components/charts/costChart/costChart.tsx, src/components/charts/costChart/index.ts, src/components/reports/ocpReportSummary/ocpReportSummaryTrend.tsx, src/locales/en.json, src/pages/ocpDashboard/ocpDashboardWidget.tsx, yarn.lock
This update adds a new chart to show both cost and infrastructure cost. This will be shown for the OpenShift cost card only.
Fixes https://github.com/project-koku/koku-ui/issues/662
OCP Overview:
=> Show infrastructure cost in OpenShift cost chart

src/locales/en.json
Updates OpenShift details cost title from "Total Cost" to "Cost".
Fixes https://github.com/project-koku/koku-ui/issues/673
=> OpenShift details cost title

src/pages/ocpDetails/detailsTableItem.tsx
Removes top projects when OpenShift details is grouped by node.
Fixes https://github.com/project-koku/koku-ui/issues/672
Group by node:
Group by cluster:
=> OpenShift details top projects

src/locales/en.json, src/pages/ocpDetails/detailsTable.tsx
This update adds derived and infrastructure cost column to the OCP details table.
Note: Sorting by derived and infrastructure costs is not enabled, for now. See https://github.com/project-koku/koku/issues/796
Fixes https://github.com/project-koku/koku-ui/issues/669
=> OCP details: Derived and infrastructure cost column

src/locales/en.json
The historical modal title, shown in the details pages, should read: `<project name> daily usage comparison`.
Fixes https://github.com/project-koku/koku-ui/issues/675
=> Historical modal title

src/components/reports/ocpReportSummary/__snapshots__/ocpReportSummaryDetails.test.tsx.snap, src/components/reports/ocpReportSummary/ocpReportSummaryDetails.tsx, src/locales/en.json
This change shows a tooltip when hovering over the total cost. This explains how the total cost is comprised of derived and infrastructure costs.
Fixes https://github.com/project-koku/koku-ui/issues/661
Mock: https://redhat.invisionapp.com/share/TYRFMZ1C8H7#/screens
OCP overview:
=> Show infrastructure cost with OpenShift card

src/locales/en.json, src/pages/ocpDetails/detailsHeader.styles.ts, src/pages/ocpDetails/detailsHeader.tsx
The popover, when clicking the info icon, describes what derived and infrastructure costs are. The tooltip shows the actual derived and infrastructure costs.
Fixes https://github.com/project-koku/koku-ui/issues/670
Cost tooltip:
Info icon popover:
=> OCP details popover & tooltip for derived and infrastructure cost

src/store/ocpOnAwsDashboard/ocpOnAwsDashboardActions.ts, src/store/ocpOnAwsDashboard/ocpOnAwsDashboardWidgets.ts
The OCP on AWS overview is generating requests for tabs that are not being displayed. Only the first cost card displays tabs. All other cards omit the tab for a smaller view. This means there are several requests being generated unnecessarily. This should help speed things up slightly?
Fixes https://github.com/project-koku/koku-ui/issues/735
=> Omit unnecessary tab requests

src/api/awsQuery.ts, src/api/ocpOnAwsQuery.ts, src/api/ocpQuery.ts, src/pages/ocpDetails/detailsTable.tsx
This change applies logical AND to the toolbar filters found in the details pages.
Fixes https://github.com/project-koku/koku-ui/issues/704
OCP, group by tag:
OCP on AWS, group by project:
AWS, group by account:
=> Apply logical AND to toolbar filters

src/components/reports/awsReportSummary/awsReportSummary.styles.ts, src/components/reports/awsReportSummary/awsReportSummary.test.tsx, src/components/reports/awsReportSummary/awsReportSummary.tsx, src/components/reports/awsReportSummary/awsReportSummaryAlt.styles.ts, src/components/reports/awsReportSummary/awsReportSummaryAlt.tsx, src/components/reports/awsReportSummary/awsReportSummaryItems.styles.ts, src/components/reports/awsReportSummary/awsReportSummaryItems.tsx, src/components/reports/ocpOnAwsReportSummary/ocpOnAwsReportSummary.styles.ts, src/components/reports/ocpOnAwsReportSummary/ocpOnAwsReportSummary.test.tsx, src/components/reports/ocpOnAwsReportSummary/ocpOnAwsReportSummary.tsx, src/components/reports/ocpOnAwsReportSummary/ocpOnAwsReportSummaryAlt.styles.ts, src/components/reports/ocpOnAwsReportSummary/ocpOnAwsReportSummaryAlt.tsx, src/components/reports/ocpOnAwsReportSummary/ocpOnAwsReportSummaryItems.styles.ts, src/components/reports/ocpOnAwsReportSummary/ocpOnAwsReportSummaryItems.tsx, src/components/reports/ocpReportSummary/ocpReportSummary.styles.ts, src/components/reports/ocpReportSummary/ocpReportSummary.test.tsx, src/components/reports/ocpReportSummary/ocpReportSummary.tsx, src/components/reports/ocpReportSummary/ocpReportSummaryAlt.styles.ts, src/components/reports/ocpReportSummary/ocpReportSummaryAlt.tsx, src/components/reports/ocpReportSummary/ocpReportSummaryItems.styles.ts, src/components/reports/ocpReportSummary/ocpReportSummaryItems.tsx, src/pages/awsDetails/detailsWidget.styles.ts, src/pages/awsDetails/detailsWidget.tsx, src/pages/ocpOnAwsDetails/detailsWidget.styles.ts, src/pages/ocpOnAwsDetails/detailsWidget.tsx, webpack.config.js
Replaces "Loading..." text with the Insights skeleton component.
Fixes https://github.com/project-koku/koku-ui/issues/691
Initial loading state:
Cost loaded, while other cards are loading:
=> Insights skeletons

src/components/reports/ocpReportSummary/ocpReportSummaryDetails.tsx
OCP cpu, memory, & volume cards should show usage, not cost
Fixes https://github.com/project-koku/koku-ui/issues/738
=> OCP usage cards should not show cost

src/locales/en.json, src/pages/ocpDetails/detailsChart.tsx, src/pages/ocpOnAwsDetails/detailsChart.tsx
This change omits the capacity from bullet charts. There's a possible the capacity could be really long and skew the charts.
Fixes: https://github.com/project-koku/koku-ui/issues/741
=> Omit capacity from bullet charts

src/components/charts/bulletChart/bulletChart.styles.ts, src/components/charts/bulletChart/bulletChart.tsx
Update bullet chart tooltip styling to look more like PF4 tooltips
Fixes ttps://github.com/project-koku/koku-ui/issues/746
=> Bullet chart tooltip styling

src/pages/sourceSettings/sourceSettings.tsx
closes #763 
In the new PF4, components won't be rendered unless wrapped with `React.Fragment` or `<>`.
=> fix(Sources): use React.Fragment to render details table item

webpack.config.js
For some reason, our webpack config is not chunking css files properly in production. This change ensures the probuction build outputs css files for missing table styles.
Fixes https://github.com/project-koku/koku-ui/issues/772
=> Missing table styles in production

src/locales/en.json, src/pages/overview/overview.styles.ts, src/pages/overview/overview.tsx
Added an info popup to describe the overview tabs.
Fixes https://github.com/project-koku/koku-ui/issues/755
=> Overview info popup

src/components/charts/historicalCostChart/historicalCostChart.styles.ts, src/components/charts/historicalCostChart/historicalCostChart.tsx, src/components/charts/historicalTrendChart/historicalTrendChart.styles.ts, src/components/charts/historicalTrendChart/historicalTrendChart.tsx, src/components/charts/historicalUsageChart/historicalUsageChart.styles.ts, src/components/charts/historicalUsageChart/historicalUsageChart.tsx
Now that the historical modal resizes horizontally, the legends should adjust as well. This ensures the legend labels are not truncated even when the modal is at it's smallest size possible. 
Note that users can scroll vertically when the height of the modal is resized smaller in height.
Fixes https://github.com/project-koku/koku-ui/issues/774
Ocp:
Ocp on AWS:
AWS:
=> Wrap historical chart legends

src/components/reports/awsReportSummary/__snapshots__/awsReportSummaryDetails.test.tsx.snap, src/components/reports/awsReportSummary/awsReportSummaryDetails.tsx, src/components/reports/ocpOnAwsReportSummary/__snapshots__/ocpOnAwsReportSummaryDetails.test.tsx.snap, src/components/reports/ocpOnAwsReportSummary/ocpOnAwsReportSummaryDetails.tsx, src/components/reports/ocpReportSummary/__snapshots__/ocpReportSummaryDetails.test.tsx.snap, src/components/reports/ocpReportSummary/ocpReportSummaryDetails.tsx, src/components/state/emptyValueState/emptyValueState.styles.ts, src/components/state/emptyValueState/emptyValueState.tsx, src/locales/en.json, src/pages/awsDetails/historicalChart.tsx, src/pages/ocpDetails/detailsHeader.tsx, src/utils/formatValue.ts
Overview empty state when no reports are available. Replaces multiple dashes with a single PatternFly "minus" icon.
Fixes https://github.com/project-koku/koku-ui/issues/228
Overview:
=> Overview empty state

src/pages/ocpOnAwsDashboard/ocpOnAwsDashboardWidget.tsx
This ensures the "All projects" link ,for the Ocp on Aws overview, navigates to the Ocp on AWS details page.
Fixes https://github.com/project-koku/koku-ui/issues/782
=> Incorrect navigation for "All projects" link

src/pages/awsDashboard/awsDashboardWidget.tsx, src/pages/awsDetails/detailsToolbar.tsx, src/pages/awsDetails/exportModal.styles.ts, src/pages/awsDetails/exportModal.tsx, src/pages/ocpDashboard/ocpDashboardWidget.tsx, src/pages/ocpDetails/detailsToolbar.tsx, src/pages/ocpDetails/exportModal.styles.ts, src/pages/ocpDetails/exportModal.tsx, src/pages/ocpOnAwsDashboard/ocpOnAwsDashboardWidget.tsx, src/pages/ocpOnAwsDetails/detailsToolbar.tsx, src/pages/ocpOnAwsDetails/exportModal.styles.ts, src/pages/ocpOnAwsDetails/exportModal.tsx
Replaced custom FormGroup, TextInput, Link, and h2 tags with PF4 components. 
Note: Did not update the login page or old providers modal since those components are no longer in use. No change to the layouts.
Fixes https://github.com/project-koku/koku-ui/issues/186
Export modal:
Filter text input:
=> Replace custom components with PF4 components

src/globals.d.ts, src/pages/awsDashboard/awsDashboardWidget.tsx, src/pages/ocpDashboard/ocpDashboardWidget.tsx, src/pages/ocpOnAwsDashboard/ocpOnAwsDashboardWidget.tsx
This fixes an issue where the Insights navigation links (in the left-side navigation pane) are not made active and highlighted properly. That is, when clicking on the "top" tabs links in the overview (i.e., "All clusters", "All services", etc.) and navigating to details pages.
This also ensures that when the user is navigated to the appropriate details page, the correct group_by is selected.
Fixes https://github.com/project-koku/koku-ui/issues/756
Fixes https://github.com/project-koku/koku-ui/issues/793
=> Fixed navigation from overview to details page

src/api/rates.ts, src/locales/en.json, src/pages/ocpDetails/priceListModal.tsx, src/pages/ocpDetails/priceListTable.tsx, src/store/priceList/__snapshots__/store.test.ts.snap, src/store/priceList/actions.ts, src/store/priceList/reducer.ts, src/store/priceList/selectors.ts, src/store/priceList/store.test.ts
closes #765 
Update the Price List selectors to the new API.
Questions:
- What should I do if both `usage start` and `usage end` are null or one of them? @nlcwong 
Screenshot
=> fix(PriceList): update price list API and display

src/pages/awsDetails/detailsHeader.tsx, src/pages/ocpDetails/detailsHeader.tsx, src/pages/ocpOnAwsDetails/detailsHeader.tsx, src/pages/overview/overview.styles.ts, src/pages/overview/overview.tsx
All headers should be the same font size. In addition, we should also hide the info icon for an empty state (i.e., when there are no providers).
Fixes https://github.com/project-koku/koku-ui/issues/799
Overview:
=> Overview header font size

src/components/state/noProvidersState/noProvidersState.styles.ts, src/components/state/noProvidersState/noProvidersState.tsx, src/locales/en.json, src/testIds.ts
This updates text for "no providers" empty state. And instead of clicking "Add Sources" to launch the providers modal, the user clicks on a "View all sources", which navigates to the sources page.
Fixes https://github.com/project-koku/koku-ui/issues/801
=> Update "no providers" empty state

src/pages/ocpDetails/detailsHeader.styles.ts, src/pages/ocpDetails/detailsHeader.tsx
The info icon shown in the Ocp details title is currently smaller than others. For example, there is an info icon in the Insights header (same page) and Overview page header.
Fixes https://github.com/project-koku/koku-ui/issues/804
Ocp details:
=> Info icons should be the same size

src/locales/en.json, src/pages/ocpDashboard/ocpDashboardWidget.tsx
The legend title for the volume card doesn't display units properly. This is because the title localization doesn't use the correct parameter name.
Fixes https://github.com/project-koku/koku-ui/issues/811
=> Volume card units

src/api/awsQuery.ts, src/api/ocpOnAwsQuery.ts, src/api/ocpQuery.ts, src/store/awsDashboard/awsDashboardCommon.ts, src/store/awsDashboard/awsDashboardWidgets.ts, src/store/awsDetails/awsDetailsCommon.ts, src/store/ocpDashboard/ocpDashboardCommon.ts, src/store/ocpOnAwsDashboard/ocpOnAwsDashboardCommon.ts, src/store/ocpOnAwsDashboard/ocpOnAwsDashboardWidgets.ts, src/store/ocpOnAwsDetails/ocpOnAwsDetailsCommon.ts
With this change, the network & database cards now use the new `service` filter instead of a `product_family`.
Fixes https://github.com/project-koku/koku-ui/issues/819
Ocp on AWS:
AWS:
=> Network & database cards to use new service filter

src/pages/onboardingModal/awsConfigure/form.tsx, src/pages/onboardingModal/enableAccountAccess/form.tsx, src/pages/onboardingModal/sourceKind/form.tsx, src/pages/onboardingModal/usageCollector/form.tsx
This fixes an issue with the providers modal, where pressing the 'enter' key in text inputs, loads the overview page.
Fixes https://github.com/project-koku/koku-ui/issues/813
=> Providers modal loads overview page

src/app.tsx
Bug fix for the sources link.
Go from:
To "Cost Management Sources":
Only remaining but is for some reason the left-hand nav under Settings highlights "Catalog Sources"
=> Add mechanism to identify the "correct" app for the insights chrome.

src/store/awsDashboard/awsDashboardWidgets.ts, src/store/ocpOnAwsDashboard/ocpOnAwsDashboardWidgets.ts
We need to apply the following filter for the "AWS compute (EC2) instances" card, shown in both "Ocp on AWS" and "AWS" overview tabs.
`filter[service]=AmazonEC2`
Fixes https://github.com/project-koku/koku-ui/issues/830
=> Add filter for "AWS compute (EC2) instances" card

src/locales/en.json, src/pages/ocpDetails/noRatesState.styles.ts, src/pages/ocpDetails/noRatesState.tsx, src/pages/ocpDetails/priceListModal.tsx
=> fix(priceList): add empty state when there are no rates

src/store/awsDashboard/awsDashboardWidgets.ts
Need to also add a filter to the tabs of the "AWS compute (EC2) instances" card.
=> Add filter to the tabs of the "AWS compute (EC2) instances" card

src/pages/awsDetails/detailsTable.tsx, src/pages/ocpDetails/detailsTable.tsx, src/pages/ocpOnAwsDetails/detailsTable.tsx, src/pages/sourceSettings/rowCell.tsx
In our tables, we must use the title property for each PatternFly table cell. For example:
```
cells: [
{ title: <div>...</div> },
],
```
This was a breaking change with PatternFly 4 beta, but didn't show up in our build until the latest packages were installed.
Fixes https://github.com/project-koku/koku-ui/issues/835
=> Broken PF tables

src/components/charts/commonChart/chart.styles.ts, src/components/charts/costChart/costChart.styles.ts, src/components/charts/historicalCostChart/historicalCostChart.styles.ts, src/components/charts/historicalTrendChart/historicalTrendChart.styles.ts, src/components/charts/historicalUsageChart/historicalUsageChart.styles.ts, src/components/charts/trendChart/trendChart.styles.ts, src/components/charts/usageChart/usageChart.styles.ts
When the PatternFly charts are built with the latest Victory chart packages, the koku-ui build breaks with due to our use of VictoryStyleInterface. Apparently, Victory changed the properties and objects associated with this interface, so our current usage is no longer valid.
Fixes https://github.com/project-koku/koku-ui/issues/838
=> VictoryStyleInterface breakage

src/components/reports/awsReportSummary/awsReportSummaryAlt.styles.ts, src/components/reports/ocpOnAwsReportSummary/ocpOnAwsReportSummaryAlt.styles.ts, src/components/reports/ocpReportSummary/ocpReportSummaryAlt.styles.ts
This fixes a very minor issue where the tooltip box can appear slightly behind the overview tab's bar charts.
Fixes https://github.com/project-koku/koku-ui/issues/828
Ocp on Aws:
AWS:
=> Tooltips appear behind bar charts

src/api/awsQuery.ts, src/api/ocpOnAwsQuery.ts, src/api/ocpQuery.ts, src/store/awsDashboard/__snapshots__/awsDashboard.test.ts.snap, src/store/awsDashboard/awsDashboardCommon.ts
AWS network & database card queries must use group_by instead of a filter for the service tab only.
Note that other tabs appear to still need the wild card (e.g., `group_by[accounts]=* `and `group_by[regions]=*`) along with the current filter for the costs to add up correctly.
Also need to ensure we don't apply logical AND to the group_by here.
Fixes https://github.com/project-koku/koku-ui/issues/846
Top services:
Top regions:
=> AWS overview network and database card values don't add up

src/pages/ocpDetails/detailsTable.tsx, src/pages/ocpDetails/detailsWidgetModal.tsx, src/pages/ocpDetails/detailsWidgetView.tsx
The 'All projects' link and kebab menu open shows all cluster projects instead of the projects belonging to just that cluster.
Fixes https://github.com/project-koku/koku-ui/issues/851
=> 'All projects' shows all cluster projects

src/api/awsQuery.ts, src/api/ocpOnAwsQuery.ts, src/api/ocpQuery.ts
Logical AND does not get applied to the filter results in details pages.
We don't want logical AND applied to the AWS overview network card, but expect to see the `and:` prefix when multiple group_by params are applied in the details pages. For example:
`group_by[and:project]=open&group_by[and:project]=sdn&order_by[cost]=desc`
Fixes https://github.com/project-koku/koku-ui/issues/856
=> Apply logical AND for multiple group_by query params

src/locales/en.json, src/pages/sourceSettings/header.tsx
=> fix(sources): breadcrumb typo and functionality

src/components/charts/costChart/costChart.tsx, src/components/charts/historicalCostChart/historicalCostChart.tsx, src/components/charts/historicalTrendChart/historicalTrendChart.tsx, src/components/charts/historicalUsageChart/historicalUsageChart.tsx, src/components/charts/pieChart/pieChart.tsx, src/components/charts/trendChart/trendChart.tsx, src/components/charts/usageChart/usageChart.tsx
This change makes the legend text clickable in order to hide/show lines of data. The user can continue to click on the legend symbol as well. However, this provides a larger, clickable area.
Fixes https://github.com/project-koku/koku-ui/issues/810
=> Make the legend text clickable in order to hide/show lines of data

src/pages/awsDetails/awsDetails.tsx, src/pages/ocpDetails/ocpDetails.tsx, src/pages/ocpOnAwsDetails/ocpOnAwsDetails.tsx
Reset pagination whenever table rows change. For example, when a new group_by is selected, filters are applied, or when the number of items per page changes.
Fixes https://github.com/project-koku/koku-ui/issues/850
=> Reset pagination whenever table rows change

src/components/reports/awsReportSummary/awsReportSummaryItems.test.tsx, src/components/reports/awsReportSummary/awsReportSummaryItems.tsx, src/components/reports/ocpOnAwsReportSummary/ocpOnAwsReportSummaryItems.test.tsx, src/components/reports/ocpOnAwsReportSummary/ocpOnAwsReportSummaryItems.tsx, src/components/reports/ocpReportSummary/ocpReportSummaryItems.test.tsx, src/components/reports/ocpReportSummary/ocpReportSummaryItems.tsx, src/pages/awsDashboard/awsDashboardWidget.tsx, src/pages/awsDetails/detailsWidgetModalView.tsx, src/pages/awsDetails/detailsWidgetView.tsx, src/pages/ocpDashboard/ocpDashboardWidget.tsx, src/pages/ocpDetails/detailsWidget.tsx, src/pages/ocpDetails/detailsWidgetView.tsx, src/pages/ocpOnAwsDashboard/ocpOnAwsDashboardWidget.tsx, src/pages/ocpOnAwsDetails/detailsWidgetModalView.tsx, src/pages/ocpOnAwsDetails/detailsWidgetView.tsx
This change ensures skeletons are only shown while the fetch status is in progress. If there is an request error (e.g., a 403), the skeletons will no longer be shown.
Fixes https://github.com/project-koku/koku-ui/issues/854
=> Show skeletons only when fetch status is in progress

src/locales/en.json, src/utils/formatValue.ts
This ensures unsupported units don't break translations. If the given units are not known, we'll just omit it instead of showing something like `units.tag-mo`.
This also places the `%` character inside the parenthesis above the progress bar.
fixes https://github.com/project-koku/koku-ui/issues/909
=> Ensure unsupported units don't break translations

src/app.tsx
fixes #907 
In general, I added another check that makes sure koku-ui won't sent more than 1 request per provider type when onboarding is completed successfully. 
By using prev props I can tell if a new source was added succesfully and in that moment to send a request.
=> fix(onboarding): update ocp and aws providers once on source creation

src/api/ocpOnAwsReports.ts, src/pages/ocpOnAwsDetails/groupBy.tsx
The Ocp on AWS Details page should use the `tags/openshift/infrastructures/aws` endpoint instead of `tags/openshift`
Fixes https://github.com/project-koku/koku-ui/issues/904
=> Update tags API for Ocp on AWS details page

src/components/charts/bulletChart/bulletChart.tsx, src/pages/ocpDetails/detailsChart.tsx, src/pages/ocpOnAwsDetails/detailsChart.tsx
The reports/openshift/compute API currently returns null for limit and request. This is a known issue with koku (https://github.com/project-koku/koku/issues/927), but we can still ensure that the bullet chart renders without these values.
Fixes https://github.com/project-koku/koku-ui/issues/915
Without requests or limit:
Without limit:
=> Ensure bullet chart renders without requests or limit

config/spandx.config.local.js
In order to run the local koku UI and local koku backend with the insights platform you need to set the route `api/cost-management` to the local koku backend and route `{/beta}*/{hybrid/api}/cost-management` to the insight proxy.
This PR updates `config/spandx.config.local.js` with those settings.
=> fix(config): set the right routes to local koku from production

package.json, yarn.lock
Still having some trouble with Insights navigation -- links often do nothing. Backing out the dependency added for react, which was required to update react-dom.
Fixes https://github.com/project-koku/koku-ui/issues/924
=> revert updated version of react

src/components/charts/bulletChart/bulletChart.styles.ts, src/components/charts/costChart/costChart.styles.ts, src/components/charts/historicalCostChart/historicalCostChart.styles.ts, src/components/charts/historicalTrendChart/historicalTrendChart.styles.ts, src/components/charts/historicalUsageChart/historicalUsageChart.styles.ts, src/components/charts/pieChart/pieChart.styles.ts, src/components/charts/trendChart/trendChart.styles.ts, src/components/charts/usageChart/usageChart.styles.ts
included commented out custom colors to show change to default imported pf4 core chart colors for bullet, cost, historical cost, historical trend, historical usage, pie, trend, and usage charts
=> fixed issue #928 pf4 chart colors

package.json, src/locales/en.json, src/pages/awsDetails/awsDetails.styles.ts, src/pages/awsDetails/awsDetails.tsx, src/pages/awsDetails/detailsToolbar.styles.ts, src/pages/awsDetails/detailsToolbar.tsx, src/pages/ocpDetails/detailsToolbar.styles.ts, src/pages/ocpDetails/detailsToolbar.tsx, src/pages/ocpDetails/ocpDetails.styles.ts, src/pages/ocpDetails/ocpDetails.tsx, src/pages/ocpOnAwsDetails/detailsToolbar.styles.ts, src/pages/ocpOnAwsDetails/detailsToolbar.tsx, src/pages/ocpOnAwsDetails/ocpOnAwsDetails.styles.ts, src/pages/ocpOnAwsDetails/ocpOnAwsDetails.tsx, src/styles/global.css, webpack.config.js, yarn.lock
This replaces the PF3 toolbar, used in the Ocp, Ocp on AWS, and AWS details pages, with PF4 components.
**This eliminates the dependency on PatternFly 3. The PF3 style sheet includes via webpack, our custom CSS overrides, and patternfly-react components have all been removed.**
Fixes https://github.com/project-koku/koku-ui/issues/208
Ocp details:
Ocp on AWS details:
AWS on details:
=> Replace PF3 toolbar with PF4 components

webpack.config.js
closes #957 
**Note**:
To verify this PR fixes the problem run `yarn start --env production` and go to /beta/hybrid/cost-management.
The `--env production` will create a minified version that is similar to what is used in the QA/CI environment (paas.psi.redhat.com).
I also set `hot: !isProduction` because in production the hot-module-reload is not used and can make the bundle not to be served.
//cc @dchorvat1 
//ping @karelhala can you review this too?
=> fix(costmodels): add scoped patternfly packages to the vendors bundle

src/pages/createCostModelWizard/api.ts
this fixes the issue where no sources are displayed even though
they exist in the source step.
the issue was due to a change in the API of cost models:
the table was relaying on "provider_uuids" that was replaced
by "providers" and because of that the source list passed to
the table was empty.
closes #978 
related to #970 
//cc @chargio
=> fix(costmodels): show available sources in the source step

src/pages/createCostModelWizard/index.tsx, src/pages/createCostModelWizard/steps.tsx
the boolean expression to enable the next button was incorrect because
the default rate is 0.  in addition, when adding a new rate the values
that were set are reset but the rate value isn't reset to 0.
this commit changes that and thus fixing the bug.
closes #985
=> fix(costmodel): setting price list is optional in creation wizard

src/pages/costModelsDetails/components/addRateModel.tsx
closes #992 
closes #994 
make sure metric exists in the available rate options before rendering.
this fixes the problem of syncing between modal state and redux store.
=> fix(costmodel): if metric is no longer available don't show rate

src/api/azureQuery.ts, src/api/azureReports.test.ts, src/api/azureReports.ts, src/locales/en.json, src/pages/awsDetails/detailsTag.tsx, src/pages/azureDashboard/azureDashboardWidget.test.tsx, src/pages/azureDashboard/azureDashboardWidget.tsx, src/pages/azureDetails/azureDetails.tsx, src/pages/azureDetails/detailsActions.tsx, src/pages/azureDetails/detailsTable.tsx, src/pages/azureDetails/detailsTableItem.tsx, src/pages/azureDetails/detailsTag.tsx, src/pages/azureDetails/detailsTagView.tsx, src/pages/azureDetails/detailsToolbar.tsx, src/pages/azureDetails/detailsWidget.tsx, src/pages/azureDetails/detailsWidgetView.tsx, src/pages/azureDetails/groupBy.tsx, src/pages/ocpDetails/detailsTag.tsx, src/pages/ocpOnAwsDetails/detailsTag.tsx, src/store/azureDashboard/__snapshots__/azureDashboard.test.ts.snap, src/store/azureDashboard/azureDashboard.test.ts, src/store/azureDashboard/azureDashboardCommon.ts, src/store/azureDashboard/azureDashboardWidgets.ts, src/utils/getComputedAzureReportItems.test.ts, src/utils/getComputedAzureReportItems.ts
The current Azure overview and details pages are a copy of AWS. Now that the Azure APIs are available, we need to update those pages to use those APIs instead.
Fixes https://github.com/project-koku/koku-ui/issues/966
Overview
Azure details
=> Update APIs for Azure overview & details pages

src/utils/getComputedAwsReportItems.ts, src/utils/getComputedAzureReportItems.ts, src/utils/getComputedOcpOnAwsReportItems.ts, src/utils/getComputedOcpReportItems.ts
The OpenShift on AWS overview page is generating an error because the /v1/reports/openshift/infrastructures/aws/costs API is returning null for cost. This change ensures the UI handles that scenario by providing its own default units.
Fixes https://github.com/project-koku/koku-ui/issues/1011
=> Handle scenario where API returns null cost

src/pages/ocpDetails/detailsChart.tsx, src/pages/ocpOnAwsDetails/detailsChart.tsx
Fixed the bullet chart, shown in the Ocp and Ocp on AWS details pages, to show the correct value for usage. Also ensured tooltips are displayed correctly -- label syntax needed to be modified, due to the Victory charts update.
Fixes https://github.com/project-koku/koku-ui/issues/1024
Hold merge until after the EMEA conference
=> Bullet chart usage shows wrong value

src/pages/awsDetails/awsDetails.styles.ts, src/pages/azureDetails/azureDetails.styles.ts, src/pages/ocpDetails/ocpDetails.styles.ts, src/pages/ocpOnAwsDetails/ocpOnAwsDetails.styles.ts
This ensures the details pages stretch properly as the number of table rows are increased. 
Note that the Cost model details page uses `height: '182vh'`, but that makes the page scroll unnecessarily.
Fixes https://github.com/project-koku/koku-ui/issues/1022
Hold merge until after the EMEA conference
=> Details page should stretch with table rows

src/pages/awsDetails/detailsTable.styles.ts, src/pages/awsDetails/detailsTable.tsx, src/pages/azureDetails/detailsTable.styles.ts, src/pages/azureDetails/detailsTable.tsx, src/pages/ocpDetails/detailsTable.styles.ts, src/pages/ocpDetails/detailsTable.tsx, src/pages/ocpOnAwsDetails/detailsTable.styles.ts, src/pages/ocpOnAwsDetails/detailsTable.tsx
Need to rename icons for Font Awesome 5. 
We're using `fa-sort-asc` and `fa-sort-desc`, but it's `fa-sort-up` and `fa-sort-down` in fa5 https://fontawesome.com/icons/sort-up?style=solid
Fixes https://github.com/project-koku/koku-ui/issues/1020
Hold merge until after the EMEA conference
=> Update icon names for font awesome 5

src/pages/awsDetails/detailsTag.tsx, src/pages/azureDetails/detailsTag.tsx, src/pages/ocpDetails/detailsTag.tsx, src/pages/ocpOnAwsDetails/detailsTag.tsx
Want to truncate the "related tags" shown in the expandable area of each details table. Currently, when the number of tag characters is greater than the allowed, a tag may not be shown at all.
Fixes https://github.com/project-koku/koku-ui/issues/1018
Hold merge until after the EMEA conference
=> Truncate tag names at 50 chars

src/pages/createCostModelWizard/addPriceList.tsx, src/pages/createCostModelWizard/index.tsx, src/pages/createCostModelWizard/steps.tsx, src/pages/createCostModelWizard/wizard.styles.tsx
=> fix(costmodels): add price list sub-step fit and finish

src/pages/createCostModelWizard/generalInformation.tsx
=> fix(costmodels): general information step fit and finish

src/pages/createCostModelWizard/index.tsx, src/pages/createCostModelWizard/markup.tsx
=> fix(costmodels): fit and finish to markup step in create cost model wizard

src/locales/en.json, src/pages/costModelsDetails/components/addRateModel.tsx, src/pages/costModelsDetails/components/priceListTable.tsx, src/pages/costModelsDetails/components/priceListTier.tsx, src/pages/costModelsDetails/components/updateRateModel.tsx
=> fix(costmodels): price list tab fit and finish

src/locales/en.json, src/pages/costModelsDetails/components/deleteMarkupDialog.tsx, src/pages/costModelsDetails/components/markup.tsx, src/pages/costModelsDetails/components/updateMarkupDialog.tsx
=> fix(costmodels): markup tab in details page - fit and finish

config/spandx.config.js, config/spandx.config.local.js, src/index.tsx
All references to `hybrid` should change to `cost-management`
https://github.com/project-koku/koku-ui/issues/1066
Doesn't address issues with left-side Insights nav
=> Switch path from hybrid to cost-management

src/app.tsx
This will enable custom app navigation trough `insights.chrome.appNavClick({id: 'cost-management-sources', secondaryNav: true})` and not triggering redirect.
=> fix(navigation): use history push only for user actions

src/index.tsx
If you refresh page on `/cost-management/aws` it will include `aws` as part of basename url and once user clicks on `ocp` in navigation path will be `/cost-management/aws/ocp` this is because basename calculation tries to include second part of pathName all the time. On other hand sources settings require this second part to be present.
It's a bit hacky writing consts in the path calculation, but this is quick and dirty solution, once sources will be in specific bundle (hopefully in 2 weeks) this hacky work around can be removed and basename can be only 
```JSX
<BrowserRouter basename=`${release}${pathName[0]}/` />
```
=> Include second pathName only for sources settings

src/components/filter/filterComposition.tsx, src/locales/en.json, src/pages/costModelsDetails/addSourceStep.tsx, src/pages/costModelsDetails/addSourceWizard.tsx, src/pages/costModelsDetails/components/sourceTable.tsx, src/pages/costModelsDetails/components/table.styles.ts, src/pages/costModelsDetails/components/table.tsx
=> fix(costmodels): details page sources tab fit and finish

src/api/azureReports.ts, src/components/reports/azureReportSummary/azureReportSummaryDetails.tsx
This adds a temporary workaround to show usage values.
Fixes https://github.com/project-koku/koku-ui/issues/1080
Currently, the Azure instance-types API returns a single property for meta total usage, where we typically expect value and units. See https://github.com/project-koku/koku/issues/1387
Example
=> Azure usage values

src/components/reports/awsReportSummary/awsReportSummaryDetails.styles.ts, src/components/reports/awsReportSummary/awsReportSummaryDetails.tsx, src/components/reports/azureReportSummary/azureReportSummaryDetails.styles.ts, src/components/reports/azureReportSummary/azureReportSummaryDetails.tsx, src/components/reports/ocpOnAwsReportSummary/ocpOnAwsReportSummaryDetails.styles.ts, src/components/reports/ocpOnAwsReportSummary/ocpOnAwsReportSummaryDetails.tsx, src/pages/awsDashboard/awsDashboardWidget.tsx, src/pages/azureDashboard/azureDashboardWidget.tsx, src/pages/ocpOnAwsDashboard/ocpOnAwsDashboardWidget.tsx, src/store/awsDashboard/awsDashboardCommon.ts, src/store/awsDashboard/awsDashboardWidgets.ts, src/store/azureDashboard/azureDashboardCommon.ts, src/store/azureDashboard/azureDashboardWidgets.ts, src/store/ocpOnAwsDashboard/ocpOnAwsDashboardCommon.ts, src/store/ocpOnAwsDashboard/ocpOnAwsDashboardWidgets.ts
Added a `usageFormatOptions` property to format cost and usage values separately. This allows the compute and storage cards to show 2 decimal places for cost, while the usage value continues to have zero decimal places.
Fixes https://github.com/project-koku/koku-ui/issues/1087
=> Skip rounding up cost for compute and storage cards

src/pages/awsDetails/awsDetails.tsx, src/pages/awsDetails/detailsTable.tsx, src/pages/awsDetails/detailsToolbar.tsx, src/pages/awsDetails/exportModal.tsx, src/pages/awsDetails/groupBy.tsx, src/pages/azureDetails/azureDetails.tsx, src/pages/azureDetails/detailsTable.tsx, src/pages/azureDetails/detailsToolbar.tsx, src/pages/azureDetails/exportModal.tsx, src/pages/azureDetails/groupBy.tsx, src/pages/ocpDetails/detailsActions.tsx, src/pages/ocpDetails/detailsTable.tsx, src/pages/ocpDetails/detailsToolbar.tsx, src/pages/ocpDetails/exportModal.tsx, src/pages/ocpDetails/groupBy.tsx, src/pages/ocpDetails/ocpDetails.tsx, src/pages/ocpOnAwsDetails/detailsTable.tsx, src/pages/ocpOnAwsDetails/detailsToolbar.tsx, src/pages/ocpOnAwsDetails/exportModal.tsx, src/pages/ocpOnAwsDetails/groupBy.tsx, src/pages/ocpOnAwsDetails/ocpOnAwsDetails.tsx
This updates the details pages to show 'Others' when applying group_by tag keys. 
Fixes https://github.com/project-koku/koku-ui/issues/1090
In the example below, selecting the 'environment' tag in the group-by dropdown results in showing 'no-environment' in the table results.
Note: When applying the 'environment' tag; for example, I see 'no-environment' in the results. I can reproduce this with AWS, Azure, and OpenShift on AWS; however, I do not see this behavior with OpenShift.
=> Show 'Others' when applying group_by tag keys

src/pages/onboardingModal/configure/index.ts, src/pages/onboardingModal/configure/instructions.tsx
closes #1070 
In regard to the text copied to the clipboard, I couldn't reproduce this and I'm using Firefox. Maybe you're using a different browser?
Thanks.
=> fix(onboarding): use cluster id in the contrab command

src/app.tsx, src/locales/en.json
Simply renames "OpenShift on Cloud" as "OpenShift Cloud Infrastructure"
Fixes https://github.com/project-koku/koku-ui/issues/1085
Overview
Details
=> Rename "OpenShift on cloud" as "OpenShift Cloud Infrastructure"

src/pages/azureDashboard/azureDashboardWidget.tsx
This change adds a workaround for an unexpected `usage` property format.
Currently, the Azure instance-types API returns a single property for meta total usage, where we typically expect value and units. See project-koku/koku#1387
Fixes https://github.com/project-koku/koku-ui/issues/1058
=> Azure overview bars show zero percentages

src/components/reports/awsReportSummary/awsReportSummaryDetails.tsx, src/components/reports/azureReportSummary/azureReportSummaryDetails.tsx, src/components/reports/ocpOnAwsReportSummary/ocpOnAwsReportSummaryDetails.tsx, src/pages/awsDashboard/awsDashboardWidget.tsx, src/pages/azureDashboard/azureDashboardWidget.tsx, src/pages/ocpOnAwsDashboard/ocpOnAwsDashboardWidget.tsx, src/store/awsDashboard/awsDashboardCommon.ts, src/store/awsDashboard/awsDashboardWidgets.ts, src/store/azureDashboard/azureDashboardCommon.ts, src/store/azureDashboard/azureDashboardWidgets.ts, src/store/ocpOnAwsDashboard/ocpOnAwsDashboardCommon.ts, src/store/ocpOnAwsDashboard/ocpOnAwsDashboardWidgets.ts
Show usage first (i.e., the hero number) for compute and storage cards -- cost is secondary
Fixes https://github.com/project-koku/koku-ui/issues/1088
OpenShift on Aws
Aws
Azure
=> Cards: Show hero number first

src/locales/en.json
=> fix(costmodels): update wizard texting

src/api/providers.ts, src/pages/createCostModelWizard/api.ts
closes #1128 
Use the cost_models data from the response of providers API instead of doing N+1 calls.
=> feat(costmodels): get provider's cost models from /providers API

src/locales/en.json, src/pages/createCostModelWizard/review.tsx
=> fix(costmodels): Make create and back bold text in the review step

src/pages/awsDetails/awsDetails.tsx, src/pages/azureDetails/azureDetails.tsx, src/pages/ocpDetails/ocpDetails.tsx, src/pages/ocpOnAwsDetails/ocpOnAwsDetails.tsx
Fix filter by tag feature, which currently generates a 400 error. This problem was introduced when adding the "or:" prefix to each tag key.
Fixes https://github.com/project-koku/koku-ui/issues/1131
=> Fix filter by tag 400 error

src/components/charts/costChart/costChart.styles.ts, src/components/charts/usageChart/usageChart.styles.ts
Legend symbols for cost and Infrastructure cost should be the same previous month, grey color
Fixes https://github.com/project-koku/koku-ui/issues/1139
=> Legend color does not match

src/pages/overview/overview.tsx
Adds white spacing between sections to the overview description pop up.
Fixes https://github.com/project-koku/koku-ui/issues/1140
=> Add white space to overview description pop up

src/pages/costModelsDetails/header.tsx
=> fix(costmodels): Move header description to popover

src/api/ocpOnCloudQuery.ts, src/locales/en.json, src/store/ocpOnCloudDashboard/ocpOnCloudDashboardCommon.ts, src/store/ocpOnCloudDashboard/ocpOnCloudDashboardWidgets.ts
This removes the invalid Azure service_name filter from the /all/ API used for the Ocp on cloud overview tab. We should append the following strings to the existing AWS service filter instead.
```
'Database,Cosmos DB,Cache for Redis' +
'Virtual Network,VPN,DNS,Traffic Manager,ExpressRoute,Load Balancer,Application Gateway'
```
Filters https://github.com/project-koku/koku-ui/issues/1188
=> Remove service_name from Ocp on cloud filter

src/locales/en.json, src/pages/createCostModelWizard/index.tsx, src/pages/createCostModelWizard/markup.tsx
closes #1159 
This patch sets a default value to Markup and adds "(optional)" to the title of the step.
By doing so the user is no longer forced to specify Markup unless he/she needs to.
=> feat(costmodels): markup is optional on creating cost model

src/components/filter/filterComposition.tsx, src/locales/en.json, src/pages/costModelsDetails/components/markup.tsx
closes #1193 
closes #1077
Current text: "We are looking for your sources. Do not refresh the browser"
Revision: "Searching for your sources; do not refresh your browser."  (Searching or Looking is fine I think)
Same for OCP.
Revision suggestion: "Select the metric you want to assign a price to, and specify a measurement unit and rate. You can set one rate per metric in a price list."
=> Cost models fix typos and update wording - fit & finish

src/components/charts/costChart/costChart.tsx, src/components/charts/trendChart/trendChart.tsx, src/components/charts/usageChart/usageChart.tsx
This moves chart titles, in the overview pages, from the legend to above the chart.
Mock: https://marvelapp.com/1jj511j6/screen/63870434
Fixes https://github.com/project-koku/koku-ui/issues/1198
Ocp on cloud
Ocp
Aws
Azure
=> Move titles above charts

src/components/details/tertiaryNav.tsx, src/locales/en.json, src/pages/awsDetails/detailsHeader.tsx, src/pages/azureDetails/detailsHeader.tsx
Modified the tertiary navigation, for the "Cloud details" page, to use standard font size. (This was overridden because it replaced the page title.) Then, added "Cloud details" as a title above the tertiary nav.
Fixes https://github.com/project-koku/koku-ui/issues/1112
Before
After
=> Update cloud details tertiary navigation

src/components/state/loadingState/loadingState.tsx
Added a PatternFly spinner to the details page loading state. This replaces the existing binocular icon.
Fixes https://github.com/project-koku/koku-ui/issues/1186
=> Add spinner to details loading state

src/pages/ocpCloudDashboard/ocpCloudDashboardWidget.tsx, src/pages/ocpCloudDetails/detailsHeader.tsx, src/pages/ocpCloudDetails/detailsTable.tsx, src/pages/ocpCloudDetails/detailsWidgetModalView.tsx, src/pages/ocpCloudDetails/detailsWidgetView.tsx, src/pages/ocpCloudDetails/historicalChart.tsx
For Ocp cloud infrastructure, we should display cost instead of infrastructure_cost, which omits markup cost.
Fixes https://github.com/project-koku/koku-ui/issues/1206
=> Show cost instead of infrastructure_cost, which omits markup cost

src/locales/en.json, src/pages/awsDetails/detailsTable.tsx, src/pages/azureDetails/detailsTable.tsx, src/pages/ocpCloudDetails/detailsTable.tsx, src/pages/ocpDetails/detailsTable.tsx, src/utils/dateRange.ts
This change shows the previous cost instead of a delta (i.e., the change since date).
Mock: https://marvelapp.com/1jj511j6/screen/64401384
Fixes https://github.com/project-koku/koku-ui/issues/1093
Note: did not implement the following. That depends on project-koku/koku#1395
- If the previous month was null, then we would not show it at all and just show the previous month’s amount — API change needed!
Aws details:
Azure details:
Ocp details (no change):
=> Change delta to show previous cost

src/api/ocpCloudReports.ts, src/components/reports/awsReportSummary/awsReportSummary.tsx, src/components/reports/awsReportSummary/awsReportSummaryAlt.tsx, src/components/reports/azureReportSummary/azureReportSummary.tsx, src/components/reports/azureReportSummary/azureReportSummaryAlt.tsx, src/components/reports/ocpCloudReportSummary/__snapshots__/ocpCloudReportSummaryDetails.test.tsx.snap, src/components/reports/ocpCloudReportSummary/ocpCloudReportSummary.tsx, src/components/reports/ocpCloudReportSummary/ocpCloudReportSummaryAlt.tsx, src/components/reports/ocpCloudReportSummary/ocpCloudReportSummaryDetails.tsx, src/components/reports/ocpReportSummary/ocpReportSummary.tsx, src/components/reports/ocpReportSummary/ocpReportSummaryAlt.tsx, src/components/reports/ocpReportSummary/ocpReportSummaryDetails.tsx, src/locales/en.json, src/pages/awsDetails/detailsTable.tsx, src/pages/azureDetails/detailsTable.tsx, src/pages/ocpCloudDetails/detailsHeader.styles.ts, src/pages/ocpCloudDetails/detailsHeader.tsx, src/pages/ocpCloudDetails/detailsTable.tsx, src/pages/ocpDetails/detailsHeader.styles.ts, src/pages/ocpDetails/detailsHeader.tsx, src/pages/ocpDetails/detailsTable.tsx, src/utils/getComputedOcpCloudReportItems.ts
Added "Ocp cloud infrastructure" tooltips and popover to show total cost breakdown. This appears similar to the Ocp tooltips and popover.
Fixes https://github.com/project-koku/koku-ui/issues/1207
Ocp cloud infrastructure overview:
Ocp cloud infrastructure details:
=> Ocp cloud infrastructure tooltips

src/pages/ocpCloudDetails/detailsChart.tsx, src/pages/ocpDetails/detailsChart.tsx
We want to always show bullet chart legends, even if data is not available. This will help show what data is expected instead of seeing an empty bullet chart without legends.
Fixes https://github.com/project-koku/koku-ui/issues/963
=> Always show bullet chart legends

src/pages/awsDetails/awsDetails.tsx, src/pages/azureDetails/azureDetails.tsx, src/pages/ocpCloudDetails/ocpCloudDetails.tsx, src/pages/ocpDetails/ocpDetails.tsx
We should use PatternFly's compact pagination controls for each details page.
Fixes #1223
=> Use compact pagination controls for details

src/api/ocpQuery.ts, src/api/ocpReports.ts, src/locales/en.json, src/pages/ocpDetails/detailsToolbar.tsx, src/pages/ocpDetails/filterBy.styles.ts, src/pages/ocpDetails/filterBy.tsx, src/pages/ocpDetails/ocpDetails.tsx, src/utils/getComputedOcpReportItems.ts
Filter by many things in details (not only the main dimension). 
Users want the ability to filter on additional projects, clusters, nodes, and tag keys. Although, the table results do not show tags in its columns, this hack will provide the requested functionality.
Fixes https://github.com/project-koku/koku-ui/issues/1219
Mock: https://user-images.githubusercontent.com/17481322/69057929-a1cb4900-09e0-11ea-8ecd-8205e9c3c0f2.png
Demo:
Note: The following issues will need to be addressed server-side
project-koku/koku#1589
project-koku/koku#1596
=> Ocp details: Filter by many things

src/api/awsQuery.ts, src/api/awsReports.ts, src/locales/en.json, src/pages/awsDetails/awsDetails.tsx, src/pages/awsDetails/detailsToolbar.tsx, src/pages/awsDetails/filterBy.styles.ts, src/pages/awsDetails/filterBy.tsx, src/utils/getComputedAwsReportItems.ts
Filter by many things in details (not only the main dimension). 
Users want the ability to filter on additional projects, clusters, nodes, and tag keys. Although, the table results do not show tags in its columns, this hack will provide the requested functionality.
Fixes https://github.com/project-koku/koku-ui/issues/1220
Mock: https://user-images.githubusercontent.com/17481322/69057929-a1cb4900-09e0-11ea-8ecd-8205e9c3c0f2.png
Demo:
Note: The following issues will need to be addressed server-side
project-koku/koku#1589
project-koku/koku#1596
=> Aws details: Filter by many things

src/locales/en.json, src/pages/costModelsDetails/addSourceWizard.tsx, src/pages/createCostModelWizard/generalInformation.tsx, src/pages/createCostModelWizard/steps.tsx
=> feat(costmodels): add Azure type to cost model

src/pages/azureDetails/filterBy.tsx, src/pages/azureDetails/groupBy.tsx, src/pages/ocpCloudDetails/filterBy.tsx, src/pages/ocpCloudDetails/groupBy.tsx
Currently we HTML escape the filter / group_by option labels on the AWS details and Ocp cloud details pages.
This was a workaround for:
project-koku/nise#169
Fixes https://github.com/project-koku/koku-ui/issues/1233
=> Remove HTML escape for filter option label

src/pages/ocpCloudDetails/detailsChart.tsx
Removes special code showing negative numbers for unused requested capacity.
Kubernetes won't allow the number of requests to exceed capacity; thus, this calculation can be simplified.
Fixes https://github.com/project-koku/koku-ui/issues/1232
=> Simplify calculation for unused requested capacity

src/components/charts/costChart/costChart.tsx, src/components/charts/historicalCostChart/historicalCostChart.tsx, src/components/charts/historicalTrendChart/historicalTrendChart.tsx, src/components/charts/historicalUsageChart/historicalUsageChart.tsx, src/components/charts/trendChart/trendChart.tsx, src/components/charts/usageChart/usageChart.tsx
Fixed chart names in order to display the correct custom tooltips.
Fixes #1238
Overview usage chart
Historical charts
=> Overview card tooltips missing usage/request info

src/pages/awsDetails/detailsTagModal.tsx, src/pages/azureDetails/detailsTagModal.tsx, src/pages/ocpCloudDetails/detailsTagModal.tsx, src/pages/ocpDetails/detailsTagModal.tsx
Modified the modal width to use 50% of window.
Fixes https://github.com/project-koku/koku-ui/issues/1239
=> "View all tags" title does not fit into the dialog

src/api/awsQuery.ts, src/api/azureQuery.ts, src/api/ocpCloudQuery.ts, src/api/ocpQuery.ts
For the details report query, the logical AND prefix is not being applied to multiple keys within the same group_by.
`group_by[and:project]=cost&group_by[and:project]=management`
Fixes https://github.com/project-koku/koku-ui/issues/1245
=> Details report query: Logical AND prefix not applied

src/pages/awsDetails/detailsTable.tsx, src/pages/azureDetails/detailsTable.tsx, src/pages/ocpCloudDetails/detailsTable.tsx, src/pages/ocpDetails/detailsTable.tsx
Show item empty state based on percentage string
Fixes https://github.com/project-koku/koku-ui/issues/1241
=> Deltas show incorrectly when there is no change

src/locales/en.json, src/pages/costModelsDetails/costModelsDetails.tsx, src/pages/costModelsDetails/costModelsTable.tsx, src/pages/costModelsDetails/sort.test.ts, src/pages/costModelsDetails/sort.ts
=> feat(costmodels): add source_type sortable column to the table

src/pages/ocpCloudDetails/detailsChart.tsx, src/pages/ocpDetails/detailsChart.tsx
The bullet chart invalid prop warning, in the browser console, is eliminated by adding a default domain.
Fixes https://github.com/project-koku/koku-ui/issues/1251
=> Bullet chart: Invalid prop type warning

src/pages/azureDetails/detailsToolbar.tsx
Fixed typo with the localized strings used for Azure's filtering chips
Fixes https://github.com/project-koku/koku-ui/issues/1254
=> Azure details filtering localized strings

src/locales/en.json
#1259 and related to https://github.com/project-koku/koku/pull/1592
We use the source type from server to translate text. Since AZURE was changed to Azure, I had to update `en.json`.
=> fix(costmodel,sources): Update AZURE to Azure

src/locales/en.json, src/pages/awsDetails/detailsTable.tsx, src/pages/azureDetails/detailsTable.tsx, src/pages/ocpCloudDetails/detailsTable.tsx, src/pages/ocpDetails/detailsTable.tsx, src/utils/dateRange.ts
When the "month over month change" delta is null, we want to show "No data available for 1-20 Dec", instead of "$0.00 for 1-20 Dec".
Azure
Ocp details
=> Add "no data available" text

package.json
Added webpack stats target to view package structure. 
The generated stats file can be viewed below
http://chrisbateman.github.io/webpack-visualizer/
=> Added webpack stats target

src/pages/costModelsDetails/costModelInfo/header.tsx
bugfix #1257 
Replace the `Flex` layout by `Split` to make sure the kebab option and the description are going to be on the same row.
=> fix(costmodels): kebab option stays on the right corner if desc long

src/api/ocpCloudQuery.ts, src/api/query.ts, src/components/details/detailsDataToolbar.styles.ts, src/components/details/detailsDataToolbar.tsx, src/pages/ocpCloudDetails/detailsToolbar.tsx, src/utils/getComputedOcpCloudReportItems.ts
This moves the new data toolbar to the components directory. This will help us reuse the component and custom tag filtering code for all details pages.
See https://github.com/project-koku/koku-ui/issues/1275
=> Move the new data toolbar to the components directory

src/api/awsQuery.ts, src/api/azureQuery.ts, src/api/ocpCloudQuery.ts, src/api/ocpQuery.ts, src/api/query.ts, src/components/details/detailsDataToolbar.tsx, src/pages/awsDetails/awsDetails.tsx, src/pages/awsDetails/detailsTable.tsx, src/pages/awsDetails/exportModal.tsx, src/pages/awsDetails/groupBy.tsx, src/pages/azureDetails/azureDetails.tsx, src/pages/azureDetails/detailsTable.tsx, src/pages/azureDetails/exportModal.tsx, src/pages/azureDetails/groupBy.tsx, src/pages/ocpCloudDetails/detailsChart.tsx, src/pages/ocpCloudDetails/detailsTable.tsx, src/pages/ocpCloudDetails/exportModal.tsx, src/pages/ocpCloudDetails/groupBy.tsx, src/pages/ocpCloudDetails/ocpCloudDetails.tsx, src/pages/ocpDetails/detailsActions.tsx, src/pages/ocpDetails/detailsChart.tsx, src/pages/ocpDetails/detailsTable.tsx, src/pages/ocpDetails/exportModal.tsx, src/pages/ocpDetails/groupBy.tsx, src/pages/ocpDetails/ocpDetails.tsx
This eliminates the "invalid prop domain" error with bullet chart when there is no data (i.e., when all values are zero). 
This is best seen when grouping by tag, then expand the others category (e.g., "no-app"). There should be no errors in the browser console.
https://github.com/project-koku/koku-ui/issues/1284
=> Bullet chart: Invalid prop domain

src/locales/en.json, src/pages/ocpCloudDetails/detailsWidget.tsx
Since the Ocp cloud infrastructure details page now includes AWS and Azure data, we need to remove the "AWS" prefix from the "top projects/services/accounts" widget.
https://github.com/project-koku/koku-ui/issues/1283
=> Removed AWS prefix from Ocp cloud infrastructure details widget

src/components/details/detailsDataToolbar.tsx
The data toolbar filter should not accept empty strings.
https://github.com/project-koku/koku-ui/issues/1282
=> Filter fails if filter field is empty

src/pages/costModelsDetails/costModelInfo/header.tsx, src/pages/costModelsDetails/costModelsDetails.styles.ts
related #1257 and https://github.com/patternfly/patternfly-react/issues/3598
This is a workaround to a long description in the header (in the cost model info page).
Setting width to 97% and wrapping the text in the description part fixes this.
=> fix(costmodels): wrap description text in the header

src/components/details/detailsDataToolbar.tsx
As a workaround, we set the width for the PatternFly Select component. We just need to wrap the select menu with `DataToolbarItem` and the `width` prop can be removed.
https://github.com/project-koku/koku-ui/issues/1292
=> Data toolbar must wrap Select with DataToolbarItem

src/components/state/errorState/errorState.tsx, src/locales/en.json
We already handle the not authorized state. However, I've updated the icon and message per the latest mock.
https://github.com/project-koku/koku-ui/issues/885
=> Updated not authorized message

src/api/ocpCloudReports.ts, src/api/ocpReports.ts, src/utils/getComputedOcpCloudReportItems.ts, src/utils/getComputedOcpReportItems.ts
As a first step to fixing the cluster names, I'm updating the details pages to use new clusters array instead of deprecated cluster_alias.
https://github.com/project-koku/koku-ui/issues/1294
=> Update details to use clusters array

README.md, config/spandx.config.local.js, src/utils/getComputedAwsReportItems.ts, src/utils/getComputedAzureReportItems.ts, src/utils/getComputedOcpCloudReportItems.ts, src/utils/getComputedOcpReportItems.ts, src/utils/getItemLabel.ts
* Utility function to see if "tag:" prefixed entry exist on tag group_by
* Update report items logic to use utility function
* Update SPANDX config for running local koku with latest insights-proxy
* Update README with overview link
This handles the following special case:
https://github.com/project-koku/koku/pull/1690
=> Update to handle special case where tag key collides with keywords.

src/store/awsReports/awsReportsActions.ts, src/store/azureReports/azureReportsActions.ts, src/store/ocpCloudReports/ocpCloudReportsActions.ts, src/store/ocpReports/ocpReportsActions.ts
The API cost reports no longer return multiple months of data. Thus, we can omit calling the dropCurrentMonthData util to remove unused data for now.
https://github.com/project-koku/koku-ui/issues/1312
=> Disable dropCurrentMonthData util

src/api/awsQuery.ts, src/api/azureQuery.ts, src/api/ocpCloudQuery.ts, src/api/ocpQuery.ts, src/api/query.ts, src/components/details/detailsDataToolbar.tsx, src/pages/awsDetails/awsDetails.tsx, src/pages/awsDetails/detailsTable.tsx, src/pages/awsDetails/exportModal.tsx, src/pages/awsDetails/groupBy.tsx, src/pages/azureDetails/azureDetails.tsx, src/pages/azureDetails/detailsTable.tsx, src/pages/azureDetails/exportModal.tsx, src/pages/azureDetails/groupBy.tsx, src/pages/ocpCloudDetails/detailsTable.tsx, src/pages/ocpCloudDetails/exportModal.tsx, src/pages/ocpCloudDetails/groupBy.tsx, src/pages/ocpCloudDetails/ocpCloudDetails.tsx, src/pages/ocpDetails/detailsActions.tsx, src/pages/ocpDetails/detailsTable.tsx, src/pages/ocpDetails/exportModal.tsx, src/pages/ocpDetails/groupBy.tsx, src/pages/ocpDetails/ocpDetails.tsx, src/utils/getItemLabel.ts
Replaced logical AND with OR when generating group_by query params. Also renamed tagKey as tagKeyPrefix.
This should allow us to filter by any group_by combination.
Note: API functionality already exists to apply logical AND between unique group_by categories.
https://github.com/project-koku/koku-ui/issues/1298
=> Replace logical AND with OR

src/components/state/errorState/errorState.tsx
Want to show the message below for both 401 and 403 error status codes.
https://github.com/project-koku/koku-ui/issues/885
=> Error message for unauthorized 401 / not entitled 403

src/locales/en.json
related to #1321 
Added the missing "source" key in en.json.
=> fix(costmodel): add missing translation in the review step

src/pages/details/components/toolbar/toolbar.tsx
Added workaround is to return `null` instead of relying on the `showToolbarItem` prop of `DataToolbarFilter`. This resolves the "maximum update depth exceeded" issue by lazily rendering each `DataToolbarFilter`.
https://github.com/project-koku/koku-ui/issues/1326
Note: While testing this fix, I discovered a separate API issue when grouping by tag. See https://github.com/project-koku/koku/issues/1773
=> DataToolbarFilter: Maximum update depth exceeded

package.json, src/pages/details/awsDetails/detailsToolbar.tsx, src/pages/details/awsDetails/groupBy.tsx, src/pages/details/azureDetails/detailsToolbar.tsx, src/pages/details/azureDetails/groupBy.tsx, src/pages/details/components/toolbar/toolbar.tsx, src/pages/details/ocpCloudDetails/detailsToolbar.tsx, src/pages/details/ocpCloudDetails/groupBy.tsx, src/pages/details/ocpDetails/detailsToolbar.tsx, src/pages/details/ocpDetails/groupBy.tsx
This fixes a couple issues with the details toolbar.
1. Don't show a tags category when there are no tags
2. The tag filter chips should remain visible when a new category is selected
https://github.com/project-koku/koku-ui/issues/1334
https://github.com/project-koku/koku-ui/issues/1335
Note: the "clear all filters" link may remain in view, due to the workaround for https://github.com/patternfly/patternfly-react/issues/3770#issuecomment-589071250
=> Details: Toolbar fixes

src/api/providers.test.ts, src/api/providers.ts
* Removing providers endpoint soon to avoid confusing with sources
* Sources endpoint was updated to provide the same support the providers endpoint had.
Image shows local run with calls to the Sources API
=> Switch from providers to sources API endpoint as providers will be removed.

src/pages/createCostModelWizard/Datatoolbar.test.tsx, src/pages/createCostModelWizard/Datatoolbar.tsx
After updating patternfly/react-core - I can test Datatoolbar.
These are tests for price list toolbar.
=> fix(costmodel): add unit test to price list data toolbar

src/locales/en.json, src/pages/dashboard/ocpCloudDashboard/ocpCloudDashboardWidget.test.tsx, src/pages/dashboard/ocpCloudDashboard/ocpCloudDashboardWidget.tsx, src/store/dashboard/ocpCloudDashboard/__snapshots__/ocpCloudDashboard.test.ts.snap, src/store/dashboard/ocpCloudDashboard/ocpCloudDashboard.test.ts, src/store/dashboard/ocpCloudDashboard/ocpCloudDashboardCommon.ts, src/store/dashboard/ocpCloudDashboard/ocpCloudDashboardWidgets.ts
For the infrastructure overview (i.e., the "All filtered by OpenShift" view), we want to show top services, accounts, and regions in the cost card instead of projects, nodes, & clusters.
https://github.com/project-koku/koku-ui/issues/1387
=> Infrastructure overview to show top services, accounts, & regions

src/routes.tsx
Added routes to support the new navigation panel. This will ensure the Insights nav panel works properly when promoted. 
The new navigation panel will appear as follows.
```
Overview
Details
> OpenShift
> Infrastructure
Cost models
```
The new routes will look like this:
```
/details/infrastructure/aws
/details/infrastructure/azure
/details/infrastructure/ocp-cloud
/details/ocp
```
And `/details/infrastructure` will redirect to `/details/infrastructure/aws`
Note: Keeping the old routes until Insights updates the nav panel. 
https://github.com/project-koku/koku-ui/issues/1390
=> Add routes for new navigation panel

src/components/reports/reportSummary/reportSummaryDetails.tsx, src/locales/en.json, src/pages/dashboard/components/dashboardWidgetBase.tsx, src/pages/details/awsDetails/detailsHeader.tsx, src/pages/details/awsDetails/detailsTable.tsx, src/pages/details/azureDetails/detailsHeader.tsx, src/pages/details/azureDetails/detailsTable.tsx, src/pages/details/ocpCloudDetails/detailsHeader.tsx, src/pages/details/ocpCloudDetails/detailsTable.tsx, src/pages/details/ocpDetails/detailsHeader.tsx, src/pages/details/ocpDetails/detailsTable.tsx, src/store/dashboard/awsCloudDashboard/awsCloudDashboardWidgets.ts, src/store/dashboard/awsDashboard/awsDashboardWidgets.ts, src/store/dashboard/azureCloudDashboard/azureCloudDashboardWidgets.ts, src/store/dashboard/azureDashboard/azureDashboardWidgets.ts, src/store/dashboard/common/dashboardCommon.ts, src/store/dashboard/ocpCloudDashboard/ocpCloudDashboardWidgets.ts, src/store/dashboard/ocpDashboard/ocpDashboardWidgets.ts, src/store/dashboard/ocpSupplementaryDashboard/ocpSupplementaryDashboardWidgets.ts, src/store/dashboard/ocpUsageDashboard/ocpUsageDashboardWidgets.ts
Removed the cumulative cost tooltip from Infrastructure overview. The only cumulative cost tooltip that should be displayed is for the Ocp overview.
Also added better testing for the new `report.meta.total.cost.total` object -- that change caused the UI to crash while APIs are being updated.
=> Remove tooltip from Infrastructure overview

src/locales/en.json
Updated the supplementary cost description in the info popup, shown in Ocp details.
https://github.com/project-koku/koku-ui/issues/1396
=> Updated the supplementary cost description in Ocp details

src/pages/dashboard/awsCloudDashboard/awsCloudDashboardWidget.tsx, src/pages/dashboard/awsDashboard/awsDashboardWidget.tsx, src/pages/dashboard/azureCloudDashboard/azureCloudDashboardWidget.tsx, src/pages/dashboard/azureDashboard/azureDashboardWidget.tsx, src/pages/dashboard/components/dashboardWidgetBase.tsx, src/pages/dashboard/ocpCloudDashboard/ocpCloudDashboardWidget.tsx, src/pages/dashboard/ocpDashboard/ocpDashboardWidget.tsx, src/pages/dashboard/ocpSupplementaryDashboard/ocpSupplementaryDashboardWidget.tsx, src/pages/dashboard/ocpUsageDashboard/ocpUsageDashboardWidget.tsx
Reusing the existing DashboardWidgetOwnProps & DashboardWidgetStateProps interfaces for each dashboard widget -- cleans things up a bit
https://github.com/project-koku/koku-ui/issues/1400
=> Reuse DashboardWidgetOwnProps & DashboardWidgetStateProps interfaces

src/locales/en.json
Renamed the "All filtered by OpenShift" overview perspective as "All cloud filtered by OpenShift"
https://github.com/project-koku/koku-ui/issues/1404
=> Rename overview perspective as "All cloud filtered by OpenShift"

src/pages/dashboard/awsCloudDashboard/awsCloudDashboardWidget.tsx, src/pages/dashboard/awsDashboard/awsDashboardWidget.tsx, src/pages/dashboard/azureCloudDashboard/azureCloudDashboardWidget.tsx, src/pages/dashboard/azureDashboard/azureDashboardWidget.tsx, src/pages/dashboard/components/dashboardBase.tsx, src/pages/dashboard/components/dashboardWidgetBase.tsx, src/pages/dashboard/ocpCloudDashboard/ocpCloudDashboardWidget.tsx, src/pages/dashboard/ocpDashboard/ocpDashboardWidget.tsx, src/pages/dashboard/ocpSupplementaryDashboard/ocpSupplementaryDashboardWidget.tsx, src/pages/dashboard/ocpUsageDashboard/ocpUsageDashboardWidget.tsx, src/store/dashboard/awsCloudDashboard/awsCloudDashboardWidgets.ts, src/store/dashboard/awsDashboard/awsDashboardWidgets.ts, src/store/dashboard/azureCloudDashboard/azureCloudDashboardWidgets.ts, src/store/dashboard/azureDashboard/azureDashboardWidgets.ts, src/store/dashboard/common/dashboardCommon.ts, src/store/dashboard/ocpCloudDashboard/ocpCloudDashboardWidgets.ts, src/store/dashboard/ocpDashboard/ocpDashboardWidgets.ts, src/store/dashboard/ocpSupplementaryDashboard/ocpSupplementaryDashboardWidgets.ts, src/store/dashboard/ocpUsageDashboard/ocpUsageDashboardWidgets.ts
Ensure all overview "view all..." links navigate correctly.
Also omit the "view all" links from the "filtered by OpenShift" overview pages. Only the following overview pages should show links.
- OpenShift > All
- Infrastructure > AWS
- Infrastructure > Azure
https://github.com/project-koku/koku-ui/issues/1406
=> Update overview "view all..." links

src/components/charts/historicalTrendChart/__snapshots__/historicalTrendChart.test.tsx.snap, src/components/charts/trendChart/__snapshots__/trendChart.test.tsx.snap, src/pages/dashboard/components/dashboardWidgetBase.tsx, src/utils/computedReport/getComputedReportItems.ts
Due to the recent supplementary API changes, we're not obtaining units correctly in the computed report items, used by the charts.
https://github.com/project-koku/koku-ui/issues/1402
=> Overview list items for cost don't show currency

src/api/reports/ocpReports.ts, src/components/charts/common/chartUtils.ts, src/pages/dashboard/components/dashboardWidgetBase.tsx, src/store/dashboard/awsCloudDashboard/awsCloudDashboardWidgets.ts, src/store/dashboard/awsDashboard/awsDashboardWidgets.ts, src/store/dashboard/azureCloudDashboard/azureCloudDashboardWidgets.ts, src/store/dashboard/azureDashboard/azureDashboardWidgets.ts, src/store/dashboard/common/dashboardCommon.ts, src/store/dashboard/ocpCloudDashboard/ocpCloudDashboard.test.ts, src/store/dashboard/ocpCloudDashboard/ocpCloudDashboardWidgets.ts, src/store/dashboard/ocpDashboard/ocpDashboard.test.ts, src/store/dashboard/ocpDashboard/ocpDashboardWidgets.ts, src/store/dashboard/ocpSupplementaryDashboard/ocpSupplementaryDashboardWidgets.ts, src/store/dashboard/ocpUsageDashboard/ocpUsageDashboardWidgets.ts, src/utils/computedReport/getComputedReportItems.ts
Refactored to show supplementary cost for "OpenShift supplementary" overview
This will use the same reports/openshift/costs/ API, but instead of grabbing the costs from cost we grab from supplementary.
https://github.com/project-koku/koku-ui/issues/1339
=> OpenShift supplementary overview

src/components/charts/common/chart.styles.ts, src/components/charts/costChart/costChart.styles.ts, src/components/charts/costChart/costChart.tsx, src/components/charts/historicalCostChart/historicalCostChart.styles.ts, src/components/charts/historicalCostChart/historicalCostChart.tsx, src/components/charts/historicalTrendChart/historicalTrendChart.styles.ts, src/components/charts/historicalTrendChart/historicalTrendChart.tsx, src/components/charts/historicalUsageChart/historicalUsageChart.styles.ts, src/components/charts/historicalUsageChart/historicalUsageChart.tsx, src/components/charts/trendChart/trendChart.styles.ts, src/components/charts/trendChart/trendChart.tsx, src/components/charts/usageChart/usageChart.styles.ts, src/components/charts/usageChart/usageChart.tsx, src/components/reports/reportSummary/reportSummaryItem.styles.ts, src/components/reports/reportSummary/reportSummaryItem.tsx
Moved `:not` selectors from style to className props. This fixes and issue where the CSS `overflow` is not being overridden, which hides the chart legends.
This was intended to be merged with https://github.com/project-koku/koku-ui/pull/1418.
https://github.com/project-koku/koku-ui/issues/1417
=> Moved :not selectors from style to className props

src/pages/details/awsDetails/awsDetails.tsx, src/pages/details/awsDetails/detailsHeader.tsx, src/pages/details/azureDetails/azureDetails.tsx, src/pages/details/azureDetails/detailsHeader.tsx, src/pages/details/ocpCloudDetails/detailsHeader.tsx, src/pages/details/ocpCloudDetails/ocpCloudDetails.tsx, src/pages/details/ocpDetails/detailsHeader.tsx, src/pages/details/ocpDetails/ocpDetails.tsx
This change ensures the details header component uses a paginated API request for total cost.
https://github.com/project-koku/koku-ui/issues/1373
=> Use paginated API request for header total cost

src/__snapshots__/app.test.tsx.snap, src/app.tsx, src/pages/dashboard/components/dashboardWidgetBase.tsx, src/pages/details/awsDetails/awsDetails.tsx, src/pages/details/azureDetails/azureDetails.tsx, src/pages/details/components/nav/tertiaryNav.tsx, src/pages/details/ocpCloudDetails/ocpCloudDetails.tsx, src/pages/details/ocpDetails/ocpDetails.tsx, src/routes.tsx, src/store/dashboard/awsDashboard/awsDashboardWidgets.ts, src/store/dashboard/azureDashboard/azureDashboardWidgets.ts, src/store/dashboard/common/dashboardCommon.ts, src/store/dashboard/ocpDashboard/ocpDashboardWidgets.ts
Implemented a workaround using redirects.
Attempted to flatten paths using `suppress_id:true` or `reload` in the main.yml of cloud-services-config. Forcing the path to be `/ocp` instead of `/details/ocp` also worked, but the Insights nav doesn't highlight when either property is used.
=> Added redirect workaround for Insights Nav

src/pages/details/awsDetails/awsDetails.tsx, src/pages/details/azureDetails/azureDetails.tsx, src/pages/details/ocpCloudDetails/ocpCloudDetails.tsx, src/pages/details/ocpDetails/ocpDetails.tsx, src/routes.tsx
Restored redirects (cleaner solution) in favor of a cloud-services-config fix. That is, I removed "paths" from main.yml of cloud-services-config -- Insights was not looking for the correct app
=> Restored redirects in favor of a cloud-services-config fix

src/api/reports/ocpUsageReports.test.ts, src/api/reports/ocpUsageReports.ts, src/components/charts/common/chartUtils.ts, src/components/charts/historicalCostChart/__snapshots__/historicalCostChart.test.tsx.snap, src/components/charts/historicalUsageChart/__snapshots__/historicalUsageChart.test.tsx.snap, src/pages/details/components/summary/summaryModalView.tsx, src/pages/details/ocpDetails/detailsTable.tsx, src/pages/details/ocpDetails/summary.tsx, src/store/dashboard/ocpSupplementaryDashboard/ocpSupplementaryDashboardWidgets.ts, src/utils/computedReport/getComputedReportItems.ts
The "Infrastructure > OpenShift usage" overview page should use the reports/openshift/costs API. In addition, we should use the infrastructure.usage property for these costs.
https://github.com/project-koku/koku-ui/issues/1446
=> Update Infrastructure > OpenShift usage API

src/components/charts/common/chartUtils.ts, src/components/charts/historicalCostChart/historicalCostChart.test.tsx, src/components/reports/reportSummary/reportSummaryDetails.tsx, src/pages/dashboard/components/dashboardWidgetBase.tsx, src/pages/details/ocpDetails/historicalChart.tsx, src/store/dashboard/awsCloudDashboard/awsCloudDashboardWidgets.ts, src/store/dashboard/awsDashboard/awsDashboardWidgets.ts, src/store/dashboard/azureCloudDashboard/azureCloudDashboardWidgets.ts, src/store/dashboard/azureDashboard/azureDashboardWidgets.ts, src/store/dashboard/common/dashboardCommon.ts, src/store/dashboard/ocpCloudDashboard/ocpCloudDashboardWidgets.ts, src/store/dashboard/ocpDashboard/ocpDashboardWidgets.ts, src/store/dashboard/ocpSupplementaryDashboard/ocpSupplementaryDashboardWidgets.ts, src/store/dashboard/ocpUsageDashboard/ocpUsageDashboardWidgets.ts, src/utils/computedReport/getComputedReportItems.ts
The Ocp Usage overview is not showing the correct cost. This page should should zero cost, right now.
For Ocp Usage, we want to use the meta prop `infrastructure.usage.value` as the total cost. However, for the Ocp overview, we still want to use the meta prop `cost.total.value` as the total cost, while using `infrastructure.total.value` for chart data.
https://github.com/project-koku/koku-ui/issues/1457
=> Ocp Usage overview not showing the correct cost

src/components/reports/reportSummary/reportSummaryDetails.tsx
The cost shown for the supplementary overview should be $0.00. We're still showing the cost prop instead of supplementary cost.
https://github.com/project-koku/koku-ui/issues/1459
=> Supplementary cost should be $0.00

src/components/reports/reportSummary/reportSummaryDetails.tsx, src/components/reports/reportSummary/reportSummaryItems.tsx, src/pages/dashboard/components/dashboardWidgetBase.tsx
The top project costs shown for the Ocp usage overview should be $0.00. We're still showing the cost prop instead of the meta's infrastructure.usage.value prop.
https://github.com/project-koku/koku-ui/issues/1461
=> 1461 ocp usage

src/components/charts/trendChart/trendChart.tsx, src/components/reports/reportSummary/reportSummaryDetails.tsx, src/locales/en.json, src/pages/dashboard/components/dashboardWidgetBase.tsx, src/pages/dashboard/ocpSupplementaryDashboard/ocpSupplementaryDashboardWidget.styles.ts, src/pages/dashboard/ocpSupplementaryDashboard/ocpSupplementaryDashboardWidget.tsx, src/store/dashboard/common/dashboardCommon.ts, src/store/dashboard/ocpSupplementaryDashboard/ocpSupplementaryDashboardWidgets.ts, src/utils/computedReport/getComputedReportItems.ts
Chart tooltip doesn’t always show the $ unit (e.g., shows as “0 infrastructure cost” or “350 infrastructure cost”).
#1468
=> Chart tooltips missing units

src/components/reports/reportSummary/reportSummaryDetails.styles.ts, src/components/reports/reportSummary/reportSummaryDetails.tsx, src/components/reports/reportSummary/reportSummaryItems.test.tsx, src/pages/dashboard/components/dashboardWidgetBase.tsx
Microsoft Azure chart is missing VM-hours for the hero number and storage services usage.
The backend APIs provide no units; thus, we must hard code something.
https://github.com/project-koku/koku-ui/issues/1469
=>  Microsoft Azure units label

src/components/reports/reportSummary/reportSummaryItem.styles.ts
The spacing between the progress bars is off.
https://github.com/project-koku/koku-ui/issues/1471
=> Progress bar margin

src/pages/overview/overview.tsx
If Ocp providers are not available, then we should show the infrastructure tab instead of Ocp.
https://github.com/project-koku/koku-ui/issues/1476
=> Initialize current overview tab

src/pages/details/awsDetails/awsDetails.tsx, src/pages/details/azureDetails/azureDetails.tsx, src/pages/details/ocpDetails/ocpDetails.tsx, src/routes.tsx
This was a request made by the Insights team to help debug their navigation pane.
While Insights works out the kinks, folks won't be able to navigate to the details pages.
https://github.com/project-koku/koku-ui/issues/1445
=> Remove route redirects

src/app.tsx
This PR fixes all navigation issues with going to details. There's also PR in clous-services-config so when users go to details the entire page won't redirect.
This way has limitations! If you'll add in future nav route with dynamic part `/details/ocp/:id` and in navigation there will be option to go to specific ID this won't work. But I don't expect dynamic routes in near future, just a disclaimer.
ping @kruai @ryelo @dlabrecq
=> Fix navigation issues by using correct pahts

src/pages/details/awsDetails/awsDetails.tsx, src/pages/details/azureDetails/azureDetails.tsx, src/pages/details/ocpDetails/ocpDetails.tsx, src/routes.tsx
Now that Insights has fixed the nav links, we can restore code temp disabled in order to help their investigation. 
https://github.com/project-koku/koku-ui/issues/1445
=> Restore temp disabled code

src/pages/details/components/groupBy/groupBy.tsx
The group-by for the Ocp details page does not appear to be initialized properly. The first item in the menu appears to be selected, while it should be showing "project".
https://github.com/project-koku/koku-ui/issues/1484
=> Group-by default selection

src/pages/overview/overview.tsx
Removed unused providers code from overview page. I don't see anything that calls `openProvidersModal`.
=> Removed unused providers code

src/components/reports/reportSummary/reportSummaryDetails.styles.ts
Overview units wrap oddly. For example, when resizing the window very small, `core-hours` looks odd when `core-` is on a line by itself. 
Adding a simple 'nowrap' style ensures `core-hours` appears on the same line.
https://github.com/project-koku/koku-ui/issues/1502
=> Overview units wrap oddly

src/components/charts/costChart/costChart.tsx, src/components/charts/historicalCostChart/historicalCostChart.tsx, src/components/charts/historicalTrendChart/historicalTrendChart.tsx, src/components/charts/historicalUsageChart/historicalUsageChart.tsx, src/components/charts/trendChart/trendChart.tsx, src/components/charts/usageChart/usageChart.tsx
Charts scale beyond card boundary when toggling Insights nav (i.e., the hamburger icon, top-left in page header). Added height and width to a div container wrapping the charts.
https://github.com/project-koku/koku-ui/issues/1493
=> Charts scale beyond cards when toggling Insights nav

src/api/exports/export.ts, src/locales/en.json, src/pages/details/components/export/exportModal.tsx, src/pages/details/components/export/exportSubmit.tsx, src/store/exports/__snapshots__/export.test.ts.snap, src/store/exports/export.test.ts, src/store/exports/exportActions.ts, src/store/exports/exportCommon.ts, src/store/exports/exportReducer.ts, src/store/exports/exportSelectors.ts, src/store/exports/index.ts
Refactored the details export functionality to better support the file naming convention described below.
>As a user I would like to see exports from the details pages have a better naming convention on files from exports. For example: app_name-details_name-date so cost-management-openshift-2020-04-14.csv
The resulting file names are shown below for the various details pages and group-by combinations.
FYI, the `js-file-download` code was moved from the store to the details page component, which allows us to customize the filename for each export. In addition, I added the ability to store reports by ID in order to fetch cached reports.
https://github.com/project-koku/koku-ui/issues/1497
=> Details pages export file naming convention

src/locales/en.json, src/pages/details/components/toolbar/toolbar.tsx
This removes the "Export" text associated with the toolbar icon. The button variant has also been changed from `link` to `plain`.
https://github.com/project-koku/koku-ui/issues/1496
=> Details page export button is not a button consistent across platform

src/pages/details/awsDetails/detailsToolbar.tsx, src/pages/details/azureDetails/azureDetails.tsx, src/pages/details/azureDetails/detailsToolbar.tsx, src/pages/details/components/toolbar/toolbar.tsx, src/pages/details/ocpCloudDetails/detailsToolbar.tsx, src/pages/details/ocpDetails/detailsToolbar.tsx
Replace workarounds for PatternFly's DataToolbarFilter with the new DataToolbarChipGroup interface.
https://github.com/project-koku/koku-ui/issues/1523
=> Update toolbar to use PF DataToolbarChipGroup interface

src/pages/details/components/groupBy/groupBy.tsx
The group-by menu may show the wrong default option.
https://github.com/project-koku/koku-ui/issues/1527
=> Group-by default option

src/pages/details/components/tag/tagModal.styles.ts
When there are only a few tags, the modal appears too large. Ideally, the modal would shrink to the height of its contents.
We had some style workarounds for PatternFly's isLarge / isSmall properties not working properly. We can remove those styles now.
https://github.com/project-koku/koku-ui/issues/1531
=> Remove tag modal islarge workaround

src/pages/details/components/historicalChart/historicalModal.styles.ts
We had some style workarounds for PatternFly's isLarge / isSmall properties not working properly. It appears that we can remove those styles now.
https://github.com/project-koku/koku-ui/issues/1533
=> Remove chart modal isLarge workaround

src/pages/overview/overview.tsx
Don't show "All cloud filtered by OpenShift" when there are no Ocp providers.
https://github.com/project-koku/koku-ui/issues/1536
=> Perspective offers choices that have no data

src/pages/details/awsDetails/detailsToolbar.tsx, src/pages/details/azureDetails/detailsToolbar.tsx, src/pages/details/components/toolbar/toolbar.tsx, src/pages/details/ocpCloudDetails/detailsToolbar.tsx, src/pages/details/ocpDetails/detailsToolbar.tsx
Seems i18next doesn't always translate when code is located outside of a component. For example, when refreshing the page or quickly navigating from one page to another.
https://github.com/project-koku/koku-ui/issues/1529
=> Ocp details shows i18n keys

src/components/charts/costChart/costChart.tsx, src/components/charts/trendChart/trendChart.tsx, src/components/charts/usageChart/usageChart.tsx
This resizes our charts (i.e., the width) upon Insight's new NAVIGATION_TOGGLE event
https://github.com/project-koku/koku-ui/issues/1504
=> Resize charts upon nav toggle event

src/pages/details/ocpDetails/detailsTable.tsx
Per today's backlog discussion, the team agreed we should remove the kebab option until the API can be updated.
https://github.com/project-koku/koku-ui/issues/1512
=> Remove view price list from kebab options

src/components/charts/costChart/costChart.tsx, src/components/charts/trendChart/trendChart.tsx, src/components/charts/usageChart/usageChart.tsx
Adjusted timeout to resize chart to 300ms. Previous attempt worked better, but could be a little longer for CI beta.
https://github.com/project-koku/koku-ui/issues/1504
=> Adjust timeout to resize chart to 300ms

src/components/charts/costChart/costChart.tsx, src/components/charts/trendChart/trendChart.tsx, src/components/charts/usageChart/usageChart.tsx
Adjusted timeout to resize chart to 500ms. Previous attempt worked better, but could be a little longer for CI beta.
#1504
=> Adjust timeout to resize chart to 500ms

src/app.tsx, src/components/state/maintenanceState/maintenanceState.styles.ts, src/components/state/maintenanceState/maintenanceState.tsx, src/locales/en.json
Added a full page for displaying maintenance state messages.
If the `maintenanceMode` flag is enabled, the providers API should error and the maintenance state is displayed; otherwise, pages will display normally. 
https://issues.redhat.com/browse/COST-47
=> Maintenance state

src/pages/costModels/costModelsDetails/addSourceStep.tsx, src/pages/costModels/createCostModelWizard/table.tsx
Remove the "Default cost model" string from all the sources that can be assigned. That way the user can easily see that the ones that are available has no cost model assigned to it and easier to see that those with a cost model attached to it cannot be selected.
=> fix(costmodel): make it easy to track unassigned sources in table

src/locales/en.json, src/pages/details/components/costChart/costChart.styles.ts, src/pages/details/components/costChart/costChart.tsx
Created custom label component to override the cost breakdown pie chart's legend layout, per mocks.
Mock https://marvelapp.com/616a7ba/screen/67774561
=> Override cost breakdown pie chart legend layout

src/components/state/loadingState/loadingState.styles.ts
Fixed style which forces loading state to be full page in wizard modal. Tested with overview and details pages -- the style isn't needed there anymore.
https://issues.redhat.com/browse/COST-139
=> Loading state forces modal to be full page

src/utils/computedReport/getComputedReportItems.ts
Whatever changed recently, the AWS and Azure pages are not rendering now without this fix.
=> Ensure dataPoint is not undefined

src/pages/details/awsDetails/detailsTable.styles.ts, src/pages/details/azureDetails/detailsTable.styles.ts, src/pages/details/ocpDetails/detailsTable.styles.ts
Adjust details table styles so the last 3 columns are right aligned per the pre-PatternFly v4 breaking change update.
https://issues.redhat.com/browse/COST-43
=> Adjust details table styles

src/pages/details/awsDetails/detailsTable.tsx, src/pages/details/components/actions/actions.tsx, src/pages/details/components/priceList/priceListModal.tsx, src/pages/details/ocpDetails/detailsTable.tsx, src/utils/computedReport/getComputedReportItems.ts
Refactored the details price list option to match UUID instead of cluster name. 
Note that this is only available for group_by cluster. And we've omitted AWS and Azure, since they don't have price lists yet.
See https://issues.redhat.com/browse/COST-266
**Ocp details**
**Existing price list modal**
=> Refactored the details price list option to match uuid instead of name

src/pages/costModels/costModel/header.tsx
Remove the `cmpRef` variable - this is no longer needed.
Change the component into a functional component.
=> refactor(costmodel): clean unnecessary code in cost model header

src/pages/costModels/costModelsDetails/addSourceWizard.tsx, src/pages/costModels/costModelsDetails/components/addRateModal.tsx, src/pages/costModels/costModelsDetails/components/updateMarkupDialog.tsx, src/pages/costModels/costModelsDetails/components/updateRateModel.tsx
Fix the following modals:
- assign sources
- edit markup
- edit rate
- add rate
=> fix(costmodels): reordered modal buttons correctly

src/pages/costModels/createCostModelWizard/index.tsx
Display the exit confirmation dialog in the following cases:
- Cost model type is Amazon or AWS and the user is in one of these steps: sources, review
- Cost model type is Openshift and the user is in one of these steps: markup, sources, review
- Cost model type is Openshift and the user is in the price list step and added at least one rate
=> fix(costmodels): show close dialog on wizard close if >20% is filled

src/pages/costModels/costModelsDetails/components/updateCostModel.tsx
Missed the edit cost model modal buttons.
This one will fix it and is part of the COST-280 ticket
=> fix(costmodel): change buttons order in update cost model modal

src/components/state/emptyFilterState/emptyFilterState.styles.ts, src/pages/details/awsDetails/detailsTable.tsx, src/pages/details/azureDetails/detailsTable.tsx, src/pages/details/ocpDetails/detailsTable.tsx
This ensures that the empty filter state appears within the table body. 
Currently, the component appears below the table. Seems to be a regression after updating to the PatternFly "breaking changes release".
https://issues.redhat.com/browse/COST-306
=> Empty filter state is positioned incorrectly

src/pages/costModels/costModelsDetails/components/dialog.test.tsx, src/pages/costModels/costModelsDetails/components/dialog.tsx, src/pages/costModels/createCostModelWizard/index.tsx
1) move the warning icon to the title
2) change the cancel button variation to "link"
=> fix(costmodels): update confirmation dialog's cancel and warning icon

src/components/state/noProvidersState/noProvidersState.styles.ts, src/pages/details/components/costOverview/costOverviewBase.tsx
Fixes the "no providers" state for ocp details. The empty state component shouldn't be at the bottom of the page.
=> Fixed no providers state for ocp details

src/api/queries/query.ts
When applying a tag filter in the details page, exporting a table row fails.
https://issues.redhat.com/browse/COST-168
=> Export fails when filtering tag key values

src/components/state/errorState/errorState.styles.ts, src/components/state/maintenanceState/maintenanceState.styles.ts
When filtering details tables, I noticed that the error state is positioned incorrectly. The component should not appear at the bottom of the page.
This regression seems to have occurred after updating to the PatternFly "breaking changes release". 
https://issues.redhat.com/browse/COST-306
=> Error state positioned incorrectly

koku-ui-manifest, package.json, yarn.lock
Dependabot is reporting websocket-extensions as a moderate severity vulnerability. We need to bump websocket-extensions to 0.1.4
Based on https://github.com/project-koku/koku-ui/pull/1604
https://issues.redhat.com/browse/COST-320
=> Bump websocket-extensions 0.1.4

src/pages/details/awsDetails/detailsTable.styles.ts, src/pages/details/azureDetails/detailsTable.styles.ts, src/pages/details/ocpDetails/detailsTable.styles.ts
The Details cost heading is no longer right aligned, due to a change in PatternFly.
We need to replace justify-content: flex-end; with margin-left: auto;
https://issues.redhat.com/browse/COST-328
=> COST-328: Details cost heading should be right aligned

src/pages/costModels/costModelsDetails/components/table.tsx
- Make the pagination on the toolbar compact
- Align the pagination on bottom to right
=> fix(costmodels): Fix pagination settings in the sources tab

src/store/costModels/actions.ts
This fixes a bug when updating a cost model.
The problem was due to the changes I did to the cost model routing and now that cost models details page and cost model details page are two different pages, I had to update the Redux action as well.
Now, when the cost model is successfully updated we will fetch it specifically and not all the cost models.
//cc @lcouzens
=> fix(costmodels): fix redirect issue on cost model update

src/pages/details/components/export/exportModal.tsx
Swapped button order for the export modal in the details pages. Updated cancel variant to a link button.
https://issues.redhat.com/browse/COST-135
=> COST-135: Export modal consistency update

src/locales/en.json, src/pages/details/components/tag/tag.styles.ts, src/pages/details/components/tag/tagLink.tsx, src/pages/details/components/tag/tagModal.styles.ts, src/pages/details/components/tag/tagModal.tsx, src/pages/details/components/tag/tagView.tsx
Updated tags modal shown on details page per new mocks. However, we're using PatternFly's data list component instead of a simple HTML table -- reviewed with Natalie.
https://issues.redhat.com/browse/COST-134
=> COST-134: Tag list modal consistency update

koku-ui-manifest, package.json, yarn.lock
Dependabot is reporting a security issue with lodash. We need to upgrade lodash to version 4.17.19 or later.
https://issues.redhat.com/browse/COST-375
=> COST-375: Update lodash dependency

src/locales/en.json, src/pages/details/components/priceList/priceListTable.tsx
This removes the price list dependency on API labels as i18n keys in the details page. Instead, the API's `metric.display` value is passed as a property to a single i18n string. That way, when a metric is added or changed, the UI won't break due to a missing i18n key.
Note that the details page price list will ultimately be replaced by https://issues.redhat.com/browse/COST-255.
https://issues.redhat.com/browse/COST-50
=> COST-50: Price list depends on API labels for i18n keys

src/pages/costModels/costModelsDetails/components/addRateModal.tsx, src/pages/costModels/costModelsDetails/components/updateMarkupDialog.tsx, src/pages/costModels/costModelsDetails/components/updateRateModel.tsx
Cost model consistency update. Modified cancel buttons to be links per latest mocks.
https://issues.redhat.com/browse/COST-362
=> Cost model consistency update

src/pages/details/awsDetails/awsDetails.tsx, src/pages/details/azureDetails/azureDetails.tsx, src/pages/details/ocpDetails/ocpDetails.tsx
Currently, app.tsx relies on the providers API to return an 403 (i.e., unauthorized) status. However, the providers API doesn't have RBAC on the `/sources/` endpoint. Therefore, each details page must test reports for 403 errors.
https://issues.redhat.com/browse/COST-390
=> Cost Details page displays empty state upon 403 response

src/locales/en.json, src/pages/details/awsDetails/awsDetails.tsx, src/pages/details/azureDetails/azureDetails.tsx, src/pages/details/ocpDetails/ocpDetails.tsx, src/pages/state/notAuthorized/notAuthorized.tsx, src/pages/state/notAuthorized/notAuthorizedState.tsx
QE found that the full page AWS error state blocks access to Azure and vice versa. In this test scenario, the user did not have RBAC access to AWS, but does have access to Azure.
This change simply moves the error state to the page body in order to show the page header. Thus, allowing the Azure tab to be selected -- reviewed with Natalie.
https://issues.redhat.com/browse/COST-390
=> Full page AWS error state blocks access to Azure

src/pages/costModels/createCostModelWizard/generalInformation.tsx
Updated the "Learn more" links in UI's cost model wizard to latest OpenShift version 4.5
https://issues.redhat.com/browse/COST-403
=> Update "Learn more" links in UI to latest OpenShift version 4.5

src/locales/en.json, src/pages/costModels/costModelsDetails/components/markup.tsx, src/pages/costModels/costModelsDetails/components/updateMarkupDialog.tsx, src/pages/costModels/createCostModelWizard/index.tsx
This change will make sure that the precision of the markup is not more than 2 digits after the dot.
//cc @nlcwong
=> fix(costmodels): edit markup dialog updates

src/pages/details/awsDetails/awsDetails.tsx, src/pages/details/azureDetails/azureDetails.tsx, src/pages/details/ocpDetails/ocpDetails.tsx
When the "View by" menu is selected, we see a full page loading state, which is a bit annoying. This moves the loading state to the page body when a report is fetched. Thus, the header remains in view while the "View by" menu is disabled.
https://issues.redhat.com/browse/COST-390
=> Moved loading state to page body

src/components/charts/costChart/costChart.styles.ts, src/components/charts/costChart/costChart.tsx, src/components/charts/historicalCostChart/historicalCostChart.styles.ts, src/components/charts/historicalCostChart/historicalCostChart.tsx, src/components/charts/historicalTrendChart/historicalTrendChart.styles.ts, src/components/charts/historicalTrendChart/historicalTrendChart.tsx, src/components/charts/historicalUsageChart/historicalUsageChart.styles.ts, src/components/charts/historicalUsageChart/historicalUsageChart.tsx, src/components/charts/trendChart/trendChart.styles.ts, src/components/charts/trendChart/trendChart.tsx, src/components/charts/usageChart/usageChart.styles.ts, src/components/charts/usageChart/usageChart.tsx, src/pages/details/components/historicalData/historicalChart.styles.ts, src/pages/details/components/historicalData/historicalDataTrendChart.tsx, src/pages/details/components/historicalData/historicalDataUsageChart.tsx
Chart legends appear to be using Overpass fonts instead of the new Red Hat fonts. At one time, we had to override the labels prop for legends, but we can remove that now.
The debugger should show PatternFly's `--pf-chart-global--FontFamily` variable as the `font-family` value.
https://issues.redhat.com/browse/COST-416
**Before**
**After**
The difference is slight, but noticeable.
=> Chart legends use Overpass font

src/pages/details/awsDetails/awsDetails.tsx, src/pages/details/awsDetails/detailsTable.tsx, src/pages/details/azureDetails/azureDetails.tsx, src/pages/details/azureDetails/detailsTable.tsx, src/pages/details/ocpDetails/detailsTable.tsx, src/pages/details/ocpDetails/ocpDetails.tsx
This adds a loading state to the table body, which follows PatternFly's examples. This is displayed during pagination, when a new report is fetched.
=> Added loading state to table body

src/app.tsx, src/locales/en.json, src/pages/state/maintenance/maintenanceState.tsx
Updated our maintenance state to use the Insights Maintenance component from the frontend-components package.
In anticipation of our upcoming outage, the text was updated to match Natalie's comments: https://docs.google.com/document/d/1i7KUJxbS6CBcKrr9gapGCxqjYNehSpMLYLSq2ID6w2U/edit#heading=h.hrfxvpk2r425
https://issues.redhat.com/browse/COST-427
=> Maintenance state update

src/locales/en.json, src/pages/details/awsDetails/awsDetails.tsx, src/pages/details/awsDetails/detailsToolbar.tsx, src/pages/details/azureDetails/azureDetails.tsx, src/pages/details/azureDetails/detailsToolbar.tsx, src/pages/details/components/dataToolbar/dataToolbar.tsx, src/pages/details/components/export/exportModal.tsx, src/pages/details/components/export/exportSubmit.tsx, src/pages/details/ocpDetails/detailsTable.tsx, src/pages/details/ocpDetails/detailsToolbar.tsx, src/pages/details/ocpDetails/ocpDetails.tsx
Added a bulk selector in the OpenShift details page to support our CSV exports. 
This maintains selections while paginating. Thus, when the export modal is opened, it shows selections made across all pages.
Note that the AWS and Azure pages will be updated next.
https://issues.redhat.com/browse/COST-422
=> Add bulk selector for CSV export

src/pages/details/components/export/exportModal.tsx
This changes the default CSV export to monthly instead of daily
> Multiple internal customers have mentioned that they generally always collect the monthly reports. We should make that the default selection in the UI so they don't have to click to change the majority of times.
https://issues.redhat.com/browse/COST-486
=> Default CSV export

src/locales/en.json, src/pages/details/awsDetails/detailsTable.tsx
When grouping by AWS Organization Units the column name for Organizations and Accounts should say "Names", not "Tag names".
https://issues.redhat.com/browse/COST-485
=> Column name is incorrect when grouped by AWS Organization Units

src/components/sources/InactiveSources/InactiveSources.tsx, src/utils/cookie.ts
This sets a session cookie to ensure the inactive sources alert will remain closed while the user is logged in. That is, providing the user closed the inline alert.
If the user logs out or closes the browser, the session cookie will be invalid and removed upon a new login. In this scenario, the alert will be shown, again.
If there are no longer inactive sources, the cookie is also removed. Thus, allowing new alerts to be shown.
https://issues.redhat.com/browse/COST-463
=> Inactive sources cookie

src/components/sources/InactiveSources/InactiveSources.tsx, src/components/sources/InactiveSources/inactiveSources.styles.ts
Added 24px padding around the inactive sources alert, per review feedback.
https://issues.redhat.com/browse/COST-463
=> Inactive sources padding

src/pages/details/awsDetails/detailsTable.styles.ts, src/pages/details/azureDetails/detailsTable.styles.ts, src/pages/details/ocpDetails/detailsTable.styles.ts
Fix misaligned "Month over month change" column.
https://issues.redhat.com/browse/COST-515
=> Fix misaligned "Month over month change" column

src/pages/costModels/costModel/costModelInfo.styles.ts, src/pages/costModels/costModelsDetails/components/markup.styles.ts, src/pages/costModels/costModelsDetails/costModelsDetails.styles.ts, src/pages/details/awsDetails/awsDetails.styles.ts, src/pages/details/awsDetails/detailsHeader.styles.ts, src/pages/details/azureDetails/azureDetails.styles.ts, src/pages/details/azureDetails/detailsHeader.styles.ts, src/pages/details/components/breakdown/breakdownHeader.styles.ts, src/pages/details/components/dataToolbar/dataToolbar.styles.ts, src/pages/details/ocpDetails/detailsHeader.styles.ts, src/pages/details/ocpDetails/ocpDetails.styles.ts
This reduces page (gray border) & header padding from 32px to 24px, per the latest PatternFly guidelines.
https://issues.redhat.com/browse/COST-519
=> Reduce page & header padding to 24px

src/utils/computedReport/getComputedReportItems.ts
The API returns different property names if we're filtering AWS org units. This ensures the ID is always used as a fallback.
https://issues.redhat.com/browse/COST-524
=> AWS details not displaying OU names on filtered data

src/locales/en.json, src/pages/details/components/export/exportModal.tsx, src/pages/details/components/export/exportSubmit.tsx
This adds a "Select month" radio button, which allows users to export a CSV for the previous months data.
https://issues.redhat.com/browse/COST-487
=> Export the previous month

src/components/charts/common/charts-common.scss, src/components/charts/costChart/costChart.tsx, src/components/charts/historicalCostChart/historicalCostChart.tsx, src/components/charts/historicalTrendChart/historicalTrendChart.tsx, src/components/charts/historicalUsageChart/historicalUsageChart.tsx, src/components/charts/trendChart/trendChart.tsx, src/components/charts/usageChart/usageChart.tsx, src/pages/costModels/costModelsDetails/components/table.tsx, src/pages/costModels/costModelsDetails/costModelsPagination.tsx, src/pages/costModels/createCostModelWizard/table.tsx, src/pages/details/components/costOverview/costOverviewBase.tsx, src/pages/details/components/usageChart/usageChart.tsx
Fixes the overflow so bullet chart (`usageChart.tsx`) tooltips are not cut off. Also cleaned up some relative paths.
Before
After
=> Bullet chart tooltips are cut off

src/components/charts/historicalCostChart/historicalCostChart.tsx, src/components/charts/historicalTrendChart/historicalTrendChart.tsx, src/components/charts/historicalUsageChart/historicalUsageChart.tsx
Historical legend items are touching, overlapping labels in some cases.
https://issues.redhat.com/browse/COST-569
Before
After
=> Historical legend item spacing

src/pages/details/components/export/exportModal.styles.ts, src/pages/details/components/export/exportModal.tsx
The export dialog description should not use PatternFly's title component.
https://issues.redhat.com/browse/COST-583
=> Export dialog description is too large

.github/workflows/codeql-analysis.yml
>For the interpreted languages that CodeQL supports (Python and JavaScript/TypeScript), you can restrict code scanning to files in specific directories by adding a paths array to the configuration file. You can exclude the files in specific directories from scans by adding a paths-ignore array.
https://docs.github.com/en/free-pro-team@latest/github/finding-security-vulnerabilities-and-errors-in-your-code/configuring-code-scanning
=> Specifying directories for codeQL to scan

.github/workflows/codeql-analysis.yml
Github encountered an error with the codeQL workflow file.
"you may only define one of `paths` and `paths-ignore` for a single event"
https://github.com/project-koku/koku-ui/actions/runs/287204312
=> Invalid workflow file

src/store/rbac/selectors.ts
We have renamed the rbac resource from rate to cost_mode. This will allow us to respect the new value and catch any existing rbac roles with rate in use instead.
=> Allow rate or cost_model resource

src/components/reports/reportSummary/reportSummaryDetails.scss, src/components/reports/reportSummary/reportSummaryDetails.tsx, src/pages/details/awsDetails/detailsHeader.tsx, src/pages/details/azureDetails/detailsHeader.tsx, src/pages/details/components/breakdown/breakdownHeader.tsx, src/pages/details/components/costOverview/costOverviewBase.tsx, src/pages/details/components/historicalData/historicalDataBase.tsx, src/pages/details/components/summary/summaryCard.tsx, src/pages/details/ocpDetails/detailsHeader.tsx, src/pages/overview/overview.tsx
- All page titles should be 24px
- All card titles should be 18px
- All "hero" numbers should be 36px
**Overview**
**Cost breakdown**
**Historical charts**
=> Font styles on the Cost Management pages are not consistent

src/components/reports/reportSummary/reportSummaryDetails.scss, src/components/reports/reportSummary/reportSummaryDetails.tsx
Natalie requested that we reduce the hero font sizes for the overview cards. The cost card will remain at 36px (4xl) while the smaller cards use 24px (2xl). This will give the hero numbers more room to grow.
https://issues.redhat.com/browse/COST-605
=> Decreased hero font sizes for overview cards

src/components/charts/costChart/costChart.tsx, src/components/charts/historicalCostChart/historicalCostChart.tsx, src/components/charts/historicalTrendChart/historicalTrendChart.tsx, src/components/charts/historicalUsageChart/historicalUsageChart.tsx, src/components/charts/trendChart/trendChart.tsx, src/components/charts/usageChart/usageChart.tsx, src/locales/en.json
Replaces date range with a chart tooltip title
https://issues.redhat.com/browse/COST-606
**Overview cost chart**
**Overview trend chart**
**Historical chart**
=> Add a title to chart tooltips

src/components/reports/reportSummary/reportSummaryDetails.scss, src/components/reports/reportSummary/reportSummaryDetails.tsx
The AWS and Azure overview have cards that show cost. The hero numbers in these cards should be the same size font.
When we updated the cost card, on the top of all overview pages, that inadvertently affected the style reused by the AWS and Azure overview cards that also show cost.
https://issues.redhat.com/browse/COST-605
**Before**
**After**
=> Cost card hero numbers should be smaller

src/pages/details/awsDetails/awsDetails.tsx, src/pages/details/azureDetails/azureDetails.tsx, src/pages/details/ocpDetails/ocpDetails.tsx
For the AWS/Azure/Ocp details page, a loading (spinning circle) is shown inside the table body. However, it's so brief that it looks like an empty table. It would be preferable to continue showing the loading state used while fetching providers.
https://issues.redhat.com/browse/COST-627
=> Show loading state while fetching details table data

src/components/charts/costChart/costChart.tsx, src/components/charts/historicalCostChart/historicalCostChart.tsx, src/components/charts/historicalTrendChart/historicalTrendChart.tsx, src/components/charts/historicalUsageChart/historicalUsageChart.tsx, src/components/charts/trendChart/trendChart.tsx, src/components/charts/usageChart/usageChart.tsx
When charts are re-rendered, the custom legend tooltip stops working. This happens whenever the user changes tabs or resizes the browser window.
The fix is to simply re-order how the "voronio" and "cursor" container properties are merged via Victory's `createContainer` function. Thus, saving the container state is no longer necessary.
https://issues.redhat.com/browse/COST-523
=> UI overview tooltip not working correctly

src/components/charts/costChart/costChart.tsx, src/components/charts/historicalCostChart/historicalCostChart.tsx, src/components/charts/historicalTrendChart/historicalTrendChart.tsx, src/components/charts/historicalUsageChart/historicalUsageChart.tsx, src/components/charts/trendChart/trendChart.tsx, src/components/charts/usageChart/usageChart.tsx
The scale (aspect ratio) is off for historical charts. This appears to have changed with the latest Victory packages.
This change ensures each chart container defines both height and width.
https://issues.redhat.com/browse/COST-626
**Before**
**After**
=> Historical chart scale is too small

src/components/state/emptyValueState/emptyValueState.scss, src/components/state/emptyValueState/emptyValueState.tsx
The empty state is picking up another `container` style. I simply changed the name to fix the alignment foe the "Month over month change" column.
https://issues.redhat.com/browse/COST-635
=> Fix empty state alignment

src/components/sources/InactiveSources/InactiveSources.tsx
The `InactiveSources` component is generating extra `sources` API requests unnecessarily. The `App.tsx` calls these APIs, so fetching again is not necessary.
https://issues.redhat.com/browse/COST-648
=> Remove extra sources API calls

src/app.tsx, src/pages/details/awsDetails/awsDetails.tsx, src/pages/details/azureDetails/azureDetails.tsx, src/pages/details/ocpDetails/ocpDetails.tsx, src/routes.tsx, src/utils/permissions.ts, src/utils/permissionsComponent.tsx
As a user, I expect UI pages to be shown according to my user's entitlements and RBAC permissions. Pages should only be shown if the following conditions are met.
1. The user has entitlements
2. If the user is an org admin, all pages are available
3. A page is shown if the user has RBAC permissions for specific resource types
As an example, consider the `cost-demo` user. Since that user is an org admin, they should have access to all pages.
The `cost-user` user is not an org admin and only has the `cost_model` resource type defined as read/write permissions. In this scenario, the user only has access to the cost models page. 
When users don't have permissions, they see the `NotAuthorized` empty state.
For more details, see https://issues.redhat.com/browse/COST-646
**The `cost-user` user …
=> Use RBAC permissions to provide user access to pages

src/pages/details/components/costChart/costChart.tsx
The markup and raw cost values shown in the breakdown chart's legend are switched.
https://issues.redhat.com/browse/COST-640
=> Breakdown chart shows markup and raw cost values switched

src/pages/overview/overview.tsx, src/utils/permissions.ts
As a user, I expect Overview tabs and perspective options to be shown according to my user's entitlements and RBAC permissions. Items should only be shown if the following conditions are met.
1. If the user is an org admin, all items are available
2. An item is shown if the user has RBAC permissions for specific resource types
3. Sources are populated with data
https://issues.redhat.com/browse/COST-647
=> Use RBAC permissions to show/hide tabs and perspective options

src/locales/en.json, src/pages/state/notAuthorized/notAuthorized.tsx, src/pages/state/notAuthorized/notAuthorizedState.tsx, src/utils/permissionsComponent.tsx
The no auth state for cost models should display "You do not have access to Cost Models in Cost Management" as the title.
Currently, we show the default title used for the overview page - "You do not have access to Cost Management"
https://issues.redhat.com/browse/COST-675
=> Cost models no auth state

src/pages/costModels/createCostModelWizard/index.tsx
closes COST 690
How to reproduce:
- Click on Cost model in the side navigation bar
- Click on create cost model
- Select OpenShift in type and enter any name
- Click Next till you get to the Review step
- Click on "Enter information" in the wizard navigation (on the left side)
- Change the type to AWS or Azure
- See error
However, if you click on Back (after reaching the Review step) till you get to the first step and change the type to anything but Openshift, everything is OK.
What happened here: when we click on the wizard navigation, the step state is not changed and that's because the Wizard is not updating it like when we clicked on the Next and Back buttons. To solve this, I had to pass the "onMove" function (which updates the step state) to the onGoToStep prop.
=> fix(costmodels): update wizard step on clicking wizard nav

package.json, scripts/utils/i18n_excludes, scripts/utils/i18n_key_tool.py
A tool that will help us find dead i18n keys.
targets:
- `yarn i18n:key:check:full`
- `yarn i18n:key:check:notfound`
example output of full report:
....
```
toolbar.sources.secondary.ocp
FOUND IN: /Users/dougdonahue/WebstormProjects/koku-ui/src/pages/costModels/costModelsDetails/components/costModelsDetailsToolbar.tsx
unit_tooltips.core-hours                                                   [NOT FOUND]
unit_tooltips.gb
FOUND IN: /Users/dougdonahue/WebstormProjects/koku-ui/src/components/charts/common/chartUtils.test.ts
unit_tooltips.gb-hours                                                     [NOT FOUND]
unit_tooltips.gb-mo                                                        [NOT FOUND]
unit_tooltips.hours                                                        [NOT FOUND] …
```
=> Remove dead i18n keys

src/locales/en.json
The only reference to the "app_title" tag is found in the archive directory. Removing in favor of cleanup
=> remove "app_title" i18n key

src/pages/details/components/breakdown/breakdownHeader.tsx
We're currently showing the previous month instead of the current month in the breakdown page header. 
The problem is that default month offset should not be used here to display the current month.
https://issues.redhat.com/browse/COST-725
=> Wrong month label shown on breakdown page

src/store/dashboard/azureCloudDashboard/azureCloudDashboardWidgets.ts, src/store/dashboard/azureDashboard/azureDashboardWidgets.ts
We had a AWS i18n tag being used in the Azure widgets. This was not causing any issues as the key values are the same.
=> Fixed tag names being used in Azure widgets

src/locales/en.json
These keys are not being utilized. We are using command keys, like "units" and "unit_tooltips"
=> Removal of azure.historical.** i18n keys, we are using common keys

src/pages/overview/overview.styles.ts
Overview heading padding is too large.
https://issues.redhat.com/browse/COST-745
=> Overview heading padding

src/store/historicalData/awsHistoricalData/awsHistoricalDataWidgets.ts, src/store/historicalData/azureHistoricalData/azureHistoricalDataWidgets.ts, src/store/historicalData/common/historicalDataCommon.ts
The AWS and Azure historical pages are only showing the wrong chart type. Should be showing a usage chart, not trend charts.
https://issues.redhat.com/browse/COST-746
AWS
Azure
=> Incorrect hIstorical usage charts

src/locales/en.json
Fixed legend for limit so it now shows date range
=> Fixed i18n key name for limits label on historical chart legend

src/locales/en.json
This is a quick fix for production.
https://issues.redhat.com/browse/COST-755
Before
After
=> Wizard non-localized metric string

src/locales/en.json
We want to shorten chart tooltip title from "Day of the month: 19" to "Day 19".
https://issues.redhat.com/browse/COST-753
=> Shorten chart tooltip title

src/components/charts/costChart/costChart.tsx, src/components/charts/trendChart/trendChart.styles.ts, src/components/charts/trendChart/trendChart.tsx, src/components/reports/reportSummary/reportSummaryAlt.scss, src/components/reports/reportSummary/reportSummaryAlt.tsx, src/pages/dashboard/components/dashboardWidgetBase.tsx, src/store/dashboard/awsDashboard/awsDashboardWidgets.ts, src/store/dashboard/common/dashboardCommon.ts, src/store/dashboard/ocpDashboard/ocpDashboardWidgets.ts
Instead of splitting the screen in half, we would like to have the chart take up about 2/3 of the available width. The progress bars can be shortened to use the remaining 1/3.
=> Overview chart width

src/pages/dashboard/components/dashboardWidgetBase.tsx
Encountered a date with empty values, which may result in a disconnected line between the forecast and current month.
https://issues.redhat.com/browse/COST-736
=> Account for dates with empty values

src/api/forecasts/forecast.ts, src/api/forecasts/forecastUtils.ts, src/api/forecasts/ocpForecast.ts, src/components/charts/costChart/costChart.styles.ts, src/components/charts/costChart/costChart.tsx, src/components/charts/trendChart/trendChart.tsx, src/pages/dashboard/components/dashboardWidgetBase.tsx, src/pages/dashboard/ocpDashboard/ocpDashboardWidget.tsx, src/store/dashboard/azureDashboard/azureDashboardWidgets.ts, src/store/dashboard/ocpDashboard/ocpDashboardActions.ts, src/store/dashboard/ocpDashboard/ocpDashboardSelectors.ts, src/store/dashboard/ocpDashboard/ocpDashboardWidgets.ts
Created the initial Ocp cost forecast and cone of confidence.
https://issues.redhat.com/browse/COST-738
Note: There is an issue with the forecast data; thus, the forecast is currently a flat line.
See https://issues.redhat.com/browse/COST-760
=> OpenShift cost forecast

src/pages/costModels/components/rateForm/rateForm.tsx
=> fix(costmodels): show measurement units in the select options

src/components/charts/common/chartUtils.ts, src/components/charts/costChart/costChart.tsx, src/components/charts/trendChart/trendChart.tsx, src/pages/dashboard/components/dashboardWidgetBase.tsx, src/store/dashboard/awsDashboard/awsDashboardCommon.ts, src/store/dashboard/awsDashboard/awsDashboardSelectors.ts, src/store/dashboard/azureDashboard/azureDashboardCommon.ts, src/store/dashboard/azureDashboard/azureDashboardSelectors.ts, src/store/dashboard/ocpDashboard/ocpDashboardCommon.ts, src/store/dashboard/ocpDashboard/ocpDashboardSelectors.ts
Added padding to chart forecast data. This will ensure tooltips will be displayed even if all other data is hidden via the chart legend.
https://issues.redhat.com/browse/COST-762
=> Incorrect display of graph labels

src/components/charts/costChart/costChart.tsx, src/components/charts/historicalCostChart/historicalCostChart.tsx, src/components/charts/historicalTrendChart/historicalTrendChart.tsx, src/components/charts/historicalUsageChart/historicalUsageChart.tsx, src/components/charts/trendChart/trendChart.tsx, src/components/charts/usageChart/usageChart.tsx
Refactored interactive legends to store chart container via state.
It appears if the chart container is recreated from scratch, each time the chart is redrawn, onMouseOver events are lost. If we store the container via state, then tooltips continue to be displayed properly after a data series is hidden / shown via the interactive legend.
https://issues.redhat.com/browse/COST-762
**Before**
**After**
=> Interactive legends to store chart container via state

src/pages/costModels/components/addPriceList.test.tsx, src/pages/costModels/components/rateForm/rateForm.tsx, src/pages/costModels/components/rateForm/useRateForm.tsx
=> fix(costmodels): hide the enter-by-tag switch on cluster metric

.github/workflows/pull_request.yml
Travis has become unbearably slow, waiting for queued PRs to build. Thus, I've created a Github workflow for PRs only.
Note that the `insights-frontend-builder-common` release scripts still require Travis in order to push to the ci-stable branch. Therefore, Travis is still used for pushes.
This mimics what Subscription Watch is doing with Github workflows. Although, I'm open to ideas about what to do with those release scripts?
This build only takes 4 minutes, compared to being queued for several hours.
**Workflow output**
=> Create GitHub workflow

src/pages/costModels/components/rateForm/useRateForm.test.tsx, src/pages/details/ocpDetails/detailsTable.tsx
OpenShift supplemental and infrastructure cost percentages, shown via the details table, should be based of of the total cost. Currently, the cost percentages are based on total supplemental cost and total infrastructure cost.
Also fixed a lint issue with cost models test.
https://issues.redhat.com/browse/COST-778
=> Ocp details page percentages should be based on total cost

src/components/charts/common/chartUtils.ts, src/components/charts/costChart/costChart.tsx, src/components/charts/historicalCostChart/historicalCostChart.tsx, src/components/charts/historicalTrendChart/historicalTrendChart.tsx, src/components/charts/historicalUsageChart/historicalUsageChart.tsx, src/components/charts/trendChart/trendChart.tsx, src/components/charts/usageChart/usageChart.tsx, src/pages/dashboard/components/dashboardWidgetBase.tsx, src/store/dashboard/awsDashboard/awsDashboardSelectors.ts, src/store/dashboard/azureDashboard/azureDashboardSelectors.ts, src/store/dashboard/ocpDashboard/ocpDashboardSelectors.ts
Refactored the chart forecast a bit for:
1. Forecast API removed the `filter[time_scope_value]` parameter
2. Scale charts dynamically when a data series is hidden / shown
3. Purne erroneous data outside forecast date range
=> Forecast params

src/components/charts/costChart/costChart.styles.ts, src/components/charts/costChart/costChart.tsx, src/components/charts/trendChart/trendChart.tsx, src/components/charts/usageChart/usageChart.tsx, src/components/reports/reportSummary/reportSummaryDetails.tsx, src/pages/dashboard/components/dashboardWidgetBase.tsx
The chart tooltip legend may show the wrong label for infrastructure data. The legend labels appear to be swapped (e.g., the value expected for "Infrastructure cost" is labeled "Cost foreccast".
This is due to reordering legend items in order to wrap items when there is not enough room. However, we can now use PatternFly's `legendAllowWrap` feature to do that for us.
**Correct tooltip labels**
**Example of legend item responsiveness**
=> Wrong tooltip label/value for cost forecast

src/locales/en.json, src/pages/costModels/components/rateTable.tsx, src/pages/costModels/costModelsDetails/components/priceListTable.tsx, src/pages/costModels/createCostModelWizard/priceListTable.tsx
closes COST 756
remove unnecessary i18n keys and removing them from toolbars and tables in cost models.
=> fix(costmodels): delete i18n keys for metrics/measurements

src/components/charts/common/chartUtils.ts, src/components/charts/costChart/costChart.tsx, src/components/charts/historicalCostChart/historicalCostChart.tsx, src/components/charts/historicalTrendChart/historicalTrendChart.tsx, src/components/charts/historicalUsageChart/historicalUsageChart.tsx, src/components/charts/trendChart/trendChart.tsx, src/components/charts/usageChart/usageChart.tsx, src/pages/dashboard/components/dashboardWidgetBase.tsx
The forecast feature should only be enabled for dev and QA users; `cost-demo` and `insights-qa`. This is a temporary change until the forecast APIs have been fully tested and ready for production.
Also set charts min y domain back to zero.
=> Enable forecast feature for dev & QA only

src/components/charts/common/chartUtils.ts, src/components/charts/costChart/costChart.tsx, src/components/charts/historicalCostChart/__snapshots__/historicalCostChart.test.tsx.snap, src/components/charts/historicalCostChart/historicalCostChart.tsx, src/components/charts/historicalTrendChart/__snapshots__/historicalTrendChart.test.tsx.snap, src/components/charts/historicalTrendChart/historicalTrendChart.tsx, src/components/charts/historicalUsageChart/__snapshots__/historicalUsageChart.test.tsx.snap, src/components/charts/historicalUsageChart/historicalUsageChart.tsx, src/components/charts/trendChart/__snapshots__/trendChart.test.tsx.snap, src/components/charts/trendChart/trendChart.tsx, src/components/charts/usageChart/__snapshots__/usageChart.test.tsx.snap, src/components/charts/usageChart/usageChart.tsx
This ensures chart tooltips are updated properly when a data series is hidden / shown. Although the container view is stored in state, the tooltip legend data still needs to be updated upon each render.
https://issues.redhat.com/browse/COST-806
=> Sync chart tooltips

src/pages/dashboard/components/dashboardWidgetBase.tsx
This ensures forecast APIs are called only for the cost-demo and insights-qa users. That is, until the forecast feature is fully tested and ready for production.
https://issues.redhat.com/browse/COST-806
=> Fetch forecast data for dev & QA only

src/api/forecasts/forecast.ts, src/api/forecasts/ocpForecast.ts, src/components/charts/common/chartUtils.ts, src/components/charts/costChart/costChart.styles.ts, src/components/charts/costChart/costChart.tsx, src/components/charts/historicalCostChart/historicalCostChart.tsx, src/components/charts/historicalTrendChart/historicalTrendChart.tsx, src/components/charts/historicalUsageChart/historicalUsageChart.tsx, src/components/charts/trendChart/trendChart.styles.ts, src/components/charts/trendChart/trendChart.tsx, src/components/charts/usageChart/usageChart.tsx, src/locales/en.json, src/pages/dashboard/components/dashboardWidgetBase.tsx, src/store/dashboard/common/dashboardCommon.ts, src/store/dashboard/ocpDashboard/ocpDashboardWidgets.ts
Added the infrastructure forecast to the OpenShift overview page. For clarity, we changed the infrastructure color from green to blue.
Note that the forecast confidence is still shown in the chart, but it has been omitted from the legend items. This was done because the legend is becoming too crowded.
When you hover over the legend item, it highlights just the forecast line. However, when you click on the legend item, it hides both the forecast line and forecast confidence cone.
The tooltip still shows both forecast and confidence, but the confidence cone appears as the last item in the list. The tooltip and legend items must appear in the same order so the indexes match exactly for on-hover events.
https://issues.redhat.com/browse/COST-817
=> OpenShift infrastructure forecast

src/pages/costModels/costModelsDetails/addSourceWizard.tsx
The problem is that the button is disabled via testing `fetchingSourcesError` for null, while the value is assigned an empty string.
https://issues.redhat.com/browse/COST-841
=> Unable to assign a source to a cost model via the UI

src/pages/dashboard/components/dashboardWidgetBase.tsx
The last forecast date is not shown. It currently stops on 12/30; although, we have data for 12/31.
https://issues.redhat.com/browse/COST-844
=> Last forecast date not shown

src/components/charts/common/chartUtils.ts, src/components/charts/costChart/costChart.tsx, src/components/charts/dailyCostChart/dailyCostChart.styles.ts, src/components/charts/dailyCostChart/dailyCostChart.tsx, src/components/charts/dailyCostChart/index.ts, src/components/reports/reportSummary/index.ts, src/components/reports/reportSummary/reportSummaryDailyCost.scss, src/components/reports/reportSummary/reportSummaryDailyCost.tsx, src/locales/en.json, src/pages/dashboard/components/chartComparison.tsx, src/pages/dashboard/components/dashboardWidget.styles.ts, src/pages/dashboard/components/dashboardWidgetBase.tsx, src/store/dashboard/common/dashboardCommon.ts, src/store/dashboard/ocpDashboard/ocpDashboardWidgets.ts
Created a daily cost comparison for the "All OpenShift cost" overview page. The cumulative cost chart is sown by default, with a dropdown to select the daily cost chart.
Unfortunately, the fake (nise) data were using for the cost-demo user doesn't produce a pretty chart. The high cost values scale the chart so that it's difficult to view the infrastructure cost and forecast values without hiding other data. 
Scaling issues are nothing new, but wanted to explain why the mock looks different. I expect the chart to look closer to the mock with real data from prod.
https://issues.redhat.com/browse/COST-834
=> Daily chart for "All OpenShift cost" overview

src/utils/permissions.ts
* Add checks for users that have the rate permissions in addition to cost_model
Related to:
- https://issues.redhat.com/browse/COST-892
- https://bugzilla.redhat.com/show_bug.cgi?id=1915513
=> Handle rate permissions for access to cost model page.

src/components/charts/costChart/costChart.tsx, src/components/charts/dailyCostChart/dailyCostChart.tsx, src/components/charts/dailyTrendChart/dailyTrendChart.tsx, src/components/charts/historicalCostChart/historicalCostChart.tsx, src/components/charts/historicalTrendChart/historicalTrendChart.tsx, src/components/charts/historicalUsageChart/historicalUsageChart.tsx, src/components/charts/trendChart/trendChart.tsx, src/components/charts/usageChart/usageChart.tsx
When hovering over an interactive legend item, all other datasets in the chart are muted (i.e., an opacity is applied to make them look slightly grayed out). When the cursor moves away from the legend item, the muted styles are removed. This works fine with line and area charts, but there is a problem with bar charts. It's more of an edge case, but under certain conditions, bars may remain muted.
https://issues.redhat.com/browse/COST-924
=> Bar chart remains muted with interactive legend

src/pages/details/awsDetails/awsDetails.tsx, src/pages/details/azureDetails/azureDetails.tsx, src/pages/details/gcpDetails/gcpDetails.tsx, src/pages/details/ocpDetails/ocpDetails.tsx
Currently, the details pages for compact pagination controls at the top and bottom of each table. We don't want the controls at the bottom to be compact, only the top.
Also moved the loading icon to table body in order to help avoid some page flashing.
https://issues.redhat.com/browse/COST-913
=> Bottom pagination controls to not be compact

src/pages/overview/overview.tsx
Need to initialize the perspective menu in the overiew's `componentDidMount` function. This will ensure the menu is reset properly when navigating between pages.
https://issues.redhat.com/browse/COST-933
=> Initialize perspective menu

src/pages/details/awsBreakdown/awsBreakdown.tsx, src/pages/details/azureBreakdown/azureBreakdown.tsx, src/pages/details/components/breakdown/breakdownBase.tsx, src/pages/details/gcpBreakdown/gcpBreakdown.tsx, src/pages/details/ocpBreakdown/ocpBreakdown.tsx
Similar to the details pages, this adds empty providers and error states for the breakdown pages.
https://issues.redhat.com/browse/COST-944
=> Empty providers state for breakdown pages

src/api/providers.ts, src/locales/en.json, src/pages/details/awsDetails/awsDetails.tsx, src/pages/details/azureDetails/azureDetails.tsx, src/pages/details/components/breakdown/breakdownBase.tsx, src/pages/details/gcpDetails/gcpDetails.tsx, src/pages/details/ocpDetails/ocpDetails.tsx, src/pages/overview/overview.tsx, src/pages/state/noData/index.ts, src/pages/state/noData/noData.tsx, src/pages/state/noData/noDataState.tsx
This adds a no data state to help indicate that a source provider has been created, but we're still processing their data. This makes use of the new `current_month_data` flag now available from the sources API response.
https://issues.redhat.com/browse/COST-914
**Details pages**
**Overview tabs**
=> No data state

src/pages/details/awsDetails/awsDetails.tsx, src/pages/details/azureDetails/azureDetails.tsx, src/pages/details/common/detailsUtils.ts, src/pages/details/gcpDetails/gcpDetails.tsx, src/pages/details/ocpDetails/ocpDetails.tsx
The details pages have a couple common functions; for example, `handleFilterAdded`, `handleFilterRemoved`, etc. I'd like to move some of this dup code to a new file, named `detailsUtils`.
https://issues.redhat.com/browse/COST-949
=> Move common functions to detailsUtils

src/pages/dashboard/components/dashboardWidgetBase.tsx
The forecast is currently limited to the cost-demo, insights-qa, and cost-management users. We would like to remove this requirement, but waiting on final testing from QA.
https://issues.redhat.com/browse/COST-947
=> Enable forecast for all users

src/pages/details/gcpDetails/detailsTable.tsx
Closes: https://issues.redhat.com/browse/COST-956
URL change - "order_by[account_alias]" to "order_by[account]" : 
`https://ci.foo.redhat.com:1337/api/cost-management/v1/reports/gcp/costs/?delta=cost&filter[limit]=10&filter[offset]=0&filter[resolution]=monthly&filter[time_scope_units]=month&filter[time_scope_value]=-1&group_by[account]=*&order_by[account]=desc`
=> gcp need to order by 'account' not 'account_alias'

src/api/userAccess.ts, src/components/async/permissionsComponent/permissions.tsx, src/locales/en.json, src/pages/details/awsDetails/detailsToolbar.tsx, src/pages/details/azureDetails/detailsToolbar.tsx, src/pages/details/components/dataToolbar/dataToolbar.tsx, src/pages/details/gcpDetails/detailsToolbar.tsx, src/pages/details/ocpDetails/detailsToolbar.tsx, src/pages/explorer/explorer.styles.ts, src/pages/explorer/explorer.tsx, src/pages/explorer/explorerFilter.styles.ts, src/pages/explorer/explorerFilter.tsx, src/pages/explorer/explorerHeader.styles.ts, src/pages/explorer/explorerHeader.tsx, src/pages/explorer/explorerTable.scss, src/pages/explorer/explorerTable.styles.ts, src/pages/explorer/explorerTable.tsx, src/pages/explorer/explorerToolbar.tsx, src/pages/explorer/index.ts, src/routes.tsx, src/utils/computedReport/getComputedReportItems.ts
Created initial Historical Cost Explorer page, based on AWS for now. More updates to follow...
- The page is only accessible via a direct URL -- Insights nav will be updated after user-access API is ready.
- Refactored some existing code so the data table can show daily data. 
- Refactored existing details components to allow filter controls to be displayed in header.
=> Historical Cost Explorer

src/pages/details/awsDetails/detailsTable.tsx, src/pages/details/azureBreakdown/azureBreakdown.tsx, src/pages/details/azureDetails/detailsTable.tsx, src/pages/details/gcpDetails/detailsTable.tsx, src/pages/details/ocpBreakdown/ocpBreakdown.tsx, src/pages/details/ocpDetails/detailsTable.tsx
Currently, the AWS details / breakdown pages show an ID underneath the (cluster / account) name. However, OCP, Azure, and GCP do not. This update makes all the pages behave similarly, providing there is an alias in use.
https://issues.redhat.com/browse/COST-955
**OCP Details**
**OCP breakdown**
=> Details pages to show IDs, along with alias

src/locales/en.json
Update documentation links for the Cost Management UI. Note that this does not include the setting page, which is a different repo
https://issues.redhat.com/browse/COST-961
=> Update documentation links

.github/workflows/tag_release.yml
Add a GitHub Action to generate a tag with commit messages when we push to prod-stable.
=> Add tag release github action

src/components/charts/historicalExplorerChart/historicalExplorerChart.styles.ts, src/components/charts/historicalExplorerChart/historicalExplorerChart.tsx, src/pages/details/components/groupBy/groupBy.tsx, src/pages/explorer/explorerHeader.tsx
Added some fixes to the explorer's perspective and group-by dropdown menus.
- Set explorer’s default perspective option
- Reset explorer group by tag dropdown
- Reset explorer group by org unit dropdown
- Removed x-domain so bars spread out across range
- Adjust y-axis labels by adding y-domain when max values are zero
=> 915 group by

src/components/charts/historicalExplorerChart/historicalExplorerChart.tsx, src/pages/details/components/dataToolbar/dataToolbar.tsx, src/pages/details/components/groupBy/groupBy.tsx, src/pages/explorer/explorer.styles.ts, src/pages/explorer/explorer.tsx, src/pages/explorer/explorerChart.tsx, src/pages/explorer/explorerFilter.styles.ts, src/pages/explorer/explorerHeader.tsx
This change ensures the explorer chart shows every 3rd tick value per our mocks. Should provide more room when displaying a lot of data.
Fixed some other issues below
- Adjust explorer chart container height
- Truncate long resource names shown in explorer chart
- Group by tag option should remain visible while selection is valid
- Reset filter tag selection when new group by is chosen
=> Historical cost explorer tick values

src/pages/explorer/explorerTable.scss, src/pages/explorer/explorerTable.styles.ts, src/pages/explorer/explorerTable.tsx
Added horizontal scroll to explorer table. This change ensures the first two columns remain sticky, while the remainder of the table may be scrolled horizontally.
=> Horizontal Cost Explorer

src/pages/explorer/explorerTable.scss, src/pages/explorer/explorerTable.tsx
Renamed the class used by the explorer table so other pages don't pick up those styles.
https://issues.redhat.com/browse/COST-1027
=> Azure drop down is cut off by sticky explorer table styles

koku-ui-manifest, package.json, src/components/charts/common/chartDatumUtils.ts, src/components/charts/costChart/costChart.tsx, src/components/charts/dailyCostChart/dailyCostChart.tsx, src/components/charts/dailyTrendChart/dailyTrendChart.tsx, src/components/charts/historicalCostChart/historicalCostChart.tsx, src/components/charts/historicalTrendChart/historicalTrendChart.tsx, src/components/charts/historicalUsageChart/historicalUsageChart.tsx, src/components/charts/trendChart/trendChart.tsx, src/components/charts/usageChart/usageChart.tsx, src/pages/dashboard/awsDashboard/awsDashboardWidget.test.tsx, src/pages/dashboard/azureDashboard/azureDashboardWidget.test.tsx, src/pages/dashboard/components/dashboardWidget.test.tsx, src/pages/dashboard/components/dashboardWidgetBase.tsx, src/pages/dashboard/gcpDashboard/gcpDashboardWidget.test.tsx, src/pages/dashboard/ocpCloudDashboard/ocpCloudDashboardWidget.test.tsx, src/pages/dashboard/ocpDashboard/ocpDashboardWidget.test.tsx, src/pages/details/components/export/exportModal.tsx, src/pages/details/components/export/exportSubmit.tsx, src/pages/explorer/explorerChart.tsx, src/pages/explorer/explorerTable.tsx, src/utils/dateRange.ts, yarn.lock
The latest date-fns package has updated a few things.
- `formatDate` was renamed `format`
- `format` uses a Date object instead of date strings
- Formatting changed from "YYYY-MM-DD" to "yyyy-MM-dd"
- `import getDate from 'date-fns/get_date'` is now `import { getDate } from 'date-fns'`
=> Update date-fns package to latest version

.prettierrc, koku-ui-manifest, package.json, src/components/async/permissionsComponent/permissionsComponent.tsx, src/pages/costModels/costModel/addSourceStep.tsx, src/pages/costModels/costModelsDetails/utils/table.tsx, src/routes.tsx, src/utils/equal.ts, yarn.lock
https://issues.redhat.com/browse/COST-1053
This adds the `arrowParens` property to match eslint. It allows functions to skip parens if they use a single parameter.
Also removed the unused `url-loader` package.
=> Update prettier package to latest version

koku-ui-manifest, package.json, webpack.config.js, yarn.lock
The cost icon, used on our empty provider state page, is not being loaded via require after updating to webpack 5.x.
This change eliminates the file-loader package.
See https://webpack.js.org/guides/asset-management/#loading-images
https://issues.redhat.com/browse/COST-1049
=> Cost icon is not being loaded via require after updating webpack

src/components/charts/costChart/costChart.tsx, src/components/charts/dailyCostChart/dailyCostChart.tsx, src/components/charts/dailyTrendChart/dailyTrendChart.tsx, src/components/charts/historicalCostChart/historicalCostChart.tsx, src/components/charts/historicalExplorerChart/historicalExplorerChart.tsx, src/components/charts/historicalTrendChart/historicalTrendChart.tsx, src/components/charts/historicalUsageChart/historicalUsageChart.tsx, src/components/charts/trendChart/trendChart.tsx, src/components/charts/usageChart/usageChart.tsx
This introduces a resource observer to resize charts. This should resize the chart when the Insights navigation pane is collapsed / expanded.
Note that we will fallback to using window resize and the Insights' NAVIGATION_TOGGLE events should this feature not be available. However, Insights has marked the NAVIGATION_TOGGLE event as deprecated, so it will likely be removed.
https://issues.redhat.com/browse/COST-1052
=> Using resource observer to resize charts

src/api/queries/query.ts, src/components/charts/common/chartDatumUtils.ts, src/components/charts/historicalExplorerChart/historicalExplorerChart.tsx, src/locales/en.json, src/pages/details/components/dataToolbar/dataToolbar.tsx, src/pages/explorer/dateRange.tsx, src/pages/explorer/explorer.tsx, src/pages/explorer/explorerChart.tsx, src/pages/explorer/explorerFilter.tsx, src/pages/explorer/explorerHeader.tsx, src/pages/explorer/explorerTable.tsx, src/pages/explorer/explorerUtils.ts
This adds a pre-canned date ranges to the Historical Cost Explorer.
Note that the "Last 60 days" option generates an error, since we currently do not support more than 2 months of data -- Doug suggested 3 months will be available shortly.
https://issues.redhat.com/browse/COST-1062
=> Add date ranges to Historical Cost Explorer

src/locales/en.json, src/pages/details/awsDetails/awsDetails.tsx, src/pages/details/awsDetails/detailsTable.tsx, src/pages/details/azureDetails/azureDetails.tsx, src/pages/details/azureDetails/detailsTable.tsx, src/pages/details/common/detailsUtils.ts, src/pages/details/components/actions/actions.tsx, src/pages/details/components/export/exportModal.tsx, src/pages/details/components/export/exportSubmit.tsx, src/pages/details/gcpDetails/detailsTable.tsx, src/pages/details/gcpDetails/gcpDetails.tsx, src/pages/details/ocpDetails/detailsTable.tsx, src/pages/details/ocpDetails/ocpDetails.tsx, src/pages/explorer/explorer.tsx, src/pages/explorer/explorerHeader.tsx, src/pages/explorer/explorerTable.scss, src/pages/explorer/explorerTable.tsx, src/pages/explorer/explorerUtils.ts, src/utils/computedReport/getComputedReportItems.ts
Fixed a couple small issues with the Historical Cost Explorer.
- Since we're using a date range, the export should not have options for current and previous months.
- The cost explorer bulk selector dropdown is hidden by the z-index used for table scrolling.
- Check boxes are not selected when clicked.
- Update getComputedReportItems to account for AWS org units, while grouped by services and regions
https://issues.redhat.com/browse/COST-1072
https://issues.redhat.com/browse/COST-1073
https://issues.redhat.com/browse/COST-1074
**Bulk selector before**
**Bulk selector after (with selected row)**
**Export before**
**Export after**
=> Historical Cost Explorer fixes

src/pages/details/awsDetails/awsDetails.tsx, src/pages/details/azureDetails/azureDetails.tsx, src/pages/details/components/actions/actions.tsx, src/pages/details/components/export/exportModal.tsx, src/pages/details/gcpDetails/gcpDetails.tsx, src/pages/details/ocpDetails/ocpDetails.tsx
Modified the export dialog to show monthly and daily resolution. This feature is still desired for the cost explorer.
https://issues.redhat.com/browse/COST-1072
=> Modified export to show resolution

src/components/charts/common/chartDatumUtils.ts, src/locales/en.json, src/utils/formatValue.ts
closes: https://issues.redhat.com/browse/COST-1070
Compute ToolTip Shown:
Storage ToolTip Shown:
=> fix for GCP compute and storage widget labels and tooltips

webpack.config.js
Not sure why we were using `eval` for dev mode and `source-map` for production -- seems backwads? We may ultimately want `eval` in production, but this will allow debugging in both cases.
=> Fixed SourceMap warnings in dev mode

src/locales/en.json, src/pages/views/details/awsDetails/detailsTable.tsx, src/pages/views/details/azureDetails/detailsTable.tsx, src/pages/views/details/gcpDetails/detailsTable.tsx, src/pages/views/details/ocpDetails/detailsHeader.tsx, src/pages/views/details/ocpDetails/detailsTable.tsx, src/store/dashboard/awsCloudDashboard/awsCloudDashboardWidgets.ts, src/store/dashboard/awsDashboard/awsDashboardWidgets.ts, src/store/dashboard/azureCloudDashboard/azureCloudDashboardWidgets.ts, src/store/dashboard/azureDashboard/azureDashboardWidgets.ts, src/store/dashboard/gcpDashboard/gcpDashboardWidgets.ts, src/store/dashboard/ocpCloudDashboard/ocpCloudDashboardWidgets.ts
Merge duplicate i18n keys into one key,value ("chart.cost": "Cost")
"Cost"                                                                     [Found: 11]
FOUND IN KEY: gcp_details.cost_column_title
FOUND IN KEY: aws_dashboard.cost_label
FOUND IN KEY: azure_details.cost_column_title
FOUND IN KEY: azure_dashboard.cost_label
FOUND IN KEY: gcp_dashboard.cost_label
FOUND IN KEY: ocp_cloud_dashboard.cost_label
FOUND IN KEY: azure_cloud_dashboard.cost_label
FOUND IN KEY: aws_cloud_dashboard.cost_label
FOUND IN KEY: ocp_details.cost_column_title
FOUND IN KEY: aws_details.cost_column_title
FOUND IN KEY: ocp_details.total_cost
=> remove duplicate "Cost" i18n keys and create one chart.cost key

src/components/charts/common/chartUtils.ts, src/components/charts/historicalExplorerChart/historicalExplorerChart.tsx, src/locales/en.json, src/utils/formatValue.ts
This formats the chart's y-axis labels using big number abbreviations.
- K for Thousands
- M for Millions
- B for Billions
- T for Trillion
https://issues.redhat.com/browse/COST-1087
**Before:**
**After:**
=> Historical Cost Explorer y-axis labels

src/components/charts/historicalExplorerChart/historicalExplorerChart.tsx
Modified the explorer chart's default domain range. The previous y-axis labels appear odd when all data series are hidden via the interactive legend.
Before
After
=> Historical Cost Explorer domain

src/locales/en.json, src/store/dashboard/awsDashboard/awsDashboardWidgets.ts, src/store/dashboard/azureCloudDashboard/azureCloudDashboardWidgets.ts, src/store/dashboard/azureDashboard/azureDashboardWidgets.ts, src/store/dashboard/gcpDashboard/gcpDashboardWidgets.ts, src/store/dashboard/ocpCloudDashboard/ocpCloudDashboardWidgets.ts, src/store/dashboard/ocpDashboard/ocpDashboardWidgets.ts, src/store/dashboard/ocpSupplementaryDashboard/ocpSupplementaryDashboardWidgets.ts, src/store/dashboard/ocpUsageDashboard/ocpUsageDashboardWidgets.ts
Closes: https://issues.redhat.com/browse/COST-1086
Label change to dashboards from "Cumulative cost" to "Cost"
The below changes have been made to all provider dashboards.
Examples of changes:
=> Overview cost lbl mismatch cost 1086

src/locales/en.json, src/store/dashboard/ocpDashboard/ocpDashboardWidgets.ts, src/store/dashboard/ocpSupplementaryDashboard/ocpSupplementaryDashboardWidgets.ts, src/store/dashboard/ocpUsageDashboard/ocpUsageDashboardWidgets.ts
Old Keys:
"Daily usage and requests comparison ({{units}})"                          [Found: 9]
- 	FOUND IN KEY: ocp_usage_dashboard.cpu_trend_title
- 	FOUND IN KEY: ocp_supplementary_dashboard.cpu_trend_title
- 	FOUND IN KEY: ocp_dashboard.memory_trend_title
- 	FOUND IN KEY: ocp_supplementary_dashboard.volume_trend_title
- 	FOUND IN KEY: ocp_supplementary_dashboard.memory_trend_title
- 	FOUND IN KEY: ocp_usage_dashboard.memory_trend_title
- 	FOUND IN KEY: ocp_dashboard.cpu_trend_title
- 	FOUND IN KEY: ocp_dashboard.volume_trend_title
- 	FOUND IN KEY: ocp_usage_dashboard.volume_trend_title
New Key:
- ocp.daily_usage_request_comparison
=> combined duplicates keys to one key value pair

src/pages/views/explorer/explorer.tsx
The Historical Cost Explorer is showing the no data state incorrectly. If there is at least one source provider, then we can show the explorer
=> Fix no data state for explorer

src/components/charts/common/chartDatumUtils.ts
Charts are not padding missing data correctly. It appears that some dates don't use 'T00:00:00', so the chart's null ("no data") values are off by a day.
https://issues.redhat.com/browse/COST-1106
Before
After
=> Fix chart null (no data) padding

src/pages/views/details/awsDetails/awsDetails.tsx, src/pages/views/details/azureDetails/azureDetails.tsx, src/pages/views/details/gcpDetails/gcpDetails.tsx, src/pages/views/details/ocpDetails/ocpDetails.tsx, src/pages/views/explorer/explorer.tsx, src/pages/views/explorer/explorerFilter.tsx
This preserves the applied filter when the "Group by" dropdown is changed. This includes the details pages as well as the cost explorer.
https://issues.redhat.com/browse/COST-1090
=> Preserve applied filter

src/components/charts/common/chartDatumUtils.ts
The cost-demo user in production is retrieving negative forecast values. As a result, data is being shown outside the chart's y-domain.
Although the forecast API is not expected to return negative values, we can ensure data is shown only for the chart's valid domain. That is, if we encounter negative values, our ChartDatumUtils can replace that with zero instead.
https://issues.redhat.com/browse/COST-1109
**Before**
**After**
=> Omit negative chart data

src/pages/views/explorer/explorerUtils.ts
~~The explorer's "Last 30 days" and "Last 60 days" features are showing 31 and 61 days. If we include today's date, then we need to subtract 29 and 59 days from today, instead.~~
After looking at more examples, I believe the current calculations are correct. I'm going to revert the change an update comments instead.
https://issues.redhat.com/browse/COST-1117
=> Cost Explorer shows 31 and 61 days

src/pages/views/details/components/costOverview/costOverviewBase.tsx, src/pages/views/details/components/summary/summaryCard.tsx, src/pages/views/details/components/summary/summaryModal.tsx, src/pages/views/details/components/summary/summaryModalView.tsx, src/pages/views/details/components/summary/summaryView.tsx, src/pages/views/details/components/usageChart/usageChart.tsx, src/pages/views/details/ocpBreakdown/ocpBreakdown.tsx
This ensures that bullet chart ,shown on the details breakdown page, includes the filter applied via the previous page.
https://issues.redhat.com/browse/COST-1128
=> Add filter to OCP breakdown compute & memory charts

src/api/queries/query.ts, src/pages/views/details/awsBreakdown/awsBreakdown.tsx, src/pages/views/details/azureBreakdown/azureBreakdown.tsx, src/pages/views/details/components/costOverview/costOverviewBase.tsx, src/pages/views/details/components/historicalData/historicalDataBase.tsx, src/pages/views/details/components/historicalData/historicalDataCostChart.tsx, src/pages/views/details/components/historicalData/historicalDataTrendChart.tsx, src/pages/views/details/components/historicalData/historicalDataUsageChart.tsx, src/pages/views/details/components/summary/summaryCard.tsx, src/pages/views/details/components/summary/summaryModal.tsx, src/pages/views/details/components/summary/summaryModalView.tsx, src/pages/views/details/components/summary/summaryView.tsx, src/pages/views/details/components/usageChart/usageChart.tsx, src/pages/views/details/gcpBreakdown/gcpBreakdown.tsx, src/pages/views/details/ibmBreakdown/ibmBreakdown.tsx, src/pages/views/details/ocpBreakdown/ocpBreakdown.tsx, src/utils/computedReport/getComputedReportItems.ts
This ensures that the details and breakdown pages represent the correct cost when multiple filters are applied.
- Updated query functions to use either logical AND or logical OR
- Fixed sum calculation of costs in getComuptedReportItem
- Renamed filterBy props as groupByValue
- Added filter_by params to summary cards
- Modified breakdown querys to include group_by from previous page as a filter
https://issues.redhat.com/browse/COST-1131
**Details page with filters**
**Breakdown page**
=> Incorrect data with multiple filters

scripts/utils/i18n_excludes, src/locales/en.json, src/store/dashboard/awsCloudDashboard/awsCloudDashboardWidgets.ts, src/store/dashboard/awsDashboard/awsDashboardWidgets.ts, src/store/dashboard/azureCloudDashboard/azureCloudDashboardWidgets.ts, src/store/dashboard/azureDashboard/azureDashboardWidgets.ts, src/store/dashboard/gcpDashboard/gcpDashboardWidgets.ts, src/store/dashboard/ibmDashboard/ibmDashboardWidgets.ts, src/store/dashboard/ocpCloudDashboard/ocpCloudDashboardWidgets.ts, src/store/dashboard/ocpDashboard/ocpDashboardWidgets.ts, src/store/dashboard/ocpSupplementaryDashboard/ocpSupplementaryDashboardWidgets.ts, src/store/dashboard/ocpUsageDashboard/ocpUsageDashboardWidgets.ts
The below keys have all been consolidated and moved under "dashboard" in the i18n json file
Original key values:
**"Database services cost"                                                   [Found: 7]**
- 	FOUND IN KEY: aws_cloud_dashboard.database_title
- 	FOUND IN KEY: aws_dashboard.database_title
- 	FOUND IN KEY: ibm_dashboard.database_title
- 	FOUND IN KEY: ocp_cloud_dashboard.database_title
- 	FOUND IN KEY: azure_cloud_dashboard.database_title
- 	FOUND IN KEY: azure_dashboard.database_title
- 	FOUND IN KEY: gcp_dashboard.database_title
**"Network services cost"                                                    [Found: 7]**
- 	FOUND IN KEY: azure_cloud_dashboard.network_title
- 	FOUND IN KEY: aws_dashboard.network_title
- 	FOUND IN …
=> consolidate duplicate i18n keys for dashboards.

src/api/providers.ts, src/modules/ocpOverviewWidget/ocpOverviewWidget.tsx, src/pages/views/details/awsDetails/awsDetails.tsx, src/pages/views/details/azureDetails/azureDetails.tsx, src/pages/views/details/components/breakdown/breakdownBase.tsx, src/pages/views/details/gcpDetails/gcpDetails.tsx, src/pages/views/details/ibmDetails/ibmDetails.tsx, src/pages/views/details/ocpDetails/ocpDetails.tsx, src/pages/views/explorer/explorer.tsx, src/pages/views/overview/overview.tsx, src/pages/views/utils/providers.ts
When displaying the "no data" state, we currently only check the `current_month_data` flag of the sources API. However, we can still show the overview page if there is data for the previous month. If there is no data for either month, then we should display an empty state.
- For the overview page, check the new `previous_month_data` flag; as well as, `current_month_data`.
- For the details pages, we only need to check the `current_month_data` flag.
- For the cost explorer, we shall check the `has_data` flag, since the date range may cover more than just the current and previous month.
=> No data states should check new previous_month_data and has_data flags

src/pages/views/components/export/exportModal.tsx, src/pages/views/components/export/exportSubmit.tsx
When the modal is opened, we're setting a default state. However, if the modal is opened a second time, it appears to lose its event handlers for `resolution` and `timeScope`.
This change resets the default state only when the modal is closed.
https://issues.redhat.com/browse/COST-1134
=> Reset export modal's default state upon close

src/locales/en.json, src/pages/views/components/export/exportSubmit.tsx
This change resets state for `ModalSubmit` upon close. Also added the current resolution, along with the current and previous months, to the filename.
https://issues.redhat.com/browse/COST-1134
=> Reset ModalSubmit state upon close

src/api/queries/userAccessQuery.ts, src/api/userAccess.ts, src/components/async/permissionsComponent/permissions.tsx, src/pages/views/explorer/explorer.tsx, src/pages/views/explorer/explorerHeader.tsx, src/pages/views/explorer/explorerUtils.ts, src/pages/views/overview/overview.tsx, src/store/userAccess/userAccessCommon.ts
GCP and IBM currently appear in the overview perspective menu for the stage environment.
For the Insights nav, we use type=beta with the user-access API to restrict access to the CI and QA environments. However, we're not currently using the param in the overview page itself.
https://issues.redhat.com/browse/COST-1172
=> GCP and IBM should use beta flag

src/pages/views/explorer/explorer.tsx
The Cost Explorer page is showing the "no providers" empty state incorrectly. For example, if we don't have a provider for GCP or IBM. It should only show that state if there are absolutely no providers available.
https://issues.redhat.com/browse/COST-1195
=> Cost Explorer empty state

src/components/sources/inactiveSources/inactiveSources.tsx, src/pages/views/explorer/explorer.tsx
The InteractiveSources component is not fetching IBM providers.
We use this component at the top level of the page to show alerts for inactive source providers. It should call the sources API with type=IBM, but that's missing.
https://issues.redhat.com/browse/COST-1198
=> InteractiveSources should fetch IBM sources

src/utils/getBaseName.ts
Cost Management has been moved under OpenShift. However, the Insights nav does not work as expected (e.g., with /beta/openshift/cost-management as the URL).
When we provide the router with a base name, we're not accounting for the new "openshift" path.
https://issues.redhat.com/browse/COST-1221
=> Fix base name for new /beta/openshift/cost-management path

src/components/async/permissionsComponent/permissions.tsx, src/pages/views/explorer/explorer.tsx, src/pages/views/explorer/explorerHeader.tsx, src/pages/views/overview/overview.tsx, src/store/userAccess/userAccessCommon.ts
This removes special code in the UI that calls the `user-access` API with `type=GCP` and `beta=true`. Since we no longer need the `beta=true` flag, we can call `user-access` with `type=` and get all providers via a single request.
Note that we still need to update the Insights nav in various CI environments.
https://issues.redhat.com/browse/COST-1225
=> Remove beta flag for GCP

src/pages/costModels/costModel/header.tsx
This fixes an issue where clicking on the cost-models breadcrumb sends the user to the overview page.
https://issues.redhat.com/browse/COST-1242
=> Cost models breadcrumb

src/pages/costModels/costModel/addSourceStep.tsx, src/pages/costModels/costModel/assignSourcesModalToolbar.tsx, src/pages/costModels/costModel/sourcesToolbar.tsx, src/pages/costModels/costModel/table.tsx, src/pages/costModels/costModelsDetails/utils/filters.tsx, src/pages/costModels/createCostModelWizard/assignSourcesToolbar.tsx, src/pages/costModels/createCostModelWizard/table.tsx
Closes: https://issues.redhat.com/browse/COST-1291
change search Input naming to filter input, this removes any confusion on if we are using the patternfly "SearchInput" or not.
filtering example:
https://user-images.githubusercontent.com/57504257/114737863-6cca3f80-9d15-11eb-8cc1-ba2fc94cc384.mov
=> change name from search input to filter input

src/pages/views/details/components/costChart/costChart.styles.ts, src/pages/views/details/components/costChart/costChart.tsx, src/pages/views/details/components/usageChart/usageChart.tsx
Updated the usage chart, shown in the breakdown page, to use the our `ResizeObserver` util. 
I also removed the resize listener from the cost chart, shown in the same breakdown page. It isn't necessary to resize a pie chart, since it does not span the entire width of the card.
=> Breakdown chart should use ResizeObserver

src/pages/costModels/costModel/addSourceStep.tsx
If a source is disabled, the "Add source" dialog's "select-all" checkbox should not be able to toggle that selection. Otherwise, users encounter an error when a source has already been assigned to a different cost model.
https://issues.redhat.com/browse/COST-1290
Source assigned to same cost model
Source assigned to a different cost model
=> Items in the "Add source" dialog should remain disabled

src/pages/views/explorer/explorerChart.tsx
This ensures that the Explorer chart legend displays account aliases.
https://issues.redhat.com/browse/COST-1316
=> Explorer chart legend items should use account aliases

src/components/charts/costExplorerChart/costExplorerChart.tsx, src/components/charts/dailyCostChart/dailyCostChart.tsx
The Explorer chart's interactive legend remains disabled after all items have been hidden. Need to omit the data instead of the entire component.
https://issues.redhat.com/browse/COST-1319
=> Interactive chart legend remains disabled

config/spandx.config.js
Insights moved Cost Management under OpenShift, so the spandx needs to be updated. Note that the old URLs still work for certain CI environments.
=> Added new URLs to spandx

src/components/charts/common/chartDatumUtils.ts, src/pages/views/explorer/explorerChart.tsx
This is a follow up to https://github.com/project-koku/koku-ui/pull/1949. Want to ensure charts save the project alias, similar to the Cost Explorer chart. 
https://issues.redhat.com/browse/COST-1316
=> Ensure charts save project alias

package.json, webpack.config.js
Replaced the `start:dev` target with `start:beta` to make it clear what environment devs are running locally. This mimics the `start:beta` target of the Insights starter app.
When accessing `https://ci.foo.redhat.com:1337/beta/openshift/cost-management/`; for example, we should run the `start:beta` target. However, when accessing `https://ci.foo.redhat.com:1337/openshift/cost-management/`, we must run the `start` target. Otherwise, `fed-mods.json` is not located via webpack's public path.
=> Replaced start:dev target with start:beta

src/api/reports/report.ts, src/components/reports/reportSummary/reportSummaryItems.tsx, src/locales/en.json, src/pages/views/details/components/summary/summaryCard.tsx, src/utils/computedReport/getComputedReportItems.ts
This restores the count to "Other/Others" labels, shown via the top costliest projects in the Overview and Cost Explorer pages.
The costs API removed the "others" count from each project ID (e.g., "1 Other", "6 Others", etc.). There is now a single project, named "Others" and the count is provided via meta data.
https://issues.redhat.com/browse/COST-1328
Cost Explorer
Cost by projects
Top regions
=> Restore count to "Others" label

src/utils/computedReport/getComputedReportItems.ts
As a workaround, I've updated the UI to ignore empty account_alias strings. However, it would be ideal if the API did not return empty strings.
https://issues.redhat.com/browse/COST-1326
=> Omit empty strings returned by APIs

src/api/tags/awsCloudTags.ts, src/api/tags/azureCloudTags.ts, src/api/tags/ocpCloudTags.ts, src/api/tags/tag.ts, src/api/tags/tagUtils.ts, src/locales/en.json, src/pages/views/components/groupBy/groupBy.tsx, src/pages/views/details/awsDetails/detailsToolbar.tsx, src/pages/views/details/azureDetails/detailsToolbar.tsx, src/pages/views/details/components/tag/tagLink.tsx, src/pages/views/details/components/tag/tagModal.tsx, src/pages/views/details/gcpDetails/detailsToolbar.tsx, src/pages/views/details/ibmDetails/detailsToolbar.tsx, src/pages/views/details/ocpDetails/detailsToolbar.tsx, src/pages/views/explorer/explorer.tsx, src/pages/views/explorer/explorerChart.tsx, src/pages/views/explorer/explorerFilter.tsx, src/pages/views/explorer/explorerHeader.tsx, src/pages/views/explorer/explorerTable.tsx, src/pages/views/explorer/explorerUtils.ts, src/pages/views/overview/overview.tsx, src/utils/dateRange.ts
Added unique API requests for OCP on cloud, OCP on AWS, and OCP on Azure. When the Cost Explorer's "Perspective" menu changes, these additional requests are mad for tags.
https://issues.redhat.com/browse/COST-1338
=> Additional tag requests for Cost Explorer

src/pages/views/explorer/explorerUtils.ts
The Cost Explorer should show infrastructure cost for the "OpenShift usage" perspective. Currently, we're showing the same cost as "All OpenShift".
https://issues.redhat.com/browse/COST-1371
=> Cost Explorer to show infrastructure cost for "OpenShift usage"

src/components/sources/inactiveSources/inactiveSources.tsx
The inactive sources widget only shows problems with OCP, AWS, and Azure. We need to include GCP and IBM as well.
https://issues.redhat.com/browse/COST-1375
=> Add GCP and IBM to inactive sources

src/components/charts/costExplorerChart/costExplorerChart.tsx
This modifies the Cost Explorer to dynamically adjust bar widths based on the screen size. Spacing is divided equally so bars fill up the available space in the chart.
https://issues.redhat.com/browse/COST-1383
=> Cost Explorer bar width

src/pages/views/explorer/explorer.tsx, src/pages/views/explorer/explorerHeader.tsx
Since each perspective (i.e., OCP, AWS, etc.) has unique order_by values (i.e., account Vs account_alias, etc.), we need to clear the Cost Explorer sort whenever a new perspective or group_by is selected. Otherwise, the order_by value may not be valid for new API requests.
https://issues.redhat.com/browse/COST-1411
=> Clear sort when group_by is updated

src/pages/views/components/export/exportModal.tsx, src/pages/views/details/awsDetails/awsDetails.tsx, src/pages/views/details/azureDetails/azureDetails.tsx, src/pages/views/details/components/actions/actions.tsx, src/pages/views/details/gcpDetails/gcpDetails.tsx, src/pages/views/details/ibmDetails/ibmDetails.tsx, src/pages/views/details/ocpDetails/ocpDetails.tsx, src/pages/views/explorer/explorer.tsx
The Cost Explorer work uses the new `start_date` and `end_date` parameters introduced to the cost APIs. However, the monthly resolution was disabled for the API.
Until monthly resolution can be supported, we want to hide the aggregate type selection from the Cost Explorer's export dialog.
https://issues.redhat.com/browse/COST-1453
=> Hide aggregate type from Cost Explorer's export dialog

config/spandx.config.js, scripts/start-dev-server.js, webpack.config.js
Refactored webpack config to work with the Insights (Docker) proxy.
=> Refactored webpack to work with Insights proxy

src/pages/views/explorer/explorerHeader.tsx, src/pages/views/overview/overview.tsx
The team requested that we temporary omit "All cloud filtered by OpenShift" option from the overview and cost explorer pages.
https://issues.redhat.com/browse/COST-1483
=> Omit "All cloud filtered by OpenShift" option

scripts/start-dev-server.js, src/federatedEntry.tsx, webpack.config.js
For testing PatternFly pre-release packages, we cannot use shared PatternFly dependencies. We also cannot use paths to local repos as a package dependency.
This update simply adds a choice to the start up script to share (default) PatternFly dependencies or not. If true, we prune PatternFly from the package dependencies shared with Insights.
=> Added choice to startup script for using shared PatternFly modules

src/components/charts/costChart/costChart.tsx, src/components/charts/dailyCostChart/dailyCostChart.tsx, src/components/charts/dailyTrendChart/dailyTrendChart.tsx, src/components/charts/trendChart/trendChart.tsx
We want to use left pointing triangles as chart legend symbols. Until now, PatternFly / Victory only supported up and down pointing triangles, not left and right. A left pointing triangle would better represent a forecast's "cone of confidence" in our tooltips.
https://issues.redhat.com/browse/COST-1484
=> Replaced chart legend triangleUp symbols with triangleLeft

src/locales/en.json
For Microsoft Azure and Google Cloud Platform, both of them use "an" and should use "a"
https://issues.redhat.com/browse/COST-1493
=> GCP & Azure empty states have grammatical error

src/components/charts/dailyTrendChart/dailyTrendChart.tsx, src/components/charts/trendChart/trendChart.tsx, src/locales/en.json, src/pages/views/overview/components/dashboardWidgetBase.tsx, src/pages/views/overview/ocpInfrastructureDashboard/index.ts, src/pages/views/overview/ocpInfrastructureDashboard/ocpInfrastructureDashboard.tsx, src/pages/views/overview/ocpInfrastructureDashboard/ocpInfrastructureDashboardWidget.tsx, src/pages/views/overview/overview.tsx, src/store/dashboard/common/dashboardCommon.ts, src/store/dashboard/ocpDashboard/ocpDashboardWidgets.ts, src/store/dashboard/ocpInfrastructureDashboard/index.ts, src/store/dashboard/ocpInfrastructureDashboard/ocpInfrastructureDashboardActions.ts, src/store/dashboard/ocpInfrastructureDashboard/ocpInfrastructureDashboardCommon.ts, src/store/dashboard/ocpInfrastructureDashboard/ocpInfrastructureDashboardReducer.ts, src/store/dashboard/ocpInfrastructureDashboard/ocpInfrastructureDashboardSelectors.ts, src/store/dashboard/ocpInfrastructureDashboard/ocpInfrastructureDashboardWidgets.ts, src/store/rootReducer.ts
Added OpenShift Infrastructure perspective to overview. This moves the infrastructure data, from the "All" perspective, to its own chart. This new perspective mimics the supplementary view.
https://issues.redhat.com/browse/COST-1491
**New "OpenShift infrastructure" perspective**
**New "All OpenShift" perspective**
**Old "All" perspective**
=> OpenShift Infrastructure chart

src/components/charts/common/chartUtils.ts, src/components/charts/dailyTrendChart/dailyTrendChart.tsx, src/components/charts/trendChart/trendChart.tsx, src/store/dashboard/ocpDashboard/ocpDashboardWidgets.ts
Updated the charts to show the forecast cone of confidence as its own legend item. I also used that new left-pointed triangle I created for PatternFly charts
https://issues.redhat.com/browse/COST-1492
**Cumulative view**
**Daily view**
=> Cone of confidence legend item

src/api/resources/awsResource.ts, src/api/resources/resourceUtils.ts
Enables the AWS regions and services typeahead feature.
https://issues.redhat.com/browse/COST-1565
**Regions**
**Services**
=> AWS regions and services typeahead

src/pages/views/details/awsDetails/detailsTable.tsx, src/pages/views/details/azureDetails/detailsTable.tsx, src/pages/views/details/gcpDetails/detailsTable.tsx, src/pages/views/details/ibmDetails/detailsTable.tsx, src/pages/views/details/ocpDetails/detailsTable.tsx
The details pages generate links with `group_by[date]` instead of `group_by[tag:tag_key]`
https://issues.redhat.com/browse/COST-1510
=> Breakdown link's group_by param is missing tag key

src/pages/costModels/costModelsDetails/utils/table.tsx, src/store/costModels/selectors.ts
Refactored cost models' empty state to test user filters only. 
Instead of looking at query params; `limit` and `offset`, it would be best to test if the `name`, `description`, and `source_type` have been filtered. In addition, there's no need to test `ordering` -- the empty state should be shown, regardless.
https://issues.redhat.com/browse/COST-1518
**Empty state**
**No match**
**Loading**
=> Cost model empty state not displaying when no models

src/components/charts/trendChart/trendChart.tsx
Small tweak to adjust chart legend responsiveness for OCP supplementary view.
=> Adjust chart legend responsiveness

src/pages/views/details/awsDetails/awsDetails.tsx, src/pages/views/details/awsDetails/detailsTable.tsx, src/pages/views/details/azureDetails/azureDetails.tsx, src/pages/views/details/azureDetails/detailsTable.tsx, src/pages/views/details/gcpDetails/detailsTable.tsx, src/pages/views/details/gcpDetails/gcpDetails.tsx, src/pages/views/details/ibmDetails/detailsTable.tsx, src/pages/views/details/ibmDetails/ibmDetails.tsx, src/pages/views/details/ocpDetails/detailsTable.tsx, src/pages/views/details/ocpDetails/ocpDetails.tsx, src/pages/views/explorer/explorer.tsx
For OCP details, the "no-project" checkbox is disabled. However, the user may choose to "select-all items" or "select all items in the page" via the bulk selector.
This change omits "no-project" from the export modal.
https://issues.redhat.com/browse/COST-1580
=> no-project items shouldn't be exportable

src/pages/costModels/costModel/header.tsx
The tab's bottom border should extend to the page margin, similar to the overview tabs.
https://issues.redhat.com/browse/COST-1581
=> Cost models tab border is too short

src/pages/costModels/costModelsDetails/utils/filters.tsx
The PatternFly TextInput requires either an ID or aria-label to be specified.
https://issues.redhat.com/browse/COST-1585
=> Cost models filter outputs a11y error message

koku-ui-manifest, package.json, webpack.config.js, yarn.lock
jira: https://issues.redhat.com/browse/RHCLOUD-14981
We also have to add the `useCloud` flag to use the `cloud.redhat.com` instead `console.redhat.com` until the migration happens.
cc @dlabrecq
=> Update config utils.

scripts/start-dev-server.js
Although `stage.foo.redhat.com` isn't working at the moment, this makes it possible to test the environment. That is, along with the package update in https://github.com/project-koku/koku-ui/pull/2001.
=> Add stage as an option for start script

src/app.tsx, src/federatedEntry.tsx
jira: https://issues.redhat.com/browse/RHCLOUD-15177
TLDR: This problem cannot be fixed in chrome because that causes issues in other applications.
- use router pathname to extract app nav pathname
- this is the preferred way forwards
- once new navigation is all the way in prod we will expose a hook with the current link pathname so no event listening will be necessary
=> Fix chrome navigation to overview.

webpack.config.js
Update webpack to include `CLOUDOT_ENV` for the proxy's `env` prop. This will ensure we can run against prod-beta, prod-stable, etc. and not just CI environments.
Follow up to https://github.com/project-koku/koku-ui/pull/2005.
=> Update webpack to include CLOUDOT_ENV

src/store/dashboard/azureCloudDashboard/azureCloudDashboardWidgets.ts, src/store/dashboard/azureDashboard/azureDashboardWidgets.ts
At one time, the Azure cost report did not provide units for the Overview's "Virtual machines usage" card. The API returned undefined as the value, so the UI hard-coded "VM-hours".
https://issues.redhat.com/browse/COST-1644
=> Replace Azure's VM-hours with hours

src/store/dashboard/azureCloudDashboard/azureCloudDashboardWidgets.ts, src/store/dashboard/azureDashboard/azureDashboardWidgets.ts
The API endpoint for azure storage is now providing units.
=> remove hard coded unit in azure's storage widget

src/api/resources/azureResource.ts, src/api/resources/resource.ts, src/api/resources/resourceUtils.ts, src/pages/views/details/awsDetails/detailsToolbar.tsx, src/pages/views/details/azureDetails/detailsToolbar.tsx, src/pages/views/explorer/explorerUtils.ts
Update the Azure details page and Cost Explorer to use new type-ahead features (i.e., account, region, & services) introduced via the `resource-types` API.
=> 1649 type-ahead azure

src/api/resources/ocpResource.ts, src/api/resources/resource.ts, src/api/resources/resourceUtils.ts, src/pages/views/components/resourceTypeahead/resourceSelect.tsx, src/pages/views/details/ocpDetails/detailsToolbar.tsx, src/pages/views/explorer/explorerUtils.ts
Update the OCP details page and Cost Explorer to use new typeahead features (i.e., clusters, projects, & nodes) introduced via the `resource-types` API.
=> OCP type-ahead support

src/api/resources/gcpResource.ts, src/api/resources/resource.ts, src/api/resources/resourceUtils.ts, src/pages/views/details/gcpDetails/detailsToolbar.tsx, src/pages/views/explorer/explorerUtils.ts
Update the GCP details page and Cost Explorer to use new type-ahead features (i.e., account, region, services, & project) introduced via the `resource-types` API.
=> GCP type-ahead support

src/api/resources/ibmResource.ts, src/api/resources/resource.ts, src/api/resources/resourceUtils.ts, src/pages/views/details/ibmDetails/detailsToolbar.tsx, src/pages/views/explorer/explorerUtils.ts
Update the IBM details page and Cost Explorer to use new type-ahead features (i.e., account, region, services, & project) introduced via the `resource-types` API.
Implemented functionality using GCP APIs, for now.
=> IBM type-ahead support

src/locales/en.json
The Cost Explorer perspective option should be renamed as "OpenShift infrastructure usage cost".
Currently, the Cost Explorer shows "OpenShift usage" as a perspective option; however, this view is shown under the "Infrastructure" tab of the overview page.
https://issues.redhat.com/browse/COST-1660
=> Rename Cost Explorer's "OpenShift usage" perspective label

src/pages/views/explorer/explorer.tsx, src/pages/views/explorer/explorerChart.tsx, src/pages/views/explorer/explorerHeader.tsx, src/pages/views/explorer/explorerUtils.ts, src/pages/views/utils/groupBy.ts
This ensures the Cost Explorer's group_by key is not undefined.
https://issues.redhat.com/browse/COST-1662
=> Cost explorer group_by key may be undefined

src/pages/views/explorer/explorer.tsx, src/pages/views/explorer/explorerChart.tsx, src/pages/views/explorer/explorerTable.tsx, src/pages/views/explorer/explorerUtils.ts
The Cost Explorer's "OpenShift infrastructure usage cost" perspective option appears to be using `infrastructure.total` instead of `infrastructure.usage`.
https://issues.redhat.com/browse/COST-1661
=> Cost explorer should show infrastructure.usage values

src/pages/views/overview/components/dashboardWidgetBase.tsx
Currently, we connect the cone of confidence with the last day of the current month. However, it's preferred to show the gap when data is missing.
https://issues.redhat.com/browse/COST-1468
=> Forecast should include gap in the data

src/pages/views/explorer/explorer.tsx, src/pages/views/explorer/explorerHeader.tsx
Discovered an edge case where the Cost Explorer accidentally shows a cached perspective option. This ensures the perspective menu is reset.
https://issues.redhat.com/browse/COST-1669
=> Cost Explorer reset cached perspective

src/api/resources/awsCloudResource.ts, src/api/resources/resource.ts, src/api/resources/resourceUtils.ts, src/pages/views/explorer/explorerHeader.tsx, src/pages/views/explorer/explorerUtils.ts
Updated Cost Explorer's "AWS filtered by OpenShift" perspective to use new type-ahead features (i.e., account, region, services, & project) introduced via the `resource-types` API.
https://issues.redhat.com/browse/COST-1675
=> "AWS filtered by OpenShift" type-ahead support

src/pages/views/overview/components/dashboardWidgetBase.tsx, src/store/costModels/actions.ts, src/store/dashboard/awsDashboard/awsDashboardWidgets.ts, src/store/dashboard/azureDashboard/azureDashboardWidgets.ts, src/store/dashboard/common/dashboardCommon.ts, src/store/dashboard/gcpDashboard/gcpDashboardWidgets.ts, src/store/dashboard/ibmDashboard/ibmDashboardWidgets.ts, src/store/dashboard/ocpDashboard/ocpDashboardWidgets.ts
The Insights team recently changed the Chrome navigation and calling `insights.chrome.appNavClick` is no longer necessary.
https://issues.redhat.com/browse/COST-1640
=> Remove insights.chrome.appNavClick

src/api/resources/azureCloudResource.ts, src/api/resources/resource.ts, src/api/resources/resourceUtils.ts, src/pages/views/explorer/explorerUtils.ts
Updated Cost Explorer's "Microsoft Azure filtered by OpenShift" perspective to use new type-ahead features (i.e., account, region, services, & project) introduced via the `resource-types` API.
https://issues.redhat.com/browse/COST-1676
=> "Microsoft Azure filtered by OpenShift" type-ahead support

src/api/forecasts/forecast.ts, src/api/forecasts/forecastUtils.ts, src/api/forecasts/gcpOcpForecast.ts, src/api/reports/gcpOcpReports.test.ts, src/api/reports/gcpOcpReports.ts, src/api/reports/report.ts, src/api/reports/reportUtils.ts, src/api/resources/gcpOcpResource.ts, src/api/resources/resource.ts, src/api/resources/resourceUtils.ts, src/locales/en.json, src/pages/views/overview/gcpOcpDashboard/gcpOcpDashboard.tsx, src/pages/views/overview/gcpOcpDashboard/gcpOcpDashboardWidget.test.tsx, src/pages/views/overview/gcpOcpDashboard/gcpOcpDashboardWidget.tsx, src/pages/views/overview/gcpOcpDashboard/index.ts, src/pages/views/overview/overview.tsx, src/store/dashboard/gcpOcpDashboard/__snapshots__/gcpOcpDashboard.test.ts.snap, src/store/dashboard/gcpOcpDashboard/gcpOcpDashboard.test.ts, src/store/dashboard/gcpOcpDashboard/gcpOcpDashboardActions.ts, src/store/dashboard/gcpOcpDashboard/gcpOcpDashboardCommon.ts, src/store/dashboard/gcpOcpDashboard/gcpOcpDashboardReducer.ts, src/store/dashboard/gcpOcpDashboard/gcpOcpDashboardSelectors.ts, src/store/dashboard/gcpOcpDashboard/gcpOcpDashboardWidgets.ts, src/store/dashboard/gcpOcpDashboard/index.ts, src/store/rootReducer.ts
This stubs-out the "GCP filtered by OpenShift" overview page. Until new APIs are ready, we're using the existing GCP APIs.
https://issues.redhat.com/browse/COST-1693
=> GCP filtered by OpenShift

src/api/tags/gcpOcpTags.test.ts, src/api/tags/gcpOcpTags.ts, src/api/tags/tag.ts, src/api/tags/tagUtils.ts, src/locales/en.json, src/pages/views/explorer/explorerHeader.tsx, src/pages/views/explorer/explorerUtils.ts
This stubs-out the "GCP filtered by OpenShift" perspective for the Cost Explorer. Until new APIs are ready, we will use the existing GCP APIs.
https://issues.redhat.com/browse/COST-1703
=> OCP filtered by OpenShift - Cost Explorer

src/api/api.ts, src/api/forecasts/forecast.ts, src/api/orgs/org.ts, src/api/providers.ts, src/api/reports/report.ts, src/api/resources/resource.ts, src/api/tags/tag.ts
The `Report` interface currently defines its own types for `ReportData`, `ReportLinks`, and `ReportMeta`. However, `api.ts` also defines similar interfaces for `PagedLinks`, `PagedMetaData`, and `PagedResponse`.
With a slight modification, the `Report` interface could extend `PagedResponse`. Thus, eliminating the need for the `ReportLinks` interface.
There are similar interfaces for tags, resources, forecasts, etc.
https://issues.redhat.com/browse/COST-1708
=> API interfaces should extend PagedResponse

src/pages/views/explorer/explorerHeader.tsx, src/pages/views/overview/overview.tsx
Temporarily hide the "GCP filtered by OpenShift" perspective from the overview and Cost Explorer, until new APIs are ready. This will ensure the new feature is not accidentally pushed to production.
https://issues.redhat.com/browse/COST-1705
=> Hide "GCP filtered by OpenShift" perspective

scripts/start-dev-server.js, webpack.config.js
We want to change webpackk.config.js to `useCloud: false`, since `cloud.stage.readhat.com` is going away.
Also changed the startup script to default to using the `stage` env.
https://issues.redhat.com/browse/COST-1726
=> webpack config should use useCloud=false

src/locales/en.json, src/pages/views/details/awsDetails/detailsHeader.styles.ts, src/pages/views/details/awsDetails/detailsHeader.tsx, src/pages/views/details/azureDetails/detailsHeader.styles.ts, src/pages/views/details/azureDetails/detailsHeader.tsx, src/pages/views/details/components/breakdown/breakdownHeader.styles.ts, src/pages/views/details/components/columnManagement/columnManagementModal.tsx, src/pages/views/details/gcpDetails/detailsHeader.styles.ts, src/pages/views/details/gcpDetails/detailsHeader.tsx, src/pages/views/details/ibmDetails/detailsHeader.styles.ts, src/pages/views/details/ibmDetails/detailsHeader.tsx, src/pages/views/details/ocpDetails/detailsHeader.styles.ts, src/pages/views/details/ocpDetails/detailsHeader.tsx, src/pages/views/details/ocpDetails/ocpDetails.tsx
Move date in details page heading to its own line and increase font size to 16px.
Add infrastructure and supplementary descriptions to column management dialog.
**Ocp details:**
**Column management:**
=> Move date in details page heading to its own line

src/locales/en.json, src/pages/views/overview/components/__snapshots__/dashboardWidget.test.tsx.snap, src/pages/views/overview/components/dashboardWidgetBase.tsx, src/pages/views/overview/overview.styles.ts, src/pages/views/overview/overview.tsx
Move dates from card subtitles to overview page heading.
https://issues.redhat.com/browse/COST-1721
**After:**
**Before:**
=> Move overview card title dates

README.md
With all the recent proxy changes, the README has become outdated.
https://issues.redhat.com/browse/COST-1750
=> Updated instructions for developing with webpack proxy

.travis/custom_release.sh
Now that stage-beta is being promoted as expected, we no longer need to push to ci-beta.
https://issues.redhat.com/browse/COST-1759
=> Update Travis to push to stage-beta only

src/pages/costModels/costModel/addSourceStep.tsx, src/pages/costModels/costModel/addSourceWizard.tsx
closed: https://issues.redhat.com/browse/COST-1758
The assign sources button should be disabled until there is a change from the current config.
With the fix we can see the button is disabled util there is change from current state/config
With a source previously assigned
=> fix for assign source button

src/pages/views/explorer/explorerChart.tsx
This forces "no data" tooltips to display in the Cost Explorer.
https://issues.redhat.com/browse/COST-1765
=> Force "no data" tooltips to display

src/api/exports/awsOcpExport.ts, src/api/exports/azureOcpExport.ts, src/api/exports/exportUtils.ts, src/api/exports/gcpOcpExport.ts, src/locales/en.json, src/pages/views/components/export/exportModal.styles.ts, src/pages/views/components/export/exportModal.tsx, src/pages/views/components/export/exportSubmit.tsx
1. Increased the number of items in exported csv files using the `limit=0` query parameter.
2. Added a generic error message.
3. Fixed missing exports for "filtered by OpenShift" perspectives for Cost Explorer.
https://issues.redhat.com/browse/COST-1690
=> Export limit

src/api/providers.ts, src/pages/views/overview/overview.tsx, src/pages/views/utils/providers.ts
Empty states are not being displayed correctly for "xxx filtered by OpenShift" perspectives. For this type of filter, we need to look at its associated OCP source.
A new `infrastructure.uuid` property was added to OCP sources. We can use this to match the uuid of the "AWS filtered by OpenShift" source with the OCP source. Once we have the correct OCP source, we can test its `current_month_data` and `previous_month_data` properties.
https://issues.redhat.com/browse/COST-1776
=> Use infrastructure.uuid property for empty states

locales/data.json, locales/de.json, locales/fr.json, locales/translations.json, src/components/charts/common/chartDatumUtils.ts, src/locales/messages.ts, src/utils/formatValue.test.ts, src/utils/formatValue.ts
Changed message keys to use snake case for group_bys and units
Azure breakdown page, which uses `subscription_guid` as "Accounts"
Overview page, which uses `gb_hours`, `gb_mo`, etc.
=> Snake case keys

.eslintrc.json, src/pages/costModels/createCostModelWizard/markup.tsx
The rule put in place should help stop the use of relative paths for all files but *.json or *.styles suffixed files.
=> Import rules

.eslintrc.json
Removed no-restricted-imports patterns which appear to be unused. For example, we probably don't want to error on "**.json" files, specifically.
=> Removed unused no-restricted-imports patterns

src/pages/views/components/resourceTypeahead/resourceSelect.tsx
Empty strings in type-ahead generate bad API requests
https://issues.redhat.com/browse/COST-1812
=> Empty strings in type-ahead

src/pages/views/explorer/explorerUtils.ts
Cost explorer is generating extra API requests. Some query params are not valid for the current perspective because it's based on sources API requests which are still in progress.  
We need to wait until those requests have returned before attempting to generate an API request for the cost report.
https://issues.redhat.com/browse/COST-1813
=> Extra cost explorer requests

src/__mocks__/react-intl.tsx, src/components/i18n/index.ts, src/components/i18n/intl.ts, src/components/state/emptyFilterState/emptyFilterState.tsx, src/components/state/loadingState/loadingState.tsx, src/pages/costModels/costModel/dialog.tsx, src/pages/costModels/costModelsDetails/createCostModelButton.tsx, src/pages/costModels/costModelsDetails/table.tsx
Cleaned up react-int testing. 
Instead of using a mock as the intl default, we can use the actual intl instance.
=> Clean up react-int testing

src/components/charts/costExplorerChart/costExplorerChart.tsx
=> Localized cost explorer chart

src/utils/__snapshots__/valueFormatter.test.ts.snap, src/utils/valueFormatter.ts
Fixed `unknownFormatter` options
https://issues.redhat.com/browse/COST-1859
=> Fixed unknownFormatter options

src/pages/views/details/awsDetails/awsDetailsTable.scss, src/pages/views/details/azureDetails/azureDetailsTable.scss, src/pages/views/details/gcpDetails/gcpDetailsTable.scss, src/pages/views/details/ibmDetails/ibmDetailsTable.scss, src/pages/views/explorer/explorerTable.scss
For the details pages "month over month change", I added space between the up arrow and percentage, matching the down arrow.
https://issues.redhat.com/browse/COST-1858
=> Added space between up arrow and percentage

src/pages/views/explorer/explorer.tsx, src/pages/views/explorer/explorerTable.scss, src/pages/views/explorer/explorerTable.tsx
This adds daily sorting to the Cost Explorer's table.
Blocked by https://github.com/project-koku/koku/pull/3081
https://issues.redhat.com/browse/COST-1689
=> Cost Explorer: Sort daily cost

src/pages/costModels/costModel/markup.tsx, src/pages/costModels/createCostModelWizard/review.tsx
Removed the hard coded '%" characters in the wizard review and cost calculations markup.
https://issues.redhat.com/browse/COST-1892
=> Cost models percentages are not localized

locales/data.json, locales/translations.json, src/locales/messages.ts, src/pages/costModels/components/inputs/rateInput.tsx, src/pages/costModels/components/rateForm/useRateForm.tsx, src/pages/costModels/components/rateForm/utils.tsx, src/pages/costModels/costModel/costCalc.styles.ts, src/pages/costModels/costModel/updateMarkupDialog.tsx, src/utils/format.ts
The cost models markup dialog currently shows a validation error for the German locale. One issue is related to the validator, which doesn't account for different decimal separators.
I refactored to format markup based on the browser's locale. In addition, I've added validation messages, similar to the rate input field. This also simplifies the modal logic a bit. 
Note: The wizard will be update via a separate PR.
**After**
**Before**
=> Markup shows validation error for German locale

src/pages/costModels/costModel/markup.tsx, src/pages/costModels/costModel/updateMarkupDialog.tsx, src/pages/costModels/createCostModelWizard/index.tsx, src/pages/costModels/createCostModelWizard/markup.tsx
The cost models markup dialog currently shows a validation error for the German locale. One issue is related to the validator, which doesn't account for different decimal separators.
- Updated wizard markup step to match "cost calculations" edit dialog
- Formatted "cost calculations" card to show 10 decimal places 
**Wizard markup step**
**Cost calculations markup card**
=> Markup shows validation error for German locale (part 2 of 2)

locales/data.json, locales/translations.json, src/locales/messages.ts, src/pages/costModels/components/inputs/rateInput.tsx, src/pages/costModels/costModel/markup.tsx, src/pages/costModels/costModel/updateMarkupDialog.tsx, src/pages/costModels/createCostModelWizard/index.tsx, src/pages/costModels/createCostModelWizard/markup.tsx, src/pages/costModels/createCostModelWizard/steps.tsx
Localized the RateInput aria-label and placeholder.
https://issues.redhat.com/browse/COST-1893
In addition, I fixed the wizard step validator to match the markup validator. That is, the next button should not be enabled unless the markup is valid. That should include checking the number of decimal places, white spaces, etc.
**Wizard markup next step button**
**Add Rate placeholder**
=> RateInput component not localized

src/components/currency/currency.tsx, src/components/inactiveSources/inactiveSources.tsx, src/globals.d.ts, src/pages/views/explorer/explorerUtils.ts, src/utils/localStorage.ts
We want to show a couple features based only in the beta environment. Specifically, the Cost Explorer 90 days view and the currency selector in the page headers.
**Stage environment**
**Beta environment**
=> Show new features in beta environment only

src/pages/costModels/createCostModelWizard/context.ts, src/pages/costModels/createCostModelWizard/index.tsx, src/pages/costModels/createCostModelWizard/markup.tsx
The wizard's `CostModelContext` object contains a few functions used by the `MarkupWithDistribution` step. Specifically, `handleOnKeyDown` and `markupValidator`.
Considering this step is never reused, and the functions don't set state, they may be better located in the `MarkupWithDistribution` component.
https://issues.redhat.com/browse/COST-1898
=> Remove MarkupWithDistribution functions from CostModelContext

src/pages/views/explorer/explorerHeader.tsx, src/pages/views/overview/overview.tsx
Show "All cloud filtered by OpenShift" feature in beta environment only. Specifically re-enables the "All cloud filtered by OpenShift" perspective option for the overview and cost explorer pages.
https://issues.redhat.com/browse/COST-1899
**Overview in stage-beta environment**
**Cost explorer in stage-beta environment**
**Overview in stage environment**
**Cost explorer in stage environment**
=> Show "All cloud filtered by OpenShift" for beta environment only

src/components/costType/costType.styles.ts, src/components/costType/costType.tsx, src/components/currency/currency.scss, src/components/currency/currency.styles.ts, src/components/currency/currency.tsx, src/pages/views/components/dataToolbar/dataToolbar.scss, src/pages/views/components/dataToolbar/dataToolbar.tsx, src/pages/views/components/perspective/perspective.styles.ts, src/pages/views/components/perspective/perspective.tsx, src/pages/views/explorer/explorerHeader.tsx, src/pages/views/overview/overview.tsx
Per the PatternFly guidelines, and after speaking with Natalie, we should be using PatternFly Select components instead of Dropdown for our overview and details pages.
This updates dropdowns for currency, "show cost as", and perspective.
=> Convert Dropdown components to use Select (1 of many)

src/utils/format.ts
The decimal count is validated separately to show a unique error message. This particular function currently prevents that test from being performed on text inputs.
https://issues.redhat.com/browse/COST-1927
=> Fixed decimal count validation

src/api/reports/awsReports.ts, src/pages/views/details/awsBreakdown/awsBreakdown.tsx, src/pages/views/details/awsDetails/awsDetails.tsx, src/pages/views/details/components/historicalData/historicalDataCostChart.tsx, src/pages/views/details/components/historicalData/historicalDataTrendChart.tsx, src/pages/views/details/components/summary/summaryCard.tsx, src/pages/views/explorer/explorer.tsx, src/pages/views/explorer/explorerChart.tsx, src/store/dashboard/awsDashboard/awsDashboardSelectors.ts, src/store/reports/reportCommon.ts
We can simplify by adding the `cost_type` param in two places. Just needed to account for the report ID used to cache requests.
https://issues.redhat.com/browse/COST-1905
=> Simplify API requests for AWS cost savings plan

src/api/reports/awsReports.ts, src/globals.d.ts, src/pages/costModels/createCostModelWizard/generalInformation.tsx, src/pages/views/details/awsDetails/detailsHeader.tsx, src/pages/views/details/azureDetails/detailsHeader.tsx, src/pages/views/details/components/breakdown/breakdownHeader.tsx, src/pages/views/details/gcpDetails/detailsHeader.tsx, src/pages/views/details/ibmDetails/detailsHeader.tsx, src/pages/views/details/ocpDetails/detailsHeader.tsx, src/pages/views/explorer/explorerHeader.tsx, src/pages/views/explorer/explorerUtils.ts, src/pages/views/overview/overview.tsx, src/store/reports/reportCommon.ts, src/utils/feature.ts
The platform now has an isProd flag. We can use the isProd and isBeta flag to keep new features out of prod and prod-beta. This means, users will only see our "in progress" features in stage-beta.
https://issues.redhat.com/browse/COST-2028
=> Omit in-progress features from prod-beta

locales/data.json, locales/translations.json, src/locales/messages.ts, src/pages/views/components/dataToolbar/dataToolbar.tsx, src/pages/views/components/dataToolbar/tagValue.tsx, src/pages/views/components/groupBy/groupBy.tsx, src/pages/views/details/awsDetails/detailsToolbar.tsx, src/pages/views/details/azureDetails/detailsToolbar.tsx, src/pages/views/details/components/breakdown/breakdownHeader.tsx, src/pages/views/details/components/tag/tagLink.tsx, src/pages/views/details/components/tag/tagModal.tsx, src/pages/views/details/gcpDetails/detailsToolbar.tsx, src/pages/views/details/ibmDetails/detailsToolbar.tsx, src/pages/views/details/ocpDetails/detailsToolbar.tsx, src/pages/views/explorer/explorer.tsx, src/pages/views/explorer/explorerFilter.tsx, src/pages/views/explorer/explorerToolbar.tsx
For better performance, we would like the UI to lazily generate API requests for tags.
In order to populate the "group by" dropdown, an initial API request will be made for just the tag keys. Then, we can lazily request tag key values after the user chooses to filter by a particular tag key.
https://issues.redhat.com/browse/COST-2053
https://user-images.githubusercontent.com/17481322/140975408-50186ebb-bc53-4a18-aee3-28e2258410cb.mov
=> Lazy generate API requests for tags

src/store/dashboard/gcpDashboard/gcpDashboardCommon.ts
https://issues.redhat.com/browse/COST-2054
=> Overview page doesn't show "Top GCP projects"

src/pages/costModels/components/priceListToolbar.tsx, src/pages/costModels/costModel/assignSourcesModalToolbar.tsx, src/pages/costModels/costModel/sourcesToolbar.tsx, src/pages/costModels/costModelsDetails/toolbar.tsx, src/pages/costModels/createCostModelWizard/assignSourcesToolbar.tsx, src/pages/views/components/dataToolbar/dataToolbar.tsx
The toolbar isn't broken per se. The toolbar items are wrapping as expected. However, the details page toolbar wraps the filter with a PatternFly `ToolbarToggleGroup` component. 
For small windows, the PatternFly `ToolbarToggleGroup` component replaces the filter with a simple icon. When the icon is clicked, the filter is expanded onto its own line.
https://issues.redhat.com/browse/COST-2065
**Device toolbar**
=> Wrap toolbar filters with PF ToolbarToggleGroup

src/pages/views/components/dataToolbar/dataToolbar.tsx, src/pages/views/components/dataToolbar/tagValue.tsx, src/pages/views/details/awsDetails/detailsToolbar.tsx, src/pages/views/details/azureDetails/detailsToolbar.tsx, src/pages/views/details/gcpDetails/detailsToolbar.tsx, src/pages/views/details/ibmDetails/detailsToolbar.tsx, src/pages/views/details/ocpDetails/detailsToolbar.tsx
The PatternFly ToolbarFilter fails to save state when a "node" label is added to the user's settings list of available tags.
The debugger shows the issue may have something to do with how PatternFly tests `ToolbarChipGroup.hasOwnProperty`.
As a workaround, I'm able to provide a string to `ToolbarFilter.categoryName` instead of a `ToolbarChipGroup` object.
https://issues.redhat.com/browse/COST-2094
=> 2094 pf toolbar

src/pages/views/components/dataToolbar/dataToolbar.tsx, src/pages/views/details/ocpDetails/detailsToolbar.tsx
This adds a workaround to prevent category name collisions with the PatternFly ToolbarFilter
https://issues.redhat.com/browse/COST-2094
=> PatternFly ToolbarFilter error

src/pages/views/components/dataToolbar/dataToolbar.tsx, src/pages/views/components/dataToolbar/tagValue.tsx
This simplifies the previous workaround to prevent category name collisions with the PatternFly ToolbarFilter.
Note that the tag key value `Select` component already uses an existing tag prefix, so we can take advantage of that instead of adding a new prefix to the category `ToolbarFilter`.
https://issues.redhat.com/browse/COST-2094
=> PatternFly ToolbarFilter

src/pages/views/details/components/breakdown/breakdownHeader.styles.ts, src/pages/views/details/components/breakdown/breakdownHeader.tsx
Moved the cost type out of the PatternFly Title component's body.
**Before**
**After**
=> Cost type options appear bold in breakdown header

src/pages/costModels/costModel/addSourceStep.tsx, src/pages/costModels/costModel/addSourceWizard.tsx
The addSourceWizard.tsx component resets the selected list of items whenever new sources are loaded; for example, when paginating between table items. If we omit that, selections will be saved across pages.
https://issues.redhat.com/browse/COST-2097
=> Can't assign multiple sources to a cost model across paginated pages

src/pages/costModels/costModel/addSourceStep.tsx, src/pages/costModels/costModel/addSourceWizard.tsx, src/pages/costModels/costModel/sourceTable.tsx, src/pages/costModels/costModel/sourcesToolbar.tsx, src/pages/costModels/costModel/table.tsx
Modified the "add sources" dialog to retain the applied sources. Currently, anything previously assigned is replaced, unless everything is deselected first.
https://issues.redhat.com/browse/COST-2097
=> Modified the "add sources" dialog to retain the applied sources

src/pages/costModels/createCostModelWizard/api.ts, src/pages/costModels/createCostModelWizard/context.ts, src/pages/costModels/createCostModelWizard/index.tsx, src/pages/costModels/createCostModelWizard/review.tsx, src/pages/costModels/createCostModelWizard/table.tsx
The sources pagination did not function because it only counted items in the current page, not the API's meta count.
In addition, the cost models wizard only retains selections for the current page.
https://issues.redhat.com/browse/COST-2160
=> Pagination in cost model creation wizard shows only one page with sources

src/api/providers.test.ts, src/api/queries/providersQuery.ts, src/pages/costModels/createCostModelWizard/review.tsx, src/store/providers/providersCommon.ts
Noticed an issue with the overview and details pages, using the insights-qa user. We recently added 15 sources to test a bug, but now those pages display an empty state indicating we're processing data.
For the overview and details pages, the UI looks at the current_month_data property returned by the sources API. By default, the API only returns 10 items, and none of those sources have data. We need to look at all the sources.
To resolve this issue, we should add the `limit=100` param to the sources API request. For example:
api/cost-management/v1/sources/?type=OCP&limit=100
=> Add limit param to the sources API request

src/pages/views/components/resourceTypeahead/resourceInput.tsx
The PatternFly Text Input Group component, used for type-ahead has issues regarding keyboard navigation. 
When navigating items with the tab key, focus should move back to the input, before moving to another element in the page. This will allow the user to edit the text input and / or tab to the clear button.
https://issues.redhat.com/browse/COST-2203
=> Updated tab key navigation for type-ahead

src/api/metrics.test.ts, src/api/metrics.ts
The metrics API request is not picking up newly added units. There are now 11 metrics, but the API returns 10 by default.
We need to add a `limit` parameter to metrics API request, so we can display all units.
https://issues.redhat.com/browse/COST-2262
=> Add limit param to metrics API request

locales/data.json, locales/translations.json, src/locales/messages.ts, src/pages/costModels/components/rateForm/rateForm.tsx, src/pages/costModels/costModel/priceListTable.tsx, src/pages/costModels/createCostModelWizard/priceListTable.tsx
When creating rates, "Effective-usage" is presented as an option, but it should include units, similar to other localized options.
https://issues.redhat.com/browse/COST-2277
=> Effective-usage metric should include units

src/pages/views/details/components/usageChart/usageChart.tsx, src/utils/feature.ts
When showing bullet charts without capacity, the requests are shown in grey instead of blue. For example, when OCP is grouped by project instead of cluster.
In this case, requests are shown as the bullet chart's "qualitative range". To be consistent, requests and usage should be shown together as the "primary segmented measure".
https://issues.redhat.com/browse/COST-2363
**Before (grouped by project)**
**After (grouped by project)**
=> Bullet chart requests shown as range for no capacity

src/pages/views/overview/components/dashboardWidgetBase.tsx, src/store/dashboard/awsDashboard/awsDashboardWidgets.ts, src/store/dashboard/awsOcpDashboard/awsOcpDashboardWidgets.ts, src/store/dashboard/azureDashboard/azureDashboardWidgets.ts, src/store/dashboard/azureOcpDashboard/azureOcpDashboardWidgets.ts, src/store/dashboard/common/dashboardCommon.ts, src/store/dashboard/gcpDashboard/gcpDashboardWidgets.ts, src/store/dashboard/gcpOcpDashboard/gcpOcpDashboardWidgets.ts, src/store/dashboard/ibmDashboard/ibmDashboardWidgets.ts, src/store/dashboard/ocpCloudDashboard/ocpCloudDashboardWidgets.ts
Some overview charts are not showing tooltips correctly. For example, the AWS "Compute (EC2) instances usage" card is showing "HRS 96.00 hours" in the chart tooltip.
https://issues.redhat.com/browse/COST-2364
**Before**
**After**
=> Some chart tooltips are not formatted properly

locales/data.json, locales/translations.json, src/components/exports/exportsTable.tsx, src/locales/messages.ts, src/pages/costModels/costModel/costModelsDetails.styles.ts, src/pages/costModels/costModel/header.tsx, src/pages/costModels/costModelsDetails/header.styles.ts, src/pages/costModels/costModelsDetails/header.tsx, src/pages/views/details/components/breakdown/breakdownHeader.tsx, src/pages/views/overview/overview.tsx, src/store/export/exportActions.tsx, src/utils/feature.ts
Add content to "All exports" drawer
- Remove only our own success notification when clicking "all exports" link
- Table's delete action should be visible for failed exports
- Omit "All exports" link from overview, cost models, and breakdown pages.
- Update failed export alert message
https://issues.redhat.com/browse/COST-2339
**Failed alert message**
=> Add content to "All exports" drawer

src/api/queries/query.ts, src/pages/components/currency/currency.tsx, src/pages/views/components/costType/costType.tsx, src/pages/views/details/awsDetails/awsDetails.tsx, src/pages/views/explorer/explorerHeader.tsx, src/pages/views/overview/overview.tsx, src/store/accountSettings/accountSettingsReducer.ts, src/utils/localStorage.ts
Update how "Show cost as" value is cached
Testing:
1. Login via incognito window - to start with a clean slate
2. Navigate to account settings
3. Update the default "Show cost as" value
4. Navigate to AWS details and see the default value
5. Select a new "Show cost as" value (same page)
6. Refresh the page and confirm the new value has been applied
7. There should now be a cost_type query param in the page URL
8. Navigate to the Overview page and AWS perspective
9. Confirm the new value has been applied
10. Navigate to the Cost Explorer page and AWS perspective
11. Confirm the new value has been applied
12. Refresh the page
13. Confirm the default value is shown
https://issues.redhat.com/browse/COST-2451
=> Update how "Show cost as" value is cached

README.md
Document how to setup /etc/hosts.
At one time, we relied on the insights-proxy and its setup instructions. We no longer use that proxy, but we still need to setup the hosts file for local development.
https://issues.redhat.com/browse/COST-2476
=> Document how to setup /etc/hosts

.travis.yml, README.md
It appears that the user-event package requires a newer version of node. 
We should bump the Travis build to use node 16.
https://issues.redhat.com/browse/COST-2526
=> Update Travis to use node 16

jest.config.js, package.json, src/pages/costModels/components/rateForm/hasDiff.ts, src/pages/costModels/components/rateForm/rateForm.tsx, src/pages/costModels/components/rateForm/taggingRatesForm.tsx, src/pages/costModels/components/rateForm/useRateForm.tsx, src/pages/costModels/components/rateForm/utils.tsx, src/pages/costModels/components/rateTable.tsx, src/pages/costModels/components/tagRateTable.tsx, src/pages/costModels/costModel/addRateModal.tsx, src/pages/costModels/costModel/updateRateModel.test.tsx, src/pages/costModels/createCostModelWizard/index.tsx, src/pages/costModels/createCostModelWizard/priceListTable.tsx, src/pages/costModels/createCostModelWizard/review.tsx, src/utils/format.ts, yarn.lock
The currency selector was already added via COST-1856 and available via the stage-beta env. However, we still need to provide the user's chosen currency to the cost-model API.
This change allows cost-models to be created in different currencies. In addition, rates can be edited and added in the cost model currency. Cost model currencies are always localized per the browser's locale.
https://issues.redhat.com/browse/COST-1907
**Cost model price list:**
=> Connect currency selection to cost model API

src/store/breakdown/costOverview/gcpCostOverview/gcpCostOverviewWidgets.ts
The GCP breakdown is missing a few cards when grouping by GCP Project; services, regions, etc. 
https://issues.redhat.com/browse/COST-2533
=> GCP breakdown not showing all cards

src/api/queries/query.ts, src/pages/views/components/dataToolbar/tagValue.tsx, src/pages/views/components/groupBy/groupBy.tsx, src/pages/views/details/awsDetails/detailsToolbar.tsx, src/pages/views/details/azureDetails/detailsToolbar.tsx, src/pages/views/details/gcpDetails/detailsToolbar.tsx, src/pages/views/details/ibmDetails/detailsToolbar.tsx, src/pages/views/details/ocpDetails/detailsToolbar.tsx, src/pages/views/explorer/explorerFilter.tsx, src/pages/views/explorer/explorerHeader.tsx
Increase number of group_by options shown for org units and tag keys. Also cleaned up some unused filters.
https://issues.redhat.com/browse/COST-2536
=> Increase number of group_by options shown

src/components/exports/exportsTable.styles.ts
Remove the "failed" button style workaround, from the all export drawer, after changes to the latest PatternFly milestone update.
https://issues.redhat.com/browse/COST-2571
=> Export all "failed" button style

src/utils/feature.ts
Insights recently broke insights.chrome.isProd, which is a public API. It now returns a function. As a result, none of the beta features are currently visible.
https://issues.redhat.com/browse/COST-2637
=> insights.chrome.isProd is broken

locales/data.json, locales/translations.json, src/locales/messages.ts, src/pages/costModels/components/inputs/selector.tsx, src/pages/costModels/components/rateForm/rateForm.tsx, src/pages/costModels/createCostModelWizard/generalInformation.tsx, src/pages/costModels/createCostModelWizard/wizard.styles.ts
https://issues.redhat.com/browse/COST-2617
ended up using inline in cases where the menu for sure fits between edges of modal and doesn't go over header/footer of wizard with the new height restriction (scrollable), and parent for cases where it goes off the edge of the modal. both ways work with keyboard and a11y (being close in dom).
the 350 max height currently only affects the currency select, and gives it most of the usable space between wizard header/footer while cutting off at half an item so it's more obvious that scrolling is possible.
=> update select menu appends

src/pages/views/overview/components/dashboardWidgetBase.tsx, src/store/dashboard/awsDashboard/awsDashboardWidgets.ts, src/store/dashboard/awsOcpDashboard/awsOcpDashboardWidgets.ts, src/store/dashboard/gcpDashboard/gcpDashboardWidgets.ts, src/store/dashboard/gcpOcpDashboard/gcpOcpDashboardWidgets.ts, src/store/dashboard/ibmDashboard/ibmDashboardWidgets.ts, src/store/dashboard/ocpCloudDashboard/ocpCloudDashboardWidgets.ts, src/store/dashboard/ocpDashboard/ocpDashboardWidgets.ts
Some dashboard charts are defaulting to the wrong formatter. Although, the tooltip units look ok, there are errors in the console.
https://issues.redhat.com/browse/COST-2638
=> Specify formatter used for dashboard charts

koku-ui-manifest, package.json, yarn.lock
GitHub's dependabot shows a "Prototype Pollution in async" alert. This dependency is inherited from webpack-dev-server.
https://issues.redhat.com/browse/COST-2644
=> Dependabot vulnerability alert

src/store/dashboard/ocpCloudDashboard/ocpCloudDashboardWidgets.ts
Missing comma for "All cloud filtered by OpenShift" network filters
https://issues.redhat.com/browse/COST-2649
=> Missing comma for "All cloud filtered by OpenShift" network filters

src/store/dashboard/gcpDashboard/gcpDashboardWidgets.ts, src/store/dashboard/gcpDashboard/index.ts, src/store/dashboard/gcpOcpDashboard/gcpOcpDashboardWidgets.ts
"GCP filtered by Openshift" view should use the same network filters as "GCP". Currently, we are only using the "Cloud DNS" filter.
https://issues.redhat.com/browse/COST-2690
=> Sync "GCP filtered by Openshift" network filters

src/store/dashboard/awsDashboard/index.ts, src/store/dashboard/awsOcpDashboard/awsOcpDashboardWidgets.ts, src/store/dashboard/azureDashboard/index.ts, src/store/dashboard/azureOcpDashboard/azureOcpDashboardWidgets.ts, src/store/dashboard/ocpCloudDashboard/ocpCloudDashboardWidgets.ts
The "All filtered by Openshift" view should include "GCP" network filters. We currently only include AWS and Azure.
https://issues.redhat.com/browse/COST-2691
=> Sync "All filtered by Openshift" network filters

src/pages/views/components/costType/costType.tsx, src/pages/views/details/awsBreakdown/awsBreakdown.tsx, src/pages/views/details/awsDetails/awsDetails.tsx, src/pages/views/details/awsDetails/detailsHeader.tsx, src/pages/views/details/components/breakdown/breakdownBase.tsx, src/pages/views/details/components/breakdown/breakdownHeader.tsx, src/pages/views/explorer/explorer.tsx, src/pages/views/explorer/explorerChart.tsx, src/pages/views/explorer/explorerHeader.tsx, src/pages/views/overview/awsDashboard/awsDashboardWidget.tsx, src/pages/views/overview/overview.tsx, src/store/dashboard/awsDashboard/awsDashboardCommon.ts, src/utils/costType.ts, src/utils/localStorage.ts
The AWS cost type dropdown state is not updating. This change ensures the dropdown state is updated as expected.
https://issues.redhat.com/browse/COST-2672
=> AWS cost type dropdown state not updating

src/store/dashboard/azureDashboard/azureDashboardWidgets.ts
Removed Azure's unused storage filter. This is redundant since we're already making a request to the storage API.
https://issues.redhat.com/browse/COST-2731
=> Remove Azure's unused storage filter

src/api/providers.ts, src/api/queries/providersQuery.ts, src/api/userAccess.ts, src/pages/views/explorer/explorer.tsx, src/pages/views/explorer/explorerHeader.tsx, src/pages/views/explorer/explorerUtils.ts, src/pages/views/overview/ociDashboard/index.ts, src/pages/views/overview/ociDashboard/ociDashboard.tsx, src/pages/views/overview/ociDashboard/ociDashboardWidget.test.tsx, src/pages/views/overview/ociDashboard/ociDashboardWidget.tsx, src/pages/views/overview/overview.tsx, src/store/dashboard/ociDashboard/ociDashboard.test.ts, src/store/dashboard/ociDashboard/ociDashboardCommon.ts, src/store/dashboard/ociDashboard/ociDashboardWidgets.ts, src/store/providers/index.ts, src/store/providers/providersCommon.ts, src/utils/computedReport/getComputedOciReportItems.test.ts, src/utils/computedReport/getComputedOciReportItems.ts, src/utils/feature.ts, src/utils/userAccess.ts
https://issues.redhat.com/browse/COST-2358 
in the story comments you say to map account to payer_tenant_id.. and in one of the PR comments you mention mapping subscription_guid to payer_tenant_id , service_name to product_service, and resource_location to region on ociQuery (https://github.com/project-koku/koku-ui/pull/2396#discussion_r903755616)
so in ociDashboardCommon, the mapping is a bit different in the getGroupByForTab.. like service_names returning a product_service object, etc (already committed, but seemed like i needed to make a couple changes)
and now working on ociDashboardWidget... in the getIdKeyForTab.. service_names will map to product_service,... resources to region and such..
i'm hoping i got it right
=> stub oci overview

src/store/rbac/selectors.ts
Currently, the cost models page only tests for the `cost_managment:cost-model:write` role. This change allows for the `cost_managment:cost-model:*` role.
https://issues.redhat.com/browse/COST-2816
**Prod env using cost-admin:**
=> Allow cost_managment:cost-model:* role

src/store/rbac/selectors.ts
Currently, the cost models page only tests the first `cost-management` role it finds. We want to check if the user created multiple roles (e.g., `cost-management:cost-model:read`, `cost-management:cost-model:write`, etc.)
https://issues.redhat.com/browse/COST-2816
=> Check multiple cost-management roles

src/api/forecasts/forecastUtils.ts
The OCI overview page is still generating errors, related to the forecast API -- missing a mapping in `forecastUtils`.
=> Fixed forecast API path for OCI overview

src/pages/views/overview/overview.tsx
This adjusts the ordering of the items appearing in the overview's info popup.
"I think we want the OpenShift stuff at the top, but then all the clouds we can alphabetize them -- Natalie"
=> Fix ordering of items appearing in the overview info popup

config/spandx.config.js, webpack.config.js
the localhost const had me hung up for awhile trying to test my cloudServicesConfig - think this will make it easier if we have to do this in the future.
=> remove spandex comments, make webpack config easier

src/api/forecasts/forecastUtils.ts
The OCI overview page incorrectly displays the OpenShift forecast.
https://issues.redhat.com/browse/COST-2852
=> OCI overview displays OCP forecast

scripts/start-dev-server.js, webpack.config.js
This adds a script option to start the UI with a local Insights cloud services config route. The script generates the prompt below.
"Do you want to use local cloud services config? y/N"
This will option will set the `useLocalCloudServicesConfig` env variable. That is, instead of manually editing our `webpack.config` file to apply the route below.
```
if (useLocalCloudServicesConfig) {
routes['/beta/config'] = {
host: `http://$/{localhost}:8889`,
};
}
```
https://issues.redhat.com/browse/COST-2910
=> Add option to start UI with local cloud services config route

src/components/featureFlags/featureFlags.tsx, src/store/featureFlags/featureFlagsActions.ts
The Unlesash feature flags are lagging a bit. This change removes the `UseEffect` hook, to ensure the dispatch (to set flags) happens before children are rendered.
https://issues.redhat.com/browse/COST-2952
=> Unleash feature lag

locales/data.json, locales/translations.json, src/locales/messages.ts, src/routes/views/details/components/costOverview/costOverviewBase.tsx, src/routes/views/details/components/usageChart/usageChart.tsx, src/store/breakdown/costOverview/common/costOverviewCommon.ts, src/store/breakdown/costOverview/ocpCostOverview/ocpCostOverview.test.ts, src/store/breakdown/costOverview/ocpCostOverview/ocpCostOverviewReducer.ts, src/store/breakdown/costOverview/ocpCostOverview/ocpCostOverviewWidgets.ts
Adds a Volume usage card to the Ocp project breakdown page.
https://issues.redhat.com/browse/COST-2957
=> Volume usage card

src/components/pageTitle/index.ts, src/components/pageTitle/pageTitle.tsx, src/components/userAccess/permissions.tsx, src/components/userAccess/permissionsWrapper.tsx, src/components/userAccess/userAccess.tsx
This simplifies the following to be functional components -- mimics the HCS UI. These components are used on every page and don't need state.
- PageTitle
- Permissions
- UserAccess
https://issues.redhat.com/browse/COST-2996
=> Simplify permission components to use React.FC

src/components/featureFlags/featureFlags.tsx
This fixes the return value for the FeatureFlags component, when children are in use.
https://issues.redhat.com/browse/COST-2997
=> FeatureFlags return value

package.json, yarn.lock
Revert eslint package to v8.22.0 due to the TypeError below. This prevents the IDE from highlighting lint errors.
"eslint TypeError: this.libOptions.parse is not a function"
=> Revert eslint package

src/routes/views/components/charts/chartTheme/theme-utils.ts
Removes the deprecated PatternFly `ChartThemeVariant` component and replaces `getCustomTheme` from PatternFly charts with `mergeTheme`
https://issues.redhat.com/browse/COST-3058
=> Remove deprecated PatternFly ChartThemeVariant

src/routes/views/components/export/exportModal.tsx
The submit button in the export dialog remains disabled. It's not obvious to users why the button is disabled, but it prevents exporting data.
https://issues.redhat.com/browse/COST-3064
=> Export dialog button remains disabled

package.json, src/__mocks__/react-intl.tsx, src/routes/costModels/costModelsDetails/utils/table.tsx, yarn.lock
Instead of using `date-fns-tz` to convert the timezone prior to formatting, this change uses the existing the `formatDate` function of `react-intl`.
The advantage here is that these functions do not require a Locale object to be provided – the locale has already been set via `IntlProvider`. We also don't need to hard code a date format (e.g., "dd LLL yyyy hh:mm, x"), where dates are expected to be formatted differently for European and Asian locales.
Spoke with Natalie and showing the month before the day is acceptable.
https://issues.redhat.com/browse/COST-3031
=> Use react-intl instead of date-fns-tz

scripts/start-dev-server.js, webpack.config.js
Add ephemeral option to UI's startup script.
Note that if we're using an ephemeral env, then the script should not prompt to setup local APIs in standalone mode
https://issues.redhat.com/browse/COST-3081
=> Add ephemeral option to start script

src/utils/format.ts
Modified the code to not show a negative zero as the card’s hero number. It’s possible you could see -100, but not -0
https://issues.redhat.com/browse/COST-3087
=> GCP compute card shows negative zero value

src/app.tsx, src/components/featureFlags/featureFlags.styles.ts, src/components/featureFlags/featureFlags.tsx, src/components/userAccess/permissionsWrapper.tsx
The feature flags component (for Unleash) occasionally generates a "React state update on an unmounted component" warning. In addition, I see multiple requests generated for the user-access, sources, and settings API. 
This change refactors the code a bit to ensure neither will happen.
=> Feature flags component generates state warning

src/routes/views/explorer/explorerChart.tsx
The explorer chart was not updating when exclude filters are applied.
https://issues.redhat.com/browse/COST-3146
=> Explorer chart doesn't update when exclude filters are applied

src/routes/views/explorer/explorer.tsx, src/routes/views/explorer/explorerChart.tsx, src/routes/views/explorer/explorerHeader.tsx, src/routes/views/explorer/explorerTable.tsx
The Cost explorer URL currently contains a `start_date` and `end_date`; however, these query params are not used directly as the page is based on the `dateRange` param. (These params are only used for the API request itself.) Want to clean this up and remove `start_date` & `end_date` from Cost explorer URL.
https://issues.redhat.com/browse/COST-3149
=> Remove start_date & end_date from cost explorer URL

package.json, yarn.lock
The eslint-plugin-cypress package was added because @redhat-cloud-services/frontend-components-config pkg had a missing dependency. The Insights team recently removed this dependency, so we should remove it as well.
https://issues.redhat.com/browse/COST-3183
=> Remove unused eslint-plugin-cypress pkg

src/routes/views/details/awsBreakdown/awsBreakdown.tsx, src/routes/views/details/azureBreakdown/azureBreakdown.tsx, src/routes/views/details/components/historicalData/historicalDataCostChart.tsx, src/routes/views/details/components/historicalData/historicalDataTrendChart.tsx, src/routes/views/details/components/historicalData/historicalDataUsageChart.tsx, src/routes/views/details/components/summary/summaryCard.tsx, src/routes/views/details/components/summary/summaryModalContent.tsx, src/routes/views/details/components/usageChart/usageChart.tsx, src/routes/views/details/gcpBreakdown/gcpBreakdown.tsx, src/routes/views/details/ibmBreakdown/ibmBreakdown.tsx, src/routes/views/details/ociBreakdown/ociBreakdown.tsx, src/routes/views/details/ocpBreakdown/ocpBreakdown.tsx
Currently, the UI provides the details page filters to the breakdown page. However, we're not providing the excludes filter.
https://issues.redhat.com/browse/COST-3204
**AWS excluded by AmazonEC2**
=> Add excludes filter to breakdown pages

src/routes/views/details/components/dataTable/dataTable.tsx, src/routes/views/explorer/explorerTable.styles.ts, src/routes/views/explorer/explorerTable.tsx
- Migrate cost explorer page to use PatternFly composable table
- Add "nowrap" style to details tables
https://issues.redhat.com/browse/COST-3231
**Explorer table:**
=> Migrate cost explorer page to use PatternFly composable table

src/components/featureFlags/featureFlags.tsx, src/store/featureFlags/__snapshots__/featureFlags.test.ts.snap, src/store/featureFlags/featureFlags.test.ts, src/store/featureFlags/featureFlagsActions.ts, src/store/featureFlags/featureFlagsReducer.ts, src/store/featureFlags/featureFlagsSelectors.ts
Added cost distribution flag. This will allow new features to be tested in stage with the cost-demo user.
Example:
```
import { featureFlagsSelectors } from 'store/featureFlags';
...
const isDistributionFeatureEnabled = featureFlagsSelectors.selectIsDistributionFeatureEnabled(state);
```
https://issues.redhat.com/browse/COST-3145
=> Added cost distribution flag

src/routes/views/explorer/explorer.tsx, src/routes/views/explorer/explorerHeader.tsx, src/routes/views/overview/awsOcpDashboard/awsOcpDashboardWidget.tsx, src/routes/views/overview/overview.tsx, src/store/accountSettings/accountSettingsReducer.ts, src/store/dashboard/awsDashboard/__snapshots__/awsDashboard.test.ts.snap, src/store/dashboard/awsDashboard/awsDashboardCommon.ts, src/store/dashboard/awsDashboard/awsDashboardSelectors.ts, src/store/dashboard/awsOcpDashboard/awsOcpDashboardCommon.ts, src/store/dashboard/awsOcpDashboard/awsOcpDashboardSelectors.ts, src/store/dashboard/awsOcpDashboard/awsOcpDashboardWidgets.ts
Add cost type selector to "AWS filtered by OpenShift" perspective in overview and cost explorer pages.
Note that this feature uses the Unleash cost-management.ui.cost-type toggle, which is currently disabled until API support is available.
https://issues.redhat.com/browse/COST-3122
=> Add cost type selector to "AWS filtered by OpenShift" perspective

src/routes/views/components/export/exportModal.tsx, src/routes/views/components/export/exportSubmit.tsx, src/routes/views/details/awsDetails/awsDetails.tsx, src/routes/views/explorer/explorer.tsx
The export feature should include AWS cost type when generating API requests for the AWS details page and Cost Explorer
https://issues.redhat.com/browse/COST-3278
=> Export should include AWS cost type

src/routes/views/details/components/cluster/cluster.tsx, src/routes/views/details/components/cluster/clusterModal.tsx, src/routes/views/details/components/costOverview/costOverviewBase.tsx, src/routes/views/details/components/historicalData/historicalDataCostChart.tsx, src/routes/views/details/components/historicalData/historicalDataTrendChart.tsx, src/routes/views/details/components/historicalData/historicalDataUsageChart.tsx, src/routes/views/details/components/usageChart/usageChart.tsx, src/routes/views/details/ocpBreakdown/ocpBreakdown.tsx, src/utils/computedReport/getComputedReportItems.ts
Added platform costs support for breakdown page
Note that the cost-demo user does not have volumes for "platform costs", so the "Volume" chart shows zero values.
https://issues.redhat.com/browse/COST-3283
=> Add platform costs support for breakdown page

locales/data.json, locales/translations.json, src/locales/messages.ts, src/routes/views/details/components/costOverview/costOverviewBase.tsx, src/routes/views/details/components/summary/summaryCard.tsx, src/routes/views/details/ocpBreakdown/ocpBreakdown.tsx, src/store/breakdown/costOverview/common/costOverviewCommon.ts, src/store/breakdown/costOverview/ocpCostOverview/ocpCostOverviewWidgets.ts, src/utils/computedReport/getComputedReportItems.ts
As part of the OpenShift "platform costs" feature, this adds a "Top costliest platform costs" card for the OCP details breakdown page.
https://issues.redhat.com/browse/COST-2775
=> Add "top costliest platform costs" card

src/routes/views/details/components/costOverview/costOverviewBase.tsx
Ensure cpu, memory, and volume cards appear on right side of page for OCP cluster breakdown.
=> OCP cluster breakdown card layout

src/routes/views/explorer/explorerDatePicker.tsx, src/utils/dates.ts
Clearing the date picker's end date per QE / UX feedback. If the end date becomes invalid, after choosing a new start date, we will clear the end date.
https://issues.redhat.com/browse/COST-3271
=> Clear date picker's end date

src/routes/views/explorer/explorerDatePicker.tsx
Adjusted the date picker to allow 65 days max. Currently, we're showing 66 days, including the start date.
https://issues.redhat.com/browse/COST-3271
=> Adjust date picker to allow 65 days max

package.json, src/api/queries/query.ts, src/routes/views/details/components/cluster/cluster.tsx, src/routes/views/details/components/cluster/clusterModal.tsx, src/routes/views/details/components/costOverview/costOverviewBase.tsx, src/routes/views/details/components/summary/summaryCard.tsx, src/routes/views/details/components/tag/tagContent.tsx, src/routes/views/details/components/tag/tagModal.tsx, src/routes/views/details/ocpBreakdown/ocpBreakdown.tsx, src/routes/views/utils/paths.ts, yarn.lock
Refactored breakdown page to simplify the platform costs feature. 
https://issues.redhat.com/browse/COST-3283
FYI, the "category" query param is only used to restore the details page. It doesn't indicate if the current project is a "platform" cost. For that, we must look at the group_by's provided to the breakdown page.
In the screenshots below, the "platform" project shows new features as expected. However, the "analitics" project should not display them.
**Example: "platform"**
**Example: "analitics"**
=> Simplify platform costs feature

src/routes/views/details/ocpDetails/detailsTable.tsx
Ensure unallocated links are disabled.
Note that the classification prop is only available for category=platform
https://issues.redhat.com/browse/COST-3248
=> Ensure unallocated links are disabled.

src/routes/views/components/export/exportModal.tsx
Radio buttons should use isChecked to avoid "uncontrolled" warning messages.
https://issues.redhat.com/browse/COST-3299
=> Export dialog warning

src/store/dashboard/awsDashboard/awsDashboardCommon.ts, src/store/dashboard/awsDashboard/awsDashboardSelectors.ts, src/store/dashboard/awsDashboard/awsDashboardWidgets.ts, src/store/dashboard/awsOcpDashboard/awsOcpDashboardCommon.ts, src/store/dashboard/awsOcpDashboard/awsOcpDashboardSelectors.ts, src/store/dashboard/awsOcpDashboard/awsOcpDashboardWidgets.ts
Add cost_type for all AWS and "AWS on OCP" overview cards. This change adds the cost_type param for compute and storage APIs.
https://issues.redhat.com/browse/COST-3122
=> Add cost_type for all AWS and "AWS on OCP" overview cards

locales/data.json, locales/translations.json, src/locales/messages.ts, src/routes/costModels/createCostModelWizard/priceList.tsx, src/routes/costModels/createCostModelWizard/priceListTable.tsx
The cost models wizard throws users into the "Create rate" dialog, in the "Price list" step, after deleting all rates. That is, when there is a single rate remaining.
It's confusing because users are blocked from navigating to the next wizard step, until they click "Cancel". With this change, the user would remain on the "Price list" table.
https://issues.redhat.com/browse/COST-3218
=> Wizard should remain on "Price list" table after deleting rates

src/api/queries/query.ts, src/routes/views/details/awsDetails/awsDetails.tsx, src/routes/views/details/awsDetails/detailsTable.tsx, src/routes/views/details/azureDetails/azureDetails.tsx, src/routes/views/details/azureDetails/detailsTable.tsx, src/routes/views/details/components/cluster/cluster.tsx, src/routes/views/details/components/costOverview/costOverviewBase.tsx, src/routes/views/details/components/summary/summaryCard.tsx, src/routes/views/details/components/tag/tagModal.tsx, src/routes/views/details/gcpDetails/detailsTable.tsx, src/routes/views/details/gcpDetails/gcpDetails.tsx, src/routes/views/details/ibmDetails/detailsTable.tsx, src/routes/views/details/ibmDetails/ibmDetails.tsx, src/routes/views/details/ociDetails/detailsTable.tsx, src/routes/views/details/ociDetails/ociDetails.tsx, src/routes/views/details/ocpDetails/detailsTable.tsx, src/routes/views/details/ocpDetails/ocpDetails.tsx, src/routes/views/details/rhelDetails/detailsTable.tsx, src/routes/views/details/rhelDetails/rhelDetails.tsx, src/routes/views/explorer/explorer.tsx, src/routes/views/explorer/explorerTable.tsx, src/routes/views/utils/paths.ts
The cost APIs are renaming a few labels in which are displayed the details table. The UI must be updated to match the strings below.
- no-\<something> =>  No-\<something>
- Platform Unallocated Capacity => Platform unallocated
- Workers Unallocated Capacity => Workers unallocated
https://issues.redhat.com/browse/COST-3335
=> Match new labels in details table

src/routes/costModels/costModelsDetails/utils/filters.tsx
Fixes a missing router property
https://issues.redhat.com/browse/COST-3340
=> Filtering of cost models by source type doesn't work

src/__mocks__/react-intl.ts, src/routes/costModels/costModelsDetails/utils/table.tsx
The recent PatternFly table upgrade is generating the test error below. The containerized build is failing, so new PRs are blocked from merging.
Note that this is a temporary fix. Ideally, we would adjust the react-intl mock; however, the snapshots are changing during PR build tests.
=> Fix cost models table test

src/routes/views/details/awsBreakdown/awsBreakdown.tsx, src/routes/views/details/awsBreakdown/costOverview.tsx, src/routes/views/details/awsBreakdown/historicalData.tsx, src/routes/views/details/azureBreakdown/costOverview.tsx, src/routes/views/details/azureBreakdown/historicalData.tsx, src/routes/views/details/components/breakdown/breakdownHeader.tsx, src/routes/views/details/components/cluster/cluster.tsx, src/routes/views/details/components/cluster/clusterContent.tsx, src/routes/views/details/components/cluster/clusterModal.tsx, src/routes/views/details/components/costOverview/costOverviewBase.tsx, src/routes/views/details/gcpBreakdown/costOverview.tsx, src/routes/views/details/gcpBreakdown/historicalData.tsx, src/routes/views/details/ibmBreakdown/costOverview.tsx, src/routes/views/details/ibmBreakdown/historicalData.tsx, src/routes/views/details/ociBreakdown/costOverview.tsx, src/routes/views/details/ociBreakdown/historicalData.tsx, src/routes/views/details/ocpBreakdown/costOverview.tsx, src/routes/views/details/ocpBreakdown/historicalData.tsx, src/routes/views/details/ocpBreakdown/ocpBreakdown.tsx, src/routes/views/details/rhelBreakdown/costOverview.tsx, src/routes/views/details/rhelBreakdown/historicalData.tsx, src/routes/views/details/rhelBreakdown/rhelBreakdown.tsx
This ensures the clusters card (shown in the breakdown page) shows all clusters for the "platform" feature.
=> Breakdown page doesn't show all "platform" clusters

src/routes/views/utils/paths.ts
* When RBAC is enabled the query fails as the user isn't given access permissions via user-friendly name
* It was decided to avoid doing a lookup that adds the alias or source name to forego and potential privilege escalation
Related to:
https://issues.redhat.com/browse/COST-3374
=> COST-3374: Update details breakdown query to use ID over label

src/routes/views/details/azureDetails/detailsTable.tsx, src/routes/views/details/gcpDetails/detailsTable.tsx, src/routes/views/details/ibmDetails/detailsTable.tsx, src/routes/views/details/ociDetails/detailsTable.tsx, src/routes/views/details/ocpDetails/detailsTable.tsx, src/routes/views/details/rhelDetails/detailsTable.tsx, src/routes/views/utils/paths.ts
This update ensures the details breakdown page title and description are unique.
https://issues.redhat.com/browse/COST-3380
OCP Clusters
=> Details breakdown title and description are same

src/utils/localStorage.ts, test/testEnv.ts
The Insights Chrome no longer appears to add the `cs_jwt` session token to local storage. As a result, the UI cannot properly clear local storage properties upon a new session. The local session is used to store user choices for currency, AWS cost type, and inactive sources alerts.
Instead of referencing the `cs_jwt` property in local storage, we can use `insights.chrome.auth.getToken()` instead.
https://issues.redhat.com/browse/COST-3500
=> Insights Chrome session token

src/routes/views/components/charts/chartTheme/theme-utils.ts
Charts should use PatternFly's getCustomTheme function instead of mergeTheme. The mergeTheme function will be removed for the upcoming v5 breaking change release.
https://issues.redhat.com/browse/COST-3496
=> Use PatternFly's getCustomTheme function

src/components/pageTitle/pageTitle.tsx, src/components/userAccess/permissions.tsx, src/routes.tsx, src/routes/costModels/costModel/header.tsx, src/routes/costModels/costModelsDetails/utils/table.tsx, src/routes/state/notAuthorized/notAuthorizedState.tsx, src/routes/views/details/awsBreakdown/awsBreakdown.tsx, src/routes/views/details/awsDetails/detailsTable.tsx, src/routes/views/details/azureBreakdown/azureBreakdown.tsx, src/routes/views/details/azureDetails/detailsTable.tsx, src/routes/views/details/gcpBreakdown/gcpBreakdown.tsx, src/routes/views/details/gcpDetails/detailsTable.tsx, src/routes/views/details/ibmBreakdown/ibmBreakdown.tsx, src/routes/views/details/ibmDetails/detailsTable.tsx, src/routes/views/details/ociBreakdown/ociBreakdown.tsx, src/routes/views/details/ociDetails/detailsTable.tsx, src/routes/views/details/ocpBreakdown/ocpBreakdown.tsx, src/routes/views/details/ocpDetails/detailsTable.tsx, src/routes/views/details/rhelBreakdown/rhelBreakdown.tsx, src/routes/views/details/rhelDetails/detailsTable.tsx, src/store/dashboard/awsDashboard/awsDashboardWidgets.ts, src/store/dashboard/azureDashboard/azureDashboardWidgets.ts, src/store/dashboard/gcpDashboard/gcpDashboardWidgets.ts, src/store/dashboard/ibmDashboard/ibmDashboardWidgets.ts, src/store/dashboard/ociDashboard/ociDashboardWidgets.ts, src/store/dashboard/ocpDashboard/ocpDashboardWidgets.ts, src/store/dashboard/rhelDashboard/rhelDashboardWidgets.ts, src/utils/paths.ts
Refactor to use Insights' shared router, formatting routes with a basename.
https://issues.redhat.com/browse/COST-3524
=> Refactor to use Insights' shared router

src/routes/views/details/components/cluster/cluster.tsx
The OCP breakdown page shows a list of clusters, but some names are too long and must be truncated. It would be ideal if we could show a tooltip to display the full cluster name.
We also show a "more" link when the entire cluster string is greater than 50 characters. However, instead of 50 characters total, we can apply a limit to each cluster name. The cluster card is responsive, so cluster names will wrap onto the next line.
That said, max characters per cluster name should be 45 – assuming there is no whitespace. Otherwise, the cluster name may overlap the card.
Note: Max characters is 30 for this screenshot only
https://issues.redhat.com/browse/COST-3533
=> OCP breakdown cluster name truncation

src/routes/views/components/dataToolbar/dataToolbar.tsx, src/routes/views/details/awsDetails/awsDetails.tsx, src/routes/views/details/awsDetails/detailsToolbar.tsx, src/routes/views/details/azureDetails/azureDetails.tsx, src/routes/views/details/azureDetails/detailsToolbar.tsx, src/routes/views/details/gcpDetails/detailsToolbar.tsx, src/routes/views/details/gcpDetails/gcpDetails.tsx, src/routes/views/details/ibmDetails/detailsToolbar.tsx, src/routes/views/details/ibmDetails/ibmDetails.tsx, src/routes/views/details/ociDetails/detailsToolbar.tsx, src/routes/views/details/ociDetails/ociDetails.tsx, src/routes/views/details/ocpDetails/detailsToolbar.tsx, src/routes/views/details/ocpDetails/ocpDetails.tsx, src/routes/views/details/rhelDetails/detailsToolbar.tsx, src/routes/views/details/rhelDetails/rhelDetails.tsx, src/routes/views/explorer/explorer.tsx, src/routes/views/explorer/explorerToolbar.tsx, src/routes/views/ros/recommendations/recommendations.tsx, src/routes/views/ros/recommendations/rosToolbar.tsx
There are scenarios when table toolbar actions should be disabled. Including the bulk select, filter, include/exclude, export, manage columns, platform costs, and pagination.
1. While the page is loading, all toolbar actions are disabled
2. If the API returns no data, all toolbar actions are disabled
3. If there is no data due to filtering, only the filter actions remain enabled
https://issues.redhat.com/browse/COST-3537
=> Disable table toolbar actions for no data

src/routes/views/details/awsDetails/detailsTable.tsx, src/routes/views/details/azureDetails/detailsTable.tsx, src/routes/views/details/components/dataTable/dataTable.styles.ts, src/routes/views/details/components/dataTable/dataTable.tsx, src/routes/views/details/gcpDetails/detailsTable.tsx, src/routes/views/details/ibmDetails/detailsTable.tsx, src/routes/views/details/ociDetails/detailsTable.tsx, src/routes/views/details/ocpDetails/detailsTable.tsx, src/routes/views/details/rhelDetails/detailsTable.tsx, src/routes/views/ros/recommendations/rosTable.tsx
The PatternFly composable table appears to have changed and broke our previous column alignments
https://issues.redhat.com/browse/COST-3568
=> Incorrect alignment of Infra and Supp cost columns

src/routes/views/overview/components/dashboardWidgetBase.tsx, src/store/dashboard/ocpDashboard/ocpDashboardActions.ts
This fixes an issue with the ROS widget, newly added to the overview page.
https://issues.redhat.com/browse/COST-3576
=> Broken currency selector on the OCP Overview page

locales/data.json, locales/translations.json, src/locales/messages.ts, src/routes/views/details/ocpDetails/detailsTable.tsx, src/routes/views/details/ocpDetails/ocpDetails.tsx
Stubbed out the recommendations column. Will update with data when API is available
https://issues.redhat.com/browse/COST-3492
=> Stub-out OCP details page for ROS

fec.config.js, src/app.tsx, src/components/drawers/recommendations/recommendationsToolbar.tsx, src/routes/views/recommendations/recommendations.tsx, src/routes/views/recommendations/recommendationsHeader.tsx, src/routes/views/recommendations/recommendationsToolbar.tsx
Fix CSS scope name to eliminate extra div tag / selector, which helps make ROS drawer sticky
=> Fix CSS scope name

src/routes/views/explorer/explorerTable.scss, src/routes/views/explorer/explorerTable.tsx
Refactor explorer table to use PatternFly sticky column props
https://issues.redhat.com/browse/COST-3633
=> Use PatternFly sticky table props

src/routes/views/details/ocpBreakdown/ocpBreakdown.tsx
Revert fix for COST-1131 -- we shouldn't omit filters
https://issues.redhat.com/browse/COST-3642
=> Revert fix for COST-1131

src/routes/views/details/components/breakdown/breakdownBase.tsx, src/routes/views/details/ocpBreakdown/ocpBreakdown.tsx
Recommendations drawer should close when tabs are selected in breakdown page.
https://issues.redhat.com/browse/COST-3652
=> Close recommendations drawer upon breakdown tab click

src/routes/views/details/components/dataTable/dataTable.tsx, src/routes/views/details/ocpBreakdown/ocpBreakdown.tsx
When navigating from the Optimizations drawer to the breakdown page, the project may not exist for Cost Management APIs. In this case, the projects cost is zero and the "Cost overview" and "Historical data" tabs don't have data to show.
I used the empty state we show in the OpenShift details page when there is no data. I realize this is fake data, but feel we should have something in place. However, it is possible that the Cost and ROS APIs are not in sync when data is updated, sources are added / removed, etc.
=> Added empty state for breakdown tabs

src/store/accountSettings/accountSettingsReducer.ts, src/utils/localStorage.ts
If account-settings returns `currency=undefined`, ensure that is not stored in local storage.
https://issues.redhat.com/browse/COST-3683
=> Ensure currency is not stored as undefined

src/routes/views/details/ocpBreakdown/optimizationsBreakdown.tsx
Don't display empty state when filters are applied in optimizations breakdown
=> Optimizations empty state & filters

src/utils/localStorage.ts
Set dropdown default to distribute overhead costs through cost model. Users should not need to enable the overhead cost feature twice; once in the cost model, then again via the dropdown.
=> Overhead costs default

src/routes/views/details/ocpDetails/detailsTable.tsx, src/routes/views/details/ocpDetails/ocpDetails.tsx
Reset delta when group by is changed. Also ensure we don't set order_by and/or overhead costs unless the group_by is 'project'
=> Reset delta when group by is changed

src/app.tsx
Remove unused app navigation from app.tsx. This will match Consoledot's starter app.
=> Remove unused app navigation

src/routes/views/components/optimizations/optimizationsTable.tsx, src/routes/views/components/optimizations/optimizationsToolbar.tsx, src/routes/views/details/awsDetails/awsDetails.tsx, src/routes/views/details/awsDetails/detailsHeader.tsx, src/routes/views/details/azureDetails/azureDetails.tsx, src/routes/views/details/components/breakdown/breakdownBase.tsx, src/routes/views/details/gcpDetails/gcpDetails.tsx, src/routes/views/details/ibmDetails/ibmDetails.tsx, src/routes/views/details/ociDetails/ociDetails.tsx, src/routes/views/details/ocpBreakdown/optimizationsBreakdown.tsx, src/routes/views/details/ocpDetails/ocpDetails.tsx, src/routes/views/details/rhelDetails/rhelDetails.tsx, src/routes/views/explorer/explorer.tsx, src/routes/views/optimizations/optimizations.tsx, src/routes/views/overview/overview.tsx, src/routes/views/utils/handles.ts
Pau reported that the optimizations drawer was open, but the table row didn't show a blue bar. The drawer likely remained opened while another action was performed in the page.
- Close optimizations drawer if filtering, pagination, or sort is applied
- Rename handle methods to better match property names
=> Close optimizations drawer

src/components/drawers/optimzations/optimizations.styles.ts, src/components/drawers/optimzations/optimizationsContent.tsx
The workload type and workload name were switched in ROS drawer. Also Adjusted drawer's table column width due to long decimal places.
=> Fixed workload_type in ROS drawer

src/routes/settings/tagDetails/tagTable.tsx, src/routes/views/components/optimizations/optimizationsTable.tsx, src/routes/views/details/awsDetails/detailsTable.tsx, src/routes/views/details/azureDetails/detailsTable.tsx, src/routes/views/details/components/dataTable/dataTable.styles.ts, src/routes/views/details/components/dataTable/dataTable.tsx, src/routes/views/details/gcpDetails/detailsTable.tsx, src/routes/views/details/ibmDetails/detailsTable.tsx, src/routes/views/details/ociDetails/detailsTable.tsx, src/routes/views/details/ocpDetails/detailsTable.tsx, src/routes/views/details/rhelDetails/detailsTable.tsx
Adjust last column padding when data table does not have an action column
=> Adjust last column padding

src/components/drawers/optimzations/optimizationsContent.tsx, src/components/drawers/optimzations/optimizationsDrawer.tsx, src/components/drawers/optimzations/optimizationsLink.tsx, src/routes/components/optimizations/optimizationsTable.tsx, src/utils/chrome.tsx
The Optimizations drawer link should be disabled when there is no OpenShift source. In this scenario, there are no projects. When the user navigates to the breakdown page, they encounter a full page empty state.
As a solution, we will fetch a cost report to determine if the OpenShift project truly exists. That is, instead of assuming there is a project if the recommendations is within 24hrs.
https://issues.redhat.com/browse/COST-3789
=> Optimizations drawer link should be disabled

scripts/release-branch.sh
"main and stage-stable branches have the same commit" - that's the problem then that's not doable with containerized apps. when you merge to a branch it kicks off a build, and it determines if it is a beta or stable build based on the branch. the container is pulled from quay via the SHA - so if you have master and stage-stable with the same SHA at HEAD you will end up with one build stomping over the other and the same build in both environments. stage-stable should be behind master. -- Andrew D
=> Update release script to not use fast forward merge

src/routes/explorer/explorerChart.tsx
Move "Others" to be the last legend label. This will allow us to apply order_by[distributed_cost]=desc, so labels appear in the expected order.
=> Move "Others" to be the last legend label

src/routes/components/costType/costType.tsx
The value in `savingsplan_effective_cost` does not accurately reflect the amortized cost as reported by AWS. There is a new field that calculates the correct amortized cost the same way that AWS does. Use this new field when amortized cost is selected.
=> [COST-3554] Use new field for amortized cost

src/app.scss
Omit global styles from frontend-components-utilities package.
While testing the PatternFly v5 pre-release packages, the UI inherited styles like `footer` defined by the frontend-components-utilities package. As a result, our modal footers display a undesired, black background. We don't appear to use any of these global frontend-components-utilities styles, nor do we want to.
=> Omit frontend-components-utilities styles

src/routes/costModels/components/rateForm/useRateForm.tsx, src/routes/settings/costModels/components/rateForm/useRateForm.tsx
The cost model "Create rate" button must remain disabled if tag key not set.
https://issues.redhat.com/browse/COST-3977
=> rates.tag_key may not be blank

src/api/queries/azureQuery.ts, src/routes/details/awsDetails/detailsTable.tsx, src/routes/details/azureBreakdown/azureBreakdown.tsx, src/routes/details/azureDetails/detailsTable.tsx, src/routes/details/gcpDetails/detailsTable.tsx, src/routes/details/ibmDetails/detailsTable.tsx, src/routes/details/ociDetails/detailsTable.tsx, src/routes/details/ocpDetails/detailsTable.tsx, src/routes/details/rhelDetails/detailsTable.tsx, src/routes/explorer/explorerTable.tsx, src/routes/utils/computedReport/getComputedReportItems.ts
Add support for Azure's subscription_name
Note: The reports/openshift/infrastructures/aws API returns null for "account_alias" when using order_by[cost]
See https://issues.redhat.com/browse/COST-4014
https://issues.redhat.com/browse/COST-4011
=> Add support for Azure's subscription_name

src/api/settings.ts, src/routes/settings/costCategory/costCategory.tsx, src/routes/settings/costCategory/costCategoryTable.tsx, src/routes/settings/tagDetails/tagDetails.tsx, src/routes/settings/tagDetails/tagTable.tsx, src/routes/settings/tagDetails/tagToolbar.tsx
Wire up new tags API to settings page
=> Wire up new tags API to settings page

scripts/release-branch.sh, src/components/permissions/permissions.tsx, src/store/costModels/actions.ts
Merged main branch to stage-stable. Use latest commit to update namespace `ref` in app-interface repo. Don't use merge commit, SHAs must be unique when images are created for each branch.
=> Deployment commit for stage-stable

scripts/release-branch.sh, src/components/permissions/permissions.tsx, src/store/costModels/actions.ts
Merged stage-stable branch to prod-beta. Use latest commit to update namespace `ref` in app-interface repo. Don't use merge commit, SHAs must be unique when images are created for each branch.
=> Deployment commit for prod-beta

scripts/release-branch.sh, src/components/permissions/permissions.tsx, src/store/costModels/actions.ts
Merged prod-beta branch to prod-stable. Use latest commit to update namespace `ref` in app-interface repo. Don't use merge commit, SHAs must be unique when images are created for each branch.
=> Deployment commit for prod-stable

locales/data.json, locales/translations.json, src/locales/messages.ts, src/routes/details/components/usageChart/usageChart.tsx, src/utils/format.ts
Limit precision of CPU/Memory/Volume maximums to two decimal places
https://issues.redhat.com/browse/COST-4116
=> Limit precision of CPU/Memory/Volume maximums

src/components/drawers/commonDrawer/commonDrawer.scss
Workaround for Consoledot's pf4-v5.css. Currently, the page background is white, but should be gray.
=> Workaround for Consoledot's pf4-v5.css

.github/dependabot.yml
Workaround for slashes in branch name
See https://issues.redhat.com/browse/RHCLOUD-27539
=> Dependabot branch separator

src/routes/details/components/breakdown/breakdownHeader.tsx, src/routes/utils/queryNavigate.ts
When changing currency or cost distribution, the details breakdown breadcrumb is missing because the page was refreshed without maintaining state.
=> Fix missing breadcrumb

src/routes/settings/costModels/components/addPriceList.test.tsx, src/routes/settings/costModels/costModel/updateRateModel.test.tsx
Act wrappers are breaking with the latest PatternFly milestone. However, the tests work without the act wrapper. At one time, @testing-library/react v12 tests broke without the wrapper, but it appears we can remove that now.
=> Remove unnecessary act wrappers from tests

src/routes/explorer/explorerTable.tsx
This is due to the PatternFly v5 upgrade. There is a new event property, which was added to the sort function.
https://issues.redhat.com/browse/COST-4276
=> Broken cost explorer sort

src/routes/details/components/breakdown/breakdownHeader.tsx
Show cluster info link even if description has been omitted
https://issues.redhat.com/browse/COST-4559
=> Show cluster info link regardless of description

.github/workflows/pull_request.yml, README.md
Note that the CI status badge is disingenous as it only shows the status of of the tag_release workflow, not the state of the code in `main` or other stable branches. The workflow needs to be updated to run on push in order to have accurate build status.
=> CI - reenable coverage

src/routes/components/dataToolbar/utils/bulkSelect.tsx
Remove bulk select workaround.
Depends on PatternFly milestone https://github.com/project-koku/koku-ui/pull/3753
Closes https://issues.redhat.com/browse/COST-4596
=> Remove bulk select workaround

src/routes/components/selectWrapper/selectWrapper.tsx, src/routes/settings/costModels/components/addPriceList.test.tsx, src/routes/settings/costModels/components/inputs/selector.tsx, src/routes/settings/costModels/components/rateForm/rateForm.tsx, src/routes/settings/costModels/costModel/addRateModal.tsx, src/routes/settings/costModels/costModel/updateCostModel.tsx, src/routes/settings/costModels/costModel/updateRateModel.test.tsx, src/routes/settings/costModels/costModel/updateRateModel.tsx, src/routes/settings/costModels/costModelWizard/costModelWizard.tsx, src/routes/settings/costModels/costModelWizard/generalInformation.tsx
Replace remaining deprecated PatternFly Select component.
Depends on PatternFly milestone https://github.com/project-koku/koku-ui/pull/3753 -- must merge that for tests to pass
Closes https://issues.redhat.com/browse/COST-4585
=> Replace remaining deprecated PatternFly Select component

locales/data.json, locales/translations.json, src/locales/messages.ts
Renamed OCP bullet chart "unused capacity" label as "unused requests"
https://issues.redhat.com/browse/COST-4976
=> Rename OCP bullet chart "unused capacity" label

src/routes/components/dataTable/dataTable.tsx, src/routes/settings/platformProjects/platformProjects.scss, src/routes/settings/platformProjects/platformProjects.styles.ts, src/routes/settings/platformProjects/platformProjectsTable.tsx
The "platform projects" table, in the settings page, is wrapping names unexpectedly for small window sizes.
https://issues.redhat.com/browse/COST-5016
=> Platform projects table wraps names incorrectly

src/routes/details/components/tag/tagLink.tsx
Tags link fix for when there are no (AWS EC2) tags shown in a table row
https://issues.redhat.com/browse/COST-4855
=> Tags link fix

src/components/featureToggle/featureToggle.tsx
Update ROS to use new Unleash preview flag. 
The `cost-management.ui.ros` Unleash toggle will now use the `platform.chrome.ui.preview` constraint.
=> Update ROS nav to use new Unleash preview flag

src/routes/details/components/costOverview/costOverviewBase.tsx, src/routes/details/components/historicalData/historicalDataBase.tsx, src/store/breakdown/costOverview/awsCostOverview/awsCostOverviewWidgets.ts, src/store/breakdown/costOverview/azureCostOverview/azureCostOverviewWidgets.ts, src/store/breakdown/costOverview/common/costOverviewCommon.ts, src/store/breakdown/costOverview/gcpCostOverview/gcpCostOverviewWidgets.ts, src/store/breakdown/costOverview/ibmCostOverview/ibmCostOverviewWidgets.ts, src/store/breakdown/costOverview/ociCostOverview/ociCostOverviewWidgets.ts, src/store/breakdown/costOverview/ocpCostOverview/ocpCostOverviewWidgets.ts, src/store/breakdown/costOverview/rhelCostOverview/rhelCostOverviewWidgets.ts, src/store/breakdown/historicalData/common/historicalDataCommon.ts, src/store/breakdown/historicalData/ocpHistoricalData/ocpHistoricalDataWidgets.ts
Refactored storage historical chart to be visible when grouped by cluster, node, and project.
Also fixed a storage card title in OCP breakdown for the "Platform" project.
https://issues.redhat.com/browse/COST-4856
=> Refactored storage cards

src/api/resources/resource.ts, src/routes/details/awsBreakdown/instances/instancesTable.tsx, src/routes/details/awsBreakdown/instances/instancesToolbar.tsx
Update AWS EC2 instances table to support account_alias sort and instance_name exclude filter
=> Update AWS EC2 instances table

src/routes/overview/overview.tsx
This is just a test to ensure the stage-stable deployment is working as expected.
=> Test deployment to stage-stable

.tekton/koku-frontend-pull-request.yaml, .tekton/koku-frontend-push.yaml
Remove deprecated check.
[Migration](https://raw.githubusercontent.com/konflux-ci/build-definitions/main/task/sbom-json-check/0.2/MIGRATION.md).
=> Remove deprecated sbom-json-check

src/routes/components/dataToolbar/utils/bulkSelect.tsx, src/routes/explorer/explorer.tsx
This workaround, provided by the PatternFly team, appends the underlying menu components to the document body.
https://issues.redhat.com/browse/COST-5320
Must be merged after https://github.com/project-koku/koku-ui/pull/3943
=> PatternFly toolbar controls scroll page when clicked

src/routes/details/awsBreakdown/awsBreakdown.tsx, src/routes/details/awsBreakdown/instances/instances.tsx, src/routes/details/awsBreakdown/instances/instancesTable.tsx, src/routes/details/components/breakdown/breakdownBase.tsx, src/routes/settings/settings.tsx
- COST-5464 Omit AWS details page filters from available EC2 filters
- COST-5468 Requests on EC2 page need to use cost_type param
- Include currency menu for EC2 tab
- Removed Konflux test
https://issues.redhat.com/browse/COST-5469
https://issues.redhat.com/browse/COST-5468
=> EC2 fit and finish

src/components/featureToggle/featureToggle.tsx, src/components/permissions/permissions.tsx, src/routes/components/charts/historicalCostChart/__snapshots__/historicalCostChart.test.tsx.snap, src/routes/components/charts/historicalCostChart/historicalCostChart.tsx, src/routes/components/charts/historicalUsageChart/historicalUsageChart.tsx, src/routes/details/components/breakdown/breakdownBase.tsx, src/routes/details/components/costOverview/costOverviewBase.tsx, src/routes/details/components/historicalData/historicalDataBase.tsx, src/routes/details/ocpBreakdown/costOverview.tsx, src/routes/details/ocpBreakdown/historicalData.tsx, src/routes/details/ocpBreakdown/ocpBreakdown.tsx, src/routes/details/ocpDetails/detailsTable.tsx, src/routes/details/ocpDetails/ocpDetails.tsx, src/routes/overview/components/dashboardWidgetBase.tsx, src/routes/overview/ocpDashboard/ocpDashboardWidget.tsx, src/routes/settings/costModels/costModel/distribution.tsx, src/routes/settings/costModels/costModel/updateDistributionDialog.tsx, src/routes/settings/costModels/costModelWizard/distribution.tsx, src/routes/settings/costModels/costModelWizard/review.tsx, src/store/featureToggle/__snapshots__/featureToggle.test.ts.snap, src/store/featureToggle/featureToggle.test.ts, src/store/featureToggle/featureToggleActions.ts, src/store/featureToggle/featureToggleReducer.ts, src/store/featureToggle/featureToggleSelectors.ts
Remove unused Unleash flags
* cost-management.ui.ros
* cost-management.ui.ocp-cloud-networking
* cost-management.ui.ocp-project-storage
=> Remove unused Unleash flags

src/api/resources/awsOcpResource.ts, src/api/resources/azureOcpResource.ts, src/api/resources/gcpOcpResource.ts, src/routes/explorer/explorerFilter.tsx, src/routes/explorer/explorerHeader.tsx, src/routes/explorer/explorerUtils.ts
Add cluster/node/project group by/filtering to OCP on cloud perspectives
- Amazon Web Services filtered by OpenShift
- Microsoft Azure filtered by OpenShift
- Google Cloud Platform filtered by OpenShift
https://issues.redhat.com/browse/COST-5514
=> Add cluster/node/project group by/filtering to OCP on cloud perspectives

src/routes/details/awsBreakdown/instances/instances.tsx, src/routes/details/awsBreakdown/instances/instancesTable.tsx
EC2 page should use a common filter key for export, in addition to filtering/excluding
https://issues.redhat.com/browse/COST-5524
=> EC2 page should use a common filter key for export

src/routes/components/charts/costChart/costChart.tsx, src/routes/components/charts/costExplorerChart/costExplorerChart.tsx, src/routes/components/charts/dailyCostChart/dailyCostChart.tsx, src/routes/components/charts/dailyTrendChart/dailyTrendChart.tsx, src/routes/components/charts/historicalCostChart/historicalCostChart.tsx, src/routes/components/charts/historicalTrendChart/historicalTrendChart.tsx, src/routes/components/charts/historicalUsageChart/historicalUsageChart.tsx, src/routes/components/charts/trendChart/trendChart.tsx, src/routes/components/charts/usageChart/usageChart.tsx, src/routes/details/components/pvcChart/pvcChart.tsx, src/routes/details/components/usageChart/usageChart.tsx, src/utils/chrome.tsx, src/utils/hooks.ts
The token refresh issue below shows an "u.current is null" error somewhere in Cost Management. This will ensure we check the `current` prop for any refs.
Error
Slack
https://redhat-internal.slack.com/archives/C023VGW21NU/p1727158886930129
Token refresh issue
https://issues.redhat.com/browse/RHINENG-10155
Token refresh PR
https://github.com/RedHatInsights/insights-chrome/pull/2945
=> Current prop

src/routes/explorer/explorer.tsx, src/routes/explorer/explorerChart.tsx, src/routes/explorer/explorerDatePicker.tsx, src/routes/explorer/explorerFilter.tsx, src/routes/explorer/explorerHeader.tsx, src/routes/explorer/explorerTable.tsx, src/routes/utils/dateRange.ts
Date picker is defaulting to current month
https://issues.redhat.com/browse/COST-5563
=> Custom date range fix

src/routes/components/resourceTypeahead/resourceInput.tsx
Adding onBlur to the resource type-ahead works as expected on Firefox, but not Chrome
https://issues.redhat.com/browse/COST-5596
=> Remove onBlur

src/routes/details/components/breakdown/breakdownHeader.tsx, src/routes/settings/settings.scss, src/routes/settings/settings.tsx, src/routes/settings/tagLabels/tagLabels.tsx
Replace accordion, in the "tags and labels" settings page, with secondary tabs
https://issues.redhat.com/browse/COST-5608
=> Replace accordion with secondary tabs

src/routes/details/awsBreakdown/instances/instances.tsx, src/routes/details/awsBreakdown/instances/instancesToolbar.tsx, src/routes/utils/computedReport/getComputedReportItems.ts, src/routes/utils/computedReport/getItemLabel.ts
The EC2 instances page refreshes when there is no data. This change avoids using a React hook in the instances toolbar.
=> Fix EC2 instances page refresh

locales/data.json, locales/translations.json, src/locales/messages.ts
Spoke with Stefan, Chloe, and Neil. Chloe confirmed the description text should read:
> To view the cost of EC2 instances, label your resources with the following tag key and value pair in the AWS console.
=> Update text for EC2 empty state

src/routes/settings/costModels/components/rateForm/hasDiff.ts, src/routes/settings/costModels/components/rateForm/rateForm.tsx, src/routes/settings/costModels/components/rateForm/taggingRatesForm.tsx, src/routes/settings/costModels/components/rateForm/useRateForm.tsx, src/routes/settings/costModels/components/rateForm/utils.tsx, src/routes/settings/costModels/costModel/updateMarkupDialog.tsx, src/utils/format.ts
Normalize numeric values for API requests where USD decimal format is expected. The cost model API cannot handle special characters such as commas.
https://issues.redhat.com/browse/COST-5682
=> Normalize numeric values for API requests

src/routes/details/awsBreakdown/awsBreakdown.tsx, src/routes/details/awsBreakdown/instances/instances.tsx, src/routes/details/azureBreakdown/azureBreakdown.tsx, src/routes/details/ibmBreakdown/ibmBreakdown.tsx, src/routes/details/ociBreakdown/ociBreakdown.tsx, src/routes/details/ocpBreakdown/ocpBreakdown.tsx, src/routes/details/rhelBreakdown/rhelBreakdown.tsx
https://issues.redhat.com/browse/COST-5746
=> EC2 instances export uses wrong API param for previous month

locales/data.json, locales/translations.json, src/locales/messages.ts, src/routes/details/components/providerStatus/components/overallStatus.tsx, src/routes/details/components/providerStatus/providerStatus.tsx, src/routes/details/components/providerStatus/providerTable.tsx, src/routes/details/components/providerStatus/utils/icon.tsx
https://issues.redhat.com/browse/COST-5749
**Integrations modal**
=> Integration status not available for sources with status = null

src/utils/format.ts
Modified y-axis label to show up to 2 decimal places
https://issues.redhat.com/browse/COST-5829
=> UI should display decimals for Cost Explorer y-axis label

src/routes/details/ocpDetails/detailsHeader.tsx
Reset details page date range dropdown when nav link is clicked
https://issues.redhat.com/browse/COST-5830
=> Reset details page date range dropdown

src/routes/components/cluster/cluster.tsx, src/routes/details/components/pvcChart/pvcChart.tsx
Truncated long cluster names to fix overlap in PVC card. We can fit 50 chars max, and less at smaller window sizes.
Also adjusted the number of characters which can fit in the cluster window.
https://issues.redhat.com/browse/COST-5877
=> Long cluster names overlap in PVC card

locales/data.json, locales/translations.json, package-lock.json, package.json, src/components/featureToggle/featureToggle.tsx, src/locales/messages.ts, src/routes/details/components/costBreakdownChart/costBreakdownChart.styles.ts, src/routes/details/components/costBreakdownChart/costBreakdownChart.tsx, src/routes/details/components/costBreakdownChart/index.ts, src/routes/details/components/costOverview/costOverviewBase.tsx, src/routes/details/ocpBreakdown/costOverview.tsx, src/store/breakdown/costOverview/common/costOverviewCommon.ts, src/store/breakdown/costOverview/ocpCostOverview/ocpCostOverview.test.ts, src/store/breakdown/costOverview/ocpCostOverview/ocpCostOverviewReducer.ts, src/store/breakdown/costOverview/ocpCostOverview/ocpCostOverviewWidgets.ts, src/store/featureToggle/__snapshots__/featureToggle.test.ts.snap, src/store/featureToggle/featureToggleActions.ts, src/store/featureToggle/featureToggleReducer.ts, src/store/featureToggle/featureToggleSelectors.ts
Created a Sankey chart to replace the two pie charts in the OCP breakdown page.
https://issues.redhat.com/browse/COST-5852
To test:
1. Log in as cost-demo
2. Ensure you're in "preview" mode
3. Navigate to OCP details page
4. Click on any project
5. See default Sankey chart -- some node values will be zero
6. Use the mouse to hover and show tooltips -- note the zero values
7. Click on the "Overhead cost" menu and select "Don't distribute overhead costs"
8. See how Sankey chart changes dynamically
9. Click on the "Toggle minimum node height" switch -- this is a workaround for zero values
10. Sankey nodes should now have a min height, even for zero values
11. Click on the "Overhead cost" menu and select "Don't distribute overhead costs"
12. See how the Sankey chart changes with the min node …
=> Sankey Diagram: Simplify cost breakdown and overhead representation

src/routes/details/components/costBreakdownChart/costBreakdownChart.tsx
Adjust padding for cost breakdown chart -- cannot see "Usage cost" label
=> Adjust padding for cost breakdown chart

src/routes/settings/costModels/components/rateForm/rateForm.tsx
For the cost model wizard price list step, omit the "Enter rate by tag" feature for "Virtual Machine" options
https://issues.redhat.com/browse/COST-5987
=>  Omit the "Enter rate by tag" feature for "Virtual Machine" options

src/routes/details/components/costBreakdownChart/costBreakdownChart.tsx, src/routes/overview/components/dashboardWidgetBase.tsx
Omit middle section from Sankey chart when grouped by cluster/node/tag
https://issues.redhat.com/browse/COST-6144
=> Update middle section from Sankey chart

src/routes/details/azureDetails/detailsToolbar.tsx, src/routes/explorer/explorerUtils.ts
Different resource APIs use unique keys. Updated filters to look for `cluster_alias` for OCP and `account_alias` for Azure.
https://issues.redhat.com/browse/COST-6433
**OCP Cluster Example**
**Azure Account Example**
=> When filtering on cluster name, cluster uuid is shown
